### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by czxinc** [zhongyang219/TrafficMonitor#1]
使用的1.65版本。win10 1709开机时还是会弹出“已经有一个程序正在运行”的对话框

**Comment by zhongyang219** [comment]
@czxinc 在win10 1709上，如果在关机时程序没有被退出，下次开机时Windows就会自动将其重启，我不知道为什么微软要做这样的处理。此时如果程序设置了开机自动运行，则会导致程序被启动两次，所以程序会弹出“已经有一个程序正在运行”的对话框。为了解决这个问题，我做的处理是，在开机后的1分钟内，如果程序是被Windows重启的，则不弹出对话框直接退出。按理说开机1分钟内是不会出现这个对话框了，应该只有开机时间过长，比如超过1分钟才会弹出这个对话框。这个版本我已经测试过很多次，都没有问题，可能我的逻辑还不够完善。你是每次都会出现这个问题，还是偶尔出现？

**Comment by czxinc** [comment]
这个是几乎每次出现的，用1709时经常出现这样的问题。
但是，我开机好像没有超过一分钟。

**Comment by zhongyang219** [comment]
@czxinc 好的，谢谢反馈，下个版本我会再改进一下。

**Comment by czxinc** [comment]
不客气

**Comment by zhongyang219** [comment]
这里我想要再解释一下开机时弹出“已经有一个程序正在运行”对话框的问题。上个版本中，我设置了在开机1分钟以内不弹出此对话框（由于有网友反馈还是会弹出，我以为1分钟的时间太短，就改成了5分钟），后来我发现这个对话框有时还是会在开机时弹出，于是我通过写日志文件的方式查看程序获取到的开机时间。我是通过GetTickCount函数来获取开机到现在的时间的，但是此函数有一个问题，就是它获取到的是完全关机后的开机到现在的时间，如果启用了混合休眠（Win是默认启用的），则此函数获取到的时间就不正确。而重启时获取的开机时间就是正确的，因为重启相当于一次完全关机。
现在的临时解决方法是，判断当前系统版本是否是Win10 build16299及以后版本，如果是，则默认不弹出这个对话框。
源代码已经提交上去了，不知道是否有大神有更好的解决办法。

**Comment by czxinc** [comment]
个人觉得是快速启动的锅。

**Comment by zhongyang219** [comment]
我发现我把问题想复杂了，我现在把它改成了只要检测到程序是被Windows重新启动的，就直接退出，也不需要检测开机时间了，这样开机时就不会被启动两次了。通常情况下，只有在程序崩溃时，才会被Windows重新启动，做了这样的处理的话，程序崩溃时就不能自动重启了，但是这种情况应该很难出现，而且影响不大。

**Comment by czxinc** [comment]
挺厉害的，还能想到这种方法。不过一般程序崩溃都是要用户手动重新启动的吧，很少有程序崩溃时能自动重启的。
或者，可以检测程序是否重复运行，如果是，则把之前运行的程序退出，再运行新的。

顺便说一下还有一个bug：如果开启了嵌入任务栏的话，在开机时如果程序还没嵌入任务栏，又打开开始菜单的话，会弹出“窗口没有嵌入任务栏，可能被安全软件阻止”的对话框，之后虽然嵌入任务栏了，但是它被任务栏给盖住了，或者显示在任务栏前面，但是背景是黑色的。我的电脑是win10系统，但是th2 rs1 rs2版本都出现了这种现象。我不敢确定是否其他版本的系统会出现这种问题。

如果上面的问题看不懂的话，可以再问我详细的情况。原谅我的语文表达能力不好。

**Comment by zhongyang219** [comment]
关于嵌入任务栏的问题其实之前我已经注意到了，这个问题在V1.66版里已经解决了，请更新到最新版本试试。我使用的方法是如果检测到无法嵌入任务栏，先不弹出提示，然后每10秒尝试一次嵌入任务栏，最多尝试30次，如果这时还无法嵌入任务栏，说明真的是被安全软件阻止了，这时再弹出提示信息。

貌似当开始菜单在打开状态时，嵌入任务栏会失败，目前只能想到这样的解决方法。现在除非你在程序启动还没有嵌入任务栏打开开始菜单，然后保持10*30秒，即5分钟，才会弹出这个提示。

**Comment by szx9231** [comment]
其实那个重启的问题把MFC默认用的restart manager关掉就不会被Windows重新启动了。

**Comment by zhongyang219** [comment]
@szx9231 restart manager要怎么关掉？我现在的方法是检测程序的命令行参数，如果程序是被restart manager重启的，参数里会带有RestByRestartManager这个字符串，检测到这个之后我就直接退出程序。

**Comment by szx9231** [comment]
@zhongyang219 
`CTrafficMonitorApp::CTrafficMonitorApp()
{
	// 支持重新启动管理器
	m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_RESTART;

	// TODO: 在此处添加构造代码，
	// 将所有重要的初始化放置在 InitInstance 中
}`
把m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_RESTART;注释掉就好了，不过缺点是如果crash了，Windows就不会帮你重启了。我之前是自己注册了一个crash handler，如果crash的话在crash handler里面重启自己。
不知道对你有没有帮助，另外，win10后面的版本会把重启这个特性取消。

**Comment by zhongyang219** [comment]
@szx9231 非常感谢，之前一直都没有注意到那句代码。另外，你说的win10后面的版本会把重启这个特性取消是什么意思，以后程序crash了Windows就不会将它重启了吗？

**Comment by szx9231** [comment]
@zhongyang219 
不客气，我正好前段时间也碰到了这个问题，原因就是rs3会在系统开机的时候用restart manager去重启，MFC上新建的程序默认会勾选支持restart manager。不过rs3后面的版本微软说会把开机用restart manager重启程序这个功能去掉。所以即使不把这个代码注释掉，也不会出现开机的时候系统帮着启动一次了。
但是restart manager还有一个功能，就是当程序crash以后，操作系统会帮我们重启crash的程序。所以如果把这行去掉以后就失去这个功能。
总结来说，去掉这一行代码以后，rs3上就不会出现操作系统自己用restart manager重启程序，但是副作用是在所有win10版本上，如果程序crash了操作系统不会帮我们重启了。
我之前解决的办法是公司有一个crash handler的库，我自己在上面注册了一个回调。crash的话这个回调就会帮着再次启动一次程序。

如果有说的不对的地方，还请指正。我也是Windows开发的新人哈。哈哈。
