### ISSUE TITLE
希望能增加高刷新率

### ISSUE THREAD

**Issue by Linqing0808** [zhongyang219/TrafficMonitor#101]
现在的刷新速度有点慢，几乎是一秒刷新一次吧，这样不能显示实时速度，如果有一个高刷新率开关就好了，一秒60次刷新！！！

**Comment by zhongyang219** [comment]
抱歉，这个提议暂时不考虑。目前几乎所有显示网速的软件都是1秒钟刷新一次的，我也认为1秒种的刷新频率是最适合的刷新频率，太慢或太快都不行。如果像你说的改成1 秒钟刷新60次，你只能看到数据在飞速地变化，根本看不清上面的数值。

**Comment by Linqing0808** [comment]
@zhongyang219 一秒60次是开玩笑的，其实一秒刷次2次到3次就可以了，一秒钟可以发生很多事了

**Comment by Just2co** [comment]
@zhongyang219 这个小巧绿色的CPU内存网速监控软件，真是出现的太及时了，满足了我的需求，感谢！还是建议在设置项里面增加刷新率，每秒1次、2次、3次，把选择权交给用户，这样就可以避免众口难调了。
