### ISSUE TITLE
联想刃9000k 12900KF处理器温度显示为两条横线，不显示温度

### ISSUE THREAD

**Issue by sephiroth0403** [zhongyang219/TrafficMonitor#1010]
LibreHardwareMonitor可以正常显示cpu温度

**Comment by sephiroth0403** [comment]
LibreHardwareMonitor可以正常显示cpu温度

**Comment by simear2004** [comment]
去下载最新构建版本就能正常显示了

**Comment by dellwins** [comment]
你好，我这里也是这样的情况，我的主板是微星x690-a 和 12600k，用的最新bios

最近版本下载的是v1.82 但问题依旧，望能给予帮助解决

**Comment by DreamL** [comment]
CPU: 12700K
OS: Win11-22000.434
Version: 1.82

同楼主,一切功能正常,只有CPU温度为"--"(其他硬件监控没开,不知是否正常)
LibreHardwareMonitor能正常获取CPU温度,如图:

![QQ截图20220120172222](https://user-images.githubusercontent.com/8446543/150310797-ca76a1ea-0ab1-4b43-a761-323ffa639a19.png)
