### ISSUE TITLE
检测外网ip的接口挂了，好几天了

### ISSUE THREAD

**Issue by jiemo9527** [zhongyang219/TrafficMonitor#1021]

**Comment by jiemo9527** [comment]
v4建议换成这个http://ip-api.com/json?lang=zh-CN    永久不挂

**Comment by jiemo9527** [comment]
@zhongyang219

**Comment by zhongyang219** [comment]
@ritaswc

**Comment by ritaswc** [comment]
我搞一下。。

**Comment by ritaswc** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/15887140/152524898-2ee17312-90a9-4303-ab1b-215d3e855dd5.png">
弄好了 @jiemo9527 @zhongyang219
