### ISSUE TITLE
希望添加一个黑色皮肤，例如

### ISSUE THREAD

**Issue by PTA00** [zhongyang219/TrafficMonitor#1027]
![image](https://user-images.githubusercontent.com/59364024/152118310-b068236b-3296-4ea9-916e-0c4fabd9e531.png)
如图

**Comment by PTA00** [comment]
或者是可自定义纯色选项，我认为很多人喜欢这样的简约风格

**Comment by soloopooo** [comment]
自己动手，丰衣足食。参照皮肤制作指南。

**Comment by PTA00** [comment]
> 自己动手，丰衣足食。参照皮肤制作指南。

我只是想把我这个皮肤添加进默认皮肤

**Comment by soloopooo** [comment]
> > 自己动手，丰衣足食。参照皮肤制作指南。
> 
> 我只是想把我这个皮肤添加进默认皮肤

发PR咯

**Comment by PTA00** [comment]
[https://github.com/zhongyang219/TrafficMonitorSkin/blob/master/%E7%9A%AE%E8%82%A4%E4%B8%8B%E8%BD%BD.md](url)
我刚刚发现这个页面可以发邮件提交皮肤。而且我做的皮肤和LT01的一模一样，哈哈撞车了。
果然喜欢这种黑色的人不少...
