### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by himitsuzero** [zhongyang219/TrafficMonitor#1034]
I have found a small typo in the `Historical Traffic Statistics` window.
Please correct me if I'm wrong, but I believe that it should say `Linear scale`, instead of `Linear scal`.
I have tried searching through the repository for keywords but I'm not quite sure where to find it it.

![preview](https://user-images.githubusercontent.com/98982999/152625138-b9b17bb4-926b-4ebf-b2d0-3c18f33c35d5.jpg)

**Comment by zhongyang219** [comment]
Thanks for your feedback. It is indeed a spelling mistake, i have fixed it.
