### ISSUE TITLE
可以增加需要显示的内容开关，并加入刷新时间，网速单位自动切换

### ISSUE THREAD

**Issue by wyrctzy** [zhongyang219/TrafficMonitor#104]
比如平时只需要显示上传和下载的网速，增加显示开关
cpu信息等不常用信息可以加大刷新时间

**Comment by zhongyang219** [comment]
CPU和内存利用率可以隐藏啊，网速单位也会自动选择，小于1M时使用KB这单位，大于1M时使用MB为单位。所以你想要的是什么功能？
