### ISSUE TITLE
网络速度超过100MB/s时，无法显示第一位数值

### ISSUE THREAD

**Issue by QianMoXi** [zhongyang219/TrafficMonitor#1043]
应该是要显示成 111.8 M/s的，但是只能显示出11.8M/s，如图所示：

![image](https://user-images.githubusercontent.com/26250460/153368322-a383b96a-427c-4476-8378-55900e08ed0b.png)

**Comment by Echo1188** [comment]
8Mbps=1M/s，这里M/s指MBytes/s，Mbps指Mbits/s，1 byte = 8 bits

**Comment by QianMoXi** [comment]
![image](https://user-images.githubusercontent.com/26250460/154436705-20b1ff50-2f25-4036-82ca-79040887c5a3.png)

发现总网速也会有问题，但是是单位未显示完全，感觉这个还是可以接受的

**Comment by Echo1188** [comment]
> > 8Mbps=1M/s，这里M/s指MBytes/s，Mbps指Mbits/s，1 byte = 8 bits
> 
> 你没认真看我说的内容，问题不在于单位，我上面都换算过了，930/8约等于116，介于任务管理器和程序的统计可能有些许区别，程序获取到的应该是111.8，然后只能显示出11.8，第一位数字目前是没办法正常显示的

sorry，不是没认真看，是我心算错了（捂脸）。
请确认或试试：
选项-任务栏-窗口设置-显示设置-网速数据宽度 ？ 字符，这个你设置的多少？默认是4个字符，11.8就是4个，你是否已经改成5个字符以上？

**Comment by QianMoXi** [comment]
> > > 8Mbps=1M/s，这里M/s指MBytes/s，Mbps指Mbits/s，1 byte = 8 bits
> > 
> > 
> > 你没认真看我说的内容，问题不在于单位，我上面都换算过了，930/8约等于116，介于任务管理器和程序的统计可能有些许区别，程序获取到的应该是111.8，然后只能显示出11.8，第一位数字目前是没办法正常显示的
> 
> sorry，不是没认真看，是我心算错了（捂脸）。 请确认或试试： 选项-任务栏-窗口设置-显示设置-网速数据宽度 ？ 字符，这个你设置的多少？默认是4个字符，11.8就是4个，你是否已经改成5个字符以上？

我的问题，确实改了按了**确认**按钮是可以生效的。
因为其它配置，都是按**应用**后，就能生效，我理所应当的以为这个配置也是这样，我之前还在纳闷，为啥这个配置改了没反应。
