### ISSUE TITLE
这个工具与7+ Taskbar Tweaker同时运行有严重bug

### ISSUE THREAD

**Issue by gundamhyl** [zhongyang219/TrafficMonitor#108]
同时运行的时候，TrafficMonitor会不断向左边移动，然后所有图标都不见

作者可以试一下http://rammichael.com/7-taskbar-tweaker

**Comment by zhongyang219** [comment]
感谢反馈，确实有这样的问题，曾经也有人向我反馈过，TrafficMonitor的任务栏窗口和7+ Taskbar Tweaker中“保留任务栏中的空白区域”这个功能有冲突，在问题解决之前，你可以去掉7+ Taskbar Tweaker中“保留任务栏中的空白区域”的勾选，或者关闭TrafficMonitor的任务栏窗口来解决问题。

**Comment by zhongyang219** [comment]
另外，同样的问题还发生在两个TrafficMonitor实例同时运行的时候，所以我一开始就做了只允许运行一个TrafficMonitor实例的处理。
