### ISSUE TITLE
任务栏界面闪烁

### ISSUE THREAD

**Issue by BenjiaH** [zhongyang219/TrafficMonitor#1086]
登录PC微信后，来消息时，任务栏界面和微信一起闪烁。100%复现
1.83（x64）win11版本21H2(0S内部版本22000.556)
使用gifcam录制不下来所以只能用手机录了，见谅。

https://user-images.githubusercontent.com/46958476/157581011-5ba5613d-3def-4e89-9601-005045fb7933.mp4

**Comment by stardust-an** [comment]
我的闪的比你还厉害，还带着所有任务栏图标一起闪[]

**Comment by Carlos920** [comment]
这是微软的bug🤣,和这软件没关系

**Comment by outsideoftime** [comment]
我的设置透明背景，却还会显示

**Comment by GF-Huang** [comment]
有缓解方法吗？

**Comment by BenjiaH** [comment]
> 有缓解方法吗？

更新Windows后问题可以解决。
