### ISSUE TITLE
[bug]程序任务栏窗口在不同DPI屏幕切换后显示不正常

### ISSUE THREAD

**Issue by BombaxCeiba** [zhongyang219/TrafficMonitor#1089]
在125%缩放的屏幕运行时
![image](https://user-images.githubusercontent.com/31007907/158047867-a23d63f2-278c-4f06-9d96-4f15365acc58.png)
切换会到100%缩放的屏幕运行时（此时文字明显偏大）
![image](https://user-images.githubusercontent.com/31007907/158047906-4c4003a3-b3d0-4d83-904b-57db2fb74001.png)
在100%缩放的屏幕正常运行时
![image](https://user-images.githubusercontent.com/31007907/158047958-0148b9e1-37ef-4f0f-a4d8-7eb36d700b6c.png)

**Comment by kevintsq** [comment]
https://github.com/zhongyang219/TrafficMonitor/issues/877#issuecomment-1173119990
