### ISSUE TITLE
字体变粗

### ISSUE THREAD

**Issue by hupo376787** [zhongyang219/TrafficMonitor#1090]
正常情况
![image](https://user-images.githubusercontent.com/14960168/158378698-108e49d8-aaed-486c-8c13-775d80c3f5eb.png)

全屏软件截图后，闪两下就变回正常字体
![image](https://user-images.githubusercontent.com/14960168/158378531-8545da8b-876f-43ed-a82a-de76204f8ad1.png)

**Comment by BombaxCeiba** [comment]
猜测是TrafficMonitorDlg.cpp 中的CTrafficMonitorDlg::OnTimer是每秒执行一次的，所以不能及时检测到任务栏背景颜色的变化导致字体渲染不正确。

**Comment by zhongyang219** [comment]
有时候确实会有这样的问题，你可以在“设置”——“任务栏窗口设置”中尝试去掉“背景透明”的勾选。

**Comment by hupo376787** [comment]
> 有时候确实会有这样的问题，你可以在“设置”——“任务栏窗口设置”中尝试去掉“背景透明”的勾选。

去掉后，目前可以了，谢谢
