### ISSUE TITLE
关于任务栏窗口双击打开任务管理器的功能 是否可以提供任务管理器路径切换

### ISSUE THREAD

**Issue by WangJerry1229** [zhongyang219/TrafficMonitor#1091]
在目前的Windows11系统中，任务管理器Taskmgr.exe有两个版本同事存在 “C:\Windows\SysWOW64”中的是32位，而"C:\Windows\System32"中的反而是64位，在我个人使用中，32位的任务管理器在性能选项卡中占用率各项数据均无法显示，而64位的就正常。目前从任务栏双击打开的任务管理器是默认32位，能否提供一个路径切换功能。

**Comment by WangJerry1229** [comment]
刚刚经过测试似乎不是目录的问题
我通过自定义双击打开应用程序 手动选择System32中的Taskmgr.exe 结果运行后依然显示32位 且性能选项卡中各项数据都为空
如果通过快捷键ctrl+shift+esc或者手动双击exe运行的任务管理器才不会显示32位且各项数据都正常
![360截图20220316133547411](https://user-images.githubusercontent.com/57123963/158523537-b1dc0b5a-dc43-4802-b996-8484896f3ae2.jpg)
![360截图20220316133604573](https://user-images.githubusercontent.com/57123963/158523540-6da8f703-1489-4f55-b01b-d044efb28741.jpg)
![360截图20220316133620860](https://user-images.githubusercontent.com/57123963/158523542-7e0de8b6-7413-48b4-b961-74e031e444e1.jpg)

**Comment by zhongyang219** [comment]
请使用64位的TrafficMonitor。

**Comment by WangJerry1229** [comment]
> 请使用64位的TrafficMonitor。

感谢回复 已可以正常使用
