### ISSUE TITLE
UI 问题

### ISSUE THREAD

**Issue by LisonFan** [zhongyang219/TrafficMonitor#110]
![image](https://user-images.githubusercontent.com/9424775/43040023-046fe3a6-8d6c-11e8-9b36-e19f855c9750.png)

**Comment by zhongyang219** [comment]
目前找到了一个办法可以基本上解决这个问题。
具体参考下面链接的第11条：
https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md

**Comment by LisonFan** [comment]
> 目前找到了一个办法可以基本上解决这个问题。
> 具体参考下面链接的第11条：
> https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md

好的，谢谢。
