### ISSUE TITLE
README单词拼写有错

### ISSUE THREAD

**Issue by SJTUboy** [zhongyang219/TrafficMonitor#112]
![image](https://user-images.githubusercontent.com/13373715/43263542-2319f474-9116-11e8-9c00-a4ff370cb395.png)

**Comment by zhongyang219** [comment]
谢谢反馈，我马上就改过来，这么久了我竟然一直都没发现，好尴尬😓

**Comment by NoahELE** [comment]
![image](https://user-images.githubusercontent.com/49080986/55266147-94394580-52cf-11e9-94fb-249272f4eee6.png)
