### ISSUE TITLE
CPU占用率和任务管理器里的CPU占用率相比高出太多

### ISSUE THREAD

**Issue by small32** [zhongyang219/TrafficMonitor#114]
如题，显示的CPU占用率偏高，同时在任务管理器里看CPU占用率实际上并没有那么高

**Comment by small32** [comment]
处理器是i7-7500U，内存16GB，系统是Windows10 1803

**Comment by zhongyang219** [comment]
![2](https://user-images.githubusercontent.com/30562462/43496614-d59032a4-9570-11e8-84fb-0b445304341c.png)
这个问题确实存在，似乎是Win10以后任务管理器检测CPU利用的方法发生了变化，导致第三方软件获取的CPU利用率偏高。上面的图中，我使用了鲁大师、360流量监控绿色版、软媒雷达和TrafficMonitor来显示CPU利用率，所有第三方软件都达到了99%或100%，只有任务管理器显示为69%。

**Comment by vvb2060** [comment]
bug10的任务管理器不可信，主页显示的CPU使用率没有算上内核占用。使用微软官方的[诊断工具](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)或者看任务管理器详细信息里的`系统空闲进程`CPU，做减法。
