### ISSUE TITLE
有mac版本吗

### ISSUE THREAD

**Issue by Snowfly-Guo** [zhongyang219/TrafficMonitor#1146]
有mac版本吗

**Comment by wangcongh** [comment]
暂时没有开发计划

**Comment by TheAnirudhGoyal** [comment]
This is such a great software that I would rather change my OS than coping with non power user customizable MacShitOS.

**Comment by Snowfly-Guo** [comment]
@wangcongh 好的 谢谢回答

**Comment by Snowfly-Guo** [comment]
@TheAnirudhGoyal Because I installed dual system, my windows 10 has this software, but my Mac OS doesn't have this software.
Thank you for your answer~

**Comment by cnliucheng** [comment]
Mac系统下iStatus很香，有些功能值得TrafficMonitor借鉴，例如每个应用的流量显示

**Comment by k4mrul** [comment]
For mac, there is an alternative https://github.com/exelban/stats

**Comment by Snowfly-Guo** [comment]
@cnliucheng 好的谢谢回复

**Comment by Snowfly-Guo** [comment]
@k4mrul OK, I'll try，Thank you for your reply.
