### ISSUE TITLE
Some mispellings in version 1.74

### ISSUE THREAD

**Issue by kator-278** [zhongyang219/TrafficMonitor#115]
As shown in follows:

![](https://user-images.githubusercontent.com/8875998/43305170-4c50569c-91a9-11e8-97a3-7df0ed30e4e4.png)

![](https://user-images.githubusercontent.com/8875998/43305206-71fb5c48-91a9-11e8-9225-ed0d3b3dcf89.png)

**Comment by zhongyang219** [comment]
Thanks for your feedback, this is indeed my mistake, I will fix it in the next version.
