### ISSUE TITLE
Win 11 Taskbar Window allignment problem

### ISSUE THREAD

**Issue by nijhummehrab** [zhongyang219/TrafficMonitor#1159]
The taskbar window is showing in center above the start,search icon etc icons.
Current version of windows is Windows 11 Pro 22H2  22610.1

**Comment by yaozijin** [comment]
https://github.com/GZTimeWalker/TrafficMonitor/commit/79cc03b0fe7304b8c4ed370f450e3f5ed179ddc1#commitcomment-70662548
I think you can download this RP to fix it.

**Comment by nijhummehrab** [comment]
Thanks .It works perfectly.
