### ISSUE TITLE
请问作者可以加个番茄钟的功能吗

### ISSUE THREAD

**Issue by Leroy-X** [zhongyang219/TrafficMonitor#1162]
~虽然和监视关系不大，但任务栏上显示个番茄钟计时器真的蛮有用的哎，可以在这设置里设置工作时间，休息时间，自定义通知铃声什么的

**Comment by soloopooo** [comment]
可以自己写插件实现该功能，详见插件文档

**Comment by Leroy-X** [comment]
。。。额，我是菜鸟不会写，，怎么办，难不难
