### ISSUE TITLE
当使用透明状态栏时，状态栏字体发虚

### ISSUE THREAD

**Issue by nicangtianws01** [zhongyang219/TrafficMonitor#1164]
![image](https://user-images.githubusercontent.com/54566234/166936316-594ccd58-3bdd-4bef-a451-3ad6e9f72444.png)
当使用透明状态栏时，状态栏字体发虚，字体外有一层背景色包裹。 
状态栏设置如下
![image](https://user-images.githubusercontent.com/54566234/166936583-6d9d2e5f-53a2-4f06-a614-af8f6420a9c2.png)

**Comment by nicangtianws01** [comment]
这是勾选根据任务栏自动设置背景色的情况，字体还是发虚
![image](https://user-images.githubusercontent.com/54566234/166945663-51ff9355-198b-4d6c-96dd-dd770a4ae390.png)

**Comment by BombaxCeiba** [comment]
#1156 可以看这个PR。

**Comment by nicangtianws01** [comment]
> #1156 可以看这个PR。

无法找到关闭D2D渲染的选项，而且当我同时勾选自动选色和透明背景时，如上条回复，还是有很明显的背景残留。
当我从桌面切入浏览器时，有大约一秒显示如下图：
![image](https://user-images.githubusercontent.com/54566234/167156911-22c65bbb-431a-4c07-aa8d-1767a1fa882d.png)

**Comment by BombaxCeiba** [comment]
> > #1156 可以看这个PR。
> 
> 无法找到关闭D2D渲染的选项，而且当我同时勾选自动选色和透明背景时，如上条回复，还是有很明显的背景残留。 当我从桌面切入浏览器时，有大约一秒显示如下图： ![image](https://user-images.githubusercontent.com/54566234/167156911-22c65bbb-431a-4c07-aa8d-1767a1fa882d.png)

PR还没被合并，所以目前下载的程序还不支持这个功能。
这里是用PR代码编译的版本 [GitHub Action](https://github.com/BombaxCeiba/TrafficMonitor/actions/runs/2285523131)

**Comment by nicangtianws01** [comment]
> > > #1156 可以看这个PR。
> > 
> > 
> > 无法找到关闭D2D渲染的选项，而且当我同时勾选自动选色和透明背景时，如上条回复，还是有很明显的背景残留。 当我从桌面切入浏览器时，有大约一秒显示如下图： ![image](https://user-images.githubusercontent.com/54566234/167156911-22c65bbb-431a-4c07-aa8d-1767a1fa882d.png)
> 
> PR还没被合并，所以目前下载的程序还不支持这个功能。 这里是用PR代码编译的版本 [GitHub Action](https://github.com/BombaxCeiba/TrafficMonitor/actions/runs/2285523131)

ok
