### ISSUE TITLE
win11 beat通道 任务栏显示窗口异常

### ISSUE THREAD

**Issue by Eliauk365** [zhongyang219/TrafficMonitor#1171]
版本：windows  11 专业版 22H2
操作系统版本：22621.1
软件版本：1.83

问题描述：
启动后，整体显示在任务栏左侧

![kmZlIfgkt2](https://user-images.githubusercontent.com/57357340/168458724-c42b3462-0e14-4157-b680-4cc0d70d5c5b.png)

**Comment by soloopooo** [comment]
请自行关闭issue。
