### ISSUE TITLE
win11提示找不到mscoree.dll文件

### ISSUE THREAD

**Issue by yaoysyao** [zhongyang219/TrafficMonitor#1173]
![image](https://user-images.githubusercontent.com/38513384/168462318-622d3e43-e4ea-4f17-9534-c8d3c1bbf21f.png)
win11 系统专业版，启动软件出现如下错误，需要去哪里下载这个dll文件

**Comment by sudarakas** [comment]
You need install Microsoft Visual C++ Redistributable latest
[Microsoft Visual C++ Redistributabl](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by 99junlin99** [comment]
和楼主问题一致，已经安装了二楼发的链接中所有的x64版本，但是并不能解决这个问题

**Comment by yaoysyao** [comment]
> 和楼主问题一致，已经安装了二楼发的链接中所有的x64、x86版本，但是并不能解决这个问题 ![image](https://user-images.githubusercontent.com/35255028/169706244-be74ee9c-5cad-43e4-be3a-d5bfc971e31d.png)

对，我也是，安装了也没用

**Comment by yaoysyao** [comment]
> 和楼主问题一致，已经安装了二楼发的链接中所有的x64、x86版本，但是并不能解决这个问题 ![image](https://user-images.githubusercontent.com/35255028/169706244-be74ee9c-5cad-43e4-be3a-d5bfc971e31d.png)

我的现在可以用了，应该是win11系统的问题，更新了系统后可以了

**Comment by 99junlin99** [comment]
> > 和楼主问题一致，已经安装了二楼发的链接中所有的x64、x86版本，但是并不能解决这个问题 ![image](https://user-images.githubusercontent.com/35255028/169706244-be74ee9c-5cad-43e4-be3a-d5bfc971e31d.png)
> 
> 我的现在可以用了，应该是win11系统的问题，更新了系统后可以了

大佬能截图下当前win11版本么。我目前检查不到更新，但还是运行不了。目前发现epic、虎牙都运行不了，其他都可以。版本是22000.708

**Comment by yaoysyao** [comment]
> > > 和楼主问题一致，已经安装了二楼发的链接中所有的x64、x86版本，但是并不能解决这个问题 ![image](https://user-images.githubusercontent.com/35255028/169706244-be74ee9c-5cad-43e4-be3a-d5bfc971e31d.png)

> 大佬能截图下当前win11版本么。我目前检查不到更新，但还是运行不了。目前发现epic、虎牙都运行不了，其他都可以。版本是22000.708
一样，我也是这个版本，截图上传不了，我听说是windows系统的bug，可能是更新后少了一些库

**Comment by yaoysyao** [comment]
> > > 和楼主问题一致，已经安装了二楼发的链接中所有的x64、x86版本，但是并不能解决这个问题 ![image](https://user-images.githubusercontent.com/35255028/169706244-be74ee9c-5cad-43e4-be3a-d5bfc971e31d.png)
> > 
> > 
> > 我的现在可以用了，应该是win11系统的问题，更新了系统后可以了
> 
> 大佬能截图下当前win11版本么。我目前检查不到更新，但还是运行不了。目前发现epic、虎牙都运行不了，其他都可以。版本是22000.708

一样，我也是这个版本，截图上传不了，我听说是windows系统的bug，可能是更新后少了一些库

**Comment by 99junlin99** [comment]
找到解决方案了，使用方案一成功解决https://blog.csdn.net/qq_29508575/article/details/124845932

**Comment by yaoysyao** [comment]
有解决方案了，有需要的参考
