### ISSUE TITLE
设置问题，怎么设置只显示任务栏中的信息，不在桌面显示？

### ISSUE THREAD

**Issue by yaoysyao** [zhongyang219/TrafficMonitor#1193]
![image](https://user-images.githubusercontent.com/38513384/171325686-7b033d4c-90e4-46c7-9fca-dbc38e80062d.png)

**Comment by dozen007** [comment]
![image](https://user-images.githubusercontent.com/35923210/171590699-a74bef40-1f9f-4128-a900-46f26fff1e98.png)
关闭这个就行了

**Comment by yaoysyao** [comment]
> ![image](https://user-images.githubusercontent.com/35923210/171590699-a74bef40-1f9f-4128-a900-46f26fff1e98.png) 关闭这个就行了

OK，谢谢，解决了
