### ISSUE TITLE
Windows 11 22H2 Taskbar Alignment

### ISSUE THREAD

**Issue by Badass-Nemesis** [zhongyang219/TrafficMonitor#1197]
The speed display is now showing in the center of the taskbar, after the windows update. Before the update, it was showing on the right side of taskbar, as normal as it should be. But now after the update, the speed display is now overlapping the icons of my taskbar icons.
![Screenshot (3)](https://user-images.githubusercontent.com/71874901/172834622-cdb0afba-6707-4066-88dd-dd51293069f7.png)

**Comment by xishizhe** [comment]
我是昨天刚升级的Win11的预览版系统22H2，我也想反馈这个来的，系统之前也有一个bug，就是明明设置了不显示通知区图标，电脑重启后又会自动显示，到选项一看发现"显示通知区图标"选项又被勾选了。我的任务栏是居中的，也遇到了这个问题，还有个问题就是当选择靠近图标而不是任务栏两侧时，这个任务栏窗口会直接消失，我把任务栏改为靠左有测试了一下，发现是一样的。
![bug详情图](https://user-images.githubusercontent.com/55939287/172834868-5a7f765e-670b-4090-adf1-2f53fe9a8eb5.png)
![电脑系统信息](https://user-images.githubusercontent.com/55939287/172834887-e4f4f6e9-10a5-4381-898e-5a28ee5059fc.png)
https://user-images.githubusercontent.com/55939287/172836034-4dd29601-71a3-4fc0-bd8a-a6e810df3c57.mp4

**Comment by Badass-Nemesis** [comment]
@xishizhe , checkout this [post comment](https://github.com/zhongyang219/TrafficMonitor/issues/1129#issuecomment-1090824737) . It's working fine for me right now. 
![image](https://user-images.githubusercontent.com/71874901/172840224-afb6c6c2-d3e8-477f-b74f-79cd290a282b.png)
