### ISSUE TITLE
主窗口设置鼠标穿透以后无法更改

### ISSUE THREAD

**Issue by lostpg** [zhongyang219/TrafficMonitor#12]
RT, 只能在目录下的 `config` 文件内手动更改键值. 

~~这算是 BUG 还是 Feature~~

**Comment by lostpg** [comment]
没有注意到, 任务栏的右键就可以更改设置..

**Comment by zhongyang219** [comment]
关于这个问题，我在一开始做鼠标穿透功能的时候就考虑到了，因为开启鼠标穿透后主窗口无法弹出右键菜单，所以只能通过通知区图标右键菜单关闭。而如果你还设置了隐藏通知区图标，则在开启鼠标穿透后通知区图标会强制显示出来，并且菜单项会变成灰色。
