### ISSUE TITLE
历史流量统计

### ISSUE THREAD

**Issue by mingzhi2018** [zhongyang219/TrafficMonitor#120]
好喜欢你这个软件，真棒！一直想有这样的软件十来年了。
可以在“历史流量统计”增加一个“年视图”吗？好奇一年能用多大数据量。或者在“日历视图”下“当前月总流量”的右边加个“当前年总流量”，然后这个数值只要在任意年内的当年某个，这个数值始终显示，只是月总流量会随每月变动。
另外：在“逗比根据地”发现你这个软件的，才用这个软件几天，这个历史记录是会永久保存，并且可以按任意年按任意月查阅的吗?这个历史数据保存在哪？以后换电脑的话或者重新安装系统的话，备份本软件的文件夹是不是可以正常保留？
我发现我好多问题啊。。。这个软件是不是还有IOS版和安卓版？在哪下载？也是叫TrafficMonitor吗?
小白话多，请见谅。

**Comment by zhongyang219** [comment]
历史流量数据保存在c:\users\用户名\appdata\roaming\Trafficmonitor\history_traffic.dat文件中，你也可以通过“选项”——“常规设置”——“打开配置文件所在目录”打开此文件夹，如果更换电脑或重装系统可以备份此文件。
安卓或ios上的Trafficmonitor只是同名而已，跟这个软件没有任何关系。
