### ISSUE TITLE
[Bug] Error Display Taskbar

### ISSUE THREAD

**Issue by thanhnhn891221** [zhongyang219/TrafficMonitor#1200]
After I update win 11 to new version 22H2 (OS Build 22621.1), Show Tasbar Windows error (Attachment)
![2022-06-10 10_15_51-](https://user-images.githubusercontent.com/43947111/172983447-b28b3ba6-940e-4040-b5b3-8911fde76e52.png)

**Comment by Badass-Nemesis** [comment]
@thanhnhn891221 checkout this #1106 . download the files from that pull request and try it, see if it works. It worked for me

**Comment by thanhnhn891221** [comment]
> @thanhnhn891221 checkout this #1106 . download the files from that pull request and try it, see if it works. It worked for me

thank you very much! It worked!
