### ISSUE TITLE
希望作者能加入只显示CPU和内存占用，不显示网络的功能

### ISSUE THREAD

**Issue by ziranjiang** [zhongyang219/TrafficMonitor#121]
就是一个单纯的CPU和内存占用悬浮窗，希望作者能考虑下，谢谢！

**Comment by ui1840** [comment]
顶，单纯的CPU和内存占用，

**Comment by JasonKhew96** [comment]
#6

**Comment by zijungit** [comment]
> 就是一个单纯的CPU和内存占用悬浮窗，希望作者能考虑下，谢谢！
自己做一个皮肤,可以指定要显示哪些东西,就是你说的这个

**Comment by zijungit** [comment]
> 就是一个单纯的CPU和内存占用悬浮窗，希望作者能考虑下，谢谢！

自己做一个皮肤,可以指定要显示哪些东西,就是你说的这个,皮肤编辑器里有,可以直接选

**Comment by liper** [comment]
我倒是希望在任务栏也是这样，不显示网络速度。只看cpu和内存的占用

**Comment by ted423** [comment]
这软件不是叫TrafficMonitor么。。

**Comment by czarea** [comment]
+1
