### ISSUE TITLE
能否调节网速的刷新率？让网速显示更平滑

### ISSUE THREAD

**Issue by xuexiaokang** [zhongyang219/TrafficMonitor#123]
现在的网速刷新频率很低，网速跳跃幅度很大，能都修改刷新率，让网速显示更加平滑些呢

**Comment by KevinYu0504** [comment]
我也这么觉得，希望作者能够添加相关选项，让 TrafficMonitor 可以设置刷新的频率。

我个人觉得目前刷新的速度太快了，似乎是一秒更新一次，
若可以有设置选项，让使用者可以微调，例如 1秒、1.5秒、2秒 刷新一次 之类的功能会更好 :)

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/44945368-82b3bc00-ae1a-11e8-9798-ee2f9fc0d918.png)

**Comment by xuexiaokang** [comment]
刷新率太低，网速显示的很不平顺
