### ISSUE TITLE
22H2显示错误

### ISSUE THREAD

**Issue by NianBroken** [zhongyang219/TrafficMonitor#1232]
![image](https://user-images.githubusercontent.com/57057288/177800292-79c2df0e-5de7-4dc8-89a1-4d5ea44ceb9d.png)
------
![image](https://user-images.githubusercontent.com/57057288/177800072-e70e984f-967b-4232-8a44-5f80231bf00e.png)
------
![image](https://user-images.githubusercontent.com/57057288/177800149-a0ae7f2b-6208-4558-b1d3-7ee2b2452239.png)

**Comment by Er1cMa** [comment]
22H2通病，
https://github.com/GZTimeWalker/TrafficMonitor/actions/runs/2105106243
他fork了一个，我现在用这个是ok的，再次感谢@GZTimeWalker

**Comment by wonchong** [comment]
> 22H2通病， https://github.com/GZTimeWalker/TrafficMonitor/actions/runs/2105106243 他fork了一个，我现在用这个是ok的，再次感谢@GZTimeWalker

下载过期了

**Comment by GZTimeWalker** [comment]
> > 22H2通病， https://github.com/GZTimeWalker/TrafficMonitor/actions/runs/2105106243 他fork了一个，我现在用这个是ok的，再次感谢@GZTimeWalker
> 
> 下载过期了

#1106  已经更新过最新的下载

**Comment by mosiri** [comment]
过期了老哥 还有安装包吗？

**Comment by wonchong** [comment]
硬件检测 https://geek-wonchong.lanzouj.com/b0cx95qgh 密码:QuTMDBaiDu




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 下午5:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhongyang219/TrafficMonitor] 22H2显示错误 (Issue #1232)





 
过期了老哥 还有安装包吗？
