### ISSUE TITLE
I7-12700H 不显示CPU核心温度

### ISSUE THREAD

**Issue by FantasyDH** [zhongyang219/TrafficMonitor#1234]
版本：[x64_20220615_200410_TrafficMonitor](https://github.com/zhongyang219/TrafficMonitor/suites/6943699539/artifacts/270593350)
![20220709161457](https://user-images.githubusercontent.com/72923692/178097735-f0d01c0c-3c32-4cb8-813c-7ff4efc7ac18.jpg)
![20220709162117](https://user-images.githubusercontent.com/72923692/178097880-d5c199e5-ae35-45ef-8816-223bb6c9093e.jpg)

**Comment by liblaf** [comment]
似乎是 [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) 的问题, intel 12th gen CPU 温度无法正常显示.

**Comment by FantasyDH** [comment]
试了下替换Drop .NET 5.0 (out of support) master #136的dll，不止CPU连硬盘都不显示了，我还是老实等修复吧 - -

**Comment by lxw314** [comment]
这么久了也不更，不知道啥时候出个解决方案呀

**Comment by small32** [comment]
OpenHardwareMonitorLib好多年没更新了，不支持12代正常，TrafficMonitor的温度监控是基于这个库的

**Comment by kino516** [comment]
顶一个，希望修复

**Comment by Trigger-CN** [comment]
我的也是这样，坐等。。

**Comment by 330079598** [comment]
台式机12700k的温度可以正常显示，笔记本12700h不行，等修复！

**Comment by Zero2key** [comment]
从 nuget 下载预发布 LibreHardwareMonitorLib，提取并替换 LibreHardwareMonitorLib.dll

**Comment by FantasyDH** [comment]
> 从 nuget 下载预发布 LibreHardwareMonitorLib，提取并替换 LibreHardwareMonitorLib.dll ，就可以显示温度了

感谢！替换后完美解决！

**Comment by FantasyDH** [comment]
不对，nuget的lib虽然显示12代CPU温度了，但是SN770硬盘温度没了（选项看不到硬盘）。。。还是得等彻底修正了。。。

**Comment by small32** [comment]
> 从 nuget 下载预发布 LibreHardwareMonitorLib，提取并替换 LibreHardwareMonitorLib.dll ，就可以显示温度了

大佬好，您这边能方便提供一下您提取的这个DLL吗？非常感谢，可以的话发我邮箱smallstronge32@gmail.com谢谢！

**Comment by Trigger-CN** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/2675554299 可以下载他们build的产物

**Comment by charley008** [comment]
13代cpu遇到同样问题，替换LibreHardwareMonitorLib.dll 得到解决，大佬要不修复一下？
