### ISSUE TITLE
VS2017打开项目，看资源视图出现加载失败

### ISSUE THREAD

**Issue by lulei8** [zhongyang219/TrafficMonitor#124]
程序能正常编译运行，但是就是打开资源视图的时候会出现这个报错：
未能正确加载 Visual C++ Resource Editor Package
求助作者，有什么解决办法吗？

**Comment by lulei8** [comment]
<entry>
    <record>891</record>
    <time>2018/08/20 02:30:04.629</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>No InprocServer32 registered for package [Visual C++ Resource Editor Package]</description>
    <guid>{74AAD8B2-3294-49CB-BB5D-E9BAB132BFD5}</guid>
    <hr>8007007f</hr>
    <errorinfo></errorinfo>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\vcpackages\resedit.dll</path>
  </entry>``

**Comment by zhongyang219** [comment]
建议重新安装Visual Studio
