### ISSUE TITLE
开启显卡监控后网速显示为实际的双倍

### ISSUE THREAD

**Issue by DearTanker** [zhongyang219/TrafficMonitor#1263]
系统：Windows 11 专业版 21H2 正式版，系统自动更新，运行库完整。

前几天才突然出现网速显示翻倍的问题，不知道是不是最近的某个系统更新导致的。因为程序本身并没有更新过版本，而且没有去调整过设置。

今天重新下载了1.46版本后，看到网速显示正常，就从头开始配置了一遍，等配置完以后又发现网速显示翻倍了，于是一个个排查，最终发现，只要关闭硬件监控中的显卡监控，网速显示就正常了。

PS，顺便还发现，当速度显示超过 100M 时，最后一位的 s 不管怎么改显示设置都不会显示。

附图1，关闭显卡监控，网速显示正常。

![附图1，关闭显卡监控，网速显示正常](https://user-images.githubusercontent.com/1122669/182543279-b7745bdb-f40f-4bf2-8803-9486276004e0.jpg)

附图2，开启显卡监控，网速显示翻倍。

![附图2，开启显卡监控，网速显示翻倍](https://user-images.githubusercontent.com/1122669/182543401-aca19436-8fe0-47a3-9af9-5580919e01d6.jpg)

**Comment by fullmoon530** [comment]
和你一样的问题，我的网速显示翻了两三倍，关了显卡监控就好了，而且之前显卡都有占用显示，有一次更新系统之后就不显示占用率了，很奇怪

**Comment by zhongyang219** [comment]
暂时没有复现出你说的问题，目前不清楚是什么原因造成的，按理说网速监控和显卡监控这两个八竿子打不着的功能不应该会有任何影响的。

**Comment by DearTanker** [comment]
最近升级到最新的1.84版后，这问题再次出现了。

**Comment by DearTanker** [comment]
@zhongyang219 @rocinante027 终于找到原因了。

【常规设置】-【监控时间间隔】改成200ms，点击【确定】会关闭选项设置窗口，这时候会测速一下就发现网速显示双倍了。

只要是设置 300ms 及以上，就正常。

**Comment by FlandreSatori** [comment]
遇到相同的情况，开启显卡监控后网速变为两倍，关闭显卡监控后甚至飙升到10倍（千兆网口跑出五千兆），目前还没定位到问题
![image](https://github.com/user-attachments/assets/dc3504e4-6bef-49a8-a59f-98432df65f07)

**Comment by Dexxxxxxxxxxx** [comment]
1.86版本还是会出现双倍的问题，默认值已经是1000了，怎么调整都会稳定双倍，关闭显卡监控也没用。。win11.

<img width="1173" height="1224" alt="Image" src="https://github.com/user-attachments/assets/e13ff25f-2af9-4fad-be43-d50402195356" />
