### ISSUE TITLE
12号主题非常棒，我特别的喜欢，但我想提一个大部分强迫症患者都难以接受的问题。

### ISSUE THREAD

**Issue by wlc743859910** [zhongyang219/TrafficMonitor#1265]
就是这个上传跟下载能不能居中显示？
![image](https://user-images.githubusercontent.com/84552324/182576132-f5a7c0dd-6610-4268-8eec-5cd8e800b8ef.png)

**Comment by Haojia521** [comment]
打开文件`...\TrafficMonitor\skins\皮肤12\skin.xml`，找到`layout`代码块，将`up`和`down`标签的`align`属性值0改为2（0、1和2分别对应左对齐、右对齐和居中，参考[皮肤编辑教程](https://github.com/zhongyang219/TrafficMonitor/wiki/%E7%9A%AE%E8%82%A4%E5%88%B6%E4%BD%9C%E6%95%99%E7%A8%8B)），如下所示
```
<root>
  ...
  <layoyt text_height="20" no_label="0">
    <layout_l width="232" height="107">
      ...
      <up x="14" y="27" width="106" align="2" show="1"/>
      <down x="122" y="27" width="106" align="2" show="1"/>
      ...
    </layout_l>
    ...
  </layout>
  ...
</root>
```
然后修改为其他皮肤再改回皮肤12，上传和下载文本就居中显示了

**Comment by wlc743859910** [comment]
OK 解决了
