### ISSUE TITLE
这么多的网络连接正常吗？

### ISSUE THREAD

**Issue by aecra** [zhongyang219/TrafficMonitor#1278]
![image](https://user-images.githubusercontent.com/34883050/184542381-2821d0c1-2043-4aab-ba41-6506b3aca741.png)

![image](https://user-images.githubusercontent.com/34883050/184542396-687cc06e-be59-4525-b06f-9be1213f71ea.png)

不知道干了啥就这么多网络连接了，😭

**Comment by FelixAce** [comment]
试试“常规设置“里取消勾选“显示所有网络连接”。

**Comment by aecra** [comment]
@FelixAce 感谢，好了
