### ISSUE TITLE
请问使用vs2022如何编译

### ISSUE THREAD

**Issue by B4night** [zhongyang219/TrafficMonitor#1286]
我是一个编程菜鸟, 轻喷
我使用vs2022编译的时候遇到了如下问题
![image](https://user-images.githubusercontent.com/70550570/185590902-62be02fa-780a-46d5-837b-af62cd1da5cf.png)
请问怎样才能从源代码编译出一个可执行文件, 求大佬指教QAQ

**Comment by lingr7** [comment]
可以试试看看https://github.com/zhongyang219/TrafficMonitor/blob/master/.github/workflows/main.yml
这个workflows里面的操作，这个构建流程就是vs2022的，然后看看能不能在本地做类似的操作。
不过要理解workflows，还是比较费力的，只是提一下，我遇到这种问题产生的想法。

**Comment by B4night** [comment]
搞了几小时, 原来是没有装MFC库, 几百个error看的我心累....workflow看得也不是很懂...不过还是谢谢大佬能对我一个小菜鸟这么友好 感恩!
