### ISSUE TITLE
Windows11任务栏字体显示异常

### ISSUE THREAD

**Issue by liulanglang22** [zhongyang219/TrafficMonitor#1289]
![image](https://user-images.githubusercontent.com/49188938/186223797-9c2c9f61-8a1d-4301-8e84-7bacdde22973.png)
如果任务栏设置为透明一定会出现这个问题，字体会闪一下然后变正常，没找到解决办法我关闭了任务栏透明，结果发现如果屏幕上有半透明的蒙层导致任务栏改变颜色，这时蒙层下面的文字显示就是不正常的，关闭蒙层之后任务栏上的文字也会刷新一下之后会显示正常。
![image](https://user-images.githubusercontent.com/49188938/186224443-544bd8ee-637d-4f20-91bc-e5d3ce196463.png)
这是正常显示的字体
蒙层的出现可以是截图的时候，截图不框选任务栏那任务栏上就是有一层蒙层覆盖的，这时候退出任务栏上的字体就会闪一下

**Comment by BombaxCeiba** [comment]
试试这个 #1156

**Comment by liulanglang22** [comment]
这个可以，赞
