### ISSUE TITLE
系统崩溃后 TrafficMonitor 个人化设置会消失

### ISSUE THREAD

**Issue by KevinYu0504** [zhongyang219/TrafficMonitor#129]
@zhongyang219 您好 !

最近一两周使用您的 TrafficMonitor 感到相当满意，
但遇上个问题，由于我这台老电脑的硬件老旧，有时会遇到突发性系统崩溃，
当我重启系统后，有几次 TrafficMonitor 的所有个人化的设置都会消失，
变回软件刚安装时预设的样子。
虽然不是每次重启系统都会这样，但已经发生过三、四次了。

但若此时查询历史流量纪录，都还是在的，并未消失，
只有个人化的设置全不见。

查询了一下 AppData\Roaming\TrafficMonitor 目录底下的 error.log，
里面只有其他一些不相关的错误讯息而以。

不知此状况是否正常 ?

感谢。

**Comment by zhongyang219** [comment]
这个问题确实存在，这似乎并不是TrafficMonitor的问题而是Windows的问题，我也曾经出现过一次这个问题，不仅仅是TrafficMonitor，其他软件也出现过配置丢失的问题。似乎系统崩溃会导致AppData目录下的一些配置文件丢失。
后续版本我会考虑增加选项设置允许用户选择将配置保存在程序所在目录下还是AppData目录下。
目前的情况下，如果你的系统经常崩溃，建议经常备份AppData\Roaming\TrafficMonitor文件夹。

**Comment by KevinYu0504** [comment]
@zhongyang219 谢谢你 !

我系统常崩溃的问题已经获得解决，是硬件的异常造成，
目前更换后已经完全正常，运行好几天都不会再有问题了。

感谢您的解释，期待以后软件的设置可以备份甚至云化 :)
