### ISSUE TITLE
谢谢开发分享好软件，能否新版加一个选项可以把设置文件设程序目录下，以实现便携化？谢谢

### ISSUE THREAD

**Issue by houxiren** [zhongyang219/TrafficMonitor#130]
谢谢开发分享好软件，能否新版加一个选项可以把设置文件设程序目录下，以实现便携化？谢谢

**Comment by zhongyang219** [comment]
你好，感谢建议，这个功能已经在考虑了。

**Comment by zixu5u** [comment]
我也希望有这个功能。
我在公司电脑用这个软件，软件配置文件默认保存到C盘，但公司电脑重启后C盘文件会重置，我想将配置文件保存到D盘（D盘不会重置）。

**Comment by Sod-Momas** [comment]
> 你好，感谢建议，这个功能已经在考虑了。

这个功能在新版已经实现了吧好像，但导致了旧版配置文件没有删除的时候直接打开新版程序会出栏窗口不出现的问题， 不知道是不是我这边偶然出现的情况呢。

我觉得可以考虑第一次打开的时候检测一下旧配置文件，存在就复制过来然后删除%UserProfile%下的旧目录。
