### ISSUE TITLE
win10 X64版本 双击EXE文件后无任何反应

### ISSUE THREAD

**Issue by Capleaves** [zhongyang219/TrafficMonitor#1308]
无论是Lite版本还是普通版本 双击exe文件后都无反应 任务管理器没看到进程 杀毒软件也关了

**Comment by BombaxCeiba** [comment]
[最新支持的 Visual C++ 可再发行程序包下载 | Microsoft Docs](https://docs.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by Capleaves** [comment]
用源代码编译后的程序可以用，已解决。暂时不知道一开始遇到的问题是什么原因，在其他电脑上并没有出现这种情况。
