### ISSUE TITLE
Windows 11 上无法启动

### ISSUE THREAD

**Issue by ZTfred** [zhongyang219/TrafficMonitor#1314]
管理员权限启动会弹出微软商店，但是没有任何程序信息，无法使用，辛苦看下如何处理
![image](https://user-images.githubusercontent.com/53425107/192127524-a39bdea5-3992-4255-a408-c70fc0cd6fa8.png)
![image](https://user-images.githubusercontent.com/53425107/192127529-35c6bf64-daf4-409d-99ca-1c3fd15e41b1.png)

**Comment by alishojaeix** [comment]
what is this?

**Comment by ZTfred** [comment]
> what is this?

can't run this program on my computer

**Comment by alishojaeix** [comment]
apt update
