### ISSUE TITLE
I also have this problem since I updated my computer to Win11 22H2. 

### ISSUE THREAD

**Issue by mohit505** [zhongyang219/TrafficMonitor#1316]

**Comment by mohit505** [comment]
plz fix this issue now I am waiting for this fix.

**Comment by Mameng57** [comment]
taskbar widget overflow to the center

**Comment by shierro** [comment]
![z8upJQ1eRw](https://user-images.githubusercontent.com/12129589/192757916-6db1c4a0-43cf-4d9a-8e16-ed31413516c9.png)

Looks like this on my end

**Comment by UsamaAshraf82** [comment]
https://github.com/zhongyang219/TrafficMonitor/pull/1106#issuecomment-1256947945

Download this Update

**Comment by injamulhaque535** [comment]
@UsamaAshraf82 Thank you so much, it is working

**Comment by vilasboas** [comment]
> [#1106 (comment)](https://github.com/zhongyang219/TrafficMonitor/pull/1106#issuecomment-1256947945)
> 
> https://github.com/GZTimeWalker/TrafficMonitor/suites/7291383559/artifacts/294066192 https://github.com/GZTimeWalker/TrafficMonitor/suites/7291383559/artifacts/294066194
> 
> Download this Update

Thanks, worked for me.

**Comment by mohit505** [comment]
@UsamaAshraf82 
This is the safe version to use this?
