### ISSUE TITLE
TrafficMonitor在Windows11最新季度更新22H2的显示问题

### ISSUE THREAD

**Issue by Elviserum** [zhongyang219/TrafficMonitor#1317]
![J6M{F0`I`BK_WWT{C`_C8LF](https://user-images.githubusercontent.com/108270919/192735024-007e97e1-4700-4a0f-be60-68c7e92f9f41.png)
如图，原来选择图标居中显示会正常的显示在左下角，现在会和图标粘在一起

**Comment by HowardKwan** [comment]
同样遇到此问题

**Comment by ChengDolan** [comment]
I have the same issue. Please repair ASAP. @zhongyang219

**Comment by Elviserum** [comment]
> 

感谢
