### ISSUE TITLE
win11 22H2 正式版  请求适配

### ISSUE THREAD

**Issue by SouLXH** [zhongyang219/TrafficMonitor#1329]
![image](https://user-images.githubusercontent.com/44329481/193440185-2d951b73-8663-4c07-ac62-2a4053705c1a.png)
![image](https://user-images.githubusercontent.com/44329481/193440192-a0ab269a-5678-445e-bde3-3d0e93a82736.png)

**Comment by imfinethanks** [comment]
+1
![1664690338583](https://user-images.githubusercontent.com/36071470/193440263-70c71d9a-f524-41dd-84b5-53a579edd6a6.png)

**Comment by PatZer0** [comment]
+1

**Comment by IzayoiAster** [comment]
+1

**Comment by MichaelChen2019** [comment]
> ![图片](https://user-images.githubusercontent.com/44329481/193440185-2d951b73-8663-4c07-ac62-2a4053705c1a.png) ![图片](https://user-images.githubusercontent.com/44329481/193440192-a0ab269a-5678-445e-bde3-3d0e93a82736.png)

https://github.com/zhongyang219/TrafficMonitor/actions/runs/3163167888

**Comment by SouLXH** [comment]
![image](https://user-images.githubusercontent.com/44329481/193461240-904ea85e-2c2d-49d4-b5a9-41ad7ce1c0e1.png)
win11 22h2 的用这个，测试过可以用
https://github.com/zhongyang219/TrafficMonitor/actions/runs/3163167888
