### ISSUE TITLE
win11 22H2 最新版不打开任何窗口 显示错位

### ISSUE THREAD

**Issue by Vickylhz** [zhongyang219/TrafficMonitor#1339]
![image](https://user-images.githubusercontent.com/84019720/194079642-e0e54539-ed2f-4e2e-a341-0a6011c1d2d2.png)
打开任何一个窗口或者固定一个软件在任务栏就恢复
![image](https://user-images.githubusercontent.com/84019720/194079944-213b9141-e315-415f-b1ec-be0ce9744328.png)

**Comment by ysway** [comment]
成功复现。任务栏有应用窗口的时候就显示正常，无窗口的时候就会出现此问题。
