### ISSUE TITLE
V1.84 在Win11 22H2中依旧打开旧版任务管理器

### ISSUE THREAD

**Issue by XuShenLZ** [zhongyang219/TrafficMonitor#1345]
今天刚更新了Win 11 22H2，通过开始菜单右键打开任务管理器已经是新版了。

![image](https://user-images.githubusercontent.com/31999415/194114607-c0f1be30-02dc-4968-ae7b-ddba4e5a4c16.png)

但通过TrafficMonitor右键菜单点开仍然为旧版

![1664987968717](https://user-images.githubusercontent.com/31999415/194114872-09e42f37-cd60-4e11-b8e9-0510e67bdb69.jpg)

![image](https://user-images.githubusercontent.com/31999415/194114930-97d3a774-b1ca-4662-afac-b6e7c17762eb.png)

安装的版本为v1.84_x86

**Comment by XuShenLZ** [comment]
更换到了x64版本，已解决

**Comment by Shubham123498765** [comment]
![image](https://user-images.githubusercontent.com/82265932/194222560-750e0dd3-cb6d-40c6-852f-5c75f3bf8e63.png)
iS THIS SAFE
