### ISSUE TITLE
1.8.4设置任务栏窗口显示在左侧无效

### ISSUE THREAD

**Issue by AdoShan** [zhongyang219/TrafficMonitor#1346]
系统21H1，无法将任务栏窗口设置到左侧。

**Comment by Edelweissor** [comment]
+1,靠的是右侧

**Comment by zhongyang219** [comment]
在1.84版本中，如果任务栏窗的对齐方式为左对齐时，则任务栏窗口总是显示在右侧，因为显示在左侧时会和任务栏原来的按钮重叠。
而程序检测任务栏对齐方式是通过读取注册表`\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced`下`TaskbarAl`的键值来获取的，但是如果你从来没有更改过任务栏的对齐设置，这个键值就不存在，此时TrafficMonitor会误以为任务栏是左对齐，这是一个bug。解决的办法是：
在任务栏在点击鼠标右键，选择任务栏设置，更改一次任务栏对齐方式，生成以上键值后，比如将“居中”改为“左对齐”，再改回“居中”就好了。
![image](https://user-images.githubusercontent.com/30562462/194207375-f421a83f-ee92-4f5e-9bd9-403341831060.png)

**Comment by CNYoki** [comment]
ThanksThanks

**Comment by AdoShan** [comment]
感谢。已解决

**Comment by zhanghean** [comment]
感谢！！！

**Comment by nekomiya-hinata** [comment]
已解决！！

**Comment by Charles920421** [comment]
![Snipaste_2022-10-12_14-04-38](https://user-images.githubusercontent.com/106381025/195262819-47471047-de16-4755-b6b8-3657b3667032.jpg)
我的电脑是这样子的

**Comment by thomasloto** [comment]
Good

**Comment by long45343** [comment]
万分感谢！！！！！！

**Comment by dandanzou-hust** [comment]
大佬大佬！专业！

**Comment by yudi126** [comment]
勾选显示虚线框，cpu频率没虚线框

**Comment by Charles920421** [comment]
> > ![Snipaste_2022-10-12_14-04-38](https://user-images.githubusercontent.com/106381025/195262819-47471047-de16-4755-b6b8-3657b3667032.jpg) 我的电脑是这样子的
> 
> 任务栏最左侧的空白是为了防止和Win11自带的天气重叠的，那个空白的宽度可以通过修改配置文件调整，在配置文件[task_bar]下面的taskbar_left_space_win11。 在Win11任务栏设置中关闭“小组件”的显示就没有那个空白了。

感谢
