### ISSUE TITLE
1.84版本在22H2上的任务栏窗口貌似仍然存在问题

### ISSUE THREAD

**Issue by Hikarizon** [zhongyang219/TrafficMonitor#1356]
如题，1.84版本的任务栏窗口在任务栏中有程序图标的时候是正常的，但当没有程序图标则会会显示不全。
![A](https://user-images.githubusercontent.com/112762339/194270922-0e3c4eee-1095-4e7d-a710-9aac4ac5a19c.png)
![B](https://user-images.githubusercontent.com/112762339/194271034-889ba021-33e9-46c9-92cc-c8cf26f456f0.png)
而“搜索”之类能够在“任务栏设置”中添加到任务栏的图标则不会改善这一问题。
![D](https://user-images.githubusercontent.com/112762339/194274594-a68489f9-2deb-41c2-98b4-d7d9e364a33d.png)
![E](https://user-images.githubusercontent.com/112762339/194274631-356eaba4-5987-4754-bb84-54cd1820e7ef.png)
系统版本为22621.608
![C](https://user-images.githubusercontent.com/112762339/194271124-bbd77d7d-6343-4bc4-ae1a-52612c4234f5.png)

**Comment by amtra** [comment]
Same issue. After i pinned calculator in taskbar it appears Normal.
**may be it will be a little workaround for this issue.**

Before
![Before](https://user-images.githubusercontent.com/9961395/194508343-0325199d-606e-4068-8f88-78c49b6330e2.jpg)

After Pining Calculator
![After Pinning App](https://user-images.githubusercontent.com/9961395/194508403-c5ba0814-07d1-4784-91cc-65b4f253ff2b.jpg)

**Comment by zhongyang219** [comment]
现在问题应该已经解决了，请到[Actions](https://github.com/zhongyang219/TrafficMonitor/actions)页面下载最新编译的版本，看看问题是否已解决。

**Comment by Hikarizon** [comment]
> 现在问题应该已经解决了，请到[Actions](https://github.com/zhongyang219/TrafficMonitor/actions)页面下载最新编译的版本，看看问题是否已解决。

感谢大佬，问题已经解决
