### ISSUE TITLE
1.84 taskbar issue

### ISSUE THREAD

**Issue by fawzynahwi** [zhongyang219/TrafficMonitor#1362]
after both 22H2 update and 1.84 update, the meter is showing next to start icon and wont go to the far left.
![image](https://user-images.githubusercontent.com/52822428/194465943-fda8e8d8-1f7a-4468-9c20-78b2830b3f6a.png)

**Comment by soloopooo** [comment]
#1346

**Comment by fawzynahwi** [comment]
> #1346
> 
> This is Chinese version. You can use Google translator.

Hi, I tried what he suggested but the left align works for me. Only not to the far left only left of start icon. its not solved for me

**Comment by soloopooo** [comment]
> 

![图片](https://user-images.githubusercontent.com/36123081/194468701-0f34ba52-778d-4cfb-8133-20265340abb9.png)

I don't know if you deselected this.

**Comment by fawzynahwi** [comment]
> > 
> 
> ![picture](https://user-images.githubusercontent.com/36123081/194468701-0f34ba52-778d-4cfb-8133-20265340abb9.png)
> 
> I don't know if you deselected this.
> 
> ![picture](https://user-images.githubusercontent.com/36123081/194468785-ccde7d5d-2a83-4280-8ffb-aeb14e3f008d.png)

I could've sworn I tried it before and it didnt work. Anyways thank you!

**Comment by soloopooo** [comment]
I think maybe both doing #1346 and this deselection solved that problem.
So without doing #1346 this deselection couldn't work.
@fawzynahwi
