### ISSUE TITLE
1.84版，任务栏上没有其它应用时显示会错位

### ISSUE THREAD

**Issue by cnkmmk** [zhongyang219/TrafficMonitor#1370]
![图片](https://user-images.githubusercontent.com/22782790/194704703-215654ea-056e-444f-bab8-4df57800129e.png)

只要任务栏上有一个应用，显示就是正常的。

**Comment by wonchong** [comment]
https://github.com/zhongyang219/TrafficMonitor/actions/runs/3204530520

在最新的构建中已经解决了这个问题
