### ISSUE TITLE
Long-click on touchscreen is not handled on taskbar window

### ISSUE THREAD

**Issue by ValdikSS** [zhongyang219/TrafficMonitor#1379]
Version: 1.84 lite.

I'm using Microsoft Surface Go tablet with touchscreen.
Touching and holding works as a right-click in any other program, however on TrafficMonitor's taskbar element it does not work as a right-click, showing no program's menu.

**Comment by zhongyang219** [comment]
Thanks for your feedback, this issue has been fixed now.

**Comment by ValdikSS** [comment]
Yes, thanks, it's working now. I've tested Github CI build.
