### ISSUE TITLE
1.84版本出现的问题

### ISSUE THREAD

**Issue by Dashan-IZ** [zhongyang219/TrafficMonitor#1380]
1.84版本貌似出现了任务栏不能靠左的问题

**Comment by DreamL** [comment]
我遇到了同样的问题, 在Win11 22H2 22621的Release上, 使用V1.84, 设置任务栏窗口在任务栏左侧无效, 但是在更高版本的Win11 22H2 25217 Insider Preview上,同样使用V1.84,却可以正常居左...

**Comment by GunVeda** [comment]
解决方式
https://github.com/zhongyang219/TrafficMonitor/issues/1346#issuecomment-1269261932

**Comment by DreamL** [comment]
> 解决方式 [#1346 (comment)](https://github.com/zhongyang219/TrafficMonitor/issues/1346#issuecomment-1269261932)

解决了, 感谢!
