### ISSUE TITLE
首先表示感谢 再冒昧地提个问题

### ISSUE THREAD

**Issue by EverybodyDiesInTheirNightmares** [zhongyang219/TrafficMonitor#14]
您好 我是一个计科大一新生 当初在贴吧里偶然发现了TrafficMonitor 觉得非常实用 但我感觉现在自己什么都没学到 想问问您花了多少时间来实现TrafficMonitor的主要功能//就是单纯地问问

**Comment by zhongyang219** [comment]
这个软件最早是从2017年2月开始编写的，都是利用业余时间在做。就实现主要的功能（网速、CPU和内存使用监控）大概花了一个月左右的时间吧，当然并不是连续的一个月的时间，有灵感的时候就写。一开始的时候更新得很频繁，感觉要做的东西很多，后来不知道还需要增加什么功能，就更新得很慢，去年经常隔好几个月才更新一次。在写这个软件的过程中，也有很多网友向我提出了很多改进的建议，以及bug的反馈。另外，在开发过程中也遇到过很多问题，最后通过上网找资料基本都解决了，其中csdn论坛和博客，以及微软的MSDN网站给了我很大的帮助。
你现在才大一，不用着急，关键要先把基础打好，最好能认真学好一门编程语言，再可以试着自己编写一些简单的小软件，凡事都是从简单的开始的。学软件就要多动手写代码，自己动手写代码、调试代码能够学到很多光看书学不到的东西。

**Comment by cs-zhuxudong** [comment]
好的 多谢前辈！
