### ISSUE TITLE
希望增加的一些功能

### ISSUE THREAD

**Issue by mlgexyz** [zhongyang219/TrafficMonitor#141]
1. 
需求：保存用户调整后的窗口大小以及列表框的宽度布局
窗口：历史流量统计（连接详情也是，只不过不常用）

↓不然像我这种强迫症&流量狂魔有几天的小流量看不清就很难受↓
![default](https://user-images.githubusercontent.com/21287731/45584915-4f8b2580-b90e-11e8-8528-1144daaeed86.png)

2. 
需求：自定义图表颜色的对应值域，不然我这边基本上全是黄和红_(:3」∠)_
窗口：历史流量统计

**Comment by zhongyang219** [comment]
如果因为每天流量数据差别太大导致一些流量太少的看不清，可以右击“图表”列的表头，在“显示比例”菜单中选择“对数比例”就可以了。
![2018-09-22_](https://user-images.githubusercontent.com/30562462/45912238-88685480-be50-11e8-80a1-c608d9cbbba0.png)
这个功能比较隐藏，可能不太容易发现~

**Comment by mlgexyz** [comment]
哇还真没触发过这个右键事件，现在改成对数拟合后舒服多了
