### ISSUE TITLE
Left alignment no longer works

### ISSUE THREAD

**Issue by Brummell67** [zhongyang219/TrafficMonitor#1412]
![image](https://user-images.githubusercontent.com/5261273/199257590-f7edd5bc-a2bc-4112-9439-c467d5464528.png)

**Comment by BenjiaH** [comment]
> In version 1.84, if the taskbar window is aligned to the left, the taskbar window will always appear on the right because it overlaps the original taskbar button when shown on the left.
The program detects taskbar alignment by reading the key value of "TaskbarAl" in the registry "\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced". But if you never change the alignment settings of the taskbar, this key is not exist and TrafficMonitor mistakenly thinks the taskbar is left aligned. This is a bug. The solution is:
Click the right mouse button in the taskbar, select Taskbar Settings, and change the alignment method of the taskbar once. After generating the above key value, for example, change "center" to "Align left", and then change it back to "center".
![image](https://user-images.githubusercontent.com/46958476/201475995-167c5785-5933-40e2-96ab-8a23ae08c023.png)

See: https://github.com/zhongyang219/TrafficMonitor/issues/1346#issuecomment-1269261932

**Comment by Brummell67** [comment]
It work now!
Thank so much.
