### ISSUE TITLE
win11 任务栏模式打开应用时显示正常，关闭所有应用时显示错位

### ISSUE THREAD

**Issue by icheto** [zhongyang219/TrafficMonitor#1434]
这是打开edge浏览器时的正常任务栏情况
![image](https://user-images.githubusercontent.com/72912780/201509677-0224a16c-482b-4d78-98b0-9e20dd8e8610.png)
这是没有打开窗口的任务栏错位情况
![image](https://user-images.githubusercontent.com/72912780/201509707-a7c8c443-5038-4b55-a84f-298614e85ef5.png)

**Comment by x-researcher** [comment]
Win11 22H2. Same problem, waiting for a fix.
