### ISSUE TITLE
如何清空/重置历史流量统计？

### ISSUE THREAD

**Issue by LinJinkang** [zhongyang219/TrafficMonitor#1452]
把"F:\TrafficMonitor\history_traffic.dat"删了还是有
![image](https://user-images.githubusercontent.com/54579927/203753468-d426428c-af71-4b60-99dc-a6307dd4b1e5.png)
![image](https://user-images.githubusercontent.com/54579927/203753566-6ff311ad-2d8a-49e4-af47-68b42e48f4c2.png)

**Comment by qwertyue** [comment]
应该是要同时把history_traffic.dat和history_traffic.dat.dak都删掉
