### ISSUE TITLE
CPU temperature of new 13th Gen Intel CPU not displayed

### ISSUE THREAD

**Issue by multimill** [zhongyang219/TrafficMonitor#1456]
Hello,

I just got a new Intel 13th Gen CPU (13600K) and the temperature is not being displayed in taskbar. I had a 12400F before and it was just perfectly fine. LibreHardwaremonitor can read the temperatures just fine:

![Screenshot 2022-11-26 140718](https://user-images.githubusercontent.com/24725624/204090596-c8e4db28-ca18-42a9-9b6b-17d7e76a0b7d.png)

The CPU usage is displayed. I am using Win 11 22H2 (updated with newest updates). Just let me know if you need any more information about the system or any logs etc.

**Comment by lingyired** [comment]
Please try https://github.com/zhongyang219/TrafficMonitor/pull/1414

**Comment by multimill** [comment]
> Please try #1414

This solved the issue! Thanks!
