### ISSUE TITLE
[BUG] 当没有应用时，状态栏会向上偏移一部分

### ISSUE THREAD

**Issue by lolisTop** [zhongyang219/TrafficMonitor#1487]
> 系统版本 
```
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎12/‎12
操作系统版本	22621.819
体验	Windows Feature Experience Pack 1000.22636.1000.0
```
> 当开始菜单旁没有应用时，状态栏会向上偏移一部分 

![image](https://user-images.githubusercontent.com/21169304/206970811-a7e5f65c-2a7c-43cd-9817-7d8fb8aad054.png)
> 当开始菜单旁存在应用【chrome、vscode等】时则会正常 

![image](https://user-images.githubusercontent.com/21169304/206970898-645f99db-d409-4916-9815-1e1c66bf3a4b.png)

**Comment by xun-mi-git** [comment]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎5/‎13
操作系统版本	22623.1037
体验	Windows Feature Experience Pack 1000.22638.1000.0

![寻觅_20221222202414](https://user-images.githubusercontent.com/43723838/209133994-1d45b91c-350e-423b-80d9-f38366af7ded.png)
我也碰到了类似的问题,我是无论是否存在应用都会这样

**Comment by comandosne** [comment]
请问有什么解决方法么
