### ISSUE TITLE
部分字体在任务栏处在白色背景下发虚

### ISSUE THREAD

**Issue by 1818yu** [zhongyang219/TrafficMonitor#1508]
微软雅黑-白色背景（发虚）
![HQRZWVJMAf](https://user-images.githubusercontent.com/56754498/211191839-d7c37b98-6181-4002-bc9a-f9106edb6839.gif)
宋体-白色背景（正常）
![p3Cy95F7GF](https://user-images.githubusercontent.com/56754498/211191863-8e870fc2-8af0-48ab-9b42-f905aeda546b.gif)
微软雅黑-黑色背景（正常）
![ApplicationFrameHost_haAeySZW0h](https://user-images.githubusercontent.com/56754498/211191870-31e97354-e800-4d39-8713-1b48d65a4652.gif)

使用了TranslucentTB将任务栏的材质由**云母**改成了**亚克力**

**Comment by BombaxCeiba** [comment]
#1156 
试试这个
