### ISSUE TITLE
win10 22h2开启hdr与背景透明后无法显示任务栏窗口

### ISSUE THREAD

**Issue by hexoctal-sur** [zhongyang219/TrafficMonitor#1563]
![QQ截图20230319150748](https://user-images.githubusercontent.com/13842432/226159769-471a98c3-494f-4405-a843-e03b3d57b055.jpg)
![image](https://user-images.githubusercontent.com/13842432/226159788-fcfd9468-e26e-4b77-a33d-8f54c1543fba.png)

**Comment by CurtisWong458** [comment]
> 

哪一个是下载链接啊？

**Comment by CurtisWong458** [comment]
> 建议试一下最新编译的版本，并勾选D2D渲染 ![image](https://user-images.githubusercontent.com/31007907/226381139-1ad4693e-e6be-45b2-8a5f-7cd3a54db63e.png)
> 
> https://github.com/zhongyang219/TrafficMonitor/actions 如果出现问题，请上传程序配置文件所在路径下的error.log（若存在）
> 
> 注：Appdata下的配置文件路径为C:\Users<用户名>\AppData\Roaming\TrafficMonitor\

哪一个是下载链接啊

**Comment by BombaxCeiba** [comment]
> > 建议试一下最新编译的版本，并勾选D2D渲染 ![image](https://user-images.githubusercontent.com/31007907/226381139-1ad4693e-e6be-45b2-8a5f-7cd3a54db63e.png)
> > https://github.com/zhongyang219/TrafficMonitor/actions 如果出现问题，请上传程序配置文件所在路径下的error.log（若存在）
> > 注：Appdata下的配置文件路径为C:\Users<用户名>\AppData\Roaming\TrafficMonitor\
> 
> 哪一个是下载链接啊

https://github.com/zhongyang219/TrafficMonitor/actions/runs/4468275475
在页面下方的Artifacts中。

**Comment by hexoctal-sur** [comment]
> > > 建议试一下最新编译的版本，并勾选D2D渲染 ![image](https://user-images.githubusercontent.com/31007907/226381139-1ad4693e-e6be-45b2-8a5f-7cd3a54db63e.png)
> > > https://github.com/zhongyang219/TrafficMonitor/actions 如果出现问题，请上传程序配置文件所在路径下的error.log（若存在）
> > > 注：Appdata下的配置文件路径为C:\Users<用户名>\AppData\Roaming\TrafficMonitor\
> > 
> > 
> > 哪一个是下载链接啊
> 
> https://github.com/zhongyang219/TrafficMonitor/actions/runs/4468275475 在页面下方的Artifacts中。

这个版本修复了这个bug
