### ISSUE TITLE
Win10下开启HDR和背景透明后整个任务栏显示界面会消失

### ISSUE THREAD

**Issue by goldenapple1** [zhongyang219/TrafficMonitor#1576]
如果只靠标题信息无法复现，尝试按照translucentTB并调整至完全透明状态。

**Comment by BombaxCeiba** [comment]
参考 #1563 下的回复

**Comment by goldenapple1** [comment]
太感谢了，问题已解决，但在新编译的版本下似乎出现了在勾选“背景透明”且不勾选“根据任务栏颜色自动设置背景

色”时，无法自动切换到Direct2D渲染模式的问题，在我手动切换之后，问题已经完美解决。
