### ISSUE TITLE
发现的两处英文翻译上的问题

### ISSUE THREAD

**Issue by Windsrise** [zhongyang219/TrafficMonitor#159]
1. 

![dllhost_2018-11-22_09-15-03](https://user-images.githubusercontent.com/29052969/48876044-1f449380-ee37-11e8-9041-dbe49bd6f728.png)
menory 应为memory

2. 

![trafficmonitor_2018-11-22_09-13-07](https://user-images.githubusercontent.com/29052969/48876050-28356500-ee37-11e8-9095-627ca9e40004.png)
windows start 应为windows starts

**Comment by zhongyang219** [comment]
感谢指正，我会在下个版本改正。
