### ISSUE TITLE
【BUG】手机USB共享网络

### ISSUE THREAD

**Issue by zhaosj98** [zhongyang219/TrafficMonitor#160]
使用手机USB共享网络时(电脑通过手机USB共享的网络上网)，TrafficMonitor卡慢无响应，如果显示在任务栏里也会导致整个任务栏出现卡慢无响应的情况，关闭USB共享网络后则没有这一情况出现。更严重的问题是，使用USB共享网络时如果开启TrafficMonitor会导致网络无法访问。

操作系统：Win7 x86_64

**Comment by zhongyang219** [comment]
这是Windows的BUG，和TrafficMonitor无关。

**Comment by qwec01** [comment]
同样的问题，请问这个Windows的BUG，有MS的官方说明吗？
