### ISSUE TITLE
Win11从平板模式切换为正常模式后，任务栏窗口的位置出现异常

### ISSUE THREAD

**Issue by Hovn** [zhongyang219/TrafficMonitor#1604]
环境：
翻转触控本，Win11，TrafficMonitor 1.84.1 Lite版

BUG出现场景：
1、360度翻转屏幕后，Win11默认会切换为“平板模式”（部分UI将变大变宽），系统设置中会多出一个选项。本应用也会调整位置并居中。如图1。
2、再次恢复OS为“正常模式”后，此时不管系统设置如何选择，以及尝试将本应用数据清除重开，乃至重启OS等。均无法恢复任务栏窗口至正常位置。整体显示偏上（步骤1中的位置）。如图2。

软件很好，辛苦了！

![平板模式](https://user-images.githubusercontent.com/6801952/236493936-7a517eaf-46a6-49a6-b62f-9b2e90662f5d.jpg)
![正常模式](https://user-images.githubusercontent.com/6801952/236493985-ab307562-3bd5-4cee-91ed-8b23efea8057.jpg)

**Comment by Hovn** [comment]
如有临时的修复方法，或开放某些参数来手动调整也是好的。
现在尝试了好些措施，还是只能如图2这样显示，只能短期内先关了。
感谢~

**Comment by 00susu00** [comment]
我也碰见了这种情况，试了很多办法也没用，希望开发者大大适配

**Comment by 00susu00** [comment]
![图片](https://github.com/zhongyang219/TrafficMonitor/assets/51123980/f5ba53f1-06f4-4412-80f5-d74693693fcd)
调整成横向显示后勉强能用，但是逼死强迫症

**Comment by 573980475** [comment]
有个Build能修复：https://github.com/zhongyang219/TrafficMonitor/actions/runs/4468275475

**Comment by Hovn** [comment]
> 有个Build能修复：https://github.com/zhongyang219/TrafficMonitor/actions/runs/4468275475

谢谢，看到已经进入master了，期待早日发新版~
