### ISSUE TITLE
一个尴尬的错误 显示不完全

### ISSUE THREAD

**Issue by Ircon** [zhongyang219/TrafficMonitor#166]
![snipaste_2018-12-29_14-53-40](https://user-images.githubusercontent.com/11171522/50534622-1f445b80-0b7a-11e9-8935-f26ba17c8f6e.png)

**Comment by Ircon** [comment]
偶尔发生一次

**Comment by LiteCoder** [comment]
我这也会出现这个问题，显示隐藏一下 通知区域图标就好了。

**Comment by Ircon** [comment]
好吧
