### ISSUE TITLE
Spacing or position in incorrect!

### ISSUE THREAD

**Issue by khaledmndev** [zhongyang219/TrafficMonitor#1679]
Hey, i;m having an issue with the net monitoring in the taskbar, where the positioning is on top a little bit.

is there anyway to fix it?

![image](https://github.com/zhongyang219/TrafficMonitor/assets/9519494/d0a722c2-6391-4b38-b2ca-55ffb773a831)

**Comment by bcutter** [comment]
See the same on one system. Could not find a fix until now...

**Comment by Shubham123498765** [comment]
#1687 Install new build

**Comment by bcutter** [comment]
> #1687 Install new build

We don't install new builds, we install updates.

**Comment by Shubham123498765** [comment]
As the developer had not issued new update yet to fix this issue,so you can
install the new build yourself to fix this issue.
Issue is only in touchscreen 360 laptops.

**Comment by bcutter** [comment]
> As the developer had not issued new update yet to fix this issue,so you can

That's the actual issue in this repository here! There are plenty of open issues and pull requests. I tend to consider this repo as unmaintained. And that creates obvious problems with uncontrolled "fixed A/B/C/D/..." versions in the wild.

**Comment by Shubham123498765** [comment]
So whats the solution

**Comment by bcutter** [comment]
Two options:

A) Best: The maintainer needs to hand over this project to a new maintainer. One needs to get the rights to grant PRs, sign releases etc.

B) Second best: There's one "big" fork where all the development continues.

**Comment by khaledmndev** [comment]
So, i was searching through the opened and closed issues and i finally found a fix it someone modified if I'm not mistaken[ [here's the link i used to update]](https://github.com/PillarsZhang/TrafficMonitor/actions/runs/6058171815)

**Comment by Shubham123498765** [comment]
Yes this is it
