### ISSUE TITLE
Data wont align to the far left of Taskbar

### ISSUE THREAD

**Issue by fawzynahwi** [zhongyang219/TrafficMonitor#1685]
![Screenshot 2023-08-29 233308](https://github.com/zhongyang219/TrafficMonitor/assets/52822428/ffa8d0e6-eee6-446a-8d17-72dd0bc11d16)
I dont know if this is related or not but after removing Windows widgets from my device the app wont align to the far left even though I have enabled the option in settings 
![Screenshot 2023-08-29 233442](https://github.com/zhongyang219/TrafficMonitor/assets/52822428/38873568-6699-4d2c-851b-7ff6705b4995)

I have tried to set the space manually in global_cfg.ini via writing : 
[task_bar]
taskbar_left_space_win11 = 160
and changing 160 to 200 or even 260 but it didnt change anything all.
Please help :( 

Edit 1:
I tried changing taskbar_left_space_win11 in config file in Roaming folder but it also changed nothing

**Comment by helix-77** [comment]
@fawzynahwi  @dinaau did you find any fix? taskbar_left_space_win11 changes back to 160 after each app restart

**Comment by carlox97** [comment]
have you found a fix?

**Comment by carlox97** [comment]
@fawzynahwi you closed this as completed, have you solved?
