### ISSUE TITLE
Text not aligned properly in touch screen laptops only.

### ISSUE THREAD

**Issue by Shubham123498765** [zhongyang219/TrafficMonitor#1687]
It is working properly in touch screen mode but not in normal mode the meter should be shifted a little bit towards the bottom.
#1554
#1521
![image](https://github.com/zhongyang219/TrafficMonitor/assets/82265932/46999dc6-00e9-47d5-b53f-b542162ebe2b)

**Comment by ZhangWebber** [comment]
Same here

**Comment by Shubham123498765** [comment]
Which company laptop

**Comment by ZhangWebber** [comment]
> Which company laptop

It's thinkpad x1 carbon 10th gen - P-series.
It worked initially and after a while it began not working (I think it was after paricular updates)

**Comment by Shubham123498765** [comment]
Yes it was after this update KB5022913 
https://github.com/zhongyang219/TrafficMonitor/issues/1554#issuecomment-1473974032

**Comment by ZhangWebber** [comment]
> Yes it was after this update KB5022913 [#1554 (comment)](https://github.com/zhongyang219/TrafficMonitor/issues/1554#issuecomment-1473974032)

Yes. But that pre-release is expired. Can you create new artificat?

**Comment by Shubham123498765** [comment]
I cant create a new artifact as it was created by someone else.

**Comment by ZhangWebber** [comment]
> I cant create a new artifact as it was created by someone else.

Oh I see. Gotcha. Thanks.
So no way to fix above issue for now?

**Comment by Shubham123498765** [comment]
Yup, I think so As of now no solutions.
I will let you know if I find any solution.

**Comment by omichde** [comment]
Same for me: Asus Rog X13 with TrafficMonitor 1.84.1

![grafik](https://github.com/zhongyang219/TrafficMonitor/assets/1526074/05b6c209-1f98-4bfa-ab3b-9789fafa4bcf)

**Comment by Shubham123498765** [comment]
Try tagging the maintainer of the repo in this thread.
Let him also know the issue

**Comment by PillarsZhang** [comment]
> > I cant create a new artifact as it was created by someone else.
> 
> Oh I see. Gotcha. Thanks. So no way to fix above issue for now?

I forked the latest repository and triggered the release CI. The issue with the text display position has been resolved.
https://github.com/PillarsZhang/TrafficMonitor/actions/runs/6058171815

**Comment by Shubham123498765** [comment]
Is this false positive?
![image](https://github.com/zhongyang219/TrafficMonitor/assets/82265932/b5db64ff-e3e2-4309-a336-23f75e1fce94)

**Comment by PillarsZhang** [comment]
> Is this false positive? ![image](https://user-images.githubusercontent.com/82265932/265211885-b5db64ff-e3e2-4309-a336-23f75e1fce94.png)

Not sure, but the source code is right here. I just compiled it. It works fine.

**Comment by Shubham123498765** [comment]
How long it will take to get into the update of the app.
The last update was in nov 2022
![image](https://github.com/zhongyang219/TrafficMonitor/assets/82265932/dcd4da14-9991-4bf5-8199-95b26d549bf2)

**Comment by omichde** [comment]
> How long it will take to get into the update of the app. The last update was in nov 2022 ![image](https://user-images.githubusercontent.com/82265932/265222016-dcd4da14-9991-4bf5-8199-95b26d549bf2.png)

Depends when and if @zhongyang219 will accept this change...

**Comment by omichde** [comment]
> > Is this false positive? ![image](https://user-images.githubusercontent.com/82265932/265211885-b5db64ff-e3e2-4309-a336-23f75e1fce94.png)
> 
> Not sure, but the source code is right here. I just compiled it. It works fine.

Thanks, seems to work...

**Comment by ZhangWebber** [comment]
> > > I cant create a new artifact as it was created by someone else.
> > 
> > 
> > Oh I see. Gotcha. Thanks. So no way to fix above issue for now?
> 
> I forked the latest repository and triggered the release CI. The issue with the text display position has been resolved. [PillarsZhang/TrafficMonitor/actions/runs/6058171815](https://github.com/PillarsZhang/TrafficMonitor/actions/runs/6058171815)

It's Working. Thank you
