### ISSUE TITLE
抓🐛，实时网速始终为 0KB/s

### ISSUE THREAD

**Issue by XMuli** [zhongyang219/TrafficMonitor#1758]
当我切换网络之后，发现实时网速始终为 0；

**ENV**
- 小主机 x86_64 Openwrt + 小米路路由器有线中继
- windows 10 22H2

<img src="https://github.com/zhongyang219/TrafficMonitor/assets/33887845/3a9671ec-860f-4e2a-bc88-435ea74e304b" width="70%"/>

<img src="https://github.com/zhongyang219/TrafficMonitor/assets/33887845/39fb5fdd-96f7-41ed-ba42-0156a17a3215" width="70%"/>

<img src="https://github.com/zhongyang219/TrafficMonitor/assets/33887845/e1dac363-92cb-43a0-a137-590a889d5155" width="70%"/>

**Comment by chnaan** [comment]
右键图标看下选的网卡对不对 或者你手动选择网卡
![image](https://github.com/zhongyang219/TrafficMonitor/assets/43342034/c1ec3c58-3ee4-459d-b105-c60ed68ff7bd)

**Comment by XMuli** [comment]
记得昨晚这个也试了下的，还是没显示。晚上我再手动逐渐一遍切换试试
