### ISSUE TITLE
新款ultra9处理器不显示温度

### ISSUE THREAD

**Issue by cinewma** [zhongyang219/TrafficMonitor#1794]
![Snipaste_2024-03-25_16-50-12](https://github.com/zhongyang219/TrafficMonitor/assets/101319624/9b8da981-7eab-4c1f-b061-f1e1dbf31cf5)
开发者辛苦了！！！

**Comment by FerdinandSu** [comment]
手动替换下LibreHardwareMonitorLib试试？我14代i7替换完就好使了

**Comment by JonathanCamus** [comment]
> 手动替换下LibreHardwareMonitorLib试试？我14代i7替换完就好使了

我的i7-13620替换完就显示了
