### ISSUE TITLE
设置开机自启之后就  无法再使用了

### ISSUE THREAD

**Issue by 474364707** [zhongyang219/TrafficMonitor#18]
![_20180406225358](https://user-images.githubusercontent.com/34829455/38428145-a1a4e040-39ed-11e8-805f-ad40d285e9d3.png)
![_20180406225348](https://user-images.githubusercontent.com/34829455/38428147-a1e15fde-39ed-11e8-9368-201cc38a4487.png)
[error.log](https://github.com/zhongyang219/TrafficMonitor/files/1884454/error.log)
[config.txt](https://github.com/zhongyang219/TrafficMonitor/files/1884458/config.txt)

win10 版本16299.309
软件用不了了 麻烦给看看..

**Comment by zhongyang219** [comment]
我目前也无法确定问题出在哪里，你先尝试一下删除config.ini，让它恢复初始设置，再打开试试。

**Comment by 474364707** [comment]
![tim 20180407041538](https://user-images.githubusercontent.com/34829455/38442269-5bb295be-3a1a-11e8-89e4-fd3818817224.jpg)

**Comment by zhongyang219** [comment]
@474364707 我的任务管理器中“启动”一栏中只有一个，不知道为什么你的有4个，而且崩溃的是搜狗拼音输入法。可能是和搜狗拼音输入法有冲突造成的。你到注册表“HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run”中把TrafficMonitor的自启动项目删掉试试，然后看看有没有问题。如果想自启动，再到开始菜单的“启动”目录下创建一个程序的快捷方式，再看看开机时会不会出问题。

**Comment by 474364707** [comment]
搞不清楚为什么
设置自启就这四个
不设置 
手动启动就没事

**Comment by 474364707** [comment]
重新创建还是这四个..
