### ISSUE TITLE
作者不更新了吗，Win11 23H2好多问题啊

### ISSUE THREAD

**Issue by shipkjzy** [zhongyang219/TrafficMonitor#1810]
它一直在任务栏左上角，被裁剪了一样
还有N100的CPU读取不到温度

**Comment by DEAN-Cherry** [comment]
https://github.com/zhongyang219/TrafficMonitor/issues/1714

自行替换LibreHardwareMonitorLib.dll

**Comment by shipkjzy** [comment]
> #1714
> 
> 自行替换LibreHardwareMonitorLib.dll

感谢大佬，CPU确实能读了，请问左上角能解决吗
![Uploading 微信截图_20240618162118.png…]()

**Comment by shipkjzy** [comment]
![20240618162118](https://github.com/zhongyang219/TrafficMonitor/assets/122106982/425a52a0-d78d-4eaa-b5f9-17e53ea3fcf8)

**Comment by DEAN-Cherry** [comment]
win11 看了 任务栏接口的，现在是假放在任务栏上面，所以作者也不管了

**Comment by shipkjzy** [comment]
> win11 砍了 任务栏接口的，现在是假放在任务栏上面，所以作者也不管了，解决了可以关闭 Issue

好的  感谢

**Comment by Jesse205** [comment]
> win11 砍了 任务栏接口的，现在是假放在任务栏上面，所以作者也不管了，解决了可以关闭 Issue

![image](https://github.com/zhongyang219/TrafficMonitor/assets/51242302/3ada7961-a89f-41f4-bc07-9f86f518f168)
360驱动大师可以，不知道他怎么搞的

**Comment by shipkjzy** [comment]
> > win11 砍了 任务栏接口的，现在是假放在任务栏上面，所以作者也不管了，解决了可以关闭 Issue
> 
> ![image](https://private-user-images.githubusercontent.com/51242302/341593983-3ada7961-a89f-41f4-bc07-9f86f518f168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzM2MjAsIm5iZiI6MTcxODkzMzMyMCwicGF0aCI6Ii81MTI0MjMwMi8zNDE1OTM5ODMtM2FkYTc5NjEtYTg5Zi00MWY0LWJjMDctOWY4NmY1MThmMTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAxMjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOGQzNmE5NDUzMjY4OGZjMjdjNzMxNjU2YTRkZWRmMjY3MjQ2NGUzMTk2NzVkMzIzYjA3OGFkODg5YjU0YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kq1ofC5DQNSH-a0-rkubqxwc-IyM5feJlbUPuAv43Yc) 360驱动大师可以，不知道他怎么搞的

这是跟随图标吧，我之前用了一款监视是根据分辨率计算的，屏幕分辨率-宽口最大化分辨率即可得出任务栏宽高，后来改成悬浮了，可以任意拖动，拖到合适位置锁定就行了
