### ISSUE TITLE
主窗口鼠标提示中cpu频率显示异常

### ISSUE THREAD

**Issue by A1247343406** [zhongyang219/TrafficMonitor#1847]
![image_20240819022057](https://github.com/user-attachments/assets/c82e0a21-d08f-4fef-9d1d-062babc42194)
![image_20240819022139](https://github.com/user-attachments/assets/0b6c93b0-74bb-4775-a1b2-73c99f8a3277)
如图。cpu是12400

**Comment by 1247343406** [comment]
最新测试，可以看到只有悬浮窗的悬停信息显示是有异常的，任务栏窗口悬停显示的频率是正常的
![image_20240821105610](https://github.com/user-attachments/assets/da4dd864-90cf-45dd-bb75-b0c97fd72678)

![image_20240821105551](https://github.com/user-attachments/assets/29dc6443-95cf-434c-a1c0-5bbd659276f5)

**Comment by 1247343406** [comment]
强迫症难受得不行，重新编译直接把鼠标悬停提示的cpu频率显示给删了，终于舒服了
