### ISSUE TITLE
win10 1809开启本软件任务栏监控后，如果重启windows资源管理器，屏幕会疯狂闪烁，且有几率监控界面向右缩进至被遮挡乃至不可见。

### ISSUE THREAD

**Issue by fantab01** [zhongyang219/TrafficMonitor#185]
如题

**Comment by JasonKhew96** [comment]
win10 1803
关闭explorer，task manager会疯狂闪烁
重启explorer后Traffic Monitor任务栏窗口有几率向右缩进

**Comment by Jiedy** [comment]
一样的~ 打开任务管理器之后，若结束掉资源管理器(直接结束掉更好看效果，重启也行)，任务管理器会狂闪。。。本人Win8.1

**Comment by zhongyang219** [comment]
感谢反馈，确实有这个问题，我会想办法解决。

**Comment by zhongyang219** [comment]
问题已经解决，请等待下个版本更新。
