### ISSUE TITLE
TrafficMonitor doesn't show anything on the task bar

### ISSUE THREAD

**Issue by dxxvi** [zhongyang219/TrafficMonitor#1851]
It worked before. Then the trafficmonitor didn't show on the task bar anymore. How could I debug it?

**Comment by dxxvi** [comment]
I changed the Taskbar alignment to Center, selected "Taskbar window appears to the left of the taskbar", then I can see it in the task bar again.

**Comment by dxxvi** [comment]
I changed the Taskbar alignment to Center, selected "Taskbar window appears to the left of the taskbar", then I can see it in the task bar again.

**Comment by drejjmit** [comment]
For me, unchecking "Background transparent" worked.
