### ISSUE TITLE
关机时阻止关机

### ISSUE THREAD

**Issue by D06F6E67** [zhongyang219/TrafficMonitor#1856]
最近怎么每次关机都会提示这个程序在阻止关机，之前没这样的提示

**Comment by D06F6E67** [comment]
找到一个解决方法，再注册表 计算机\HKEY_USERS\.DEFAULT\Control Panel\Desktop 中添加一个AutoEndTasks 设置值为1就行了，软件层面搞不了，就直接系统层面搞

**Comment by pedrohenrque** [comment]
It's not working for me either, CPU is constantly at 0%. Nothing I do changes that.
