### ISSUE TITLE
能否支持下自定义宽度(调整浮窗大小)

### ISSUE THREAD

**Issue by mzzsfy** [zhongyang219/TrafficMonitor#189]
![image](https://user-images.githubusercontent.com/43053461/54668687-711dd180-4b2a-11e9-9909-6811503109cb.png)
中间太宽了, 能否支持下自定义宽度呢(调整浮窗大小)?感谢作者大大!

**Comment by zhongyang219** [comment]
这个可以通过自定义皮肤来解决，你可以选择更换其他皮肤，也可以在“更换皮肤”界面中点击“皮肤制作教程”查看如何编辑一个皮肤。

**Comment by mzzsfy** [comment]
好的谢谢
