### ISSUE TITLE
有个小问题，每次开机都会弹出以下界面，请问怎么解决？

### ISSUE THREAD

**Issue by JohnsonTam9527** [zhongyang219/TrafficMonitor#193]
没有办法发图片，只能发文字。
警告：窗口没有成功嵌入任务栏，可能已经被安全软件阻止！错误代码：87.
软件没有啥其他的问题，就是总是开机弹出这个界面，有点烦。。。

**Comment by CLannadZSY** [comment]
不是写的很清楚吗,被你的安全软件阻止了,去你的安全软件里给它相应的权限或者让你的安全软件不再阻止它嵌入任务栏不就好了.
问一句,你用的什么安全软件?

**Comment by zhongyang219** [comment]
原因可能是被360等阻止了。另外，如果你打开了开始菜单，也会导致嵌入任务栏失败。

**Comment by JohnsonTam9527** [comment]
> 不是写的很清楚吗,被你的安全软件阻止了,去你的安全软件里给它相应的权限或者让你的安全软件不再阻止它嵌入任务栏不就好了.
> 问一句,你用的什么安全软件?
最近有点忙，回复晚了，我用的是win10自带的安全软件，请问怎样设置？

**Comment by JohnsonTam9527** [comment]
问题解决了，感谢各位的回复。
