### ISSUE TITLE
菜单[显示主窗体]应该改成[显示悬浮窗]

### ISSUE THREAD

**Issue by sonichy** [zhongyang219/TrafficMonitor#196]
用户怎么知道哪个是主窗体？
建议：鼠标悬浮提示，增加开机时长，启动时长，未来还可以增加开机记录。
![](https://github.com/sonichy/CMDU_DDE_DOCK/raw/master/preview.png)
任务栏显示文字是哪个cpp？我想学习一下。

**Comment by zhongyang219** [comment]
感谢建议。任务显示文字在“TaskBarDlg.cpp”。但是这个类是我在两年前的时候写的，那时经验不足，代码结构写得不好，写得很乱很复杂，我现在自己都看不下去了，你可以拿来参考。

**Comment by sonichy** [comment]
编译环境怎么搭建，教教我。
