### ISSUE TITLE
能否上架微软商店？

### ISSUE THREAD

**Issue by xhml** [zhongyang219/TrafficMonitor#20]
感谢作者的辛勤付出
请问能否上架微软商店？
上架以后获取软件很容易，并且更新十分方便。

**Comment by zhongyang219** [comment]
如果可以，我也希望能上架微软商店，但是上架微软商店好像必须转制成UWP，而微软转制UWP的说明不够详细，而且教程都是基于C#的项目的，不知道MFC项目能不能转制。

**Comment by xhml** [comment]
@zhongyang219 
[微软说可以.](https://blogs.windows.com/buildingapps/2017/06/19/distribute-existing-desktop-applications-via-windows-store-windows-10-pcs-including-new-windows-10-s-configuration/)
辛苦作者能看一下上面的文章,上架商店后真的方便许多.

**Comment by ov360** [comment]
支持老哥上架到微软商店，更易小白安装和传播
