### ISSUE TITLE
您好，希望能只提供内存和cpu的显示的界面，因为网速的话一般需要具体查看各个程序的连接速度，需要开启火绒的悬浮窗，但是火绒没有cpu和内存

### ISSUE THREAD

**Issue by grayVI** [zhongyang219/TrafficMonitor#203]

**Comment by ziranjiang** [comment]
讲道理，我想提的建议和你一模一样

**Comment by tea1111980** [comment]
这说的是啥意思？ 只查看某一项，设置里面不是有吗？

**Comment by lzpong** [comment]
提过一样的建议~~

**Comment by zhongyang219** [comment]
此功能在最新版本中已经添加。

**Comment by grayVI** [comment]
大佬好，可以给个官网或下载地址吗，找不到了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhongyang219"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午5:18
收件人: "zhongyang219/TrafficMonitor"<TrafficMonitor@noreply.github.com&gt;; 
抄送: "xx"<1070364566@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhongyang219/TrafficMonitor] 您好，希望能只提供内存和cpu的显示的界面，因为网速的话一般需要具体查看各个程序的连接速度，需要开启火绒的悬浮窗，但是火绒没有cpu和内存 (#203)





 
此功能在最新版本中已经添加。

**Comment by grayVI** [comment]
如何设置只显示cpu和内存呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhongyang219"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午5:18
收件人: "zhongyang219/TrafficMonitor"<TrafficMonitor@noreply.github.com&gt;; 
抄送: "xx"<1070364566@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhongyang219/TrafficMonitor] 您好，希望能只提供内存和cpu的显示的界面，因为网速的话一般需要具体查看各个程序的连接速度，需要开启火绒的悬浮窗，但是火绒没有cpu和内存 (#203)





 
此功能在最新版本中已经添加。

**Comment by zhongyang219** [comment]
在任务栏窗口上点击鼠标右键，选择“显示设置”，去掉“显示网速”的勾选，勾选“显示CPU和内存利用率”即可。
![image](https://user-images.githubusercontent.com/30562462/88911882-130e0c00-d291-11ea-8f24-85f165273730.png)
最新版本链接：https://pan.baidu.com/s/15PMt7s-ASpyDwtS__4cUhg 
提取码：ou0m

**Comment by grayVI** [comment]
多谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhongyang219"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上6:26
收件人: "zhongyang219/TrafficMonitor"<TrafficMonitor@noreply.github.com&gt;; 
抄送: "xx"<1070364566@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhongyang219/TrafficMonitor] 您好，希望能只提供内存和cpu的显示的界面，因为网速的话一般需要具体查看各个程序的连接速度，需要开启火绒的悬浮窗，但是火绒没有cpu和内存 (#203)





 
在任务栏窗口上点击鼠标右键，选择“显示设置”，去掉“显示网速”的勾选，勾选“显示CPU和内存利用率”即可。
 
 最新版本链接：https://pan.baidu.com/s/15PMt7s-ASpyDwtS__4cUhg
 提取码：ou0m
