### ISSUE TITLE
请问能否编译新版

### ISSUE THREAD

**Issue by toshichi** [zhongyang219/TrafficMonitor#205]
代码版本比 Release 最新版新了不少，能否考虑编译一下新版本发布呢？

**Comment by SykieChen** [comment]
我使用 Azure DevOps 在线编译成功，感谢作者，感谢微软！
![image](https://user-images.githubusercontent.com/5460009/56474092-84b0b500-64a7-11e9-9178-660e158ce29b.png)
[drop.zip](https://github.com/zhongyang219/TrafficMonitor/files/3101481/drop.zip)

**Comment by zhongyang219** [comment]
这几天就会发布新版本了，请耐心等待
