### ISSUE TITLE
Win 10 defender 报毒

### ISSUE THREAD

**Issue by 9riffin** [zhongyang219/TrafficMonitor#212]
Win 10 defender 报毒

**Comment by zhongyang219** [comment]
报毒这个问题解决不了，添加信任吧

**Comment by ted423** [comment]
https://virusscan.jotti.org/en-US/filescanjob/hzvja405o1

**Comment by ted423** [comment]
https://www.virustotal.com/zh-cn/file/3ecbb52a939301544b293a05bdd39f76c3329604221f6660824f8150d0be493a/analysis/

**Comment by yzhang-gh** [comment]
感谢回复，应该是 Windows 误报了
不过问题是，文件下载下来一解压就被 Windows 自动删除了（连提示都没有；也没有装其它杀毒软件）
当然我可以先禁用 defender 然后添加信任再打开，但是有点担心以后每次更新的时候还会这样，以前一直挺好的

不过现在暂时不考虑这个问题也没事，之后如果更多人也这样再研究

**Comment by msydh** [comment]
> 感谢回复，应该是 Windows 误报了
> 不过问题是，文件下载下来一解压就被 Windows 自动删除了（连提示都没有；也没有装其它杀毒软件）
> 当然我可以先禁用 defender 然后添加信任再打开，但是有点担心以后每次更新的时候还会这样，以前一直挺好的
> 
> 不过现在暂时不考虑这个问题也没事，之后如果更多人也这样再研究

你可以把你的的下载文件夹添加白名单
