### ISSUE TITLE
速度显示不准

### ISSUE THREAD

**Issue by lurne** [zhongyang219/TrafficMonitor#224]
10G卡显示速度为4294Mbps

**Comment by ChackBox** [comment]
你的问题有点问题?
> 建议你重新说明

e.g：我的{无线/有线}网卡是10G的，但是在下载/测试的时候是1000Mbps{或者其他数值}，显示的是4294Mbps, 建议你附上截图

**Comment by lurne** [comment]
![a](https://user-images.githubusercontent.com/34796103/62302305-af4dd900-b4ac-11e9-908a-e66f3444c1e1.png)
就是这个了，没能正确识别适配器的速度呗（10G有线卡）

**Comment by ChackBox** [comment]
ok，實際的網絡數值有錯誤嗎？

**Comment by lurne** [comment]
> ok，實際的網絡數值有錯誤嗎？

实时的数字无误~都蛮好的

**Comment by ChackBox** [comment]
所以並沒有功能性錯誤？

**Comment by lurne** [comment]
是的
所以，这个只算是个小bug吧，哈哈

**Comment by ChackBox** [comment]
那沒有其他功能性問題or重大BUG請麻煩你關閉

**Comment by ChackBox** [comment]
Thanks
