### ISSUE TITLE
加入双击打开任务管理器

### ISSUE THREAD

**Issue by patrick330602** [zhongyang219/TrafficMonitor#23]
就是双击主界面或者任务栏界面后能够打开任务管理器

**Comment by zhongyang219** [comment]
谢谢建议，我会考虑增加选项，允许用户自由选择鼠标双击的动作。

**Comment by zhongyang219** [comment]
现在已经添加鼠标双击动作的选项，可以选择双击打开任务管理器，在即将发布的V1.72版本中可以看到这个功能。
