### ISSUE TITLE
设置中不能显示自定义图标字体

### ISSUE THREAD

**Issue by huhuime** [zhongyang219/TrafficMonitor#234]
![image](https://user-images.githubusercontent.com/6631239/58761746-2254d500-857a-11e9-8e1c-ebd997c0ea31.png)
设置了自定义图标字体，在设置中的文本就不对，所以这个会修吗？不修也行

**Comment by zhongyang219** [comment]
这是字体的问题，文本框输入的字符使用的是微软雅黑字体，任务栏中显示的字体是你设置的字体。
