### ISSUE TITLE
多个网络连接时显示错误的流量监控情况，且没法选择

### ISSUE THREAD

**Issue by nbyh** [zhongyang219/TrafficMonitor#27]
![image](https://user-images.githubusercontent.com/7239908/38727677-47f0262e-3f40-11e8-8670-41f5d00d7269.png)

**Comment by zhongyang219** [comment]
通常情况下，它会自动选择要监控的网卡，它会选择已经使用的流量数最多的那个网卡。如果自动选择不正常，你可以在右键菜单“选择网络连接”中手动选择要监控的网卡。你说的没法选择是什么情况？

**Comment by nbyh** [comment]
右键菜单“选择网络连接”中手动选择要监控的网卡，原来是在主窗体上右键。我在任务栏窗口上右键确实没找到选择的地方，是我没摸索清楚，误会误会。另请教，任务栏窗口和主窗口右键菜单不一样是基于什么考虑？

**Comment by ky0ncheng** [comment]
@zhongyang219 @nbyh 
？？？

![](https://i.imgur.com/cGG631S.png)
