### ISSUE TITLE
网络链接不能自动从wifi切换到网线

### ISSUE THREAD

**Issue by 1SZX1** [zhongyang219/TrafficMonitor#270]
插上网线后网速就一直是0，手动切换到选择全部后才正常，希望至少可以有个默认选择全部的选项，每次都手动切换太麻烦了

**Comment by 1SZX1** [comment]
> 插上网线后网速就一直是0，手动切换到选择全部后才正常，希望至少可以有个默认选择全部的选项，每次都手动切换太麻烦了

**Comment by Wuzongyuan** [comment]
我也发现了这个问题 确实很不方便
