### ISSUE TITLE
电脑使用手机USB网络共享上网，任务栏会反应变慢甚至无响应并自动刷新

### ISSUE THREAD

**Issue by QiTianzu** [zhongyang219/TrafficMonitor#273]
电脑既连接WIFI又连接手机USB共享网络的情况下（不论先连哪个）任务栏反应会变慢无响应，关闭TrafficMonitor或断开USB共享网络就能恢复正常，断开WIFI不行。先连上WIFI再连上USB共享网络，电脑会改用USB共享网络上网，但监控的网络连接并不会自动切换到USB共享网络，网速显示没有网速，必须手动改为选择全部，再改为自动选择才能切换。

**Comment by Ming-Yang** [comment]
之前windows 10 ltsb 2016有这个问题（基于1607），更新了ltsc2019版本（基于1809）没有类似问题，其他更新的版本也没遇到类似问题
