### ISSUE TITLE
能否增加显示磁盘利用率和GPU利用率的功能呢

### ISSUE THREAD

**Issue by leishufei** [zhongyang219/TrafficMonitor#274]
很好用的软件，但是光有CPU和内存的实时监控，总觉得少了点什么，要是再加上磁盘和GPU的利用率就更好了。

**Comment by netsonicyxf** [comment]
最好还能选择显示某几个硬盘温度

**Comment by gioxouly** [comment]
楼上两位就不能去下载个crystaldiskinfo吗……

**Comment by LiuLiujie** [comment]
GPU利用率我暂时没有找到一个比较好的API来获取，目前已知的方法的是求和所有PID的GPU利用来计算总体的利用率但效率太低。NVIDIA AMD获得GPU利用率的方法也不相同还需要驱动支持。显存的利用率倒是可以做。

**Comment by zhongyang219** [comment]
最新版本已经增加温度和GPU利用率的显示
