### ISSUE TITLE
能否根据 Windows 浅色/深色模式切换颜色配置

### ISSUE THREAD

**Issue by Lyaiya** [zhongyang219/TrafficMonitor#276]
因为我安装了 Auto Dark Mode（一款能根据特定时间来自动切换浅色/深色模式的软件），而 TrafficMonitor [任务栏窗口设置]中的[文本颜色]，[背景颜色]和[透明色]只能固定为一套设置。这些设置在浅色模式下显示正常，切换到深色模式后就显示异常或者不协调。

（Windows 任务栏图标在浅色模式下为黑色，而在深色模式下为白色。）

我建议能否根据 Windows 浅色/深色模式来设置不同的[文本颜色]，[背景颜色]和[透明色]，即浅色模式下有一套颜色配置，深色模式下有另一套颜色配置。

**Comment by lecholin** [comment]
附议

**Comment by NestRoomPast** [comment]
同样的诉求……

**Comment by dsf1995cn** [comment]
附议

**Comment by msydh** [comment]
俺也一样

**Comment by SamToki** [comment]
附议＋１

**Comment by zhongyang219** [comment]
你好，建议已收到，我正在考虑实现这个功能

**Comment by Lyaiya** [comment]
@zhongyang219 我更新到 1.78 版本了，但好像没达到我想要的效果，我的意思是当 Windows 切换浅色/深色模式时，TrafficMonitor 能监听到这一变动，进而可以自行切换预设方案，而不是仅在首次启动时进行检测。

**Comment by SamToki** [comment]
没错，就是这个意思  (｢･ω･)｢
估计要实现这个有不小难度  (￣▽￣)

**Comment by zhongyang219** [comment]
新版本（V1.79）已添加这个功能、
