### ISSUE TITLE
Win10 4K分辨率下不显示任务栏窗口

### ISSUE THREAD

**Issue by VeEdwardH** [zhongyang219/TrafficMonitor#279]
在Win10 4K分辨率（150%缩放）下，任务栏窗口失效，无法正常显示

**Comment by zhongyang219** [comment]
我的电脑在150%缩放下是正常的，无法正常显示是什么样的情况，能否提供一下截图昵？

**Comment by VeEdwardH** [comment]
抱歉，应该是开启HDR会引起这个问题，而与缩放无关。
下面图1是正常的（未开启HDR）；
图2无法显示（开启HDR），但是鼠标移动到相应位置依然会有信息出现。










------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhongyang219"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 晚上10:00
收件人:&nbsp;"zhongyang219/TrafficMonitor"<TrafficMonitor@noreply.github.com&gt;;
抄送:&nbsp;"Edward H."<709132116@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhongyang219/TrafficMonitor] Win10 4K分辨率下不显示任务栏窗口 (#279)




我的电脑在150%缩放下是正常的，无法正常显示是什么样的情况，能否提供一下截图昵？

**Comment by kasisi** [comment]
找到原因了，关掉就好
