### ISSUE TITLE
Win7显示在任务栏无法全透明

### ISSUE THREAD

**Issue by laozhong** [zhongyang219/TrafficMonitor#283]
![2020-1-3 1-21-35](https://user-images.githubusercontent.com/5498798/71681371-72716f80-2dc7-11ea-8e87-804bb940d597.png)

**Comment by laozhong** [comment]
希望能把背景图bmp格式改为png，这样就能使用透明图了

**Comment by ifu25** [comment]
我的好难看呢~
![20210317_111342](https://user-images.githubusercontent.com/5575008/111409501-0819c600-8712-11eb-86f3-76244f237774.png)
