### ISSUE TITLE
能加入显示IP功能 吗？

### ISSUE THREAD

**Issue by cgy7986** [zhongyang219/TrafficMonitor#29]
能加入显示内外网IP就好了

**Comment by zhongyang219** [comment]
谢谢建议，我会考虑一下这个功能。

**Comment by zhongyang219** [comment]
要实现显示外网IP地址的功能，我只能通过下面的方法实现：访问某个能显示当前外网IP地址的网站，将网页的源码保存到内存，通过解析网页源码获取到外网IP地址。但是这种方法依赖于第三方网站，如果网页布局发生变化，甚至网站无法访问了，获取IP地址的功能很可能就会失效。
虽然我在1.72版本开始增加了获取外网IP地址的功能，但是由于这个功能不太稳定，所以我将这项功能设置成了默认关闭，可以通过修改配置文件，将show_internet_ip改成1来打开。

**Comment by hsr-GitHub** [comment]
之前翻Rainmeter配置文件的时候翻到了一段，应该可以。

[MeasureWANIP]
;Measure=Plugin
;Plugin=Plugins\WebParser.dll
;Url=http://checkip.dyndns.org/%22
;RegExp="(?siU)<body>(.+)Address: (.;+)</body>"
;StringIndex=2
;UpdateRate=600
Measure=Plugin
Plugin=WebParser
URL=https://checkip.amazonaws.com/
UpdateRate=14400
RegExp=(?siU)^(.*)$
StringIndex=1
Substitute="":"N/A"

**Comment by zhangguanzhang** [comment]
带curl的ua访问ip.sb这个url就行了
