### ISSUE TITLE
win7旗舰版 7601 设定开机启动失败

### ISSUE THREAD

**Issue by really-good** [zhongyang219/TrafficMonitor#3]
昨天晚上，第一次用，感觉非常不错，但是，今天开机后，点击程序显示不能使用，多次尝试无果后，删掉文件夹重新使用后，正常工作，且重启电脑后，还可以正常使用，但是当我设定开机启动后失败了，希望可以解决这个问题。对了，使用的版本为1.66

**Comment by really-good** [comment]
不好意思，今天设定开机自动运行就突然成功了。我怀疑是因为我一运行后，没有更改皮肤等设置就直接设定开机自动运行的原因

**Comment by zhongyang219** [comment]
@really-good 你说的“点击程序显示不能使用”具体是什么提示信息呢？另外目前的版本开机启动使用的方法是通过在开始菜单的“启动”目录下创建快捷方式来实现的，也许这并不是一个好办法，后续我会考虑改成通过写入注册表来实现开机自启。

**Comment by really-good** [comment]
不好意思，可能是我没表达清楚，就是指点击“TrafficMonitor.exe”。不管现在已经可以了
