### ISSUE TITLE
[BUG] 任务栏悬浮窗被关闭后无法自动重新打开

### ISSUE THREAD

**Issue by hv0905** [zhongyang219/TrafficMonitor#303]
## 重现步骤
1. 打开TrafficMonitor, 关闭主悬浮窗,托盘图标, 开任务栏窗口, 然后关闭设定窗口.
2. 左键点击一下任务栏的窗口, 然后按 `Alt+F4` 键, 此时任务栏窗口会被直接关闭.
3. 每隔一秒应用会弹出 `遇到不适当的参数` 错误, 猜测是由于ipc出错造成.

## 希望的行为
1. 能够自动重新打开任务栏窗口
-- 或者 --
2. 在不弹出任何错误窗口的情况下直接退出应用

**Comment by LiuLiujie** [comment]
感谢您的反馈，已复现您发现的错误。我尝试一下能否进行修复。

**Comment by zhongyang219** [comment]
感谢你的反馈，这个问题确实存在，我正在调试这个问题

**Comment by zhongyang219** [comment]
问题已经解决，现在按Alt+F4不会弹出错误提示了。
