### ISSUE TITLE
win10 18363.592 , 不能显示下载速度和流量了!!!

### ISSUE THREAD

**Issue by lzpong** [zhongyang219/TrafficMonitor#306]
![image](https://user-images.githubusercontent.com/10493371/75956828-ab2ae380-5ef3-11ea-8d6b-1516beb6cd6e.png)

![image](https://user-images.githubusercontent.com/10493371/75956864-c564c180-5ef3-11ea-8bef-a6f3dbdb35d0.png)

**Comment by LiuLiujie** [comment]
![image](https://user-images.githubusercontent.com/47711081/76037932-40c18400-5f83-11ea-86e1-63c805a9a9eb.png)
您好，感谢您的反馈。在18363.693未能发现您所说的错误，请尝试右键-选择网络连接-手动选择您访问互联网的连接。若未能解决问题，我再仔细看一下代码

**Comment by lzpong** [comment]
额,  我用的 是蓝牙网络
![image](https://user-images.githubusercontent.com/10493371/76591991-e13c1900-652c-11ea-8a5f-12aa870aa4c2.png)
选择全部,或者 选择 蓝牙网卡 , 都没有下载速度
![image](https://user-images.githubusercontent.com/10493371/76591957-c8336800-652c-11ea-9763-390ca8c33cc6.png)
![image](https://user-images.githubusercontent.com/10493371/76592051-12b4e480-652d-11ea-99e3-8a1f0c2ccf6c.png)

**Comment by zhongyang219** [comment]
你好，这个问题曾经有人反馈过，使用蓝牙网络时，系统只能获取到“已发送”字节数，而无法获取到“已接收”字节数。如图所示：
![image](https://user-images.githubusercontent.com/30562462/77073797-c84ece80-6a2a-11ea-855b-407f941a7852.png)
因此TrafficMonitor使用的API也无法正常获取下下载速度。但是经过观察发现，这里显示的上传速度似乎是下载+上传的网速。

**Comment by lzpong** [comment]
OKy
