### ISSUE TITLE
如果与Musicplayer2同时使用，在打开又关闭小娜搜索框时，任务栏显示会偏移...

### ISSUE THREAD

**Issue by ChenYFan** [zhongyang219/TrafficMonitor#308]
![image](https://user-images.githubusercontent.com/53730587/76178189-871c1a80-61f1-11ea-94f3-1f0d91eb2e26.png)

![image](https://user-images.githubusercontent.com/53730587/76178118-4f14d780-61f1-11ea-921c-64a780871e99.png)
在开启搜索框时打开TrafficMonitor,接着又关闭,就会出现如上偏移,希望能用个任务栏位置定时刷新,这样就能解决.
讲真,这是唯二(第一个是musicplayer2)我愿意让它开机自动运行的软件,非常喜爱这款软件,希望能支持您的开发.
另:如果不建议,我愿意将您的软件宣传出去,可以吗?

**Comment by zhongyang219** [comment]
关于任务栏窗口位置不对的问题确实一直存在，目前也没有好的解决方法，如果你遇到这个问题，你可以将通知区任意一个图标向上拖动将其隐藏起来，再将其拖下来，也就是让任务栏的宽度发生变化以触发TrafficMonitor自动调整其位置。

**Comment by zhongyang219** [comment]
这个软件是开源免费的软件，欢迎宣传和推广。

**Comment by ChenYFan** [comment]
好的👌既然无解，那我就Close了
