### ISSUE TITLE
任务栏bug

### ISSUE THREAD

**Issue by Sc7-git** [zhongyang219/TrafficMonitor#309]
鼠标点击任务栏窗口(注：不是任务栏)，然后按alt+f4，会循环报错。只有关闭进程。
![image](https://user-images.githubusercontent.com/40767807/76191253-dece7c00-6219-11ea-9295-b615100a6985.png)

**Comment by ChenYFan** [comment]
同上，有这样一模一样的问题

**Comment by LiuLiujie** [comment]
#303 问题一样
