### ISSUE TITLE
显示通知区域图标选项勾掉后不知道什么情况会突然再显示出来

### ISSUE THREAD

**Issue by gyflonely** [zhongyang219/TrafficMonitor#312]
OS win10 ltsc x64 1809 17763.1098 17763之前的版本也出现过

**Comment by zhongyang219** [comment]
你好，这并不是bug，请参见 https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md 的第8条“设置了鼠标穿透后如何取消？”。
