### ISSUE TITLE
3項建議..

### ISSUE THREAD

**Issue by anime5167** [zhongyang219/TrafficMonitor#314]
希望可以新增
鼠標在流量球上方懸停時不顯示泡泡信息 設定
和
雙擊系統列TrafficMonitor圖標時不會打開主視窗(流量球) 的設定
和
主視窗希望也有數值向右對齊選項

**Comment by zhongyang219** [comment]
1. 这个功能在最新版本（V1.78）中已经实现了，你可以在“主窗口设置”和“任务栏窗口设置”中去掉“显示鼠标提示”的勾选。
2. 这个功能我觉得似乎没有很大的必要，如果更多人提出类似的需求再考虑。
3. 主窗口的对齐方式跟随皮肤的设定，你可以通过皮肤编辑器来指定对应皮肤中数值的对齐方式。
