### ISSUE TITLE
您好后期会考虑加入温度监控吗

### ISSUE THREAD

**Issue by dylumian** [zhongyang219/TrafficMonitor#315]
类似软妹魔方雷达这种，感觉特别全，而且里面还会监控哪个应用程序占用哪个端口等等，主要是软妹魔方的总不更新流量监控不好用了，然后网上搜了搜发现了这个，感谢作者给我们带来了这么好的神器

**Comment by omaidb** [comment]
我个人非常支持增加温度监控的功能

**Comment by gcczm** [comment]
非常支持增加温度监控的功能

**Comment by chenqian3788** [comment]
支持增加温度监控的功能

**Comment by ninko2019** [comment]
支持增加温度监控的功能
