### ISSUE TITLE
自动编译状态栏存在编码问题

### ISSUE THREAD

**Issue by LiuLiujie** [zhongyang219/TrafficMonitor#316]
![image](https://user-images.githubusercontent.com/47711081/76740393-c8d83280-67a8-11ea-9ce6-b81423c015c5.png)
win10版本1909,traffic版本为action编译的最新x64版

**Comment by zhongyang219** [comment]
确实存在这个问题，初步判断可能是自动编译时把所有源代码的文本格式默认按UTF8格式解析导致的，我先尝试修改一下源代码的编码格式试试。

**Comment by zhongyang219** [comment]
问题好像已经解决了。
