### ISSUE TITLE
master编译CPU使用率无法获取 一直是0

### ISSUE THREAD

**Issue by meowao** [zhongyang219/TrafficMonitor#317]
我用最新的编译后 在win10下正常,在win7则CPU使用率一直是0;
包含了#293的修改

**Comment by zhongyang219** [comment]
你好，感谢你的反馈，我一会先测试一下

**Comment by LiuLiujie** [comment]
抱歉会出现这样的问题，#293是我提交的，但是我已经没有运行win7的设备可供调试了。当初我的修改是对windows的性能监视器设置计数器。可以在win7打开性能监视器对比一下下列界面的路径，看看这个计数器能否在性能监视器中正常使用，以及与我修改的代码中的是否是相同的路径。
![image](https://user-images.githubusercontent.com/47711081/76861230-382c5000-6897-11ea-809a-0c2b3dc092e8.png)

**Comment by LiuLiujie** [comment]
![批注 2020-03-17 214012](https://user-images.githubusercontent.com/47711081/76861652-e7692700-6897-11ea-90f3-a2dc9d12566c.jpg)
![批注 2020-03-17 214044](https://user-images.githubusercontent.com/47711081/76861722-ffd94180-6897-11ea-8632-12db3b79574a.jpg)
![批注 2020-03-17 214152](https://user-images.githubusercontent.com/47711081/76861837-28613b80-6898-11ea-9ae8-99ba0b02ec09.jpg)

**Comment by zhongyang219** [comment]
win7中性能监视器中的计数器是这样的：
![image](https://user-images.githubusercontent.com/30562462/76865059-15049f00-689d-11ea-9a77-a033479d88e5.png)

**Comment by zhongyang219** [comment]
@LiuLiujie 我已经修改了代码，现在Win7/Win8可能正常获取CPU利用率了：
![image](https://user-images.githubusercontent.com/30562462/76866851-ad9c1e80-689f-11ea-8ba9-8f0b17da0694.png)
![image](https://user-images.githubusercontent.com/30562462/76866871-b42a9600-689f-11ea-96c3-aa348dd71644.png)

**Comment by LiuLiujie** [comment]
utility是任务管理器的CPU利用率的数据源，侧重于负载，与任务管理器的利用率仅有采样频率的差别；time是原来我没修改之前的那种获取CPU利用率方式的数据源，侧重于时钟，与任务管理器的稍有差异。但两种均可表示CPU利用率。
请问win7/8是无法获得utility吗？ time是性能监视器原本就提供的一个计数器范例。按照我上面发的图操作是可以自行增加一个utility的计数器，我在代码里写的也是相同原理只不过换成了代码形式。@zhongyang219 
使用性能监视器+计数器还可以实现显示硬盘的读写和利用率，每个线程的GPU利用率，GPU的显存利用率等等。如果想把这个软件开发成全能监视器可以考虑一下/笑/ : )

**Comment by meowao** [comment]
可以了! 感谢各位大佬的无私奉献.
