### ISSUE TITLE
建议获取外网 IP 的功能使用国内的服务

### ISSUE THREAD

**Issue by qianxu2001** [zhongyang219/TrafficMonitor#319]
![image](https://user-images.githubusercontent.com/62287903/77237074-95116880-6bff-11ea-97a9-1595df4c0d19.png)
由于 gfwlist 项目停更，现在在路由器上挂代理的用户大部分已经换成了绕过大陆 IP 模式，目前本项目的查询外网 IP 似乎用的国外的接口，想知道能否换成国内的服务？

**Comment by ritaswc** [comment]
我有提出建议使用我的服务器 来获取外网IP，支持ipv4 ipv6 作者还没回复
​https://v4.yinghualuo.cn/bejson
https://v6.yinghualuo.cn/bejson

**Comment by soloopooo** [comment]
http://ip.cn/

**Comment by ritaswc** [comment]
> ipv4：http://ip.cn/
> ipv6暂时没好网站，可以考虑一下楼上的兄弟

未经允许，不可以随便用别人的服务，这样不就白嫖了么

**Comment by soloopooo** [comment]
看了一下issue的需求...我倒是觉得可以分别获取未代理和代理的外网ip（考虑某些人可能会需要代理后的ip地址）

**Comment by ritaswc** [comment]
看开源作者定夺吧

**Comment by ttimasdf** [comment]
我在 IpAddress 插件里加了个可选项，一个国内服务，一个国外服务，目前只适配IPv4，有需要的可以试试 zhongyang219/TrafficMonitorPlugins/pull/119
