### ISSUE TITLE
Can not use `Bold` font style of `MS YaHei UI`

### ISSUE THREAD

**Issue by lj3lj3** [zhongyang219/TrafficMonitor#32]
![sshot-2018-04-18- 14-34-13](https://user-images.githubusercontent.com/2476642/38915292-c0024024-4315-11e8-9705-b2695d86fb6d.png)
![sshot-2018-04-18- 14-36-58](https://user-images.githubusercontent.com/2476642/38915378-033f83a6-4316-11e8-8be9-e1e2bebf275e.png)
Target System: Win10x64 16299
Issues: Can not use `Bold` font style of `MS YaHei UI`. BTW, I use small task bar.

**Comment by zhongyang219** [comment]
Thanks for you feedback. But sorry, TrafficMonitor does not support the font bold and oblique style at  current. I will try to improve it in the later versions.

**Comment by zhongyang219** [comment]
This problem has been resolved in V1.73, please update to the latest version.
By the way, I have add the English language support in V1.73.

**Comment by lj3lj3** [comment]
Thank you, it's working right now!
