### ISSUE TITLE
1.77升级到最新版本之后，缺失了“任务栏窗口显示在任务栏左侧”的功能

### ISSUE THREAD

**Issue by Kang-S** [zhongyang219/TrafficMonitor#321]
希望后续更新把这个功能再加上：任务栏窗口显示在任务栏左侧

**Comment by dyt5AAUI** [comment]
![image](https://user-images.githubusercontent.com/26762239/77246828-ea806080-6c65-11ea-8314-4fd291a337ce.png)
1.78已经回来了。你要不在覆盖一下。

**Comment by zhongyang219** [comment]
请把右侧滚动条滚到最下面
