### ISSUE TITLE
CPU USAGE NOT ACTIVELY SHOWING ON WINDOWS TASKBAR

### ISSUE THREAD

**Issue by MCHALMEI** [zhongyang219/TrafficMonitor#324]
Hi, 

Thanks for your dev efforts. Cool proggie your TrafficMonitor.

Just downloaded its latest 1.78 version. Unfortunately, although appearing graphically on Windows 10 x64 1903 taskbar, the CPU feature is not being ACTIVELLY shown there, that is, the program may be "monitoring" CPU usage, but not ACTIVELY AND GRAPHICALLY showing it there, just leaving the numerical indicator at "0%" all the time instead, even when, of course, the CPU is ACTUALLY being used. This does not occur the program previous version (1.77), to which use I reverted, naturally. Such a pity...

Kind regards from Niterói, RIO, Brazil.

**Comment by LiuLiujie** [comment]
Thanks a lot for your report.
In v1.78, we change the way we get CPU usage to keep the CPU usage the same as the  data in Windows Task Manager. In the code I use the Windows Performance Monitor to get the data. Maybe there are some differences in different computers' Windows Performance Monitor that I didn't know before. 
I will try to find the bugs. Maybe we need your help later.

GitHub mention that this is the first issue you comment in GitHub. Have a nice time in GitHub!
Best wishes From GuangDong, China.

**Comment by MCHALMEI** [comment]
Hi, LiuLiujie:

Thanks for your reply and be willing to take the trouble to find the bugs, if any indeed. OK also about eventually needing my help. Feel free to contact me when needed. 

Warm regards.

**Comment by rmattuschka** [comment]
#393 There i have explaint my workaround!

**Comment by zhongyang219** [comment]
See #393
