### ISSUE TITLE
双击打开任务管理器有个bug存在很久了

### ISSUE THREAD

**Issue by u2shana** [zhongyang219/TrafficMonitor#325]
双击程序打开任务管理和其他任务管理器打开方式会相互重置状态

包括这个主界面的简详状态,还有cpu的图形显示方式等等

![QQ截图20200323190428](https://user-images.githubusercontent.com/14146754/77310835-fccbce80-6d39-11ea-9b55-18262487a585.jpg)
![QQ截图20200323191020](https://user-images.githubusercontent.com/14146754/77310840-fe959200-6d39-11ea-826b-6008d4fb8e28.jpg)

**Comment by TwoPlusEight** [comment]
我也遇到过

**Comment by zhongyang219** [comment]
这个问题是由于你在64位系统中使用了32位的TrafficMonitor导致的，32位的TrafficMonitor无法打开64位的任务管理器，只能打开32位的任务管理器，使用64位的TrafficMonitor即可解决。
