### ISSUE TITLE
请问可否考虑增加显示cpu温度

### ISSUE THREAD

**Issue by wangfreexx** [zhongyang219/TrafficMonitor#33]
请问可否考虑增加显示cpu温度？

**Comment by zhongyang219** [comment]
关于添加CPU温度的问题，目前已经有很多人提出来了，虽然我也想添加这个功能，但是目前我确实不知道如何在程序中获取CPU的温度。有一个叫“permo”的开源软件有这个功能，但是那个软件在很多情况下都无法获到温度。

**Comment by huanghaozi** [comment]
[CPU核心温度获取 - CSDN](https://blog.csdn.net/caoyahong114/article/details/51557111)
找到一个用汇编实现的，也许有用
可以用**asm宏**嵌入汇编代码

**Comment by huanghaozi** [comment]
[C++使用汇编获取CPU信息](https://blog.csdn.net/cool_sec/article/details/14228401)
这里有个实例

**Comment by lucka-me** [comment]
[Using the Intel Power Gadget 3.0 API on Windows](https://software.intel.com/blogs/2014/01/07/using-the-intel-power-gadget-30-api-on-windows)
Intel CPU 可以通过安装控件获取温度，macOS 那边的 iStat Menu 似乎就是这种方法。
