### ISSUE TITLE
求加一个cpu温度项

### ISSUE THREAD

**Issue by littleStar0o0** [zhongyang219/TrafficMonitor#338]
您好，可以加个cpu温度项吗？

**Comment by lzdnico** [comment]
同求，再加个GPU温度吧

**Comment by secriy** [comment]
作者很久以前已经表示了难以实现，不考虑这类功能。

**Comment by oneisall8955** [comment]
同求，希望可以。如果难以实现，实在很遗憾

**Comment by hili210** [comment]
CPU、GPU、硬盘和主板温度我已经加上了， 我问下作者是否需要参考吧，另外我准备加上主动清理功能，不过这个是大功能了一直在研究清理，我本身也是做功能开发的

**Comment by lzdnico** [comment]
> CPU、GPU、硬盘和主板温度我已经加上了， 我问下作者是否需要参考吧，另外我准备加上主动清理功能，不过这个是大功能了一直在研究清理，我本身也是做功能开发的

有项目地址看看不

**Comment by hili210** [comment]
> > CPU、GPU、硬盘和主板温度我已经加上了， 我问下作者是否需要参考吧，另外我准备加上主动清理功能，不过这个是大功能了一直在研究清理，我本身也是做功能开发的
> 
> 有项目地址看看不

我的核心部分主动清理一直在编写，还没写完，温度部分我已经联系到了作者，这几天空了我整理一份给他，因为显卡温度涉及到NVIDIA、AMD、Intel不同的GPU还是有点复杂还需要测试，所以稍微等一阵子，代码可以的话估计会更新，我先整理出来温度的切换

**Comment by taifeng12** [comment]
强烈要求支持cpu和gpu温度显示，其实软媒的雷达不错，就是在任务栏动态显示的这点不喜欢

**Comment by gcczm** [comment]
同求，希望可以。

**Comment by Purmap** [comment]
> 强烈要求支持cpu和gpu温度显示，其实软媒的雷达不错，就是在任务栏动态显示的这点不喜欢

软媒的雷达主窗口太***丑***，任务栏又是动态的……

**Comment by ninko2019** [comment]
支持。

**Comment by zhongyang219** [comment]
温度监控功能已添加
