### ISSUE TITLE
弹出没有成功嵌入任务栏但仍然嵌入了

### ISSUE THREAD

**Issue by patrick330602** [zhongyang219/TrafficMonitor#34]
如图
![image](https://user-images.githubusercontent.com/15316889/39028035-61792760-441a-11e8-9055-e1bdcbff8ddf.png)

**Comment by zhongyang219** [comment]
我个问题确实很罕见，我修正了一处可能会导致这个问题的代码，1.72版本也许可以解决这个问题。
