### ISSUE TITLE
怎么关闭白色背景

### ISSUE THREAD

**Issue by xivi1839** [zhongyang219/TrafficMonitor#344]
![_2020040217382838SS](https://user-images.githubusercontent.com/24610024/78232870-79636780-7507-11ea-9e2b-1e742b742e73.png)
怎么取消这个白色背景显示，还是原先透明的好看点

**Comment by wchqybs** [comment]
没找到，白色背景确实难看，已经退回旧版本了

**Comment by juzi214032** [comment]
选项设置-任务栏窗口设置-CPU/内存显示状态条 取消勾选
