### ISSUE TITLE
反馈Win10屏幕缩放Bug

### ISSUE THREAD

**Issue by sakatatoushirou** [zhongyang219/TrafficMonitor#355]
首先非常感谢作者开发这款小工具 给我带来了非常大的便利。

在高分辨率屏幕缩放和恢复100%缩放下字体还是上次的缩放大小。
就会使得在4K模式150%缩放切换到1080P 100%缩放时字体会变很大，
1080P 100%缩放切换到4k 150%缩放字体会很小。
必须退出 重新打开才可以。

任务栏窗口和通知栏模式都会这样。

当前版本1.77

系统版本：Windows 10 x64 1909
感谢！

**Comment by zhongyang219** [comment]
你好，这个问题已经解决，请等待下个版本更新
