### ISSUE TITLE
建议调整任务栏 UI 至系统默认风格

### ISSUE THREAD

**Issue by wiryls** [zhongyang219/TrafficMonitor#36]
### 1.1 将任务栏界面与右侧时间对齐

目测，在宽任务栏下：

1. 第一行上调 2 个像素单位
2. 第二行下调 1 个像素单位

参考这张图：

![sample](https://user-images.githubusercontent.com/7984500/39080631-383c42aa-4565-11e8-9a93-b3052a06c285.png)

### 1.2 数值的右对齐

附议 #21

### 2.1 使用 `Microsoft YaHei UI` 替换默认的`微软雅黑`

两种字体在[细节](https://www.zhihu.com/question/20137844)上存在一点差异

### 2.2 调整字体的渲染方式

在设定字体为白色的场合下，看到的结果存在杂色，和系统 UI 仍然存在差异

![sample2](https://user-images.githubusercontent.com/7984500/39080824-b2c2e38c-4568-11e8-9288-70a1ff7b4c7e.png)

### 3.1 使用 `▲ ` 替换 `↑: `，`▼ ` 替换 `↓: `

个人使用体验中，`↑` 偶尔会和 `1` 混淆

### 3.2 加一份简单的 issue 指南

避免目前 issue 混乱，特别是【无意义的 issue 标题】的情况，不利于检索和管理

**Comment by zhongyang219** [comment]
首先感谢你提了这么多建议。
1.1 关于任务栏中显示的位置，我觉得现在的位置很合适啊，没有必要一定要和时间的位置一样吧，而且目前的高度可以兼顾使用小任务栏图标的情况。如果改成和右下角时间一样的位置，则当使用小任务栏图标时，任务栏的高度会变小，将会导致项目显示不全。当然我可以判断任务栏的高度，自动调整项目的位置，但是目前我并不想做这样的处理，因为并不是很有必要。
1.2 数值右对齐的功能已经在1.72版本中添加了，你应该已经更新了吧。
2.1 请问微软雅黑和Microsoft YaHei UI这两种字体具体有什么差别？
2.2 我想说这种细微的差别你竟然也能发现！我完全没有注意到这种差别，这个貌似不放大的话肉眼看不出来吧。我也不知道是什么造成的两种渲染方式的差异，以后有空再研究一下吧。
3.1 最新版本中增加了颜色单独设置和数值右对齐的功能，设置成数值右对齐或调整一下颜色可以更好地区分。
3.2 抱歉我Github用的不是太熟，issue指南是什么样的，能否给个例子参考？

**Comment by wiryls** [comment]
@zhongyang219 

关于 issue template，可以：
1. 参考[官方教程](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)，或者
2. 参考 [OpenCV](https://github.com/opencv/opencv/issues/new) 的模板文件，这个链接：[这里](https://raw.githubusercontent.com/opencv/opencv/master/.github/ISSUE_TEMPLATE.md)

主要也是有部分用户的标题完全没有意义，这样不方便其他人检索，容易导致提出相同的 issue 等等潜在问题。可以学习 OpenCV 的方式，放一些注释用于提醒用户如何描述清问题，以及不要使用无意义的标题等注意事项（建议同时准备两种语言的提示）。

**Comment by zhongyang219** [comment]
@wiryls 使用Micorsoft YaHei UI替换默认的微软雅黑，你说的有道理，不过我还是决定保持使用微软雅黑，因为Micorsoft YaHei UI字体只默认存在于Windows 8以上的系统中，如果默认字体设置为Micorsoft YaHei UI，则在Win7会由于找不到字体而变成宋体，我必须兼顾到Win7的用户，而且微软雅黑和Micorsoft YaHei UI的细微判别一般人也察觉不出来。

**Comment by aplk1002** [comment]
乱提什么建议啊
本来居中好好的
现在搞得下面空了一行
退回1.72
![1](https://user-images.githubusercontent.com/36945730/41537995-a7ea5498-733c-11e8-9b26-1acee617f562.png)
