### ISSUE TITLE
深色任务栏下，字体显示不清晰

### ISSUE THREAD

**Issue by MisakaSakura** [zhongyang219/TrafficMonitor#362]
我使用NetSpeedMonitor挺长一段时间了，但是这软件早已停更，虽然能用但是缺乏一些人性化功能。TrafficMonitor我打算换来试试，但是我发现深色任务栏下（实际上我使用了任务栏透明软件以及Wallpaper Engine）显示效果并不理想，设置我照搬了NetSpeedMonitor的，但是并不理想，NetSpeedMonitor有个“抗锯齿”的功能，不知道是不是因为这个。

**Comment by NavisLab** [comment]
通过自定义Windows主题, 将任务栏改成深色, 软件字体是白色. 
软件字体也改一下, 比如微软雅黑, 这样显示比较清晰.

我的屏幕: 14英寸 1920*1080

**Comment by MisakaSakura** [comment]
现在设置就是这样，实际上不仔细去看倒是无所谓，但是显示清晰度确实没有NetSpeedMonitor高
