### ISSUE TITLE
内存CPU不显示

### ISSUE THREAD

**Issue by lvhjean** [zhongyang219/TrafficMonitor#363]
当主窗口关闭，仅通过“通知区域图标”鼠标放上显示数据时，内存和CPU数不准

**Comment by lvhjean** [comment]
我再次提这个问题了。现在更新1.78版（x64）问题依旧。我看不是不准，是关闭“主窗口”或“任务栏窗口”都是显示到关闭时的信息，后续只有通知区域图标就不更新了

**Comment by zhongyang219** [comment]
你好，这个问题确实存在，目前的逻辑是，如果主窗口和任务栏窗口都不显示的话，就不会更新监控数据。我会在后面的版本中解决此问题。
