### ISSUE TITLE
定时提醒喝水、休息、提肛的功能

### ISSUE THREAD

**Issue by aimutu** [zhongyang219/TrafficMonitor#364]
看了下issues列表后想顺带问下，定时提醒休息、喝水、提肛的功能有没有考虑加入呢（注重健康党表示对于这些有点care）

**Comment by dayfan0810** [comment]
提纲已经和休息和喝水处于同意地位了啊,牛逼

**Comment by 2220209876** [comment]
你需要 
https://github.com/rcaelers/workrave/releases
https://github.com/Planshit/ProjectEye/releases
