### ISSUE TITLE
增加自动切换深/浅色主题的功能

### ISSUE THREAD

**Issue by yangzhaopeng3** [zhongyang219/TrafficMonitor#365]
Windows切换深/浅色模式后主题不会跟随系统变化，导致需要手动更改主题很不方便，建议添加主题跟随系统设置自动切换深/浅色主题~

**Comment by aoeiuv-liu** [comment]
+1

**Comment by zhongyang219** [comment]
我今天刚刚提交了代码，新增了自动适应Windows10深色/浅色主题的功能，请等待下个版本更新。或者你也可以[点击这里](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22)下载预发行版本体验。

**Comment by aoeiuv-liu** [comment]
nice！用上了。可以自动切换。暂时没发现BUG

**Comment by aoeiuv-liu** [comment]
还有个问题。 自动切换的时候是否可以自动更换托盘图标？

**Comment by aoeiuv-liu** [comment]
好像要求有点苛刻了。毕竟托盘图标可以选择那个蓝色的。

**Comment by aoeiuv-liu** [comment]
@zhongyang219 会从浅色模式自动切换成深色模式，但我刚才开电脑发现不会从深色模式自动切换成浅色模式

**Comment by aoeiuv-liu** [comment]
![image](https://user-images.githubusercontent.com/20061353/83756086-19bd4000-a6a1-11ea-8124-bdbb2e2c567e.png)

**Comment by zhongyang219** [comment]
@aoeiuv-liu 它只有在程序开着的时候检测到深浅色模式变化时才会切换，如果你在程序退出后从浅色模式切换成了深色模式，再打开程序的时候是不会自动切换的。当然这个设定也不一定就是合理的，或许还有改进的空间。

**Comment by zhongyang219** [comment]
@aoeiuv-liu 刚刚试了一下，好像确实有些问题，我再看一下。

**Comment by yangzhaopeng3** [comment]
> @aoeiuv-liu 刚刚试了一下，好像确实有些问题，我再看一下。

复议，深色模式关机第二天开机系统切换到浅色了这个不会变色

**Comment by zhongyang219** [comment]
@aoeiuv-liu @yangzhaopeng3 刚刚提交了代码，解决了这个问题，[点击这里](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22)下载。

**Comment by aoeiuv-liu** [comment]
我下载了最新的，今天早上开机还是不行。颜色还是错的，是不是只能下载你修好自动换色的那版？
![image](https://user-images.githubusercontent.com/20061353/83957546-31f8af00-a89b-11ea-9dee-93518b8ccc73.png)

**Comment by zhongyang219** [comment]
@aoeiuv-liu 我想确认一下，这个颜色设置和你关机之前是一样的吗？如果是一样的，那就不是程序的没问题了。另外，我这边也发现了一个bug，就是有时候会出现预设方案中的颜色全部变成了黑色的问题，我现在还在调查中，但是我很难复现它，你看看你这里是不是也出现了这个问题。

**Comment by aoeiuv-liu** [comment]
> @aoeiuv-liu 我想确认一下，这个颜色设置和你关机之前是一样的吗？如果是一样的，那就不是程序的没问题了。另外，我这边也发现了一个bug，就是有时候会出现预设方案中的颜色全部变成了黑色的问题，我现在还在调查中，但是我很难复现它，你看看你这里是不是也出现了这个问题。

不一样的。我下载了个自动切换深浅模式的软件叫auto dark mode ，昨晚重新启用网速软件的时候应该是深色模式，那个时候是正常的，今早开机的时候由auto dark mode自动切换成的浅色模式，网速的这个软件并没有切换

**Comment by aoeiuv-liu** [comment]
@zhongyang219 中间设置了一次浅色貌似正常了。

**Comment by aoeiuv-liu** [comment]
。。。。还是不行。

**Comment by zhongyang219** [comment]
新版本已经发布，问题应该解决了，issue先关闭，有问题再反馈。
