### ISSUE TITLE
透明任务栏,监控器的文字显示有问题

### ISSUE THREAD

**Issue by baosfeng** [zhongyang219/TrafficMonitor#367]
![snipaste20200505_135942](https://user-images.githubusercontent.com/26006595/81038488-c3f64c00-8ed8-11ea-8611-aeaa8c84b229.png)
![snipaste20200505_105353](https://user-images.githubusercontent.com/26006595/81031408-c186f880-8ebe-11ea-81ea-0f2a43ee11f8.png)

**Comment by kimonoki** [comment]
![image](https://user-images.githubusercontent.com/11910307/85503465-b0d44280-b624-11ea-976a-ca9aceb52ae1.png)
我的这样

**Comment by zhongyang219** [comment]
打开“选项设置”>“任务栏窗口设置”，将文本颜色设置为白色，背景颜色设置为黑色即可解决。
