### ISSUE TITLE
增加显示电池电量的功能

### ISSUE THREAD

**Issue by Young-Lord** [zhongyang219/TrafficMonitor#368]
Windows在任务栏显示的电池图标无法准确看出电池电量，望增加显示电池电量的功能

**Comment by zzzop** [comment]
加一，愚蠢的win10都没个百分比能看

**Comment by Young-Lord** [comment]
本人目前在用percentage，缺点就是样式太死板了


---原始邮件---
发件人: &quot;zzzop&quot;<notifications@github.com&gt;
发送时间: 2020年8月9日(周日) 晚上8:00
收件人: &quot;zhongyang219/TrafficMonitor&quot;<TrafficMonitor@noreply.github.com&gt;;
抄送: &quot;Young-Lord&quot;<2926182876@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [zhongyang219/TrafficMonitor] 增加显示电池电量的功能 (#368)




 
加一，愚蠢的win10都没个百分比能看
 
&mdash;

**Comment by takuen** [comment]
赞同

**Comment by Young-Lord** [comment]
https://github.com/zhongyang219/TrafficMonitorPlugins/blob/main/download/plugin_download.md#%E7%94%B5%E6%B1%A0%E7%94%B5%E9%87%8F%E6%8F%92%E4%BB%B6
