### ISSUE TITLE
流量历史记录如果一天大于2TB则重启程序后会回到2TB

### ISSUE THREAD

**Issue by xie0077** [zhongyang219/TrafficMonitor#369]
内存里可以记录，但是一旦程序退出再进入，读取traffic 历史记录文件后，则会回到2TB流量。

程序应该不支持64位统计日流量，建议修复这个bug。

**Comment by zhongyang219** [comment]
你好，感谢反馈，确实有这个问题，当初做的主要考虑到应该不会有人一天之内流量超过2TB🤣，所以一直没有去解决。目前这个问题已经在想办法解决了。

**Comment by zhongyang219** [comment]
新版本中已解决。
