### ISSUE TITLE
是否考虑过只有任务栏显示的版本, 不知这样是否可以加快启动速度

### ISSUE THREAD

**Issue by NavisLab** [zhongyang219/TrafficMonitor#370]
这个小工具非常棒, 但是感觉有个地方可以小小改进一下.

我的电脑实用的是SSD, 但是本工具设置了开机启动后, 在进入桌面后, 大概需要两秒钟才能完成启动.
对比了一下NetSpeedMonitor, 本工具开机自启动耗时有点长. 本工具更像是进入桌面后再打开. 不知道如果只在任务栏显示会不会速度会快一些.

因为我没有开发过这种开机自启动的GUI程序, 所以不清楚这个建议是否合适. 如果不合适, 请关闭该issue.

谢谢~

**Comment by PRAJNAPLAYER** [comment]
我也只喜欢任务栏

**Comment by liuxb** [comment]
同意，基本上很少看桌面，放桌面上意义不大。
