### ISSUE TITLE
无法记住网卡选择

### ISSUE THREAD

**Issue by AgaigetS** [zhongyang219/TrafficMonitor#376]
我一直定位在无线网卡，但有时不知是重启还是开了vpn就会使得网卡选择自动更改，比如定位到有线网卡，这样就很纳闷，期待修复

**Comment by Josh-Zhen** [comment]
可以自己更改啊

**Comment by zhongyang219** [comment]
在右键菜单“选择网络连接”中选择你要监控的无线网卡，不要选择“自动选择”，再试试看问题是否依然存在。

**Comment by zhongyang219** [comment]
你的问题和 #577 应该是同一个问题，现在已经修复，请更新到最新版本试试，如果还有问题欢迎反馈。
