### ISSUE TITLE
希望添加内存清理和温度查看的功能

### ISSUE THREAD

**Issue by wytskshu** [zhongyang219/TrafficMonitor#38]
如果再添加这2个功能，真的方便很多，可以抛弃其它很多软件，只需要下这一个，希望作者能看到

**Comment by ted423** [comment]
rammap

**Comment by zealotCE** [comment]
内存释放，这个是唬人的。最好的办法是把程序杀掉。

**Comment by yz0808** [comment]
> 如果再添加这2个功能，真的方便很多，可以抛弃其它很多软件，只需要下这一个，希望作者能看到

清理内存没什么乱用，加这个干嘛？
