### ISSUE TITLE
感谢作者，太好用了！提个小需求不知能否指日可待？

### ISSUE THREAD

**Issue by JackyWWX** [zhongyang219/TrafficMonitor#383]
此前一直用黑苹果，习惯用istat menu看各种系统监控
Win下确实没有可以完全代替的（什么360、鲁大师忽略）
期待状态栏添加CPU、GPU频率数值，以及各种硬件温度的监控显示，就完美了

**Comment by blog55** [comment]
赞同

**Comment by zhongyang219** [comment]
温度监控功能已添加
