### ISSUE TITLE
希望在任务栏能显示更多信息

### ISSUE THREAD

**Issue by itswrj** [zhongyang219/TrafficMonitor#389]
首先谢谢作者。工具很好用。
但是任务栏窗口只能显示网速，能不能把CPU和内存信息也加上？

**Comment by lovecyc** [comment]
任务栏窗口右键菜单，可以选择显示CPU和内存利用率
或者修改安装目录下的config.ini文件
task_bar_show_cpu_memory = true

**Comment by zhongyang219** [comment]
可以在任务栏窗口右键菜单“显示设置”中选择要显示的信息。
