### ISSUE TITLE
当每日流量过多的时候，统计值会溢出，无法正确统计。（约4000GB左右）

### ISSUE THREAD

**Issue by soloopooo** [zhongyang219/TrafficMonitor#391]
火绒同步统计流量：
![image](https://user-images.githubusercontent.com/36123081/84152677-8d8f8c00-aa97-11ea-8aec-55a3640c2d1a.png)
程序显示：
![image](https://user-images.githubusercontent.com/36123081/84153234-30e0a100-aa98-11ea-9566-806c4b964030.png)
3553GB时截图：
![RS~}8_ ~6)K4Z33$TYR594H](https://user-images.githubusercontent.com/36123081/84152802-aef07800-aa97-11ea-857c-7704e564f6fd.png)
history_traffic.dat的今日数据：
![image](https://user-images.githubusercontent.com/36123081/84152981-eb23d880-aa97-11ea-9b42-cbdf3fa85e2b.png)

另希望添加总流量使用的功能

**Comment by soloopooo** [comment]
中途并没有任何退出程序的操作。

**Comment by zhongyang219** [comment]
你好，这个问题确实存在，目前已经解决，请等待下个版本的发布。你也可以[点击这里](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22)下载最新的预发行版本以解决这个问题。

**Comment by zhongyang219** [comment]
新版本已经解决。
