### ISSUE TITLE
能否不显示网速？主窗体CPU/内存能显示状态条吗？

### ISSUE THREAD

**Issue by tp1415926535** [zhongyang219/TrafficMonitor#392]
能不能只监控CPU/内存情况？好像没有这个选项。
主窗体不能像任务栏窗口一样，显示占用状态条吗？或者占用率高的时候颜色发生变化加以提醒。

**Comment by huai168an** [comment]
同意，我也想不显示网络上传下载，只关注cpu和内存的

**Comment by zhongyang219** [comment]
任务栏只显示CPU和内存利用率的功能已经加上了，请等待版本更新。或者可以[点击这里](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22)下载预编译版本。

**Comment by huai168an** [comment]
非常棒，马上就去用 ：》



shenyang713@qq.com
 
发件人： zhongyang219
发送时间： 2020-07-07 18:20
收件人： zhongyang219/TrafficMonitor
抄送： huai168an; Comment
主题： Re: [zhongyang219/TrafficMonitor] 能否不显示网速？主窗体CPU/内存能显示状态条吗？ (#392)
任务栏只显示CPU和内存利用率的功能已经加上了，请等待版本更新。或者可以点击这里下载预编译版本。

**Comment by tp1415926535** [comment]
> 任务栏只显示CPU和内存利用率的功能已经加上了，请等待版本更新。可以或者[点击这里](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22)下载预编译版本。

期待主窗口也提供这样的选择

**Comment by zhongyang219** [comment]
@tp1415926535 主窗口没有这样的选项，因为主窗口显示哪些项目是跟随皮肤的，如果你想在主窗口中只显示CPU和内存利率而不显示网速，可以在右键菜单>其他功能>更换皮肤中点击“更多皮肤下载”，或者直接[点击这里](https://github.com/zhongyang219/TrafficMonitorSkin/blob/master/%E7%9A%AE%E8%82%A4%E4%B8%8B%E8%BD%BD.md)下载相应的皮肤，其中“默认皮肤（简洁）”、“皮肤09（简洁）”、“皮肤11 (2)”、“金山悬浮窗 (2)”都是只显示CPU内存利用率而不显示网速的。
