### ISSUE TITLE
CPU usage does not work with Spanish as default System language.

### ISSUE THREAD

**Issue by EternalARK** [zhongyang219/TrafficMonitor#393]
I've tested in several devices of Windows 10 2004.
If I set the language to Spanish, then the CPU usage will always be 0 percent.
Can you patch that?

**Comment by rmattuschka** [comment]
i had the same problem with german win10. 
Replacing in function "CCPUUsage::GetCPUUsageByPdh()": 
          PdhAddCounter(..) -> PdhAddEnglishCounter(..)
 works for me!

**Comment by zhongyang219** [comment]
Thank for your feedback. I have noticed that some users have encountered the same problem. You can [click here](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22) to download the latest pre-release version. Select "Options..." - "General Settings" - "CPU usage acquisition method" -"Based on CPU time". It may save this problem.

**Comment by EternalARK** [comment]
Done, Gracias.
