### ISSUE TITLE
Win10 64位 使用应用商店主题 “Wooden walkways PREMIUM”  状态栏字体看不清

### ISSUE THREAD

**Issue by liaosc-ai** [zhongyang219/TrafficMonitor#397]
如图所示
![微信截图_20200618092042](https://user-images.githubusercontent.com/39718889/84967104-bffb5200-b145-11ea-95ff-71b7aebd1c8f.png)

**Comment by zhongyang219** [comment]
请打开“选项设置”——“任务栏窗口设置”，将“背景颜色”和“透明色”都改成纯黑色，应该可以解决这个问题。
我在下个版本中对任务栏显示做了一些改进，下个版本应该可以避免这种情况了。

**Comment by liaosc-ai** [comment]
设置后可以解决
