### ISSUE TITLE
调整分辨率后不自动跟着变

### ISSUE THREAD

**Issue by PHCSJC** [zhongyang219/TrafficMonitor#398]
有时切换显示器，分辨率不一样，切换后，TrafficMonitor的大小并没有跟着改变，还是之前的分辨率，就会显得特别小，临时的解决办法是退出TrafficMonitor再打开。

**Comment by Vtrust** [comment]
我也遇到了这个问题 从2k 200%缩放 到 1080p 100%的外接显示器 软件还是按照2k 200%的缩放 进行显示 就会比正常的大很多
![image](https://user-images.githubusercontent.com/16085476/86075912-b1a12480-babb-11ea-9ff6-4d820adba76a.png)

**Comment by kkzzhizhou** [comment]
+1

**Comment by ninko2019** [comment]
+1

**Comment by weizhi2020** [comment]
+1

**Comment by zhongyang219** [comment]
这个问题解决起来比较复杂，如果遇到这个问题，建议还是退出TrafficMonitor再启动吧。

**Comment by zhongyang219** [comment]
这个问题在1.80版本中已经解决
