### ISSUE TITLE
希望任务栏窗口增加显示CPU和GPU温度

### ISSUE THREAD

**Issue by xiaoxiongmao666** [zhongyang219/TrafficMonitor#399]
因为只需求这两个，同时又非常喜欢任务栏显示的风格，希望作者能考虑一下。另外任务栏显示很少有监控软件做，又方便又省空间，能否考虑增加更多的显示内容，同时，网络监控也作为可选内容可以取消掉。

**Comment by yzgyyang** [comment]
+1

**Comment by ninko2019** [comment]
+1

**Comment by flyingleafwh** [comment]
同样希望增加cpu温度显示 。

但请保留网络速度的选项，网络还可以选不同的网卡，做的真不错。

**Comment by frustreated** [comment]
同求

**Comment by bearbro** [comment]
首先感谢作者!
希望能增加GPU利用率和显存利用率

**Comment by txyyh** [comment]
同求，老电脑散热不好，需要可以监视CPU GPU温度

**Comment by MIONKING** [comment]
感谢作者的付出，同求这个功能~

**Comment by Crownzhu** [comment]
+1

**Comment by MakkZitning** [comment]
附议。

**Comment by zhongyang219** [comment]
温度监控功能已添加

**Comment by xiaoxiongmao666** [comment]
> 温度监控功能已添加

立刻用上了，新皮肤配色很好看，任务栏窗口也弄成了这个配色，我直接喊大佬牛逼！
