### ISSUE TITLE
希望优化“只启用任务栏窗口”时软件自启动

### ISSUE THREAD

**Issue by aisubing** [zhongyang219/TrafficMonitor#4]
设置：启用任务栏窗口+隐藏主窗口
问题：软件启动时会先显示主窗口，然后隐藏，再显示任务栏窗口
感觉这个过程有点拖沓，能不能不启动主窗口，直接显示任务栏窗口

**Comment by zhongyang219** [comment]
@aisubing 这个问题我已经注意到了，你的意思是说，如果设置了隐藏主窗口，在程序启动时主窗口还是会显示1秒钟再隐藏是吧。在最初的时候我确实是想让它在启动时直接隐藏的，但是在窗口初始化时设置隐藏窗口这个操作会无效，所以我就让它在定时器第1次触发时再隐藏，就变成了现在的样子。由于我觉得这个问题不大所以一直没管它，我会在下个版本中修正这个问题的。
至于为什么任务栏窗口也延迟了1秒再显示，那是以前为了避免刚开机时任务栏还没有启动导致嵌入任务栏操作失败，我可以试试让它不延迟1秒。

**Comment by aisubing** [comment]
@zhongyang219 感谢回复，就是这个意思。期待新版本！

**Comment by zhongyang219** [comment]
这个问题已经修正了，解决的方法其实是在启动时将主窗口的不透明度设为0，窗口就完全看不见了，1秒钟后再将不透明度改回来。
