### ISSUE TITLE
¡Presets Does not keep after reboot the Windows ! 

### ISSUE THREAD

**Issue by EternalARK** [zhongyang219/TrafficMonitor#400]
Sorry to bother you again.
I'm using the latest test build of it. With configuration of save to program directory on.
The presets I've configured will always reset to all black after reboot the windows. Any idea now?

**Comment by zhongyang219** [comment]
Thank you for your feedback. I have noticed this problem too. The latest build may have save this problem. You can download the latest pre-release version, and check if this problem still exist.
In fact, I still didn't found out why this problem happened. I just added a judgement when saving the presets, if the presets are all black, then don't save it.

**Comment by zhongyang219** [comment]
The commit that I try to save this problem is [here](https://github.com/zhongyang219/TrafficMonitor/commit/2fa1ae23da258a4c263ec973a8b4d458687e466c).
