### ISSUE TITLE
CPU利用率和任务管理器一致性的问题

### ISSUE THREAD

**Issue by antatura** [zhongyang219/TrafficMonitor#406]
我看到最新版的更新说明中有一条：“修正Windows10中CPU利用率和任务管理器不一致的问题”。
这指的是最新版的TrafficMonitor的CPU使用率已经同任务管理器一致了吗？
我用 HWiNFO 查看CPU使用率信息，有两个项目：Max CPU/Thread Usage 和 Total CPU Usage
Max CPU/Thread Usage 值较大；而 Total CPU Usage 值较小
任务管理器用的是 Max CPU/Thread Usage 值； 旧版本 TrafficMonitor 用的是 Total CPU Usage 值
我更倾向于关注 Total CPU Usage 值。
因为 Total CPU Usage 从字面意义上来看是CPU总体使用率，而另一个是最大使用率。

**Comment by zhongyang219** [comment]
你好，我现在为TrafficMonitor添加了一个选项，可以切换回旧版TrafficMonitor的CPU使用率，请等待更新

**Comment by antatura** [comment]
> 你好，我现在为TrafficMonitor添加了一个选项，可以切换回旧版TrafficMonitor的CPU使用率，请等待更新

好的👌非常感谢🙇‍
