### ISSUE TITLE
增加设置数据刷新频率的选项

### ISSUE THREAD

**Issue by shellqiqi** [zhongyang219/TrafficMonitor#407]
https://github.com/zhongyang219/TrafficMonitor/blob/167e9940df72f8d9dca8a9eb187c3020ad8a4686/TrafficMonitor/TrafficMonitorDlg.cpp#L819-L820
https://github.com/zhongyang219/TrafficMonitor/blob/167e9940df72f8d9dca8a9eb187c3020ad8a4686/TrafficMonitor/TrafficMonitorDlg.cpp#L866

这些值可修改

**Comment by zhongyang219** [comment]
新版本中已添加此功能。
