### ISSUE TITLE
压缩包可能损坏

### ISSUE THREAD

**Issue by bebestmaple** [zhongyang219/TrafficMonitor#419]
下载了TrafficMonitor_V1.79_x64.7z，打不开，TrafficMonitor_V1.79_x86.7z可以打开

**Comment by zhongyang219** [comment]
我这边测试下来的压缩包是正常的，github国内访问可能会比较慢，请检查一下你下载的压缩包是否完整。如果还是不行可以从百度网盘链接下载。
