### ISSUE TITLE
希望 历史流量统计 功能可以关闭

### ISSUE THREAD

**Issue by awakening233** [zhongyang219/TrafficMonitor#42]
顺便, 多谢大大开发出这么好用的软件.

**Comment by zhongyang219** [comment]
为什么要关闭呢？如果你不用，它也没什么影响啊。

**Comment by awakening233** [comment]
可能就是强迫症吧, 哈哈

**Comment by vvb2060** [comment]
> 为什么要关闭呢？如果你不用，它也没什么影响啊。

#2225 可能影响ssd寿命，发现在静置PC期间依然每30s完整写入一次
