### ISSUE TITLE
建議：在  [主視窗設定]  中增加  [最上層顯示]  選項

### ISSUE THREAD

**Issue by pandy003** [zhongyang219/TrafficMonitor#421]
您好：
問題點：當 [主視窗] 位置放在工作列時 ，按右鍵取消  [最上層顯示]  後無法再次顯示 [主視窗] ，因此無法再次選取  [最上層顯示] 。 
              需要到 config.ini  中修改 always_on_top = false  改成 true  [主視窗] 才會顯示，實在不方便。
建   議：在  [主視窗設定]  中增加  [最上層顯示]  選項     .............  謝謝

**Comment by zhongyang219** [comment]
一般情况下，主窗口是不能移动到任务栏区域的，除非你开启了“允许超出屏幕边界”选项。由于任务栏同样具有置顶属性，因此任务栏可能会把主窗口覆盖。
你可以在通知区的图标中点击鼠标右键，在菜单中重新选中“最上層顯示”。

**Comment by zhongyang219** [comment]
这些设置后面会考虑添加到“选项设置”>“主窗口设置中”.

**Comment by pandy003** [comment]
謝謝
