### ISSUE TITLE
设置了开机启动项，但是开机不会自动启动

### ISSUE THREAD

**Issue by zhaokelei** [zhongyang219/TrafficMonitor#423]
设置了开机启动项，但是开机不会自动启动
![image](https://user-images.githubusercontent.com/17022061/88994512-2796e680-d31b-11ea-8900-0c2b3006b0bf.png)
![image](https://user-images.githubusercontent.com/17022061/88994541-34b3d580-d31b-11ea-9aea-331e8688bcc8.png)
需要双击软件才会启动

**Comment by littleghost2016** [comment]
同出现这个问题。
常规设置里面勾选了`开机时自动启动`且`确定`后，再打开设置，`开机时自动启动`仍然是未勾选状态。
`以管理员身份运行`执行上述操作依然存在同样问题。
操作系统为Winsows10 1909，使用`scoop`安装。

**Comment by zhongyang219** [comment]
@littleghost2016 我这边并没有出现你说的问题。另外，我没有用过scoop这个软件，TrafficMonitor是绿色软件，不需要安装，将下载的压缩包解压就能直接运行。

**Comment by littleghost2016** [comment]
> @littleghost2016 我这边并没有出现你说的问题。另外，我没有用过scoop这个软件，TrafficMonitor是绿色软件，不需要安装，将下载的压缩包解压就能直接运行。

开发者您好，我发现我的问题是其他设置均可保存，唯独开机启动无法勾选。经排查是安装的`联想电脑管家`自动阻止的原因（没有任何阻止了的提示）。
解决方法：关闭`联想电脑管家`，设置勾选`开机时自动启动`，这样之后即可正常开机自启动。
非常感谢您的软件开发！

**Comment by zhongyang219** [comment]
@littleghost2016 开机启动的功能其实是通过在注册表\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run中添加启动项来实现的，如果遇到无法开机启动的问题，可以先检查一下注册表项是否已创建，以及路径是否正确。

**Comment by littleghost2016** [comment]
> @littleghost2016 开机启动的功能其实是通过在注册表\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run中添加启动项来实现的，如果遇到无法开机启动的问题，可以先检查一下注册表项是否已创建，以及路径是否正确。

学到了学到了，感谢您的耐心解答！

**Comment by zhaokelei** [comment]
> @littleghost2016 我这边并没有出现你说的问题。另外，我没有用过scoop这个软件，TrafficMonitor是绿色软件，不需要安装，将下载的压缩包解压就能直接运行。
![image](https://user-images.githubusercontent.com/17022061/89248571-adc86b00-d642-11ea-9aaf-ecc54a81ae4d.png)

![image](https://user-images.githubusercontent.com/17022061/89248593-bcaf1d80-d642-11ea-94de-d871f0ad0723.png)
勾选注册表有数据 但是不启动，找不到问题

**Comment by zhaokelei** [comment]
现在问题解决了  用另一个软件注册注册表启动后启动软件
