### ISSUE TITLE
最新版，注册表句柄泄露

### ISSUE THREAD

**Issue by QQ2017** [zhongyang219/TrafficMonitor#431]
![image](https://user-images.githubusercontent.com/23667705/89241008-528d7d00-d630-11ea-8d08-c726233912e2.png)
![image](https://user-images.githubusercontent.com/23667705/89241072-7c46a400-d630-11ea-8dc1-6ddcac835241.png)

版本1.79。如图，这个注册表键打开后未关闭：
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize

**Comment by MarioCrane** [comment]
我也遇到了同样的问题，每秒访问一次，已经退回到1.78。请问用的什么分析软件？

**Comment by QQ2017** [comment]
> 我也遇到了同样的问题，每秒访问一次，已经退回到1.78。请问用的什么分析软件？

Process explorer

**Comment by QQ2017** [comment]
看了下代码，请作者增加一行绿色框中的代码即可解决问题。
![image](https://user-images.githubusercontent.com/23667705/89362488-9cde2f00-d700-11ea-9659-be0ccb2077ab.png)

**Comment by QQ2017** [comment]
我重新编译了，大家可以试试，版本1.7.9.1
下载：https://wwa.lanzous.com/ijimFfb3ecf

**Comment by zhongyang219** [comment]
感谢你的反馈，代码已修正，我会在今天晚上推送一个修正后的版本。

**Comment by MarioCrane** [comment]
> > 我也遇到了同样的问题，每秒访问一次，已经退回到1.78。请问用的什么分析软件？
> 
> Process explorer

多谢
