### ISSUE TITLE
建议对流量传输显示进行数值优化，以及大流量的单位换算问题

### ISSUE THREAD

**Issue by soloopooo** [zhongyang219/TrafficMonitor#434]
## 大流量传输的显示问题
在进行大流量传输（超过300MB/s）时，如果刷新时间过长，会出现无法统计（显示为0）的情况。
例：（与火绒对比）
刷新率为500ms：大约4次统计出现一次
![image](https://user-images.githubusercontent.com/36123081/89373942-9362c000-d71c-11ea-83eb-fb35e4022faf.png)
![image](https://user-images.githubusercontent.com/36123081/89374064-e2a8f080-d71c-11ea-861c-cfb6bbbcf63f.png)

刷新率为1000ms：全部为0

## 大流量传输的单位：

GB/s和Gb/s换算出现错误：
与火绒对比：
![image](https://user-images.githubusercontent.com/36123081/89374268-78448000-d71d-11ea-8228-7a289b8e146f.png)

具体：数值在40Mb/s和4Gb/s间来回跳动4-5次后突然变为0，与上面的情况一样。

**Comment by zhongyang219** [comment]
感谢反馈，这个问题存在，后面会想办法优化

**Comment by zhongyang219** [comment]
目前如果每一次统计的流量超过1GB就会变成0。之所以这么处理是因为当网络环境发生变化时可能会导致计算流量时数据溢出导致网速变成4GB的问题，当初设计的时候并没有想到会有人在一秒的流量达到1GB。但是由于目前使用的统计流量的API使用的数据类型是32位整数，因此仍然不能支持一次统计超过4GB的流量。

**Comment by soloopooo** [comment]
> 目前如果每一次统计的流量超过1GB就会变成0。之所以这么处理是因为当网络环境发生变化时可能会导致计算流量时数据溢出导致网速变成4GB的问题，当初设计的时候并没有想到会有人在一秒的流量达到1GB。但是由于目前使用的统计流量的API使用的数据类型是32位整数，因此仍然不能支持一次统计超过4GB的流量。

谢谢您的解释。

**Comment by soloopooo** [comment]
> 目前如果每一次统计的流量超过1GB就会变成0。之所以这么处理是因为当网络环境发生变化时可能会导致计算流量时数据溢出导致网速变成4GB的问题，当初设计的时候并没有想到会有人在一秒的流量达到1GB。但是由于目前使用的统计流量的API使用的数据类型是32位整数，因此仍然不能支持一次统计超过4GB的流量。

然而这里查看的情况是，可以正常显示4-5次 1GB/s ，之后的一次统计会变成0，而且，在300-400MB/s的时候，也会产生这种情况。

**Comment by heicks** [comment]
果然贫穷限制了我的想象力, 网速每秒GB见识到了.....

**Comment by Hoshiya233** [comment]
> 果然贫穷限制了我的想象力, 网速每秒GB见识到了.....

内网传输1GB/s不是很正常的事情吗

**Comment by soloopooo** [comment]
2021/03/09补充：

据观察与测试，现阶段即使是在较低流量速度状态下（120MB/s左右），也会出现时不时速度变为0的问题。

使用最新的构建测试。

**Comment by zhongyang219** [comment]
你好，请使用最新版本测试一下这个问题是否还存在。

**Comment by soloopooo** [comment]
> 你好，请使用最新版本测试一下这个问题是否还存在。

![image](https://user-images.githubusercontent.com/36123081/118363861-e67d7380-b5c8-11eb-8d87-4500723ba263.png)
![image](https://user-images.githubusercontent.com/36123081/118363862-e9786400-b5c8-11eb-88e3-05f5ecc54543.png)
问题应该是解决了

**Comment by soloopooo** [comment]
![image](https://user-images.githubusercontent.com/36123081/118364287-753ec000-b5ca-11eb-9baf-7fff56bb20d4.png)

补充 Bytes和Bits的转换也正常了
