### ISSUE TITLE
选项设置页和任务栏右键菜单自动适应 Windows10 深色／浅色主题

### ISSUE THREAD

**Issue by Geeyun-JY3** [zhongyang219/TrafficMonitor#435]

**Comment by Geeyun-JY3** [comment]
很抱歉之前没有先善用搜索，没发现已有相关 commit (https://github.com/zhongyang219/TrafficMonitor/commit/279b933df323b2d38a128e137bbe1ecdd84fe35f )，也不知道 Actions 有最新预发行构建版本。

**Comment by Geeyun-JY3** [comment]
看错了 commit message，好像还没实现

**Comment by zhongyang219** [comment]
很抱歉，在TrafficMonitor目前的框架下无法实现这个需求，除非微软实现Win32程序的全局深色/浅色主题，或者使用其他框架重写TrafficMonitor，但是我目前不打算这么做。
