### ISSUE TITLE
BUG？

### ISSUE THREAD

**Issue by linexu** [zhongyang219/TrafficMonitor#436]
今天升級了最新版本，但是在任務欄無法顯示“CUP”和“內存”的數據了。無論怎麼調試都不顯示。

**Comment by Miao-Mico** [comment]
这里开一下，就可以了
![image](https://user-images.githubusercontent.com/42897857/89498118-30daf400-d7f0-11ea-8b75-ad3c6bcaed38.png)

**Comment by linexu** [comment]
OK，好了，謝謝
