### ISSUE TITLE
trend micro ransom buster detect TrafficMonitor as suspicious

### ISSUE THREAD

**Issue by Monessem** [zhongyang219/TrafficMonitor#441]
![image](https://user-images.githubusercontent.com/8516994/89651364-1d995880-d8c4-11ea-9b8b-98abeec2de6e.png)

![image](https://user-images.githubusercontent.com/8516994/89651243-ed51ba00-d8c3-11ea-91cc-d7aaabf1537c.png)

![image](https://user-images.githubusercontent.com/8516994/89651292-00648a00-d8c4-11ea-9bb6-89d04e3beeb9.png)

**Comment by zhongyang219** [comment]
I' m sory I have no idea of this problem. You can add TrafficMonitor to their allow list.
