### ISSUE TITLE
在任务栏显示不靠右，与通知区域图标位之间留有空白

### ISSUE THREAD

**Issue by chenhsu007** [zhongyang219/TrafficMonitor#443]
![image](https://user-images.githubusercontent.com/47135790/89711426-d2af3c00-d9bc-11ea-8aa9-305cb57a85f8.png)
(url)
![image](https://user-images.githubusercontent.com/47135790/89711484-228e0300-d9bd-11ea-9ade-743c4cba2f38.png)

如图，设置默认显示，但是显示的位置中间留有空白，离最右侧通知图标区域很远，不知道什么原因

**Comment by skyformat99** [comment]
这个是不是系统问题啊

**Comment by chenhsu007** [comment]
> 这个是不是系统问题啊

不像啊，我两台电脑都这样了，不知道啥原因

**Comment by zhongyang219** [comment]
先重新启动一下软件试试，如果还是不行，那么这可能是任务栏右侧还有其他工具栏导致的，在任务栏点击鼠标右键，选择“工具栏”，看看有没有勾选其他实际上不显示的工具栏，如果有，去掉其勾选看看。

**Comment by chenhsu007** [comment]
莫名其妙自己好了，已经解决了，谢谢了
