### ISSUE TITLE
win10显示cpu占用和任务管理器中的占用不一致

### ISSUE THREAD

**Issue by xingzhuimuming** [zhongyang219/TrafficMonitor#445]
![QQ截图20200811140358](https://user-images.githubusercontent.com/69234422/89862959-9279d480-dbdb-11ea-8eb0-d35e83591bec.png)
![QQ截图20200811140453](https://user-images.githubusercontent.com/69234422/89862986-a58ca480-dbdb-11ea-8aba-b18827c6766d.png)

在win10中主窗口中显示占用很低，但是实际占用很高

**Comment by TechnologyK** [comment]
我的Win10也是这样的情况。
查看选项设置，发现默认CPU使用率获取方式是【基于CPU使用时间】，改成【使用性能计数器】后发现数值和系统任务管理器的值差不多了。

**Comment by zhongyang219** [comment]
楼上+1。目前默认是选择的时“基于CPU使用时间”，上一个版本就是使用的性能计数器，但是部分用户反馈会出现CPU使用率一直为0的问题。

**Comment by xingzhuimuming** [comment]
> 我的Win10也是这样的情况。
> 查看选项设置，发现多个CPU使用率获取方式是【基于CPU使用时间】，改成【使用性能计数器】后发现数值和系统任务管理器的值差不多了。
> ![Snipaste_2020-08-12_15-15-28](https://user-images.githubusercontent.com/7446325/89986443-28cafa80-dcaf-11ea-9ce5-feb17d86ad1d.png)
> ![Snipaste_2020-08-12_15-20-14](https://user-images.githubusercontent.com/7446325/89986583-557f1200-dcaf-11ea-8ea5-d872ee930113.png)

好的 谢谢

**Comment by xingzhuimuming** [comment]
> 楼上+1。目前总是是选择的时“基于CPU使用时间”，上一个版本就是使用的性能计数器，但是部分用户反馈会出现CPU使用率一直为0的问题。

明白了 谢谢

**Comment by lzfyh2017** [comment]
请问这个“选项设置”在哪里打开，没有找到，谢谢各位大佬
![image](https://user-images.githubusercontent.com/46252635/90298747-f7784780-dec5-11ea-8c9f-003198f4c867.png)

**Comment by zhongyang219** [comment]
@lzfyh2017 右键菜单里选择“选项(O)...”
![image](https://user-images.githubusercontent.com/30562462/90304054-6cf41000-dee6-11ea-8107-ed00f8899959.png)

**Comment by lzfyh2017** [comment]
> @ lzfyh2017快捷菜单里选择“选项（O）...”
> ![图片](https://user-images.githubusercontent.com/30562462/90304054-6cf41000-dee6-11ea-8107-ed00f8899959.png)

感谢，原来是软件里的，，，

**Comment by MRWangXiaoSuai** [comment]
啥软件
