### ISSUE TITLE
1.79.1无论如何设置，任务栏窗口始终不显示CPU占用率和内存占用率，1.79.0没有此问题。

### ISSUE THREAD

**Issue by steelpad** [zhongyang219/TrafficMonitor#451]
已解决，在任务栏窗口鼠标右键设置即可。

**Comment by 0xinsheng0** [comment]
具体一点？我也是是这个问题。

**Comment by hao3han3** [comment]
![图片](https://user-images.githubusercontent.com/46490355/93019750-460a2600-f5d9-11ea-81ef-f86caa5c8904.png)

1，右键单击，呼出菜单
2，（不解释）
3，（不解释）

这个issue可以关闭了

**Comment by ritaswc** [comment]
请关闭issue
