### ISSUE TITLE
主机4k 缩放200%，通过远程1080P访问，任务栏数值不会相应的缩小

### ISSUE THREAD

**Issue by Actuallymax** [zhongyang219/TrafficMonitor#455]
家里的电脑是4k显示器，缩放200%
办公室电脑是1080P

办公室电脑通过远程连接家里的电脑，任务栏的网速字会特别大，要重启一下trafficmonitor才正常，其他app的图标字体都会相应的缩小。

**Comment by jayagami** [comment]
same with me. Tow seceen with different resolution and resolution

**Comment by zhongyang219** [comment]
这个问题现在已经解决，请等待下载版本更新，或者下载最新的预发行构建版本试试。
