### ISSUE TITLE
【选择网络连接里】能否增加全部连接？

### ISSUE THREAD

**Issue by aglent** [zhongyang219/TrafficMonitor#46]
我的电脑有些特殊 
有线网卡和无线网卡分别接电信和移动宽带 win10系统添加了路由表 有线网卡走国内 无线网卡走国外
TrafficMonitor 网络连接 选了【自动选择】 但是软件只显示有线网卡的流量 无线网卡流量显示0
能否添加选项 监控所有网络接口的流量？
谢谢

**Comment by Steven2131** [comment]
+1
如果能自动调整网络接口监视状态就好了

**Comment by zhongyang219** [comment]
目前对于多个网卡都有网速的情况确实支持得不够好，监控所有网络的功能我会考虑一下。

**Comment by zhongyang219** [comment]
监视所有网卡网速的功能已经增加了，请更新到1.74版本试试。

**Comment by aglent** [comment]
@zhongyang219 非常感谢！
