### ISSUE TITLE
ip address not work

### ISSUE THREAD

**Issue by ritaswc** [zhongyang219/TrafficMonitor#465]
<img width="949" alt="Jietu20200906-121222" src="https://user-images.githubusercontent.com/15887140/92318345-b21ae600-f03d-11ea-90b7-c1695a1d7185.png">

Version 1.79.1 x64 最后编译时间2020-08-05
操作系统 windows7 旗舰 x64 sp  6.1.7601  内部版本7601

如果你需要
我可以给你编写一个通用型使用报错上报的接口，然后通过钉钉群聊机器人、企业微信群聊机器人、邮件、Server酱(微信公众号模板消息) 其中之一方式通知到你，当然肯定需要用户点击同意上报才行

**Comment by zhongyang219** [comment]
感谢反馈，这个问题好像只在Win7下出现，Win10是正常的。我看了一下返回的错误代码是12057，MSDN的解释是“Revocation of the SSL certificate failed.”，目前我也没有什么头绪。

**Comment by zhongyang219** [comment]
我知道了，在“Internet选项”——“高级”中去掉“检查服务器证书是否已吊销”的选项就好了，跟Win7还是Win10无关。

**Comment by ritaswc** [comment]
应该是win7 没有内置我这网站证书对应的根证书
