### ISSUE TITLE
主窗口消失问题

### ISSUE THREAD

**Issue by hunklovey** [zhongyang219/TrafficMonitor#467]
作者您好，本人是双屏幕，调到副屏幕后，主屏幕启动全屏游戏后，副屏幕的主窗口消失，退出全屏游戏又重现，这是bug吗？还是我设置问题？PS.真是款不错的小软件，非常喜欢，作者大大厉害么么哒~

**Comment by zhongyang219** [comment]
![image](https://user-images.githubusercontent.com/30562462/112836470-3cf02a80-90cd-11eb-9c6e-8ea908a3c513.png)
把图中的勾去掉即可。
