### ISSUE TITLE
x64 debug 报错

### ISSUE THREAD

**Issue by ghosoft** [zhongyang219/TrafficMonitor#47]
多谢楼主的分享, 我刚开始学习, 用vs打开了项目, 点debug, x86不报错, x64会报错

![image](https://user-images.githubusercontent.com/4844538/39456480-44a07c9e-4d19-11e8-95eb-5a544cb49e93.png)

**Comment by ghosoft** [comment]
![image](https://user-images.githubusercontent.com/4844538/39456525-96d36274-4d19-11e8-872d-9a8e33d7d015.png)
就是这里

**Comment by liuzhyun** [comment]
hFile类型改一下就可以了，msdn里_wfindfirst返回的的类型是intptr_t，在64位时实际定义的是__int64，32位才是int

**Comment by zhongyang219** [comment]
@sondragon 多谢指正，之前就发现x64时会出错的问题，但是一直没有去调查。现在代码已经改正了。
@ghosoft 改正后的代码已经提交了，你重新下载一下最新的代码就好了。
