### ISSUE TITLE
可以新增状态栏高度间隙吗？

### ISSUE THREAD

**Issue by Shillber** [zhongyang219/TrafficMonitor#472]
![image](https://user-images.githubusercontent.com/32611596/93852207-34650480-fce4-11ea-9e85-11cac68a96df.png)
可以新增状态栏高度间隙吗？目前感觉右边那个更漂亮

**Comment by Shillber** [comment]
> 我也感觉默认的样式不太行，不过既然开发者提供了自定义字体和大小的功能，调整一下后个人感觉也还不错
> ![ERFQ%ZO%6XF%IH D} G3H3](https://user-images.githubusercontent.com/66640838/95905369-4b998e00-0d88-11eb-9381-a746500a3cd8.png)

你的挺好看的，设置参数是呀

**Comment by Savues** [comment]
这样的
![20201014031701](https://user-images.githubusercontent.com/66640838/96260961-55bec500-0ff2-11eb-9ae4-6b6110dc662d.png)
