### ISSUE TITLE
在任务栏的时候，虚线的框框不美观

### ISSUE THREAD

**Issue by wang-yichun** [zhongyang219/TrafficMonitor#476]
任务栏显示CPU 和内存，并且显示状态条的时候。发现周围会出现一圈虚线。比较丑，能否有其它的方案？

**Comment by 0xinsheng0** [comment]
选项>任务窗口设置>cpu/内存显示状态 把√去掉！

**Comment by zhongyang219** [comment]
我已经增加了一个去掉虚线框的选项，请等待下个版本更新
