### ISSUE TITLE
建议添加CPU，GPU温度。

### ISSUE THREAD

**Issue by 0xinsheng0** [zhongyang219/TrafficMonitor#478]
每次开机都要开几个软件才能安心玩游戏，心累，关键是其他软件吃内存和CPU。

**Comment by febzhang** [comment]
+1
强烈建议增加CPU温度。
CPU温度、CPU和内存利用率、网速。唯三需要监控的指标。

**Comment by dearjnana** [comment]
CPU温度，GPU温度 确实很有必要，现在这个软件就缺这两项了。

**Comment by gx199112** [comment]
显示在任务栏windows徽标旁边，而不是任务托盘附近 如何解决

**Comment by pdone** [comment]
+1

**Comment by cfzy** [comment]
CPU温度，GPU温度，++++++++++

**Comment by guilin007** [comment]
能加上CPU温度，GPU温度，就完美了

**Comment by boyl** [comment]
+1

**Comment by fjj739964256** [comment]
越来越臃肿了。。。我还是用旧版吧。加这加那的，最后回头看，已不是流量监控软件了。

**Comment by hatanoyui** [comment]
加这加那，干部不直接用  ludashi   ？

**Comment by 0xinsheng0** [comment]
> 加这加那，干部不直接用 ludashi ？

不觉得鲁大师更加臃肿吗？

**Comment by Riajyuu** [comment]
如果楼主的电脑必须要看着CPU/GPU温度才能小心玩游戏。。。那我觉得离换也不远了

**Comment by taotao913** [comment]
![image](https://user-images.githubusercontent.com/56316172/100234457-16c34e00-2f66-11eb-93f4-88acc70bc0b6.png)
楼上各位，微星小飞机可以做到监控温度哦

**Comment by taotao913** [comment]
1

**Comment by zhongyang219** [comment]
温度监控的功能已经加上了，请等待下个版本更新。当然，如果你觉得功能太多太臃肿，我也同时提供了不含温度监控的版本。
