### ISSUE TITLE
分辨率更改时悬浮窗位置变化

### ISSUE THREAD

**Issue by CBPJ** [zhongyang219/TrafficMonitor#480]
当分辨率从小变大时，悬浮窗从右下角移动到较中心位置。

建议在配置文件中用悬浮窗位置的x,y坐标与屏幕分辨率的百分比表示悬浮窗位置，并在屏幕分辨率变化时重新计算悬浮窗位置，以避免分辨率变化时悬浮窗位置变化。

**Comment by zhongyang219** [comment]
这个问题已经解决了，请等待下个版本更新，或者下载最新的预发行构建版本试试
