### ISSUE TITLE
无法获取外网IP地址（IPV4和IPV6都不行）

### ISSUE THREAD

**Issue by Jensenhang** [zhongyang219/TrafficMonitor#488]
![捕获](https://user-images.githubusercontent.com/38093101/98329941-50bec580-2034-11eb-82af-e0916a19812b.JPG)

**Comment by ritaswc** [comment]
你好，获取外网IP地址背后的接口是我提供的。
是win7系统么，win7系统的根证书比较低。
个人建议更新一下系统跟证书，毕竟买兼容性比较好的根证书太费钱了
手动狗头

**Comment by ritaswc** [comment]
亲，能否加一下我的微信，麻烦你协助我测试一下
maidou__xhu

**Comment by Jensenhang** [comment]
我用的是win10 版本号20H2



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Charles Zhu"<notifications@github.com&gt;; 
发送时间: 2020年11月13日(星期五) 上午10:09
收件人: "zhongyang219/TrafficMonitor"<TrafficMonitor@noreply.github.com&gt;; 
抄送: "张航"<zhanghang2009@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhongyang219/TrafficMonitor] 无法获取外网IP地址（IPV4和IPV6都不行） (#488)





 
你好，获取外网IP地址背后的接口是我提供的。
 是win7系统么，win7系统的根证书比较低。
 个人建议更新一下系统跟证书，毕竟买兼容性比较好的根证书太费钱了
 手动狗头

**Comment by Jensenhang** [comment]
已加




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhongyang219/TrafficMonitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 上午10:12
收件人:&nbsp;"zhongyang219/TrafficMonitor"<TrafficMonitor@noreply.github.com&gt;;
抄送:&nbsp;"张航"<zhanghang2009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhongyang219/TrafficMonitor] 无法获取外网IP地址（IPV4和IPV6都不行） (#488)





 
亲，能否加一下我的微信，麻烦你协助我测试一下
 maidou__xhu

**Comment by Jensenhang** [comment]
系统Windows10 版本号20H2

**Comment by ritaswc** [comment]
@Jensenhang  我已经开启了OCSP协议了，节约首次打开时间。剩余的问题由作者跟进吧
