### ISSUE TITLE
update interval 

### ISSUE THREAD

**Issue by beatstick** [zhongyang219/TrafficMonitor#489]
The update interval of the taskbar notification seems to be set to one second. Is it possible to let us set a variable so it updates only every couple of seconds? It would be less distracting to me if it updates less often and could potentially safe on cpu overhead as well. 

Cheers, 
beatstick

**Comment by zhongyang219** [comment]
The monitoring time interval can be changed in "Options"-"General Settings"-"Advanced"-"Monitoring Intervals". It can be set up to 2 seconds.
![image](https://user-images.githubusercontent.com/30562462/108500967-88076880-72eb-11eb-925a-30f73849726b.png)
