### ISSUE TITLE
【需求】 是否可以新增对文件夹的监控功能

### ISSUE THREAD

**Issue by hardcoresecz** [zhongyang219/TrafficMonitor#494]
在某些场景下，需要监控哪些程序读写了某个文件夹，用于定位后门程序，希望能新增该功能

**Comment by zhongyang219** [comment]
几年前我的一个朋友开发了一个这样的软件，叫FileMonitor，也是一个开源软件，你可以[点击这里](https://gitee.com/XCCU/FileMonitor)查看此项目，他没有提供Release版本，你可以自己用Visual Studio编译一下。
如下图所示，你可以添加一个文件夹进行监控
![2021-03-27](https://user-images.githubusercontent.com/30562462/112716532-edb9c680-8f21-11eb-8ca5-afedd7be21c2.png)
双击会显示所有监控到的文件更改
![2021-03-27 (2)](https://user-images.githubusercontent.com/30562462/112716553-04601d80-8f22-11eb-8eac-317c90cd5047.png)
同时也会将它们保存到日志文件中。
