### ISSUE TITLE
位于任务栏时，在远程桌面上，字体显示有问题

### ISSUE THREAD

**Issue by baiyijun** [zhongyang219/TrafficMonitor#495]
当监控器位于任务栏时，通过远程桌面访问该电脑，任务栏中的监控器文字很大；不能根据当前远程桌面显示器进行自动调整。

**Comment by liudsl** [comment]
没错，我也出现了这样的问题

**Comment by carryhcc** [comment]
一样的，等解决方案

**Comment by haodiao** [comment]
这个问题没有适配分辨率DPI，
比如在笔记本高分屏下，外接一个显示器之后不会随着 DPI 而变化

**Comment by zhongyang219** [comment]
这个问题现在应该已经解决了，请等待下个版本更新，或者下载最新的预发行构建版本试试。

**Comment by ttimasdf** [comment]
使用下面的版本测试，已经可以适应桌面DPI更改。

https://github.com/zhongyang219/TrafficMonitor/actions/runs/960730697

**Comment by baiyijun** [comment]
最新版本已经解决了
