### ISSUE TITLE
CPU跳动过大

### ISSUE THREAD

**Issue by wantflyfly** [zhongyang219/TrafficMonitor#498]
本软件检测的CPU跳动过大，与任务管理器显示的CPU占用率有差别，
例如系统管理器在15%-20%跳动，同时本软件在7%-27%跳动，
修改CPU获取方式和间隔时间都无差别，
建议增加积分平均功能，例如本次显示结果为前n次平均值，谢谢。

**Comment by wshidaijingshen** [comment]
参考这个，基本上符合 资源管理器的cpu占用数值了。https://github.com/zhongyang219/TrafficMonitor/issues/445
