### ISSUE TITLE
在windows8.1下任务栏显示异常，手都调背景色无效

### ISSUE THREAD

**Issue by 5605006** [zhongyang219/TrafficMonitor#5]
http://7sbycd.com1.z0.glb.clouddn.com/20180212220044.png
http://7sbycd.com1.z0.glb.clouddn.com/20180212220152.png

**Comment by zhongyang219** [comment]
关于Windows8.1下任务栏背景色的问题，是系统限制，我暂时无法解决。当窗口嵌入任务栏后，窗口也会变成像任务栏一样半透明的。Win8.1下背景颜色并非无法调整，只是背景变得比较透明而已。把背景色设置为纯黑色时，它就是最透明的，但是在win8.1下它仍然无法和任务栏完全融合，而Win10下效果是很完美的。
关于弹出“注册表删除失败”的问题，确实是我的疏忽，请暂时忽略那个提示，下个版本会修正这个问题。
