### ISSUE TITLE
焦点不在任务栏上时，比如点击右键设置界面会被其他程序挡住

### ISSUE THREAD

**Issue by Windsrise** [zhongyang219/TrafficMonitor#50]
Win7，焦点不在任务栏上时，比如点击右键设置界面会被其他程序挡住，偶尔点击右下角显示桌面程序会崩溃

**Comment by zhongyang219** [comment]
你好，我不是很清楚你遇到的问题，能详细说明一下吗？什么叫“点击右键设置界面会被其他程序挡住”？

**Comment by Windsrise** [comment]
在任务栏显示模式时，点击右键菜单，再点选项或关于，出来的界面会被其他正在运行的程序挡住，不过这个问题在更新到最新版本后好像没有了
