### ISSUE TITLE
希望能增加ping功能、任务栏速度超过100mb显示异常

### ISSUE THREAD

**Issue by sankLibrary** [zhongyang219/TrafficMonitor#506]
十分感谢作者能做出这么优秀的小插件。
1、当上传下载超过100mb时，任务栏上的显示就只有后面几位了。百位就丢了。
2、要是能加入ping功能就更完美了，可以自定义内网ip和外网ip。

**Comment by soloopooo** [comment]
> 1、当上传下载超过100mb时，任务栏上的显示就只有后面几位了。百位就丢了。
@sankLibrary 解决方式：
![image](https://user-images.githubusercontent.com/36123081/115133919-50444500-a03e-11eb-9c2c-d43f80f72b3d.png)

**Comment by sankLibrary** [comment]
> > 1、当上传下载超过100mb时，任务栏上的显示就只有后面几位了。百位就丢了。
> 
> @sankLibrary 解决方式： 勾上数据右对齐
> 
> ![image](https://user-images.githubusercontent.com/36123081/115133919-50444500-a03e-11eb-9c2c-d43f80f72b3d.png)

好的谢谢提醒，实测5个字符就能正常显示100+mb的啦
