### ISSUE TITLE
CPU计算显示不准确

### ISSUE THREAD

**Issue by FLVE** [zhongyang219/TrafficMonitor#508]
发现一个小问题，CPU的计算不准确，内存的显示是准确的

![codedw_2020-12-04_11-46-08](https://user-images.githubusercontent.com/46079296/101120863-a6819000-3629-11eb-9da9-2975b5038949.png)

**Comment by RoderickXiang** [comment]
我也发现了

**Comment by sixcubo** [comment]
在设置的常规设置中，将**CPU使用率获取方式**改为使用**性能计数器**
![image](https://user-images.githubusercontent.com/43727795/101756974-911cd200-3b11-11eb-8b32-75bbcdb9cc1c.png)

**Comment by FLVE** [comment]
> 在设置的常规设置中，将**CPU使用率获取方式**改为使用**性能计数器**
> 
> In the general setting of the settings, change the CPU usage capture to use the performance counter
> 
> <img alt="Editor" width="400" src="https://user-images.githubusercontent.com/43727795/101756974-911cd200-3b11-11eb-8b32-75bbcdb9cc1c.png">

使用这个解决了CPU显示相差的问题，谢谢啦
