### ISSUE TITLE
重启电脑后流量统计全部清空了

### ISSUE THREAD

**Issue by Canscx** [zhongyang219/TrafficMonitor#509]
![XEOS-CANSCXS_2020-12-04_18-56-01](https://user-images.githubusercontent.com/36366115/101156206-35f76500-3663-11eb-9497-daae26b1ab52.png)
如图 
history_traffic.dat 和 history_traffic.dat.bak 都还有之前的流量数据
但是软件就是不显示之前的...
还有什么方法可以恢复吗

**Comment by zhongyang219** [comment]
你好，请检查一下“选项”——“常规设置”——“配置和数据文件”中配置文件目录的设置是否为你的history_traffic.dat所在目录。
