### ISSUE TITLE
能否增加内存优化功能

### ISSUE THREAD

**Issue by 1050035126** [zhongyang219/TrafficMonitor#510]
比如双击优化清理内存，就可以完全取代360了

**Comment by soloopooo** [comment]
你知道内存优化的原理吗，其实没有必要，那玩意就是给你心里安慰的

**Comment by S15932807676** [comment]
个人认为没有必要，与其动不动优化内存不如注意是哪个软件占用异常，或者直接加根内存条。

**Comment by zhongyang219** [comment]
这个功能暂时不考虑，因为如果你知道了它的原理之后就会发现，所谓的内存优化功能其实并不会让你的电脑变快。
