### ISSUE TITLE
Windows 10 20H2：任务栏窗口中的处理器和内存不显示状态条

### ISSUE THREAD

**Issue by PiscesDante** [zhongyang219/TrafficMonitor#515]
操作系统：Microsoft Windows 版本 20H2（ OS 内部版本 19042.685 ）；
选择颜色：浅色；
透明效果：关；
---
任务栏窗口中的处理器和内存标签中不显示占用比例状态条；请尽快修复这个问题；

**Comment by xxyangyoulin** [comment]
确实该问题存在。
