### ISSUE TITLE
使用过程中遇到的一个小问题

### ISSUE THREAD

**Issue by uzxin** [zhongyang219/TrafficMonitor#519]
将任务栏图标开启后，切换窗口过程中，该图标会被隐藏，需要手动点一下才会出来
![image](https://user-images.githubusercontent.com/49435090/102568669-e3b44a80-411e-11eb-847d-9b8e4eabd0ca.png)

**Comment by zhongyang219** [comment]
抱歉，我好像没明白你的问题，可以详细描述一下吗，如果可以的话最好附上屏幕录像
