### ISSUE TITLE
任务栏窗口乱码

### ISSUE THREAD

**Issue by Remonli** [zhongyang219/TrafficMonitor#52]
按这个帖子设置utf后, 任务栏窗口上下箭头变乱码. 

https://www.v2ex.com/t/451563

**Comment by zhongyang219** [comment]
谢谢反馈，我会调查一下这个问题，你先试试在“选项设置”——“任务栏窗口设置”的“显示文本”里面点击“恢复默认”看看能不能恢复正常。

**Comment by zhongyang219** [comment]
@Remonli 我试了一下，按这个链接里方法改成UTF8之后，整个系统的默认编码都是UTF8了，所有以ANSI格式保存的含有中文的纯文本文件再也无法正常显示。由于TrafficMonitor的配置文件是以ANSI的编码格式保存的（这也是目前Windows的默认编码格式），将Windows的默认编码改成UTF8之后，TrafficMonitor只能以UTF8的格式来读取配置，所以当然会变成乱码。这并不是个很严重的问题，你只要在“选项”——“任务栏设置”中的“显示文本”下面点击“恢复默认”按钮，再点击确定就可以了。

**Comment by zhongyang219** [comment]
另外，如果你遇到了无法设置微软雅黑字体的问题，请参照这里 #63 或 [帮助](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md)。

**Comment by Remonli** [comment]
是不是可以把配置文件默认改为UTF8 ? 毕竟连notepad也要默认utf8 了.

**Comment by zhongyang219** [comment]
@Remonli 目前读写配置文件使用的是Windows API中读写ini文件的函数，这个API微软似乎很早就不维护了，而且不支持UTF8。对于MFC程序，微软推荐的读写配置文件的方式是通过注册表，但是由于这是一个绿色软件，所以我不太想将配置保存到注册表，我正考虑以后也许可以将配置文件改成xml格式的。
