### ISSUE TITLE
功能建议：可自定义添加显示项

### ISSUE THREAD

**Issue by BruceLee569** [zhongyang219/TrafficMonitor#520]
最近在玩`Home Assistant`，希望将`电脑功率`和`室内温度`这两项添加到任务栏实时显示，但是`TrafficMonitor`好像不支持扩展功能，另外很多用户也非常想添加cpu显卡温度等更多的自定义信息，所以可以考虑看能不能提供一个接口扩展供外部调用，这样就直接解决了大家的各种需求啦 😊

**Comment by zhongyang219** [comment]
我目前也正有这个计划，目前计划在下下个版本中增加插件功能

**Comment by BruceLee569** [comment]
赞一个！😘
