### ISSUE TITLE
流量统计页，最好能把数据以小数点对齐

### ISSUE THREAD

**Issue by zhuoziqiang** [zhongyang219/TrafficMonitor#524]
并且统一单位，建议统一用GB做单位，如果流量很小，就显示 <0.1GB

![Snipaste_2020-12-20_18-51-51](https://user-images.githubusercontent.com/69742519/102711404-6e9a6e00-42f4-11eb-8bf7-02eb242047b1.png)

**Comment by notfound945** [comment]
数值右对齐，小数点后填充固定长度
😄

**Comment by zhongyang219** [comment]
已经改成了数值右对齐显示，暂时不考虑全部使用GB为单位。
