### ISSUE TITLE
CPU占用显示与实际不符

### ISSUE THREAD

**Issue by ppinkie** [zhongyang219/TrafficMonitor#53]
CPU显示比实际占用高得多，任务管理器查看占用1%，却显示15%左右或更高。

**Comment by ted423** [comment]
跟任务管理器对不上，我这边比任务管理器里看到的低，不知道会不会是单取了其中一个核心的

**Comment by ted423** [comment]
我发现rainmeter的cpu占有也时一样

**Comment by lilingang162786** [comment]
我这显示cpu也是比任务管理器低，好像其他这类显示cpu占用的软件都是比任务管理器稍低点
