### ISSUE TITLE
希望任务栏显示能设置上下间隔

### ISSUE THREAD

**Issue by aiegh002** [zhongyang219/TrafficMonitor#541]
因为本人的电脑任务栏是竖向设置的，显示的数据也是竖向排列的，数据之间的间距有点接近，比较难以分辨，希望可以增加间隔调整的选项，十分感谢！这是一款很棒的软件。

**Comment by zhongyang219** [comment]
最新版本(1.82)中已经增加任务栏项目间距的设置。
