### ISSUE TITLE
预发行构建版本无法使用

### ISSUE THREAD

**Issue by a982027400** [zhongyang219/TrafficMonitor#544]
新版的预发行构建版本运行报错，要怎么解决啊。
![image](https://user-images.githubusercontent.com/25918335/108589108-b3e02800-7397-11eb-9bd6-7f7692fb0e0a.png)

**Comment by zhongyang219** [comment]
抱歉，我目前还不知道怎么把自动编译的dll文件添加到预发行构造压缩包里，目前正在想办法。如果有哪位大佬知道望告知。

**Comment by zhongyang219** [comment]
问题已解决，请下载最新的预发行版本试试
