### ISSUE TITLE
预构建的版本无法使用

### ISSUE THREAD

**Issue by Spoience** [zhongyang219/TrafficMonitor#545]
因为最新的Releases一直有一些小不过没有解决，就尝试使用Github Actions构建的预发行版包，但很遗憾，我一直尝试到一周以前的构建包都无法使用，提示缺少一个dll。但是我看作者在多个WorkFlow里有添加`预构建添加DLL`，我看了下无论构建成功与否似乎都是不能使用的，里面都只有`TrafficMonitor.exe`一个文件~

**Comment by zhongyang219** [comment]
@1466587594 可以帮忙看看如何把自动编译的OpenHardwareMonitorApi.dll和OpenHardwareMonitorLib.dll两个文件添加到预发行版本包里吗？我尝试了几次都失败了。

**Comment by 1466587594** [comment]
> @1466587594 可以帮忙看看如何把自动编译的OpenHardwareMonitorApi.dll和OpenHardwareMonitorLib.dll两个文件添加到预发行版本包里吗？我尝试了几次都失败了。

多路径上传是upload-artifact@v2的特性，更新版本即可

https://github.com/zhongyang219/TrafficMonitor/pull/546#issue-577098376

**Comment by zhongyang219** [comment]
@1466587594 谢谢，问题已解决

**Comment by a982027400** [comment]
感谢，已经可以正常使用

**Comment by Spoience** [comment]
感谢项目贡献者们，预构建版现已正常使用，任务栏显示很输入，希望早日Release正式版让更多人体验到

**Comment by zhaoqingqing** [comment]
发布一个新点儿的构建版本到Release? 我试了下3.14的构建版本，无法使用，任务栏不显示，设置界面功能也有问题。
