### ISSUE TITLE
关于开机自启动

### ISSUE THREAD

**Issue by Fantasy0516** [zhongyang219/TrafficMonitor#547]
Win7系统，如果设置开机自启动，经常下次开机的时候找不到。
但是进程里面还有，这样就需要结束进程，然后再次启动才可以。
不管开不开悬浮贴边隐藏都有这个问题

**Comment by AlphaD999** [comment]
最新预览版遇到同样的问题，需要开机点一下才能启动，我觉得可能是因为开机需要管理员权限，没有获取到，所以没有法开机自启，操作系统是win10最新版

**Comment by 1466587594** [comment]
通过任务计划程序创建可以以管理员权限自启动，设置用户登陆后延迟几秒，图标就不会消失

**Comment by BlancRay** [comment]
由于新增的OpenHardwareMonitorLib需要管理员权限，通过注册表`Software\\Microsoft\\Windows\\CurrentVersion\\Run`自启的方法已经失效。项目可以参照 [OpenHardwareMonitor](https://github.com/openhardwaremonitor/openhardwaremonitor/blob/master/GUI/StartupManager.cs)或[PowerToys](https://github.com/microsoft/PowerToys/blob/master/src/runner/auto_start_helper.cpp)中通过计划任务实现开机自启

**Comment by zhongyang219** [comment]
感谢 @BlancRay 提供的建议，现在已经实现通过PowerToys中计划任务的方式开机自启动，应该不会再出现开机自启动失效的问题了。

**Comment by BlancRay** [comment]
🤗

zhongyang219 ***@***.***> 于2021年3月28日周日 下午12:12写道：
