### ISSUE TITLE
希望增加显卡温度，主板温度，风扇转速,硬盘读写速度等监控

### ISSUE THREAD

**Issue by helloworldiambeok** [zhongyang219/TrafficMonitor#549]
目前在用 PCMaster 的 radar，他的主板跟硬盘还有风扇转速监控不到，不够完美，希望TrafficMonitor完美超越PCMaster

**Comment by soloopooo** [comment]
该类issue已经被提超过10次，请善用issue search. 另，请检查预购建版本。

**Comment by zhongyang219** [comment]
温度监控功能已添加，风扇转速、硬盘监控功能目前不支持
