### ISSUE TITLE
怎么启动程序？

### ISSUE THREAD

**Issue by AustinLiu1988** [zhongyang219/TrafficMonitor#55]
怎么启动程序？

**Comment by zhongyang219** [comment]
下载7z压缩包后解压到任意位置，双击TrafficMonitor.exe就能启动了。你不会是像有些人一样，不知道从哪里下载程序，下载了源代码，解压后发现里面没有可执行文件吧？在主页面上点击“releases”进入发行版的页面就能下载了。为了避免这个问题，我已经在主页面的readme.md上的醒目位置添加了下载页面的链接。
