### ISSUE TITLE
CPU显示占用率在 10750H 下不准确

### ISSUE THREAD

**Issue by cwdao** [zhongyang219/TrafficMonitor#552]
希望下一版更新中默认显示改为使用性能计数器，而不是现在的使用时间

**Comment by laoqiuqiu** [comment]
设置->常规设置->使用高性能计数器

**Comment by zhongyang219** [comment]
由于使用性能计数时有部分用户反馈CPU使用率无法正常获取，因此默认设置使用了使用时间

**Comment by soloopooo** [comment]
在笔记本平台上的CPU占用率确实会不准确 我的9750H也是如此，更换了性能计数器就正常了。不知道算法是什么
