### ISSUE TITLE
在弹窗报告无法嵌入任务栏后，再次双击运行，报告“已经有一个程序正在运行”

### ISSUE THREAD

**Issue by AprildreamMI** [zhongyang219/TrafficMonitor#558]
在弹窗报告无法嵌入任务栏后，再次双击运行，报告“已经有一个程序正在运行”
+ 打开任务管理器并未找到相关进程
+ 任务栏也并不存在相关图标

**Comment by zhongyang219** [comment]
这个问题现在还存在吗？

**Comment by AprildreamMI** [comment]
> 这个问题现在还存在吗？

在1.79.1(x64)版本发生的，此问题发生后，重启电脑就又可以运行软件了，目前没有再发生过

**Comment by AprildreamMI** [comment]
> 这个问题现在还存在吗？

在1.79.1(x64)版本发生的，此问题发生后，重启电脑就又可以运行软件了，目前没有再发生过

**Comment by zhongyang219** [comment]
这个issue先关闭了，有问题可以再次反馈
