### ISSUE TITLE
浅色模式下文字锯齿

### ISSUE THREAD

**Issue by the1812** [zhongyang219/TrafficMonitor#559]
![image](https://user-images.githubusercontent.com/26504152/111572408-7b3f3d00-87e3-11eb-8843-56f10207e34b.png)
对比下右边的时间还是挺明显的, 深色模式就没问题
![image](https://user-images.githubusercontent.com/26504152/111573030-afffc400-87e4-11eb-9518-98dbaa6d5b83.png)

不太清楚原因, 试着换了几个字体也没用
![image](https://user-images.githubusercontent.com/26504152/111572764-37990300-87e4-11eb-9f15-535d9c5cfa33.png)

----

Windows 10 20H2
分辨率 2736x1824

![image](https://user-images.githubusercontent.com/26504152/111572570-cfe2b800-87e3-11eb-95b8-8039d4a64a8a.png)

**Comment by zhongyang219** [comment]
在浅色模式下确实会有这个问题，你可能尝试勾选“根据任务栏颜色自动设置背景”来解决这个问题。

**Comment by the1812** [comment]
好的 感谢解答
