### ISSUE TITLE
vs 2015 不能编译，能不能向下兼容一下

### ISSUE THREAD

**Issue by Mebigger** [zhongyang219/TrafficMonitor#56]
没有 v141工集

**Comment by zhongyang219** [comment]
点击菜单“项目”——“TrafficMonitor 属性”——“常规”，更改一下平台工具集即可。

**Comment by Mebigger** [comment]
并没有141的工具集，
![_20180608135146](https://user-images.githubusercontent.com/34804384/41141146-6cc1a09a-6b23-11e8-8221-2e95f0a1455b.png)

**Comment by zhongyang219** [comment]
@Mebigger 改成140工具集就可以了啊。
