### ISSUE TITLE
上一次更新去年，您是打算弃坑了吗？

### ISSUE THREAD

**Issue by qq775818258-01-jakeslee-is-fool** [zhongyang219/TrafficMonitor#560]
如题

**Comment by simear2004** [comment]
你应该去看下眼睛，Actions栏目里几天前还在更新，作者坑你1分钱了吗？

**Comment by qq775818258-01-jakeslee-is-fool** [comment]
> 你应该去看下眼睛，Actions栏目里几天前还在更新，作者坑你1分钱了吗？
你赢过去看以下脑子，TrafficMonitor 显示的 Latest release 是去年八月份，你在TrafficMonitor的话题下说NM的Actions。

**Comment by qq775818258-01-jakeslee-is-fool** [comment]
> 你应该去看下眼睛，Actions栏目里几天前还在更新，作者坑你1分钱了吗？

你应该去看以下脑子，TrafficMonitor 显示的 Latest release 是去年八月份，你在TrafficMonitor的话题下说NM的Actions。

**Comment by qq775818258-01-jakeslee-is-fool** [comment]
> 你应该去看下眼睛，Actions栏目里几天前还在更新，作者坑你1分钱了吗？

你应该去看一下脑子，TrafficMonitor 显示的 Latest release 是去年八月份，你在TrafficMonitor的话题下说NM的Actions。

**Comment by qq775818258-01-jakeslee-is-fool** [comment]
> 你应该去看下眼睛，Actions栏目里几天前还在更新，作者坑你1分钱了吗？

你应该去看一下脑子，TrafficMonitor的Release显示为去年更新，版本依旧为1.71.9，说NMB的Action。
你最好再去看看心理医生，我就问问更不更新版本，也没催更，你就满口喷屎，你是不是有特殊癖好，喜欢吃屎呀？

**Comment by CatGuai** [comment]
你俩真有意思，干嘛戾气这么大。
回到问题上：
作者最后一次提交是在10天前，说明没打算弃坑。Release没更新只是预编译的二进制文件没更新，开源软件嘛，等不急的可以拉源码自编译。

**Comment by CatGuai** [comment]
你俩真有意思，干嘛戾气这么大。
回到问题上：
作者最后一次提交是在10天前，说明没打算弃坑。Release没更新只是更新内容还没达到作者的发布要求。而且二楼也回答你问题了，Actions中有实时构建的最新预发行构建版本，如果你追求最新版可以从Actions中下载。
你可以认为Release里的是“稳定发行版”，Actions里的是“预发行版/测试版”。
这些作者在首页都有写到。

**Comment by KevinYu0504** [comment]
我個人也覺得與其頻繁的更新，
不如每次更新的時候都是經過測試確定沒啥 Bugs 的穩定版 ~

總之這軟體(軟件)是作者佛心做善事所發布的，沒收費、沒廣告，
更沒要求你買大禮包，每次的更新、Bug 修復都該感謝作者辛苦付出，
所以不用火氣這麼大，多給鼓勵甚至打賞，對作者才是真正有幫助的。

**Comment by StewartXiang** [comment]
> 
> 
> 你俩真有意思，干嘛戾气这么大。
> 回到问题上：
> 作者最后一次提交是在10天前，说明没打算弃坑。Release没更新只是更新内容还没达到作者的发布要求。而且二楼也回答你问题了，Actions中有实时构建的最新预发行构建版本，如果你追求最新版可以从Actions中下载。
> 你可以认为Release里的是“稳定发行版”，Actions里的是“预发行版/测试版”。
> 这些作者在首页都有写到。

请问，action里面如何下载呢？我找不到选项

**Comment by CatGuai** [comment]
> 请问，action里面如何下载呢？我找不到选项

如图：

![1](https://user-images.githubusercontent.com/80637600/114337396-9fdcc980-9b83-11eb-8266-a0200aaff41f.gif)

**Comment by StewartXiang** [comment]
> 
> 
> > 请问，action里面如何下载呢？我找不到选项
> 
> 如图：
> 
> ![1](https://user-images.githubusercontent.com/80637600/114337396-9fdcc980-9b83-11eb-8266-a0200aaff41f.gif)

谢谢！原来是我开了缩放，所以下面的artifacts没有看到（搜了半天也没有这个问题，谢谢您！
