### ISSUE TITLE
提供非管理员权限的运行方式

### ISSUE THREAD

**Issue by tudnew** [zhongyang219/TrafficMonitor#565]
我注意到预览版本需要管理员权限运行，对于少数不提供管理权限的电脑就无法运行了。
可能温度这些相关需要提权，但可以接受看不到温度的。

**Comment by zhongyang219** [comment]
正式发布的时候会提供不含温度监控的版本。当然你也可以自己编译一个不含温度监控的版本，在Visual Studio的“解决方案配置”中选择“release (without temperature)”即可。

**Comment by soloopooo** [comment]
这个问题，可以参考一下everything的自启方式。据我目测，everything的自启是将自己注册为一个或者多个服务进行启动。
