### ISSUE TITLE
超过10M时（数字5位数），数字显示不全。

### ISSUE THREAD

**Issue by iwfq** [zhongyang219/TrafficMonitor#57]
作者你好，非常喜欢你的这个作品，非常美观又实用。在使用中，发现一个问题：如果下载速度超过每秒10000KB/s时，数字显示不全。即使选择了‘精简模式’，仍然会显示不全。虽然在单位那里，可以选择‘自动’，自动换算成MB/s，但是仍然希望可以以KB/s来显示，毕竟有时候上行20KB，下行20MB，不好识别，如果看数字长短就能直观知道使用情况。建议可以增加数字位数的选项，比如6位数可能会刚好，毕竟现在百兆光线已经很普遍，下载速度普遍会有5位数的KB，再加1位小数点，刚好6位数。
再次感谢作者开发这么好的作品。

**Comment by zhongyang219** [comment]
感谢你的反馈，确实存在这样的问题，我会在下一个版本中修正它，并增加数据位数的选项。

**Comment by zhongyang219** [comment]
这个问题现在已经在1.73版本中修正了。

**Comment by iwfq** [comment]
感谢作者的辛勤付出。已更新1.73，一切正常。
