### ISSUE TITLE
每日上传和下载流量分别超过4TB时会重新计数

### ISSUE THREAD

**Issue by gzycode39** [zhongyang219/TrafficMonitor#571]
例如某日上传量为4.125TB，统计只能统计为123GB

**Comment by zhongyang219** [comment]
感谢反馈，现在正好在解决流量统计和网速数值溢出的问题，这个问题应该很快就能解决了

**Comment by zhongyang219** [comment]
你好，这个问题现在应该已经解决了，为了保险起见，请帮忙在Actions中下载最新的预构建版本，看看这个问题是否已解决。

**Comment by gzycode39** [comment]
已更新，会持续观察一段时间再来反馈，谢谢开发者的辛勤劳动

**Comment by gzycode39** [comment]
经过实际测试，问题依旧存在。。

**Comment by zhongyang219** [comment]
请确保你使用的最新的预构建版本再试试看。
我这边测试下来是正常的：
![](https://user-images.githubusercontent.com/30562462/116802721-b0131380-ab47-11eb-9281-c2cc024e957d.png)
当然，由于我无法让我的电脑产生如此大的流量，我是通过在代码中强行修改当前网速来测试的。

**Comment by BluePointLilac** [comment]
太恐怖了，一天居然能用这么多
