### ISSUE TITLE
wsl 中的下载速度会被错误地认为是上传网速

### ISSUE THREAD

**Issue by cathaysia** [zhongyang219/TrafficMonitor#573]
![图片](https://user-images.githubusercontent.com/42114817/114848112-f874c680-9e10-11eb-86fc-165c25bd4b36.png)

如图，wsl 中下载的速度被错误地识别为上传网速而不是下载速度

**Comment by cathaysia** [comment]
呃，这个问题待定中。它现在不知道为什么又好了

**Comment by soloopooo** [comment]
因为选择了所有网卡，导致HyperV-wslAdapter的流量被统计为上传流量了，手动选择网卡应该可以解决
