### ISSUE TITLE
“项目改成vs2019”构建的版本状态栏文字颜色有问题

### ISSUE THREAD

**Issue by mxy493** [zhongyang219/TrafficMonitor#574]
[最新构建的版本](https://github.com/zhongyang219/TrafficMonitor/actions/runs/737913783)，状态栏文字颜色仅固定部分有效，动态变化部分始终是黑色
<img width="134" alt="Snipaste_2021-04-15_17-52-43" src="https://user-images.githubusercontent.com/46776216/114850899-d6307800-9e13-11eb-8c71-69913992c102.png">

**Comment by zhongyang219** [comment]
选项设置——任务栏窗口设置，点击文本颜色可以设置文字的颜色。
![image](https://user-images.githubusercontent.com/30562462/115032715-339ff400-9efc-11eb-8025-c5a0206d9e8c.png)

**Comment by mxy493** [comment]
感谢回答，这样设置确实有效，但在取消勾选“指定每个项目的颜色”的情况下，设置的颜色仅对固定部分有效，不知道是bug还是设计如此~

**Comment by zhongyang219** [comment]
你好，刚刚尝试了一下，这确实是一个bug。感谢你的反馈，我会尽快修复这个问题。

**Comment by zhongyang219** [comment]
问题已解决
