### ISSUE TITLE
希望增加新功能

### ISSUE THREAD

**Issue by alelinshy** [zhongyang219/TrafficMonitor#575]
希望增加CPU和GPU及其他硬件温度检测的功能

**Comment by LittleNewton** [comment]
![image](https://user-images.githubusercontent.com/17793356/115132625-7238ca00-a034-11eb-966f-e9892efbbb28.png)

这些功能都已经实现了。至于你说的“其他硬件”就不好界定具体是什么了。

**Comment by zhongyang219** [comment]
温度监控功能将在下一个版本中到来，敬请期待
