### ISSUE TITLE
最新构建的版本启动会崩溃

### ISSUE THREAD

**Issue by zhaoqingqing** [zhongyang219/TrafficMonitor#576]
因为之前用着release中的版本开机启动项，每次都无法保存，所以从预构建下载。
但是从预构建下载的最新三个版本都会启动崩溃，其中最新的这个版本下载后，https://github.com/zhongyang219/TrafficMonitor/actions/runs/760719333，用RAR打开提示文件损坏，重复+梯子下载了三次都是文件损坏。
另外旧点儿的两个版本启动后打开设置就崩溃了。

**Comment by zhongyang219** [comment]
打开设置崩溃的问题已经解决了，如果还有其他崩溃的问题，请把dmp文件和错误信息发上来，以便我调查这个问题。

**Comment by zhaoqingqing** [comment]
挂上梯子，使用浏览器自带的下载最新的构建版本，崩溃问题已修复。 PS.上午是通过第三方下载工具IDM下载的，一直会提示文件损坏。
