### ISSUE TITLE
选择了网络连接，每次睡眠后恢复，或者开机启动后都会切换到列表第一个

### ISSUE THREAD

**Issue by mxy493** [zhongyang219/TrafficMonitor#577]
手动选择了网络连接，电脑睡眠后恢复，或者开机后启动软件，网络连接都会切换到列表第一个，如图：

<img width="251" alt="Snipaste_2021-04-20_11-55-49" src="https://user-images.githubusercontent.com/46776216/115335477-e22f8780-a1cf-11eb-8d9d-27c5eda82b8b.png">

用过最后一个稳定版存在这个问题，然后换到最新的构建版也仍然存在这个问题！

**Comment by zhongyang219** [comment]
请打开配置文件config.ini，然后把`[other]`下面的`debug_log`项改成true，然后重新启动TrafficMonitor，在出现你的问题之后，把connections.log文件发上来，并告诉我出现问题的具体时间，我来调查这个问题

**Comment by mxy493** [comment]
> 请打开配置文件config.ini，然后把`[other]`下面的`debug_log`项改成true，然后重新启动TrafficMonitor，在出现你的问题之后，把connections.log文件发上来，并告诉我出现问题的具体时间，我来调查这个问题

好的

**Comment by mxy493** [comment]
@zhongyang219 昨晚开始睡眠，今早大概10:35开电脑，日志：[connections.log](https://github.com/zhongyang219/TrafficMonitor/files/6347694/connections.log)

**Comment by zhongyang219** [comment]
通过分析你的配置文件，我发现从 2021/04/21 02:04:33.384 开始，“Intel(R) Wireless-AC 9560 160MHz”就不在连接列表里了，可能是由于电脑休眠导致网卡关闭了导致的，由于程序找不到Intel(R) Wireless-AC 9560 160MHz这个网卡，因此它就只好选择了第一个

**Comment by mxy493** [comment]
> 通过分析你的配置文件，我发现从 2021/04/21 02:04:33.384 开始，“Intel(R) Wireless-AC 9560 160MHz”就不在连接列表里了，可能是由于电脑休眠导致网卡关闭了导致的，由于程序找不到Intel(R) Wireless-AC 9560 160MHz这个网卡，因此它就只好选择了第一个

明白你的意思了，我刚也看了日志，10:35:55.435 的时候确实没有这个网卡，但过了一会儿 10:36:06.212 就有了。

10:35:55.435

![image](https://user-images.githubusercontent.com/46776216/115561710-6bd27880-a2e8-11eb-946d-2608e03ceddc.png)

10:36:06.212

![image](https://user-images.githubusercontent.com/46776216/115561575-4a718c80-a2e8-11eb-8009-cf237fabf4fd.png)


我没理解错的话程序的逻辑是：一旦没找到配置文件中的网卡，就默认选择列表第一个（没测试过，不确定是不是配置文件也自动修改了）。

如果是这样的话，建议在没找到配置文件中的网卡的情况下，添加循环，比如隔 2s 再查找一次，一般网卡正常的话很快就会恢复，以我这份日志为例，仅仅间隔了 11s 就能找到配置文件中的网卡了，这时候恢复配置文件中的网卡；如果真遇到极端情况循环了 2 分钟还找不到配置文件中的网卡，再修改网络连接为别的选项，同时也提醒一下用户~

**Comment by 469312306** [comment]
太好了，我也每次解锁后都要重新手动选一下无线网卡，这下终于不用再选了。赞作者！
