### ISSUE TITLE
希望能增加GPU使用率

### ISSUE THREAD

**Issue by MorKe9986** [zhongyang219/TrafficMonitor#578]
希望作者能加上GPU的使用率监控，对于玩游戏或者视频制作者来说，看着GPU被吃满是件很幸福的事

**Comment by FanlaFanla** [comment]
这个<a href="https://github.com/zhongyang219/TrafficMonitor/actions">预发行版</a>已经满足你的需求

**Comment by zhongyang219** [comment]
此功能现在已经添加
