### ISSUE TITLE
希望每一个皮肤都能够自定义显示各个选项

### ISSUE THREAD

**Issue by qwer130140190** [zhongyang219/TrafficMonitor#579]
希望每一个皮肤都能够自定义显示各个选项，现在所有皮肤好像都不能显示温度

**Comment by zhongyang219** [comment]
这个做不到，跟现有的设计无法兼容，相当于重做皮肤系统。现有的设计是每个皮肤的布局是固定的，想要切换布局只要更换皮肤即可，而且皮肤也能自定义。
