### ISSUE TITLE
最近的几个构建版，在睡眠后恢复或开机自启后，CPU利用率快速闪烁

### ISSUE THREAD

**Issue by mxy493** [zhongyang219/TrafficMonitor#580]
大致情况如图：

![tmp](https://user-images.githubusercontent.com/46776216/115490227-4023a400-a290-11eb-9881-c1b1a2e513b9.gif)

**Comment by zhongyang219** [comment]
你是否在“选项”——“常规设置”——“高级”里面调整了“监控时间间隔”？

**Comment by mxy493** [comment]
> 你是否在“选项”——“常规设置”——“高级”里面调整了“监控时间间隔”？

没有，默认的时间间隔1000ms

**Comment by zhongyang219** [comment]
抱歉，我也想不到还有什么原因会造成这个问题

**Comment by mxy493** [comment]
先留个坑吧，说不定哪天就找到原因了~

![tmp](https://user-images.githubusercontent.com/46776216/115653768-5f8b0180-a362-11eb-9329-28397d7fee8a.gif)

**Comment by lingyired** [comment]
> 抱歉，我也想不到还有什么原因会造成这个问题

我发现这个问题是在 windows 休眠后重新启动出现的，并且似乎这种快速闪烁的持续时间取决于休眠阶段的时间。

这时候如果手动再去修改监控时间间隔的话，频率能恢复正常。

希望对你抓虫有帮助

**Comment by simear2004** [comment]
我也有这个问题，只要是睡眠后就会快递闪烁

**Comment by zhongyang219** [comment]
请尝试一下最新的预构建版，看看这个问题是否已解决

**Comment by mxy493** [comment]
> 请尝试一下最新的预构建版，看看这个问题是否已解决

应该是没问题了

**Comment by simear2004** [comment]
> 请尝试一下最新的预构建版，看看这个问题是否已解决

最新版本已解决睡眠恢复后快速闪烁问题
