### ISSUE TITLE
注册表项写入失败，可能该键值没有权限访问！

### ISSUE THREAD

**Issue by YUDIDIFEI** [zhongyang219/TrafficMonitor#582]
今天刚刚下载这个软件，想设置开启运行，可是勾选后点击确认就会出现报错，管理员运行也没有用。

版本号：20h2
![屏幕截图 2021-04-21 231826](https://user-images.githubusercontent.com/68810699/115578966-4f3e3c80-a2f8-11eb-8b87-7a53e477a0fa.png)

**Comment by zhongyang219** [comment]
暂时不清楚为什么会出现这个现象，如果你想实现开机自启动，你还可以在`C:\Users\<你的用户名>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`下面放一个TrafficMonotor的快捷方式。或者等下个版本更新，下个版本使用了进度计划的方式实现开机自启动。

**Comment by zhongyang219** [comment]
另外，你也可以尝试在注册表`\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`路径下手动创建一个启动项。
