### ISSUE TITLE
【功能建议】增加CPU  GPU温度监控

### ISSUE THREAD

**Issue by L-GROSS** [zhongyang219/TrafficMonitor#585]
如题

**Comment by soloopooo** [comment]
该issue已经被提过超过10次了，请善用issue search功能

**Comment by ha-na-bi** [comment]
另外此功能在[预发布版本](https://github.com/zhongyang219/TrafficMonitor/actions?query=workflow:%22Release+CI%22)中已经实现了。
![图片](https://user-images.githubusercontent.com/11753411/115985946-aede6580-a5e0-11eb-8bf5-698e5041e539.png)

**Comment by L-GROSS** [comment]
看到了，感谢

**Comment by ZnBDPang** [comment]
温度监控貌似不能监控amd吗

**Comment by zhongyang219** [comment]
温度监控功能已添加
