### ISSUE TITLE
任务栏位置bug

### ISSUE THREAD

**Issue by pseadev** [zhongyang219/TrafficMonitor#586]
任务栏在下时，显示正常。

![pic_10](https://user-images.githubusercontent.com/25172023/116055245-14008c80-a6af-11eb-805e-8108e0d3f5a6.png)

任务栏在上时，字体显示不正常。

![pic_9](https://user-images.githubusercontent.com/25172023/116055302-25e22f80-a6af-11eb-8553-6f56fe371e4b.png)

**Comment by zhongyang219** [comment]
你好，我这边无法复现你的问题，如果你出现了这样的问题，可以打开选项——“任务栏设置”，取消勾选“自动适应Windows10深色/浅色主题”，然后将“背景颜色”设置成和任务栏相近的颜色
