### ISSUE TITLE
建议任务栏模式下，是否显示流量可设置

### ISSUE THREAD

**Issue by mikudehuane** [zhongyang219/TrafficMonitor#595]
因为任务栏空间有限，希望能只显示内存和CPU占用，而不显示流量，希望能增加该设置到选项，非常感谢！

**Comment by zhongyang219** [comment]
任务栏窗口右键菜单“显示设置”可以选择要显示的信息：
![image](https://user-images.githubusercontent.com/30562462/118363630-e0d35e00-b5c7-11eb-88cc-a1c4e65d0191.png)

**Comment by mikudehuane** [comment]
> 任务栏窗口右键菜单“显示设置”可以选择要显示的信息：
> ![image](https://user-images.githubusercontent.com/30562462/118363630-e0d35e00-b5c7-11eb-88cc-a1c4e65d0191.png)

找到了，之前没发现这里，非常感谢！
