### ISSUE TITLE
v1.80版无法读取多项温度及核显GPU利用率

### ISSUE THREAD

**Issue by microka** [zhongyang219/TrafficMonitor#597]
系统：Windows 10 20H2 (19042.985) 专业工作站版
CPU：Intel i5-11500
GPU：Intel UHD 750
使用版本：TrafficMonitor_V1.80_x64.zip

TrafficMonitor 无法读取主板、CPU、GPU温度，显卡（GPU）利用率也无法读取
![2021-05-15_203506](https://user-images.githubusercontent.com/490351/118361512-694d0100-b5be-11eb-81d3-f9a33208873d.png)

而使用 AIDA64 (6.33.5700) 可顺利读取主板、CPU及GPU（CPU GT Cores）温度
![2021-05-15_203524](https://user-images.githubusercontent.com/490351/118361593-bd57e580-b5be-11eb-9b2b-4969662bad60.png)

而显卡（GPU）利用率也可在任务管理器性能页面看到
![2021-05-15_204054](https://user-images.githubusercontent.com/490351/118361605-c5b02080-b5be-11eb-88b0-46d04ef48135.png)

不知为何在 TrafficMonitor 中无法读取上述信息。另外，还想知道对于多块硬盘的情况下，TrafficMonitor 显示的是哪块 HDD 温度？

**Comment by zhongyang219** [comment]
温度功能使用了第三方库[OpenHardwareMonitor](https://github.com/openhardwaremonitor/openhardwaremonitor)，如果你遇到无法获取温度的问题，请先尝试一下使用OpenHardwareMonitor能否正常获取，如果OpenHardwareMonitor也不能获取，请向OpenHardwareMonitor的作者反馈。

**Comment by zhongyang219** [comment]
刚刚看了一下OpenHardwareMonitor的issue，好像有人已经解决了11代处理器无法获取温度的问题：https://github.com/openhardwaremonitor/openhardwaremonitor/pull/1431 ，不过作者并没有合并该pull request。

**Comment by microka** [comment]
> 刚刚看了一下OpenHardwareMonitor的issue，好像有人已经解决了11代处理器无法获取温度的问题：[openhardwaremonitor/openhardwaremonitor#1431](https://github.com/openhardwaremonitor/openhardwaremonitor/pull/1431) ，不过作者并没有合并该pull request。

嗯，我也看到了，那再等等，thx. :)

**Comment by itfish92** [comment]
i5-10400 核显温度和占用也显示不了，别的都显示正常，

**Comment by zhongyang219** [comment]
> i5-10400 核显温度和占用也显示不了，别的都显示正常，

核显温度和使用率好像是不支持的。

**Comment by itfish92** [comment]
> > i5-10400 核显温度和占用也显示不了，别的都显示正常，
> 
> 核显温度和使用率好像是不支持的。

好嘞，那我就安心用吧，谢谢大佬的好软

**Comment by zhongyang219** [comment]
目前多块硬盘时显示的第一块硬盘的温度，就是OpenHardwareMonitor获取到的第一块硬盘，通常是电脑的主硬盘。

**Comment by MAX-XiaoKui** [comment]
有多块显卡时它也是只会显示一个

**Comment by zhongyang219** [comment]
@microka 我已经把那位老哥关于解决11代CPU无法获取温度的提交合并到我的仓库里了：https://github.com/zhongyang219/openhardwaremonitor/commit/833150960c946d1a912f8a0f9b85a54e99e7e035 。
我重新编译了一个dll：[OpenHardwareMonitorLib.zip](https://github.com/zhongyang219/TrafficMonitor/files/6488582/OpenHardwareMonitorLib.zip)
请用这个dll替换一下，并测试一下CPU温度是否能正常获取。

**Comment by Cannikin76** [comment]
![无标题](https://user-images.githubusercontent.com/1356594/118383748-5b859300-b633-11eb-8cd4-77727db2361d.png)
WIN7下，替换了OpenHardwareMonitorLib，还是无法正常显示显卡占利用率及显卡、主板的温度。intel核显+主硬盘M2固态+机械仓库盘

**Comment by zhongyang219** [comment]
@Cannikin76  替换的那个dll是用于解决Intel 11代CPU无法获取温度的问题的

**Comment by Cannikin76** [comment]
> @Cannikin76 替换的那个dll是用于解决Intel 11代CPU无法获取温度的问题的

好吧...

**Comment by zhongyang219** [comment]
@microka 请帮忙测试一下替换此dll后是否能正常获取Intel 11代CPU的温度信息：
[OpenHardwareMonitorLib.zip](https://github.com/zhongyang219/TrafficMonitor/files/6488582/OpenHardwareMonitorLib.zip)

**Comment by microka** [comment]
> @microka 请帮忙测试一下替换此dll后是否能正常获取Intel 11代CPU的温度信息：
> [OpenHardwareMonitorLib.zip](https://github.com/zhongyang219/TrafficMonitor/files/6488582/OpenHardwareMonitorLib.zip)

替换dll后 i5-11500 CPU温度能正常显示了，其它情况依旧。
