### ISSUE TITLE
新1.80版(x64)无法获取GPU温度

### ISSUE THREAD

**Issue by shjohnnyyu** [zhongyang219/TrafficMonitor#602]
提示升级了1.80(x64)无法获取GPU温度，AMD RX480显卡，而原1.79.1版却可以。

**Comment by zhongyang219** [comment]
你好，请告知可以正常获取你的GPU温度的确切版本（哪天编译的），我来为你调查这个问题。

**Comment by shjohnnyyu** [comment]
> 1.79.1

**Comment by shjohnnyyu** [comment]
> 你好，请告知可以正常获取你的GPU温度的初始化版本（哪天编译的），我来为你调查这个问题。

<img width="257" alt="捕获" src="https://user-images.githubusercontent.com/5878418/118372425-16864000-b5e4-11eb-8908-0e963b22cb85.PNG">

**Comment by dunkeng** [comment]
有同样问题，版本号1.80
编译日期2021/5/15
WIN10的任务管理器显示正常，版本20H2，19042.985
显卡AMD RX5700，显卡驱动Adrenalin 21.4.1 Recommended (WHQL)
![微信截图_20210516072231](https://user-images.githubusercontent.com/22165870/118380837-9f6a9f00-b617-11eb-8dd7-84719c570905.png)
![微信截图_20210516072135](https://user-images.githubusercontent.com/22165870/118380838-a09bcc00-b617-11eb-8e41-25ac3a14a837.png)
![微信截图_20210516072146](https://user-images.githubusercontent.com/22165870/118380839-a1346280-b617-11eb-98d6-a5f09bc6e75d.png)
![微信截图_20210516072205](https://user-images.githubusercontent.com/22165870/118380840-a1ccf900-b617-11eb-9369-7c4092c34b7f.png)

**Comment by dunkeng** [comment]
OpenHardwareMonitor 0.9.6版本能正常显示GPU温度
![微信截图_20210516073229](https://user-images.githubusercontent.com/22165870/118380996-fd4bb680-b618-11eb-8c8a-cd509fde66d7.png)

**Comment by zhongyang219** [comment]
> > 你好，请告知可以正常获取你的GPU温度的初始化版本（哪天编译的），我来为你调查这个问题。
> 
> <img alt="捕获" width="257" src="https://user-images.githubusercontent.com/5878418/118372425-16864000-b5e4-11eb-8908-0e963b22cb85.PNG">
这个截图里的最后编译时间还没有更新，这是你自己编译的还是从Github的Action里面下载的，你下载或编译的时间

**Comment by zhongyang219** [comment]
@shjohnnyyu 请下载最新预构建版本，看看这个问题是否已经解决

**Comment by shjohnnyyu** [comment]
> @shjohnnyyu请下载最新预构建版本，看看这个问题是否已经解决

最新预构建版本可以了，完美显示，感谢。
