### ISSUE TITLE
HDR模式下任务栏无法使用透明背景 transparent background for taskbar can't be used on HDR mode

### ISSUE THREAD

**Issue by takuron** [zhongyang219/TrafficMonitor#605]
在HDR模式下使用透明背景会直接使文字消失，希望能修复此问题。

Using transparent background in HDR mode will make the text disappear, hope to fix this problem.

**Comment by zhongyang219** [comment]
我的显示器不支持HDR，无法调查这个问题，你可以参照 https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md 里面的的第11条。
