### ISSUE TITLE
无法显示AMD RX570 显卡的温度

### ISSUE THREAD

**Issue by roko89** [zhongyang219/TrafficMonitor#606]
![image](https://user-images.githubusercontent.com/82091775/118382866-16aa2e00-b62c-11eb-9581-68fd3d9d387c.png)
TrafficMonitor版本：1.80 (x64)
显卡驱动程序版本：21.10.03.01-210430a-367126E-RadeonSoftware
![image](https://user-images.githubusercontent.com/82091775/118382923-5d982380-b62c-11eb-9b18-0a667a93d0c0.png)
Windows 10任务管理器可以显示温度
![image](https://user-images.githubusercontent.com/82091775/118382959-86201d80-b62c-11eb-8807-051fa7179f0d.png)
Windows 版本为
![image](https://user-images.githubusercontent.com/82091775/118382984-a8b23680-b62c-11eb-8d05-bcfd9a7ea17a.png)

**Comment by zhongyang219** [comment]
你好，请下载最新预构建版本，看看这个问题是否已经解决

**Comment by dunkeng** [comment]
@zhongyang219 请问预构建版本在哪下载啊？抱歉，我百度不到

**Comment by zhongyang219** [comment]
> @zhongyang219 请问预构建版本在哪下载啊？抱歉，我百度不到

https://github.com/zhongyang219/TrafficMonitor/actions/runs/846100996

**Comment by dunkeng** [comment]
@zhongyang219 问题解决
![微信截图_20210516103107](https://user-images.githubusercontent.com/22165870/118383601-ed8c9c00-b631-11eb-95c0-135e1827ca11.png)

**Comment by roko89** [comment]
> 你好，请下载最新预构建版本，看看这个问题是否已经解决

![image](https://user-images.githubusercontent.com/82091775/118384971-54fc1900-b63d-11eb-8d2a-b73592f9993b.png)
最新预构建版本成功显示AMD 显卡温度，感谢大佬！

**Comment by Z-LL** [comment]
> > 你好，请下载最新预构建版本，看看这个问题是否已经解决
> 
> ![image](https://user-images.githubusercontent.com/82091775/118384971-54fc1900-b63d-11eb-8d2a-b73592f9993b.png)
> 最新预构建版本成功显示AMD 显卡温度，感谢大佬！

小白问一下，这个可执行文件在哪？ <https://github.com/zhongyang219/TrafficMonitor/actions/runs/846100996> ，在哪找啊？
