### ISSUE TITLE
主板温度显示不正确

### ISSUE THREAD

**Issue by Zii911** [zhongyang219/TrafficMonitor#607]
![Snipaste_2021-05-16_10-31-38](https://user-images.githubusercontent.com/77745139/118383599-ea91ab80-b631-11eb-8801-07333ba256d3.png)
![Snipaste_2021-05-16_10-32-27](https://user-images.githubusercontent.com/77745139/118383608-085f1080-b632-11eb-9c27-30b02b1b9090.png)

**Comment by zhongyang219** [comment]
你好，请先下载OpenHarwareMonitor这个软件，看看里面显示的主板温度是否正常

**Comment by ace-lsp** [comment]
俺也一样
![image](https://user-images.githubusercontent.com/84299931/118426514-ec28a580-b6fd-11eb-8c47-6944ce126679.png)

**Comment by 1726400669** [comment]
@zhongyang219 
![BaiduShurufa_2021-5-18_22-59-9](https://user-images.githubusercontent.com/26129421/118674967-ccdc6600-b82c-11eb-9b07-4c74760de2b6.png) 一样主板温度显示不正常！

**Comment by zhongyang219** [comment]
请先更新到最新版本。TrafficMonitor的温度监控功能依赖第三方开源库[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)，温度显示不正常的问题我无法解决，请向LibreHardwareMonitor的作者反馈。
