### ISSUE TITLE
显卡的使用率是核显的还是独显的，显卡的占用率也不正确

### ISSUE THREAD

**Issue by Codesmadness** [zhongyang219/TrafficMonitor#608]

**Comment by zhongyang219** [comment]
独显

**Comment by zhongyang219** [comment]
TrafficMonitor的硬件监控功能使用了第三方开源库[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)，温度监控不准确的问题我无法解决，请向LibreHardwareMonitor的作者反馈。
