### ISSUE TITLE
希望增加显示CPU、显卡、主板温度的功能

### ISSUE THREAD

**Issue by w1324296014** [zhongyang219/TrafficMonitor#61]
希望增加温度显示功能，类似软媒魔方的“雷达”。我不想用他们的产品，故而希望能增加这个功能！

**Comment by zhongyang219** [comment]
到目前为止已经有非常多人想要我增加温度检测的功能，之前曾经想过做这个功能，但由于最终实现不了所以放弃了。GitHub上有个叫permo的开源软件有这个功能，但是它的CPU温度检测经常检测不到。所以暂时可能不会有温度检测的功能。
除了各种温度检测功能之外，还有网友希望我做磁盘读写速度、GPU使用率等功能，甚至还有人想要游戏帧率检测，说实话，暂且不说我目前的能力还无法做到这些，我也并不想把这个软件做成一个任务管理器啊。这个软件我取名叫TrafficMonitor只是想安安静静地做一个网速检测的软件啊！我没想做这么多别的功能，CPU和内存利用率还是顺带的。如果要把网友提出的功能都加上，估计这个软件就得改名叫“系统全能监控器”、“Windows全能工具箱”之类的了。

**Comment by Windsrise** [comment]
哈哈小而美即可

**Comment by w1324296014** [comment]
可以把那些作为可选项，供需要的人用啊

**Comment by w1324296014** [comment]
好的，如果以后可以实现的话，还是希望能考虑下作为一个可选项吧！
