### ISSUE TITLE
显卡温度都有了  FPS还会远么~~

### ISSUE THREAD

**Issue by zuosc** [zhongyang219/TrafficMonitor#611]
期待加入一个FPS功能。  

体验了目前已经有了FPS功能软件。做的多多少少都有各种问题。

比如英伟达自带的，经常就不显示了。

win+G 那个微软自带的，功能做的倒挺好。  不过显示了以后会覆盖。 导致那一块无法点击。  真无力吐槽。

游戏++  感觉太重了。  为了一个FPS ，结果整了一堆无用的东东

**Comment by soloopooo** [comment]
这个已经有了，详情参见MSI Afterburner.
这个软件没必要为了添加而添加功能

**Comment by zuosc** [comment]
MSI Afterburner 看了教程，但是没体验。  总的看起来就是好重。

**Comment by soloopooo** [comment]
我还是那个观点，没必要做的没必要做。
TrafficMonitor顾名思义只是TrafficMonitor， 而且有些应用全屏会隐藏任务栏，意义何在

**Comment by zhongyang219** [comment]
我下一步的工作重心计划会转移到网络监控上来，其他信息的监控功能应该不会做了，温度监控功能因为太多人提，因此顺带做了一下。

**Comment by xushet** [comment]
微星小飞机就够了
