### ISSUE TITLE
V1.80 版本导致 System 进程 (ntoskrnl.exe) 每秒占用一次独立显卡

### ISSUE THREAD

**Issue by Ivanlon30000** [zhongyang219/TrafficMonitor#613]
V1.80 版本 TrafficMonitor 运行时系统进程 System(定位到"C:\Windows\System32\ntoskrnl.exe") 会每秒占用一次独立显卡，即使没有开启监控 GPU 温度。
在同时有核显和独显的笔记本上会导致独立显卡频繁唤醒。

**Comment by zhongyang219** [comment]
这个问题我也没办法解决，如果你遇到这个问题，可以下载不含温度监控的版本：
https://download.fastgit.org/zhongyang219/TrafficMonitor/releases/download/V1.80/TrafficMonitor_V1.80_x64_without_temperature.zip

**Comment by Ivanlon30000** [comment]
> 这个问题我也没办法解决，如果你遇到这个问题，可以下载不含温度监控的版本：
> https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80/TrafficMonitor_V1.80_x64_without_temperature.zip

感谢及时解决和回复。
希望 TrafficMonitor 专注于网络流量监控，keep simple。
