### ISSUE TITLE
恢复任务栏标签与数值的独立对齐

### ISSUE THREAD

**Issue by login404** [zhongyang219/TrafficMonitor#614]
1.80使用不等宽字体
并关闭数值右对齐
且标签文本宽度不一致时
数值不能正确左对齐
![180](https://user-images.githubusercontent.com/69505914/118387024-4cf8a500-b64e-11eb-849d-d9764ef8354d.png)

1.79是正常的
![179](https://user-images.githubusercontent.com/69505914/118387033-584bd080-b64e-11eb-8b30-9e5d8e1c6b57.png)

**Comment by zhongyang219** [comment]
这个不考虑恢复到之前的设计，因为现在1.80版本中显示的信息可以完全自定义，上下两项可能是没有关系的两项，它们的标签文本宽度可能相差很大，这样做可以尽可能有效地利用任务栏宽度。
![image](https://user-images.githubusercontent.com/30562462/118387168-5cc4b900-b64f-11eb-9a10-868e460d5389.png)

**Comment by Joker5017** [comment]
> 这个不考虑恢复到之前的设计，因为现在1.80版本中显示的信息可以完全自定义，上下两项可能是没有关系的两项，它们的标签文本宽度可能相差很大，这样做可以尽可能有效地利用任务栏宽度。
> ![image](https://user-images.githubusercontent.com/30562462/118387168-5cc4b900-b64f-11eb-9a10-868e460d5389.png)

1.8版本网速/占用率/温度之间的间距是不同的，这点不知道能不能修改
![image](https://user-images.githubusercontent.com/27394674/118387224-c9d84e80-b64f-11eb-8979-81f856dc8968.png)

**Comment by soloopooo** [comment]
> > 这个不考虑恢复到之前的设计，因为现在1.80版本中显示的信息可以完全自定义，上下两项可能是没有关系的两项，它们的标签文本宽度可能相差很大，这样做可以尽可能有效地利用任务栏宽度。
> > ![image](https://user-images.githubusercontent.com/30562462/118387168-5cc4b900-b64f-11eb-9a10-868e460d5389.png)
> 
> 1.8版本网速/占用率/温度之间的间距是不同的，这点不知道能不能修改
> ![image](https://user-images.githubusercontent.com/27394674/118387224-c9d84e80-b64f-11eb-8979-81f856dc8968.png)

请使用数值右对齐

**Comment by zhongyang219** [comment]
> > 这个不考虑恢复到之前的设计，因为现在1.80版本中显示的信息可以完全自定义，上下两项可能是没有关系的两项，它们的标签文本宽度可能相差很大，这样做可以尽可能有效地利用任务栏宽度。
> > ![image](https://user-images.githubusercontent.com/30562462/118387168-5cc4b900-b64f-11eb-9a10-868e460d5389.png)
> 
> 1.8版本网速/占用率/温度之间的间距是不同的，这点不知道能不能修改
> ![image](https://user-images.githubusercontent.com/27394674/118387224-c9d84e80-b64f-11eb-8979-81f856dc8968.png)

打开“数值右对齐”选项就相同了

**Comment by Joker5017** [comment]
> > > 这个不考虑恢复到之前的设计，因为现在1.80版本中显示的信息可以完全自定义，上下两项可能是没有关系的两项，它们的标签文本宽度可能相差很大，这样做可以尽可能有效地利用任务栏宽度。
> > > ![image](https://user-images.githubusercontent.com/30562462/118387168-5cc4b900-b64f-11eb-9a10-868e460d5389.png)
> > 
> > 
> > 1.8版本网速/占用率/温度之间的间距是不同的，这点不知道能不能修改
> > ![image](https://user-images.githubusercontent.com/27394674/118387224-c9d84e80-b64f-11eb-8979-81f856dc8968.png)
> 
> 打开“数值右对齐”选项就相同了

谢谢提醒了，其实我试过，但是还是不理想，现在是缩小了网速的字符数，然后把后面的单位里加入空格，强行拉开距离了；
新版本上下反馈肯定很多，这里很感谢作者的无私劳动，借楼建议后续版本可以自定义数据的顺序就好了。
![image](https://user-images.githubusercontent.com/27394674/118387810-1ffac100-b653-11eb-8646-bf0b2b41011a.png)

**Comment by login404** [comment]
既然有右对齐了
再加个左对齐选项
让用户选择也可以吧

另外默认顺序可以改成3楼图中那样
内存往后移 CPU跟GPU的使用率和温度同一列
这样可以直接隐藏两者的温度标签文本
