### ISSUE TITLE
win10切换到浅色模式下报错

### ISSUE THREAD

**Issue by CurtisWong458** [zhongyang219/TrafficMonitor#615]
System Info:
Windows Version: 10.0 build 19042
DPI: 120
Version: 1.80 x64
Last compiled date: 2021/05/15 19:30:32

**Comment by CurtisWong458** [comment]
[20210516154302_TrafficMonitor.exe.dmp.zip](https://github.com/zhongyang219/TrafficMonitor/files/6488879/20210516154302_TrafficMonitor.exe.dmp.zip)

**Comment by zhongyang219** [comment]
这个问题现在应该已解决了，请下载最新的预构建版本试试：
https://github.com/zhongyang219/TrafficMonitor/actions/runs/846372602

**Comment by CurtisWong458** [comment]
> 这个问题现在应该已解决了，请下载最新的预构建版本试试：
> https://github.com/zhongyang219/TrafficMonitor/actions/runs/846372602

大佬下载哪一个啊？看不懂英文
