### ISSUE TITLE
v1.8无法开机启动

### ISSUE THREAD

**Issue by nasaboy** [zhongyang219/TrafficMonitor#619]
v1.8 x64不带温度监控无法开机启动
环境windows10 20H2 19042.985 
我之前用的v1.79我把开机启动先取消了，然后把目录下面的文件全部删除了，把v1.8复制进去的，发现设置完开机启动后，v1.8无法开机启动了，设置的时候点开机启动然后点确定无任何错误提示，但是再次进到设置里那个勾选的开机启动就没有勾选到了。

**Comment by singularity2000** [comment]
我也有同样的问题！！！但我没事先取消开机自启，而是下载完成后直接解压覆盖的

**Comment by CurtisWong458** [comment]
https://github.com/zhongyang219/TrafficMonitor/actions/runs/846372602

**Comment by zhongyang219** [comment]
1.8版本新增了温度监控的功能，如果你不需要温度监控，我也提供了不含温度监控的版本，可以解决你的所有问题
https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80/TrafficMonitor_V1.80_x64_without_temperature.zip

**Comment by nasaboy** [comment]
> 1.8版本新增了温度监控的功能，如果你不需要温度监控，我也提供了不含温度监控的版本，可以解决你的所有问题
> https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80/TrafficMonitor_V1.80_x64_without_temperature.zip

我用的就是这个版本，我说的bug也是这个版本有的啊。

**Comment by nasaboy** [comment]
换回v1.79.1了
