### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by liwenjie001** [zhongyang219/TrafficMonitor#62]
最新的系统 win10  1803

**Comment by zhongyang219** [comment]
也有其他网友反馈程序有时会出现停止工作的问题，目前正在调查中。

**Comment by zhongyang219** [comment]
目前有一些网友反馈程序出现了闪退问题，现在问题已经找出。打开“连接详情”后将窗口关闭，一段时间后程序会崩溃。
这个问题是“连接详情”对话框中获取外网IP地址时导致的。由于获取外网IP地址是在新开的线程中处理的，如果外网IP地址还没获取到就关闭了对话框，就会由于使用了已经释放的变量导致程序崩溃。
这个问题已经解决，请等下一个版本更新。暂时请尽量不要使用“连接详情”功能。
