### ISSUE TITLE
V1.8版本若干问题：无法自启动；会锁定移动设备；会导致死机

### ISSUE THREAD

**Issue by iccfish** [zhongyang219/TrafficMonitor#620]
HI，感谢更新1.8版。

看起来1.8版使用了底层的硬件驱动检测信息，导致需要管理员身份启动。在测试过程中发现了一些小问题：

1. 无法自启动；自启动选项勾选无效；这个应该是和管理员身份的需求有关系；
2. 会阻止弹出移动设备（我是在尝试使用Rufus写入树莓派的启动镜像到SD卡时发现的，会提示TrafficMonitor.exe锁定了设备）
3. 承接上一条（目前只是怀疑）会导致系统锁死。我在升级到V1.8后，写入SD卡的过程中（因测试需要反复插拔若干次SD卡），系统死机了若干次，具体为：系统死机一次；虽鼠标键盘有响应但整个系统挂起两次。

以上第三条目前只是怀疑，没有确认是否是硬件监控导致的。已经回退1.79版本，目前表现正常。
笔记本和台式机均出现此类问题（均为AMD的Zen3 CPU+Windows 10 Insider Preview 21382）。

**Comment by singularity2000** [comment]
同样的问题：无法开机自启！想知道如何把管理员图标去掉。（只去掉单个程序的管理员图标）
网上有去掉所有管理员图标的方法，但不想一刀切，因为之前差点手痒运行了恶意程序，幸好冒管理员提示之后点了取消。

**Comment by iccfish** [comment]
刚发现1.8有不带温度监控的版本，先换这个试试了 😄

**Comment by iccfish** [comment]
运行大概十个小时，进程的虚拟内存有点儿大……

<img width="524" alt="screenshoot_2021-05-17_20-01-37" src="https://user-images.githubusercontent.com/1091653/118485345-e60ce600-b74a-11eb-989b-d0919333767f.png">

**Comment by iccfish** [comment]
监控了一下，整体成缓慢上涨趋势，如下图：

<img width="573" alt="screenshoot_2021-05-17_20-21-04" src="https://user-images.githubusercontent.com/1091653/118487613-7cdaa200-b74d-11eb-83d6-b3bf589983f3.png">

粗粗估算了一下，大概1分钟1MB。

**Comment by zhongyang219** [comment]
温度监控功能使用了OpenHardwareMonitor，我做的事情只是调用了它的接口而已，如果你在TrafficMonitor中遇到了这些问题，那么这些问题可能在OpenHardwareMonitor中同样存在。如果你不需要温度监控功能，建议你使用不含温度监控的版本：
https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80.1/TrafficMonitor_V1.80.1_x64_without_temperature.zip

**Comment by soloopooo** [comment]
@iccfish 确认问题解决后，请关闭issue。
