### ISSUE TITLE
V1.8无法开机自启

### ISSUE THREAD

**Issue by singularity2000** [zhongyang219/TrafficMonitor#621]
1.8版似乎使用了底层的硬件驱动检测信息，导致需要管理员身份启动，带来十分严重的体验问题：

TrafficMonitor无法开机自启；自启动选项勾选无效（注册表完全没反应，安全软件也没检测到新增自启项）

想知道如何把管理员图标去掉。（只去掉单个程序的管理员图标）
网上有去掉所有管理员图标的方法，但原理是默认管理员模式运行所有应用，安全性堪忧，不想一刀切。（之前差点手痒运行了恶意程序，幸好冒管理员提示之后点了取消）

**建议还是把那些需要管理员权限的功能删了吧，或至少与主要功能隔离开**（实在不想放弃这部分劳动成果，可另出一个设备性能监控插件），免得每次开机都要手动运行TrafficMonitor

各种硬件温度信息其实很多电脑管家都有，包括我在内的大部分用户平时也不太关心。一个流量监控插件安排了这么多与主题关系不太密切的功能属实没必要。相较任务管理器和安全软件，亲测温度显示有时也不准确。
**当然，若艺高人胆大保留所有功能的同时解决了自启问题，以上当我没说。**

**Comment by singularity2000** [comment]
啊，刚刚重启试验了一下，发现自启动生效了。应该是更新日志中所说的计划任务终于开始正常工作的结果。前几次重启都自启失败。
![image](https://user-images.githubusercontent.com/61232355/118408163-cdeb8700-b6b6-11eb-85df-8571f79ceb4f.png)

**Comment by yafovo** [comment]
1.80我用的不含温度监控版本，一样无法勾选开机自启，重启电脑也没自启。

**Comment by nasaboy** [comment]
你可以下载不带温度监控的版本啊，那个不需要管理员权限，不过也有开机无法自动启动的bug。

**Comment by zhongyang219** [comment]
开机自启动的问题已经解决，请更新到最新版本。
建议你使用不含温度监控的版本：
https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80.1/TrafficMonitor_V1.80.1_x64_without_temperature.zip
