### ISSUE TITLE
更新时数据保留问题

### ISSUE THREAD

**Issue by Z-LL** [zhongyang219/TrafficMonitor#622]
希望可以有一个数据文件夹，更新时，历史数据得以保留，现在更新就是简单粗暴的把原来的TrafficMonitor文件夹删了，新的替换，历史数据没了。

另外，可以希望有个附加功能，就是监控各个应用关于各个网卡的流量，而不是总流量，有时候流量异常，都找不到是哪个应用；
win10网络设置里面，可以看到各应用的累计流量，这个太简陋了，按分钟、小时、天，细化更好。

**Comment by soloopooo** [comment]
> 希望可以有一个数据文件夹，更新时，历史数据得以保留，现在更新就是简单粗暴的把原来的TrafficMonitor文件夹删了，新的替换，历史数据没了。
> 
> 另外，可以希望有个附加功能，就是监控各个应用关于各个网卡的流量，而不是总流量，有时候流量异常，都找不到是哪个应用；
> win10网络设置里面，可以看到各应用的累计流量，这个太简陋了，按分钟、小时、天，细化更好。

不是很明白为什么要删文件夹，直接替换文件就可以了
![image](https://user-images.githubusercontent.com/36123081/118453810-3889da80-b72a-11eb-814b-48ffa2706c14.png)
另外
![image](https://user-images.githubusercontent.com/36123081/118453861-450e3300-b72a-11eb-8480-c9f81f86b512.png)

**Comment by ivkeji** [comment]
解压新程序，拖入程序文件夹，全部替换。

**Comment by Z-LL** [comment]
楼上两位，谢了！
