### ISSUE TITLE
amd 5800h笔记本无法读取硬盘温度和主板温度

### ISSUE THREAD

**Issue by kindgxs** [zhongyang219/TrafficMonitor#624]
可以正常读取cpu，显卡温度，但是硬盘主板温度显示--；而且待机cpu占用会显示0，任务管理器显示2-5%跳动

**Comment by zhongyang219** [comment]
温度监控的功能使用了开源库[OpenHardwareMonitor](https://github.com/openhardwaremonitor/openhardwaremonitor)，如果遇到温度无法显示的问题，请向OpenHardwareMonitor的作者反馈。
