### ISSUE TITLE
最新版本会一直使用笔记本独立显卡

### ISSUE THREAD

**Issue by webzhouyan** [zhongyang219/TrafficMonitor#626]
最新版本会一直使用笔记本独立显卡，导致显卡发热严重

**Comment by zhongyang219** [comment]
建议你使用不含温度监控的版本，可以解决你的所有问题
https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80/TrafficMonitor_V1.80_x64_without_temperature.zip

**Comment by webzhouyan** [comment]
笔记本使用不含温控版本，完美解决
