### ISSUE TITLE
RX显卡，使用率显示不正常，温度无显示

### ISSUE THREAD

**Issue by toisard** [zhongyang219/TrafficMonitor#628]

**Comment by zhongyang219** [comment]
请更新到最新版本，看看这个问题是否仍然存在。

**Comment by zhongyang219** [comment]
请参见[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
