### ISSUE TITLE
1803改UTF8编码后字体异常的问题

### ISSUE THREAD

**Issue by kbj** [zhongyang219/TrafficMonitor#63]
改系统默认编码为UTF8后，在软件的设置中的字体原先是“微软雅黑”，如今就变成“微软雅”，我尝试重新设置成微软雅黑，但是依旧无法改变，然后任务栏上的字体就变得很细锯齿有点严重，有点丑😂，请教下作者这应该如何解决？![](https://i.loli.net/2018/05/12/5af65a5cbb7b2.jpg)

**Comment by zhongyang219** [comment]
关于这个问题我也注意到了，不知道什么原因，在Win10 1803下编码改成UTF8时部分中文字符写入ini文件时会被截断，暂时的解决方法是直接在“字体”右边文本框内输入字体的英文名称，比如输入Microsoft YaHei，点击确定关闭对话框即可。

**Comment by kbj** [comment]
好的  谢谢作者解答~
