### ISSUE TITLE
建议使用LibreHardwareMonitor

### ISSUE THREAD

**Issue by eritpchy** [zhongyang219/TrafficMonitor#630]
自己改了个华硕B550的主板cpu温度监控, 瞄了一眼LibreHardwareMonitor感觉比OpenHardwareMonitor好多了, 至少支持很多新设备, 以及我的设备.

只是提个建议, 不喜勿喷.

LibreHardwareMonitor: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
修改: https://github.com/eritpchy/TrafficMonitor/commit/f55c0aa0669730f9c3f694b5518e444f7745a3bd
Demo: https://github.com/eritpchy/TrafficMonitor/releases

**Comment by zhongyang219** [comment]
感谢你的建议，LibreHardwareMonitor好像确实更好一些，OpenHardwareMonotor有一段时间没有更新了，你可以把你的更改以pull request的形式提交一下
