### ISSUE TITLE
1.80版本AMD3600cpu可以正常显示温度，rx580.也是可以显示。1.8.1修复显示后，不再显示。。。

### ISSUE THREAD

**Issue by jyiwbb** [zhongyang219/TrafficMonitor#632]

**Comment by Sansming** [comment]
我也是这样，更新后也无法显示了，仅显示CPU利用率+内存使用
配置为：
5950x+3090

**Comment by iccfish** [comment]
我的硬件同楼上，最新版的结果是：GPU温度正确，硬盘温度为仓库盘HDD的温度（我有四块硬盘……NVME*2 SATA*1 HDD*1）……CPU主板温度和AIDA显示的完全不一样，我也不知道哪个对 😢

**Comment by zhongyang219** [comment]
那你用1.80版本的OpenHardwareMonitorLib.dll替换一下试试

**Comment by Sansming** [comment]
> 那你用1.80版本的OpenHardwareMonitorLib.dll替换一下试试

替换了也无法显示

**Comment by willaytoun** [comment]
我也是这样

**Comment by whp98** [comment]
+1

**Comment by whp98** [comment]
![image](https://user-images.githubusercontent.com/32877126/118692485-b5a57480-b83c-11eb-81ee-6669b63d3820.png)

**Comment by whp98** [comment]
1.80是能显示的 gpu是 amd 4650g 核显
![image](https://user-images.githubusercontent.com/32877126/118692709-ea193080-b83c-11eb-9471-3c4448dbd56b.png)

**Comment by whp98** [comment]
550bf41 构建版本action编译产物     试过了还是不行      
![image](https://user-images.githubusercontent.com/32877126/118693810-ffdb2580-b83d-11eb-89d1-9636c96820d6.png)

**Comment by zhongyang219** [comment]
请更新到最新版本，看看这个问题是否仍然存在。

**Comment by jyiwbb** [comment]
> 请更新到最新版本，看看这个问题是否仍然存在。

已修复
