### ISSUE TITLE
笔记本T14s无法获取cpu以外的温度

### ISSUE THREAD

**Issue by kz-wind** [zhongyang219/TrafficMonitor#634]
cpu 4750U
gpu集成vega7
硬盘sn730
目前只有cpu温度显示正确，其余温度均为--℃

**Comment by kz-wind** [comment]
![QQ截图20210518092835](https://user-images.githubusercontent.com/33864547/118576616-71be5b00-b7bb-11eb-9490-24d7fd3862db.png)
主板可能不带测温点，目前温度主要是硬盘和显卡温度显示

**Comment by zhongyang219** [comment]
[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
