### ISSUE TITLE
建议开发debian版本的

### ISSUE THREAD

**Issue by 1457384613gh** [zhongyang219/TrafficMonitor#635]

**Comment by jimstar06** [comment]
这程序基于MFC的，基本没可能移植到别的OS。

**Comment by 1457384613gh** [comment]
> 这程序基于MFC的，基本没可能移植到别的OS。

Thanks for reply of earnest you

**Comment by zhongyang219** [comment]
程序无法直接移植，要开发Linux版本相当于全部重写，我没有足够的时间和精力来做这些，因此没有这方面的计划。

**Comment by 1457384613gh** [comment]
> 程序无法直接移植，要开发Linux版本相当于全部重写，我没有足够的时间和精力来做这些，因此没有这方面的计划。

Thanks for your reply and how earnest you are !
