### ISSUE TITLE
只显示独显usage

### ISSUE THREAD

**Issue by Lucas-TY** [zhongyang219/TrafficMonitor#636]
当使用核显时，usage一直为0

**Comment by zhongyang219** [comment]
请参见[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
另外，温度监控好像是不支持核显的。
