### ISSUE TITLE
可以考虑加个选项

### ISSUE THREAD

**Issue by BluePointLilac** [zhongyang219/TrafficMonitor#639]
看到一些Issues想要将任务栏窗口和时间放在一起，在我看来这几乎是不可能实现的
但是你可以换个思路，**隐藏系统原有时间按钮**，**并在自己的程序任务栏窗口中显示时间**

下面的注册表项新建相关键值，设为1时隐藏对应按钮，
设为0或删除键值时显示，需要重启explorer生效
> 相关注册表项（分别为所有用户和当前用户）
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
```
> 相关键值（类型均为REG_DWORD）：
- `HideClock`（时间）
- `HideSCAVolume`（音量）
- `HideSCANetwork`（网络）
- `HideSCAPower`（电源）

或者你可以使用以下命令打开设置界面让用户自行关闭按钮，无需重启explorer
```
explorer shell:::{05D7B0F4-2121-4EFF-BF6B-ED3F69B894D9}\SystemIcons
```

**Comment by BluePointLilac** [comment]
另外，你这一年不更新，一更新一堆issues，心疼加膜拜一下233
我可是贴吧、Github都关注了你的，总在打原神😏

**Comment by zhongyang219** [comment]
> 另外，你这一年不更新，一更新一堆issues，心疼加膜拜一下233
> 我可是贴吧、Github都关注了你的，总在打原神😏

是啊，做个这个东西搞得比上班还累，不想搞了，以后我打算只做我自己需要的功能，我觉得我用不上的一律不做了。

**Comment by BluePointLilac** [comment]
其实我也用不上，只是给个思路
