### ISSUE TITLE
1.80.1任务栏显示不正常

### ISSUE THREAD

**Issue by xingxing404** [zhongyang219/TrafficMonitor#642]
截图的时候可以看见，但是平时看不见，但是左右键功能正常。好像是在我开机热插拔了一次显示器过后出现的

**Comment by xingxing404** [comment]
截图时：![image](https://user-images.githubusercontent.com/56675968/118646998-7151ae80-b813-11eb-85d3-3d8bf52f7638.png)
拍照：![image](https://user-images.githubusercontent.com/56675968/118647217-af4ed280-b813-11eb-8c97-f229c89c514a.png)

**Comment by soloopooo** [comment]
HDR的原因？

**Comment by xingxing404** [comment]
> HDR的原因？

好像确实是HDR的问题。

**Comment by zhongyang219** [comment]
请参照[常见问题-Windows10中开启HDR后任务栏窗口无法显示](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#11-windows10%E4%B8%AD%E5%BC%80%E5%90%AFhdr%E5%90%8E%E4%BB%BB%E5%8A%A1%E6%A0%8F%E7%AA%97%E5%8F%A3%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA)
