### ISSUE TITLE
1.80.1 x64版本不能开机自动启动

### ISSUE THREAD

**Issue by HP-hhe** [zhongyang219/TrafficMonitor#644]
更新到 1.80.1 x64 版本不能开机自动启动

**Comment by omaidb** [comment]
我也发现这个问题,正准备提issue

**Comment by XinSSS** [comment]
我这边好像也遇到了这个问题

**Comment by wuyudi** [comment]
测试过，勾选后关掉，再打开，勾就不见了。

**Comment by xiaodaowanwan** [comment]
我也是同样的问题，1.80.0没有这个现象

**Comment by tonywbh** [comment]
开机自动启动的注册表项没有成功添加
1.80.2

**Comment by zhongyang219** [comment]
请参照[常见问题-设置了开机自动运行仍然无法开机自启](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#3-%E8%AE%BE%E7%BD%AE%E4%BA%86%E5%BC%80%E6%9C%BA%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C%E4%BB%8D%E7%84%B6%E6%97%A0%E6%B3%95%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
