### ISSUE TITLE
1.80.1版本，thinkpad t14，只能获取CPU温度，其余获取不到

### ISSUE THREAD

**Issue by Z-LL** [zhongyang219/TrafficMonitor#648]
thinkpad t14，没有独显，显卡温度获取不到；但是硬盘和主板的温度，也获取不到：
![图片](https://user-images.githubusercontent.com/27721325/118772492-62700800-b8b6-11eb-9474-51b3752a2177.png)

版本：
![图片](https://user-images.githubusercontent.com/27721325/118772506-6865e900-b8b6-11eb-9852-1741606dbe66.png)

另外，这个硬盘温度是不是得有区分啊，一般都至少两块盘的。

**Comment by Freeman1989** [comment]
我的MateBook 13也是初始CPU其他的温度都获取不到
