### ISSUE TITLE
1.80.1版关闭了“显示通知区域图标”，但弹出过通知后就会自动开启

### ISSUE THREAD

**Issue by mxy493** [zhongyang219/TrafficMonitor#649]
1.80.1版关闭了“显示通知区域图标”，但弹出过通知后就会自动开启。如下：

![bug](https://user-images.githubusercontent.com/46776216/118783550-c21fe080-b8c1-11eb-99e7-dc604222d0d7.gif)

**Comment by Helloearther** [comment]
我也发现相同问题，重启后图标也会再出现

**Comment by zhongyang219** [comment]
这是正常的，Windows就是这么设计的，通过Windows API弹出通知时通知区图标会自动显示出来。如果你不想显示通知区图标，请不要开启通知功能。

**Comment by mxy493** [comment]
> 这是正常的，Windows就是这么设计的，通过Windows API弹出通知时通知区图标会自动显示出来。如果你不想显示通知区图标，请不要开启通知功能。

可不可以把这一项配置保存下来，在Windows弹出通知显示出来后后，程序再次自动将它设置为隐藏呢？

**Comment by zhongyang219** [comment]
> > 这是正常的，Windows就是这么设计的，通过Windows API弹出通知时通知区图标会自动显示出来。如果你不想显示通知区图标，请不要开启通知功能。
> 
> 可不可以把这一项配置保存下来，在Windows弹出通知显示出来后后，程序再次自动将它设置为隐藏呢？

这个实现起来比较麻烦，我不想做，而且我认为也没有必要。

**Comment by mxy493** [comment]
好吧，遗憾
