### ISSUE TITLE
右下角图标颜色

### ISSUE THREAD

**Issue by fengchenggf** [zhongyang219/TrafficMonitor#65]
右下角图标颜色可不可以改成除了白色的其他颜色，在win7 隐藏图标 背景是白色的，这样就看不到软件图标了

**Comment by zhongyang219** [comment]
我很早以前就注意到了这个问题，所以我提供了“更换通知区图标”的功能，点击右键菜单——“其他功能”——“更换通知区图标”，选择“图标2”或“图标3”即可。
