### ISSUE TITLE
[BUG]"显示通知区域图标"功能失效

### ISSUE THREAD

**Issue by BenjiaH** [zhongyang219/TrafficMonitor#651]
1.80.1(X64)版本
复现：在关闭"显示通知区域图标"功能且打开温度检测报警的情况下。若发出一次报警，则"显示通知区域图标"功能失效。

![GIF 2021-5-19 19-38-04](https://user-images.githubusercontent.com/46958476/118807152-804f6400-b8da-11eb-9cf8-7473d93a50d0.gif)

gif动画较长。

**Comment by BenjiaH** [comment]
补充：电脑重启后也会失效

**Comment by zhongyang219** [comment]
这是正常的，Windows就是这么设计的，通过Windows API弹出通知时通知区图标会自动显示出来。如果你不想显示通知区图标，请不要开启通知功能。
