### ISSUE TITLE
TrafficMonitor is locking my USB Disk

### ISSUE THREAD

**Issue by luqmanfadlli** [zhongyang219/TrafficMonitor#655]
I cannot safely remove my USB Disk because it's currently in use. Turn out, the one using the USB Disk is Traffic Monitor. I have to kill it first to remove the USB device. Why is it using my USB Disk? Is it accessing my files without me knowing?
![image](https://user-images.githubusercontent.com/75630095/119106751-d17d6600-ba48-11eb-98fc-94a47e789a78.png)

**Comment by zhongyang219** [comment]
Hello, please update to the latest version and turn off all of the item in "Option Settings"-"General Settings"-"Hardware Monitoring", restart TrafficMonitor, then check if this problem still exist.

**Comment by zhongyang219** [comment]
By the way, can you tell me what software is in the screenshot above?

**Comment by luqmanfadlli** [comment]
It's USB Safely Remove, by Crystal Rich, creator of LockHunter.
I can confirm that the problem fixed after updating.
Thanks
