### ISSUE TITLE
关机/重启都会显示该程序阻止关机

### ISSUE THREAD

**Issue by shyshy-a** [zhongyang219/TrafficMonitor#656]
系统使用的是windows 10 企业版 LTSC 1809
每次关机都会遇到

**Comment by zhongyang219** [comment]
请更新到最新版本，然后看看这个问题是否仍然存在。

**Comment by shyshy-a** [comment]
不是最新版的 最新版打开直接报错 应该是倒数第二个最新版 可以显示cpu gpu温度的版本

**Comment by zgcwkj** [comment]
> 请更新到最新版本，然后看看这个问题是否仍然存在。

还是有这个问题，win10 21H1

**Comment by gc89925** [comment]
> 不是最新版的 最新版打开直接报错 应该是倒数第二个最新版 可以显示cpu gpu温度的版本



> 请更新到最新版本，然后看看这个问题是否仍然存在。

这个问题也困扰我半年之久了，前两天终于解决了，是个BUG,右键把显示主窗口的勾取消掉就可以正常关机了，但是平时没显示，折中的办法就是打开显示任务栏按钮，这样就有显示，同时也可以正常关机了，希望下个版本可以修复这个问题
