### ISSUE TITLE
cpu temp not measuring after new update

### ISSUE THREAD

**Issue by anirudh-pixel** [zhongyang219/TrafficMonitor#659]
mbd tempature gpu temperature and cpu temperature not measuring.

in 1.80 and 1.80.1 cpu temperature was measured after new update cpu temperature is broken. other 2 are broken since the inception. gpu % is probably fixed more testing is needed to be sure earlier it used to be either on 0 or 100 only.

Update: Gpu percent is still broken . 

Testing conditions: 2160p HDR BDRip x265 10bit TrueHD 7.1 Atmos video file 
video played using potplayer.
using performance counter in settings the task manager showed around 68-73% gpu usage but the trafficmonitor program still showed either 0 or 100 with only a few instances 1 instance per 10 seconds average where the usage showed was between 1-99. Update time for trafficmonitor = 1000ms.

**Comment by zhongyang219** [comment]
Hello, please update to the latest version and check if the problem still exists.
