### ISSUE TITLE
1.80.2更新后温度显示问题

### ISSUE THREAD

**Issue by smaiiboy** [zhongyang219/TrafficMonitor#660]
![image](https://user-images.githubusercontent.com/17917669/119228268-d0316380-bb44-11eb-8d1e-5c7ee8ca234f.png)
![image](https://user-images.githubusercontent.com/17917669/119228312-053db600-bb45-11eb-9c33-d0a5ab6c4f1f.png)
1.80.2更新后温度部分不显示
CPU：AMD 3500X

**Comment by applemiku** [comment]
我的3600也是，上一个版本是显示的

**Comment by qunshao** [comment]
![image](https://user-images.githubusercontent.com/56646377/119228873-acbbe800-bb47-11eb-848b-70821f6cf288.png)
AMD 5800X CPU 温度也不能正常显示，上个版本正常

**Comment by zhongyang219** [comment]
请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常

**Comment by qunshao** [comment]
> 请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常

![image](https://user-images.githubusercontent.com/56646377/119232638-7f2b6a80-bb58-11eb-9202-0a494e38713b.png)
显示正常

**Comment by zhongyang219** [comment]
> > 请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常
> 
> ![image](https://user-images.githubusercontent.com/56646377/119232638-7f2b6a80-bb58-11eb-9202-0a494e38713b.png)
> 显示正常

请把CPU温度部分的完整的截图发上来看看，谢谢！

**Comment by xishizhe** [comment]
怎么直接覆盖更新啊，每次更新都要重新设置一遍。

**Comment by xishizhe** [comment]
> > > 请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常
> > 
> > ![image](https://user-images.githubusercontent.com/56646377/119232638-7f2b6a80-bb58-11eb-9202-0a494e38713b.png)
> > 显示正常
> 
> @qunshao 请把CPU温度部分的完整的截图发上来看看，谢谢！

作者你好，借个楼，我想请问一下怎么直接覆盖更新啊，我每次更新都要重新设置一遍。

**Comment by qunshao** [comment]
> > > 请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56646377/119232638-7f2b6a80-bb58-11eb-9202-0a494e38713b.png)
> > 显示正常
> 
> @qunshao 请把CPU温度部分的完整的截图发上来看看，谢谢！

![image](https://user-images.githubusercontent.com/56646377/119234171-07147300-bb5f-11eb-8c94-3f10c91a3be0.png)
这样可以吗？

**Comment by CurtisWong458** [comment]
我是主板温度不显示

**Comment by db-one** [comment]
我的是系统重启之后CPU温度不显示，退出然后手动重新运行之后CPU温度就回来了，系统是企业版1809 LTSC

**Comment by zhongyang219** [comment]
> > > > 请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常
> > > 
> > > 

> > > 显示正常
> > 
> > 
> > @qunshao 请把CPU温度部分的完整的截图发上来看看，谢谢！
> 
> 作者你好，借个楼，我想请问一下怎么直接覆盖更新啊，我每次更新都要重新设置一遍。

@xishizhe 把zip压缩包里的所有文件复制到原来TrafficMonitor目录下覆盖同名文件即可。

**Comment by CurtisWong458** [comment]
> > > > > 请下载[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v0.8.7/LibreHardwareMonitor-net452.zip)这个软件，看看CPU温度显示是否正常
> 
> > > > 显示正常
> > > 
> > > 
> > > @qunshao 请把CPU温度部分的完整的截图发上来看看，谢谢！
> > 
> > 
> > 作者你好，借个楼，我想请问一下怎么直接覆盖更新啊，我每次更新都要重新设置一遍。
> 
> @xishizhe 把zip压缩包里的所有文件复制到原来TrafficMonitor目录下覆盖同名文件即可。

亲，我的主板温度一直不显示怎么回事？？？1.80.2 版本

**Comment by zhongyang219** [comment]
问题已解决
