### ISSUE TITLE
建议添加自动更新功能

### ISSUE THREAD

**Issue by LebranceBW** [zhongyang219/TrafficMonitor#664]
首先感谢这个项目的开发人员！确实很好用。很赞。:thumbsup:
软件每次更新的时候，都是弹出一个对话框然后跳转到下载页面。需要我们手动退出程序然后解压覆盖，有些麻烦。有没有可能编写一个小的类似于bootloader的部分实现自动更新？

**Comment by zhongyang219** [comment]
不用担心，以后应该不会经常更新的😅
