### ISSUE TITLE
更新后测不到CPU温度了

### ISSUE THREAD

**Issue by biubiubbiuok** [zhongyang219/TrafficMonitor#665]
cpu是3700x，1.8版本温度正常检测，1.82不行了

**Comment by smounives** [comment]
+1,CPU是5800H

**Comment by Sakaizd** [comment]
+1,3700x

**Comment by yypboy** [comment]
5800X也一样

**Comment by Feiwenkeke** [comment]
https://github.com/zhongyang219/TrafficMonitor/actions/runs/867754513

**Comment by wanguaf2016** [comment]
> https://github.com/zhongyang219/TrafficMonitor/actions/runs/867754513

牛，更新了这里面的文件就好了

**Comment by qunshao** [comment]
> https://github.com/zhongyang219/TrafficMonitor/actions/runs/867754513

非常感谢，实测用这个把原文件覆盖CPU温度能正常显示了

**Comment by biubiubbiuok** [comment]
> cpu是3700x，1.8版本温度正常检测，1.82不行了

使用楼上的方法成功了，灰常感谢~
