### ISSUE TITLE
LibreHardwareMonitor疑似无法监测硬盘温度

### ISSUE THREAD

**Issue by soloopooo** [zhongyang219/TrafficMonitor#666]
![image](https://user-images.githubusercontent.com/36123081/119249511-af602100-bbcb-11eb-9e41-de444d095dca.png)

DT为Disk Temp,为硬盘温度

两块硬盘都不能被监测到

**Comment by zhongyang219** [comment]
去给LibreHardwareMonitor的作者提issue吧
