### ISSUE TITLE
温度无法检测

### ISSUE THREAD

**Issue by mlrsyz** [zhongyang219/TrafficMonitor#667]
更新最目前最新版无法检测某些温度模块
CPU温度模块
GPU温度模块
主板温度模块
我推测可能是厂商的原因
![Snipaste_2021-05-23_15-05-10](https://user-images.githubusercontent.com/44489042/119251250-4df27f00-bbd8-11eb-86fb-5c32bd6869e3.jpg)

![Snipaste_2021-05-23_15-05-58](https://user-images.githubusercontent.com/44489042/119251270-68c4f380-bbd8-11eb-92d4-af8b9478e924.jpg)

我电脑型号是magicbook pro 2020
cpu:  AMD 4800H
Hdd: 西部数据sn730
具体数据放下面图
![Snipaste_2021-05-23_15-10-27](https://user-images.githubusercontent.com/44489042/119251432-0ae4db80-bbd9-11eb-89dd-98b05a3e4b57.jpg)

**Comment by mlrsyz** [comment]
![Snipaste_2021-05-23_15-17-03](https://user-images.githubusercontent.com/44489042/119251609-fbb25d80-bbd9-11eb-9c60-44f6224c4230.jpg)
我将LibreHardwareMonitorLib.dll(LibreHardwareMonitor.exe插件的)依赖覆盖了此项目   还是无法显示cpu温度,希望作者大大抽空修复下哈   哈哈

**Comment by zhongyang219** [comment]
请更新到最新版本
