### ISSUE TITLE
1.80.2版本监控显卡温度时会使核显输出笔记本未工作的独立显卡进入工作状态

### ISSUE THREAD

**Issue by AlphaAnother** [zhongyang219/TrafficMonitor#668]
如果打开显卡监控 在核显输出的情况下依旧会启动独立显卡 利用率显存使用率等全0 风扇微速启动；常规设置中关闭监控显卡勾选后显卡风扇停转 显卡关闭。
可能是新监控库的原因。

**Comment by zhongyang219** [comment]
请到”选项设置“——”常规设置“——”硬件监控“中关闭对应的硬件监控功能，或者使用不含温度监控的版本。

**Comment by AlphaAnother** [comment]
> 请到”选项设置“——”常规设置“——”硬件监控“中关闭对应的硬件监控功能，或者使用不含温度监控的版本。

1.80.1版本的话监控显卡温度时如果独显不工作会直接不显示温度 并不会把独显打开 只是想问下作者能修复这个问题吗

**Comment by zhongyang219** [comment]
> > 请到”选项设置“——”常规设置“——”硬件监控“中关闭对应的硬件监控功能，或者使用不含温度监控的版本。
> 
> 1.80.1版本的话监控显卡温度时如果独显不工作会直接不显示温度 并不会把独显打开 只是想问下作者能修复这个问题吗？

解决不了，TrafficMonitor的温度监控功能依赖第三方开源库[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)，这个问题你得向LibreHardwareMonitor的作者反馈。
