### ISSUE TITLE
新版本无法监测硬盘温度

### ISSUE THREAD

**Issue by YuI2333** [zhongyang219/TrafficMonitor#670]
![2021-05-24_07-44-09](https://user-images.githubusercontent.com/26202875/119280434-fc8fd180-bc63-11eb-819a-f395b5fe625c.png)

麻烦有空修复下，万分感谢！！

**Comment by zhongyang219** [comment]
问题已解决，请更新到1.80.3版本

**Comment by Tsuk1ko** [comment]
1.80.3 依然存在这个问题

![image](https://user-images.githubusercontent.com/24877906/120092049-cdd19980-c142-11eb-9aee-69a0d6a75144.png)

**Comment by zhongyang219** [comment]
请参照常见问题的第13条：
https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-trafficmonitor%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E6%9F%90%E4%BA%9B%E7%A1%AC%E4%BB%B6%E7%9A%84%E6%B8%A9%E5%BA%A6
