### ISSUE TITLE
无法正常检测CPU温度，是因为不能检测AMD的CPU吗？麻烦大佬修复一下

### ISSUE THREAD

**Issue by 1546734477** [zhongyang219/TrafficMonitor#673]

**Comment by liuwentiansie** [comment]
我的amdcpu可以喔,看下你是不是设置错了

**Comment by z1908144712** [comment]
我也遇到了相同的问题，CPU型号是R7-5800H

**Comment by z1908144712** [comment]
已解决 https://github.com/zhongyang219/TrafficMonitor/actions/runs/867754513

**Comment by 9o8i7u** [comment]
> 已解决 https://github.com/zhongyang219/TrafficMonitor/actions/runs/867754513

多谢！我的R1700 刚开始也没有注意。现在使用这个版本可以正常显示温度了。
