### ISSUE TITLE
自启动失败

### ISSUE THREAD

**Issue by MisakaSakura** [zhongyang219/TrafficMonitor#675]
更新新版后多了盾锁，无法随系统开机自启

**Comment by zhongyang219** [comment]
请参照[常见问题-设置了开机自动运行仍然无法开机自启](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#3-%E8%AE%BE%E7%BD%AE%E4%BA%86%E5%BC%80%E6%9C%BA%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C%E4%BB%8D%E7%84%B6%E6%97%A0%E6%B3%95%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
