### ISSUE TITLE
OpenHardwareMonitorLib.sys 无法删除

### ISSUE THREAD

**Issue by netsonicyxf** [zhongyang219/TrafficMonitor#677]
因为程序版本更新，更新退出主程序后，无法删除OpenHardwareMonitorLib.sys，必须注销后重新登录才能删除

**Comment by Chers-Jane** [comment]
https://blog.csdn.net/weixin_43914632/article/details/106851236

**Comment by netsonicyxf** [comment]
> https://blog.csdn.net/weixin_43914632/article/details/106851236

1.首先将.sys文件后缀改为.txt
2.重启Windows
3.打开修改后的以.txt结尾的文件即可删除

我这里退出主程序后，无法删除sys，删除除sys之外的程序后，再重启不用改后缀名就能删除sys
但每次升级trafficmonitor就要重启一次，有些麻烦

**Comment by zhongyang219** [comment]
1.80.2版本已经解决这个问题了，如果你在升级到1.80.2的时候出现了这问题，请先关闭TrafficMonitor的开机自启动功能，然后重启电脑就能删除了。

**Comment by netsonicyxf** [comment]
1.80.2已解决，感谢
