### ISSUE TITLE
debug启动时提示找不到tinyxml2.dll

### ISSUE THREAD

**Issue by mdmbct** [zhongyang219/TrafficMonitor#678]
vs2019导入后，TrafficMoniyor模块debug启动时提示找不到tinyxml2.dll

**Comment by zhongyang219** [comment]
我这边是正常的，dll文件也已经上传到版本库中。而且在debug模式下，程序依赖的tinyxml2d.dll而不是tinyxml2.dll。

**Comment by zzy28** [comment]
FYI，还没解决的话可以尝试给VS加装 .NET和MFC模块

**Comment by zhongyang219** [comment]
现在已经把tinyxml2的源代码添加到项目中，对tinyxml2的引用不再使用动态库，这个问题已经不存在了。
