### ISSUE TITLE
1.8.0_2闪退

### ISSUE THREAD

**Issue by kevinnet37** [zhongyang219/TrafficMonitor#679]
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

Failed to request MethodData, not in JIT code range

KEY_VALUES_STRING: 1

    Key  : AV.Dereference
    Value: NullPtr

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.Sec
    Value: 11

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on OFFICEHP

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 11

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 180

    Key  : Analysis.System
    Value: CreateObject

    Key  : CLR.Engine
    Value: CLR

    Key  : CLR.Version
    Value: 4.0.30319.0

    Key  : Timeline.Process.Start.DeltaSec
    Value: 7441

CONTEXT:  (.ecxr)
rax=00000004437bf248 rbx=0000000000000eec rcx=0000000000000000
rdx=0000000000000000 rsi=00000004437bdb50 rdi=00000004437be8e0
rip=00007ff6842160d8 rsp=0000000443cfea10 rbp=0000000443cfeb10
 r8=0000000443cff5e8  r9=0000000000000000 r10=0000000000000000
r11=0000000000000246 r12=0000000000000000 r13=00000004437bee08
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
TrafficMonitor+0x560d8:
00007ff6`842160d8 8b19            mov     ebx,dword ptr [rcx] ds:00000000`00000000=????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff6842160d8 (TrafficMonitor+0x00000000000560d8)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

PROCESS_NAME:  TrafficMonitor.exe

READ_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p            0x%p                    %s

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

MISSING_CLR_SYMBOL: 0

STACK_TEXT:  
00000004`43cfea10 00007ff6`8423a7e4 : 00000000`00000eec 00000000`00000eec 00000004`437bdb50 0000018b`3b924350 : TrafficMonitor+0x560d8
00000004`43cff620 00007ff6`843c9780 : 00000004`437bdb50 0000018b`3b924350 0000018b`3b91eb00 00000000`00000000 : TrafficMonitor+0x7a7e4
00000004`43cff750 00007ffc`756a7034 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : TrafficMonitor+0x209780
00000004`43cff780 00007ffc`77642651 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000004`43cff7b0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

SYMBOL_NAME:  TrafficMonitor+560d8

MODULE_NAME: TrafficMonitor

IMAGE_NAME:  TrafficMonitor.exe

STACK_COMMAND:  ~8s ; .ecxr ; kb

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_TrafficMonitor.exe!Unknown

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {63f5a703-339a-d245-8ed0-90fbbc61cc10}

Followup:     MachineOwner
---------

**Comment by azhe403** [comment]
In 1.80.2 cpu temp stop working too
![gambar](https://user-images.githubusercontent.com/17938038/119601542-93e75700-be13-11eb-99f1-7426e9042e7b.png)

**Comment by zhongyang219** [comment]
这个问题应该已经解决了，请更新到1.80.3版本再试试看
