### ISSUE TITLE
能否添加一个电量显示

### ISSUE THREAD

**Issue by WillZaan** [zhongyang219/TrafficMonitor#680]
能否添加一个电量显示，感觉还挺有必要的，因为本身电池无法显示数字化的电量

**Comment by zhongyang219** [comment]
抱歉，没有这方面的计划

**Comment by txyyh** [comment]
https://github.com/kas/percentage ~~提供一个此类开源应用~~

**Comment by soloopooo** [comment]
可以自己写插件。自己动手丰衣足食。
