### ISSUE TITLE
Wiki 文档错误

### ISSUE THREAD

**Issue by Geeyun-JY3** [zhongyang219/TrafficMonitor#682]
[配置和数据文件](https://github.com/zhongyang219/TrafficMonitor/wiki/配置和数据文件) 一节中 global_cfg.ini 的说明写反了。
![image](https://user-images.githubusercontent.com/49396421/119492473-b20c7300-bd91-11eb-8f23-6a59cc38c2f9.png)
应该是
> 当“portable_mode”为 false 时，config.ini、history_traffic.dat、history_traffic.dat.bak 和 error.log 这几个文件将会保存到“C:\Users\<用户名>\AppData\Roaming\TrafficMonitor”目录下。
>
> 当“portable_mode”为 true 时，以上文件将保存到程序所在目录。

**Comment by zhongyang219** [comment]
感谢反馈，已修正
