### ISSUE TITLE
更新后任务栏出现迷之占位

### ISSUE THREAD

**Issue by datou1996** [zhongyang219/TrafficMonitor#687]
如图所示，升级时是直接覆盖的，当时显示是正常的，重启电脑后程序没有自启动，手动启动就变成这样了。大概是之前的残留
，但找不到清理的方法，改回之前的版本后残留依然还在，重启explorer并没有什么用。

![image](https://user-images.githubusercontent.com/14991024/119584932-3eec1680-bdfc-11eb-95e8-9645f5b28ee6.png)

**Comment by vonl1** [comment]
![image](https://user-images.githubusercontent.com/40910092/119600546-d90e8780-be19-11eb-80e1-6fe1ee8864dd.png)
![image](https://user-images.githubusercontent.com/40910092/119600581-eb88c100-be19-11eb-996b-f97ca02bf636.png)
软件版本TrafficMonitor_V1.80.2_x64，wind 10版本21H1，操作性系统内部版本：19043.1023，重启更新软件都还存在空位

**Comment by HQ9527** [comment]
> ![image](https://user-images.githubusercontent.com/40910092/119600546-d90e8780-be19-11eb-80e1-6fe1ee8864dd.png)
> ![image](https://user-images.githubusercontent.com/40910092/119600581-eb88c100-be19-11eb-996b-f97ca02bf636.png)
> 软件版本TrafficMonitor_V1.80.2_x64，wind 10版本21H1，操作性系统内部版本：19043.1023，重启更新软件都还存在空位

这个应该是 WIN10 的问题

**Comment by vonl1** [comment]
![image](https://user-images.githubusercontent.com/40910092/119615128-a3759880-be31-11eb-958b-ece9f8a221c6.png)
这就是win10的锅了，等下次更新解决吧

**Comment by pigeon-coo** [comment]
![image](https://user-images.githubusercontent.com/72596694/119616125-d66c5c00-be32-11eb-8cee-90a6cf3d98a2.png)
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎5/‎19
操作系统内部版本	19043.985
体验	Windows Feature Experience Pack 120.2212.2020.0

同上述，一开始我还以为是我的双屏引发，看来只是系统问题。

**Comment by yafovo** [comment]
如果是升级21H1后出现这个问题 任务栏右键 - 资讯和兴趣-关闭。
可以试试。

**Comment by leozzyzheng** [comment]
![image](https://user-images.githubusercontent.com/6134295/120064480-f0aa7200-c09e-11eb-8958-f0d849c1f0f2.png)
更新出来的咨询天气这个功能导致的

**Comment by zhongyang219** [comment]
> 如果是升级21H1后出现这个问题 任务栏右键 - 资讯和兴趣-关闭。
> 可以试试。

我也是21H1，但是我的任务栏上并没有”资讯和兴趣“，这个功能不是要等到21H2才有的吗？

**Comment by CurtisWong458** [comment]
> > 如果是升级21H1后出现这个问题 任务栏右键 - 资讯和兴趣-关闭。
> > 可以试试。
> 
> 我也是21H1，但是我的任务栏上并没有”资讯和兴趣“，这个功能不是要等到21H2才有的吗？

版本号升级到19043.1023就有了

**Comment by zhongyang219** [comment]
这是Win10的bug实锤了！今天Win10版本到了19043.1023，任务栏多了“资讯和兴趣”，就变成这个样子了：
![image](https://user-images.githubusercontent.com/30562462/120091064-09b43100-c13a-11eb-9b5c-3168a29b90f2.png)
我原以为是TrafficMonitor有问题，但是我发现Windows自带的地址栏也会和“资讯和兴趣”冲突：
![image](https://user-images.githubusercontent.com/30562462/120091132-bb536200-c13a-11eb-93d6-db2d395d4878.png)

**Comment by NoverNobida** [comment]
请问是否有任何解决方法？

**Comment by LTHPKBTE** [comment]
见#702
关掉就能解决的话就close吧...
