### ISSUE TITLE
1.80.2版本经常崩溃

### ISSUE THREAD

**Issue by vicjl** [zhongyang219/TrafficMonitor#690]
首先感谢作者，这个软件很好用，不过最近的版本遇到了问题，会经常崩溃
不管使用含温度监控还是不含温度监控的版本都是如此，使用了最新的release，在1.79没有问题，使用覆盖更新，期间未修改设置。
信息如下：
很抱歉，程序出现了错误，请将此文件 “...\20210527134157_TrafficMonitor.exe.dmp” 通过电子邮件发送到 zhongyang219@hotmail.com，以帮助作者确定问题所在。并将以下内容添加到邮件正文中：
System Info:
Windows Version: 10.0 build 19043
DPI: 240
Version: 1.80.2 x64 (不含温度监控)
Last compiled date: 2021/05/22 19:29:44 
文件已通过邮箱发送，另以压缩形式附在该Issue中
[20210527134157_TrafficMonitor.zip](https://github.com/zhongyang219/TrafficMonitor/files/6551403/20210527134157_TrafficMonitor.zip)

**Comment by jouleken** [comment]
我也遇到这个问题，使用预发行构建版本后正常。 https://github.com/zhongyang219/TrafficMonitor/actions/runs/868611838

**Comment by willaytoun** [comment]
我也一样，试一下预发行构建版本看看吧。

**Comment by vicjl** [comment]
> 我也遇到这个问题，使用预发行构建版本后正常。 https://github.com/zhongyang219/TrafficMonitor/actions/runs/868611838

使用之后目前没有出现崩溃情况
