### ISSUE TITLE
System进程CPU使用率与耗电量增加

### ISSUE THREAD

**Issue by Eric-the-Red-00** [zhongyang219/TrafficMonitor#691]
由于某种不明原因，在所有其他条件相同时，v1.80.2相比v1.79.1会缩短我的笔记本2/3的续航。
该问题在反复测试中可100%复现，我已被迫回退至v1.79.1。
系统版本为21H1（19043.1023）。

**Comment by gcy798199642** [comment]
我的21h1不显示ssd温度

**Comment by SuLingGG** [comment]
有同样的问题。任务管理器中发现 system 这一进程 CPU 使用率大幅度增加。排查很久才发现是这里的问题。

**Comment by Eric-the-Red-00** [comment]
> 有同样的问题。任务管理器中发现 system 这一进程 CPU 使用率大幅度增加。排查很久才发现是这里的问题。

那就没错了，我也注意到**System进程CPU使用率大幅度增加**，在我的系统上稳定在10%左右，不过没有深入探究原因。

**Comment by sky-279** [comment]
我也发现这个问题在今天，在常规设置中关闭所有硬件监控可以缓解，希望开发者能够注意。

**Comment by sky-279** [comment]
> 我也发现这个问题在今天，在常规设置中关闭所有硬件监控可以缓解，希望开发者能够注意。

另外显卡硬件监控会导致笔记本独立显卡始终负载不能休眠

**Comment by penetrater** [comment]
> > 我也发现这个问题在今天，在常规设置中关闭所有硬件监控可以缓解，希望开发者能够注意。
> 
> 另外显卡硬件监控会导致笔记本独立显卡始终负载不能休眠

非常感谢，不说我都没注意，我说电脑风扇以前办公时声音很小的。惯了硬件监控，风扇声音小多了

**Comment by zhongyang219** [comment]
如果你没有温度监控的需求，建议下载不含温度监控的版本

**Comment by penetrater** [comment]
嗯嗯，明白了，谢谢大佬！多谢大佬开发这个软件，很实用
