### ISSUE TITLE
V1.80(X64)版本随微信通知闪烁

### ISSUE THREAD

**Issue by JJrousi** [zhongyang219/TrafficMonitor#693]
![fof23-pts4s](https://user-images.githubusercontent.com/42690700/119926786-9b8d3400-bfaa-11eb-8435-dbe747d46d3d.gif)
更新之后就遇到了，刚开始以为是任务栏工具startisback冲突造成的，卸载后还是有问题，不知道有没有人遇到过

**Comment by hfc1994** [comment]
Duplicate of #640

**Comment by breaklj** [comment]
> Duplicate of #640

试了下，还是会闪，退出了也会闪

**Comment by JJrousi** [comment]
> Duplicate of #640
问题已解决，判断出是win10更新版本后，在任务栏界面加入了咨询和兴趣功能造成的，关闭即可
![lrqhl-zu5lr](https://user-images.githubusercontent.com/42690700/120137097-274ecc80-c206-11eb-8a0e-dc52a05d7f6b.gif)
