### ISSUE TITLE
V1.80.3版本不显示任何温度了

### ISSUE THREAD

**Issue by BigAppleClass** [zhongyang219/TrafficMonitor#694]
选项全变灰色了。
V1.80.2没事。
我决定换回V1.80.2

**Comment by CurtisWong458** [comment]
我这边新版本没问题，可以正常显示温度

**Comment by zhongyang219** [comment]
新版本默认关闭了温度监控功能，请在“选项”——“常规设置”中开启硬件监控。

**Comment by BigAppleClass** [comment]
> 新版本默认关闭了温度监控功能，请在“选项”——“经常设置”中开启硬件监控。

**Comment by BigAppleClass** [comment]
> 新版本默认关闭了温度监控功能，请在“选项”——“经常设置”中开启硬件监控。

好的

**Comment by yumuye** [comment]
主板的温度好像无法监控，显示温度皮肤只有最后一个选项是么？

**Comment by zhongyang219** [comment]
> 主板的温度好像无法监控，显示温度皮肤只有最后一个选项是么？

温度监控的功能使用的是[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)库，温度监控的问题我也解决不了，可以向LibreHardwareMonitor的作者提issue。
目前只能`皮肤12`支持显示温度。

**Comment by yumuye** [comment]
好的，以前在用软媒雷达radar，但windows10更新1706版本后流量就显示不出来了，十分感谢。
