### ISSUE TITLE
主窗口的“总是置顶”在最新版本失效

### ISSUE THREAD

**Issue by System-Warning** [zhongyang219/TrafficMonitor#698]
之前的版本V1.80在应用程序最大化或全屏的状态下都可以置顶显示。
更新到V1.80.3之后，在“总是置顶”功能打开的情况下，应用程序最大化或全屏之后主窗口被隐藏。

**Comment by System-Warning** [comment]
不好意思是我自己搞错了

**Comment by ymyguang** [comment]
如何解决的?我的也是这种问题
