### ISSUE TITLE
1.80.3获取CPU温度错误，显示的应该是硬盘温度！

### ISSUE THREAD

**Issue by yvhkchao** [zhongyang219/TrafficMonitor#699]
1.80.3获取CPU温度错误，显示的应该是硬盘温度！
我这显卡都67度了，CPU温度还是57度。感觉不正常，打开娱乐大师一看，CPU温度显示是72度，这个显示就正常。
1.80.3估计是数据读取错误了。

**Comment by zhongyang219** [comment]
请参照常见问题的第13条：
https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-trafficmonitor%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E6%9F%90%E4%BA%9B%E7%A1%AC%E4%BB%B6%E7%9A%84%E6%B8%A9%E5%BA%A6

**Comment by db-one** [comment]
我目前遇到的问题是开机自启时候CPU温度会显示 - ，把软件退出，然后重新手动运行就好了
不知道是什么情况

**Comment by yvhkchao** [comment]
> 请参照常见问题的第13条：
> https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-trafficmonitor%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E6%9F%90%E4%BA%9B%E7%A1%AC%E4%BB%B6%E7%9A%84%E6%B8%A9%E5%BA%A6

LibreHardwareMonitor的温度监没有问题。在使用1.80.02版本的时候也没有出现这个问题

![LibreHardwareMonitor](https://user-images.githubusercontent.com/77866080/120093672-59045c80-c14e-11eb-9cbc-d47f56fdd3df.png)

**Comment by wang745125665** [comment]
我用的时候也以为温度不准，其实修改一下选择监控的CPU温度即可，修改为 Core Average或者Core Max

**Comment by yvhkchao** [comment]
> 我用的时候也以为温度不准，其实修改一下选择监控的CPU温度即可，修改为 Core Average或者Core Max

谢谢，修改CPU温度监控，就行了。

![TrafficMonitor](https://user-images.githubusercontent.com/77866080/120098405-57479280-c168-11eb-9275-48d3a551323b.png)
