### ISSUE TITLE
是否可通过修改config，去掉小数点后的数值

### ISSUE THREAD

**Issue by 2huYa0** [zhongyang219/TrafficMonitor#7]
作者，您好！非常感谢您制作了这个那么好的软件并分享分大众使用。
有个问题想咨询一下您：因为任务栏上的空间珍贵，是否可通过修改config，去掉小数点后的数值，我只需取整，不需要那么精确，另，是否考虑KB和MB自动切换功能？是否可以自定义是否显示CPU和内存的情况？
期待您的回复，感谢。

**Comment by zhongyang219** [comment]
我已经提交了一个新版本的代码，增加了“网速显示简洁模式”选项，当单位为KB/s时数值只保留到整数。另外，能否详细描述一下你说的“KB和MB自动切换功能”是什么功能。我目前的处理是，当网速大于1024KB时单位显示为MB/s。软件本来就可以在右键菜单中勾选“显示CPU和内存利用率”选项，你说的“自定义是否显示CPU和内存的情况”具体是什么样的？

**Comment by 2huYa0** [comment]
非常感谢，原来我是不会设置，下载了最新版本，按你的回复里的指引去设置了一下，已经完全符合我的使用习惯~谢谢！
