### ISSUE TITLE
任务栏的时候，竖排的布局有些不好看。

### ISSUE THREAD

**Issue by specter119** [zhongyang219/TrafficMonitor#70]
![snipaste_2018-05-21_00-39-12](https://user-images.githubusercontent.com/8768524/40281096-6ab57904-5c8f-11e8-8780-78293f46818d.png)

或许，判断下竖排的时候两侧都留一点点会好些？

**Comment by zhongyang219** [comment]
谢谢反馈，我会想办法调整一下。

**Comment by zhongyang219** [comment]
但是竖排时，由于任务栏宽度的限制，无法做到两侧都留一点空白。这种情况下，你可以通过选项设置中显示文本设置，将冒号和空格去掉，使它的宽度变小。我可以在左侧稍微增加一点空白。
