### ISSUE TITLE
一直提示-由于找不到写VCRUNTIME140.DLL,无法继续执行代码.重新安装程序可能会解决此问题

### ISSUE THREAD

**Issue by xzsaqe** [zhongyang219/TrafficMonitor#700]
一直提示-由于找不到写XX.DLL,无法继续执行代码，好像从V1.79.1后就不行了，一直提示这个错误。无法正常运行。现在只能用V1.79.1这个版本了，新版都提示这个错误https://sm.ms/image/kytsKhE6P5DrWlL

**Comment by zhongyang219** [comment]
安装[Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)可以解决这个问题
