### ISSUE TITLE
從加入溫度後 問題多 不如取消

### ISSUE THREAD

**Issue by ghost** [zhongyang219/TrafficMonitor#703]
.

**Comment by zhongyang219** [comment]
遇到问题前不如先看一下常见问题和帮助文档？
https://github.com/zhongyang219/TrafficMonitor/wiki/%E7%A1%AC%E4%BB%B6%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD
https://github.com/zhongyang219/TrafficMonitor/wiki/%E9%80%89%E9%A1%B9%E8%AE%BE%E7%BD%AE#%E7%A1%AC%E4%BB%B6%E7%9B%91%E6%8E%A7

**Comment by Geeyun-JY3** [comment]
不需要的话你可以用不含温度监控的版本啊……
