### ISSUE TITLE
可以加入CPU的功耗监测吗？

### ISSUE THREAD

**Issue by wjj0227** [zhongyang219/TrafficMonitor#706]

**Comment by zhongyang219** [comment]
后面打算把主要精力放在网络监控这块，硬件监控功能不打算做了。

**Comment by CurtisWong458** [comment]
> 后面打算把主要精力放在网络监控这块，硬件监控功能不打算做了。

大佬，这是什么情况？
很抱歉，程序出现了错误，请将此文件 “C:\Users\**\AppData\Local\Temp\20210531180000_TrafficMonitor.exe.dmp” 通过电子邮件发送到 zhongyang219@hotmail.com，以帮助作者确定问题所在。并将以下内容添加到邮件正文中：
System Info:
Windows Version: 10.0 build 19043
DPI: 120
Version: 1.80.3 x64
Last compiled date: 2021/05/29 17:50:23

**Comment by kindgxs** [comment]
> 后面打算把主要精力放在网络监控这块，硬件监控功能不打算做了。

那温度监控还会维吗

**Comment by kindgxs** [comment]
> > 后面打算把主要精力放在网络监控这块，硬件监控功能不打算做了。
> 
> 那温度监控还会维吗

维护吗

**Comment by zhongyang219** [comment]
> > 后面打算把主要精力放在网络监控这块，硬件监控功能不打算做了。
> 
> 大佬，这是什么情况？
> 很抱歉，程序出现了错误，请将此文件 “C:\Users**\AppData\Local\Temp\20210531180000_TrafficMonitor.exe.dmp” 通过电子邮件发送到 [zhongyang219@hotmail.com](mailto:zhongyang219@hotmail.com)，以帮助作者确定问题所在。并将以下内容添加到邮件正文中：
> System Info:
> Windows Version: 10.0 build 19043
> DPI: 120
> Version: 1.80.3 x64
> Last compiled date: 2021/05/29 17:50:23

@CurtisWong458 你到是把dmp文件发上来啊

**Comment by zhongyang219** [comment]
> > > 后面打算把主要精力放在网络监控这块，硬件监控功能不打算做了。
> > 
> > 
> > 那温度监控还会维吗
> 
> 维护吗

其实基本上没有什么需要维护的，硬件监控功能使用的是第三方库LibreHardwareMonitor，如果LibreHardwareMonitor有问题，那么TrafficMonitor也会有同样的问题，这只能由LibreHardwareMonitor来解决。

**Comment by CurtisWong458** [comment]
> > > 能不能把主要的维护网络监控这块，智能监控功能不知道。
> > 
> > 
> > 大佬，这是什么情况？
> > 很抱歉，程序出现了错误，请将此文件“C：\用户** \应用程序数据\本地的\ Temp \ 20210531180000_TrafficMonitor.exe.dmp”电子邮件通过发送到[zhongyang219@hotmail.com](mailto:zhongyang219@hotmail.com)，，以帮助作者确定问题所在。另外，将以下内容添加到邮件正文中：
> > 系统信息：
> > Windows版本：10.0 build 
> > 19043 
> > DPI：120版本：1.80.3 x64
> > 最后编译日期：2021/05/29 17:50:23
> 
> @CurtisWong458你到是把dmp文件发上来啊


[20210531180000_TrafficMonitor.zip](https://github.com/zhongyang219/TrafficMonitor/files/6570051/20210531180000_TrafficMonitor.zip)

**Comment by zhongyang219** [comment]
> > > > 能不能把主要的维护网络监控这块，智能监控功能不知道。
> > > 
> > > 
> > > 大佬，这是什么情况？
> > > 很抱歉，程序出现了错误，请将此文件“C：\用户** \应用程序数据\本地的\ Temp \ 20210531180000_TrafficMonitor.exe.dmp”电子邮件通过发送到[zhongyang219@hotmail.com](mailto:zhongyang219@hotmail.com)，，以帮助作者确定问题所在。另外，将以下内容添加到邮件正文中：
> > > 系统信息：
> > > Windows版本：10.0 build
> > > 19043
> > > DPI：120版本：1.80.3 x64
> > > 最后编译日期：2021/05/29 17:50:23
> > 
> > 
> > @CurtisWong458你到是把dmp文件发上来啊
> 
> [20210531180000_TrafficMonitor.zip](https://github.com/zhongyang219/TrafficMonitor/files/6570051/20210531180000_TrafficMonitor.zip)

![image](https://user-images.githubusercontent.com/30562462/120190310-0066b980-c24b-11eb-9c03-b917bfb9eacd.png)
你这个问题可能解决不了，调试时显示程序在执行wstring::operator=时崩溃了，等号右边的地址无法访问，但是等号右边是Windows API获取的结果。如果这个问题只是偶现就无视它吧。

**Comment by CurtisWong458** [comment]
> > > > > 能不能把主要的维护网络监控这块，智能监控功能不知道。
> > > > 
> > > > 
> > > > 大佬，这是什么情况？
> > > > 很抱歉，程序出现了错误，请将此文件“C：\用户** \应用程序数据\本地的\ Temp \ 20210531180000_TrafficMonitor.exe.dmp”电子邮件通过发送到[zhongyang219@hotmail.com](mailto:zhongyang219@hotmail.com)，，以帮助作者确定问题所在。另外，将以下内容添加到邮件正文中：
> > > > 系统信息：
> > > > Windows版本：10.0 build
> > > > 19043
> > > > DPI：120版本：1.80.3 x64
> > > > 最后编译日期：2021/05/29 17:50:23
> > > 
> > > 
> > > @CurtisWong458你到是把dmp文件发上来啊
> > 
> > 
> > [20210531180000_TrafficMonitor.zip](https://github.com/zhongyang219/TrafficMonitor/files/6570051/20210531180000_TrafficMonitor.zip)
> 
> ![image](https://user-images.githubusercontent.com/30562462/120190310-0066b980-c24b-11eb-9c03-b917bfb9eacd.png)
> 你这个问题可能解决不了，调试时显示程序在执行wstring::operator=时崩溃了，等号右边的地址无法访问，但是等号右边是Windows API获取的结果。如果这个问题只是偶现就无视它吧。

感谢，这个的确只出现过两次，第一次出现在1.80初版
