### ISSUE TITLE
1.8.3 CPU 温度显示的不实？

### ISSUE THREAD

**Issue by at2008** [zhongyang219/TrafficMonitor#709]
1.8.3 CPU 温度显示的似乎不是CPU的温度，比实际温度高了大概10°

**Comment by blackbeaf** [comment]
我也是.
我机器上X大师, CPUID HWMONITOR的cpu温度是一样的, 40左右, trafficmonitor是47.

**Comment by sakumakenshin** [comment]
![微信截图_20210603191010](https://user-images.githubusercontent.com/85289689/120635852-80855d00-c49f-11eb-83ca-4c5020c44f9f.png)
确实不准。

**Comment by zhongyang219** [comment]
[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by sakumakenshin** [comment]
![微信截图_20210604220736](https://user-images.githubusercontent.com/85289689/120814595-9ff4b680-c581-11eb-9edf-ea575f03b56c.png)

**Comment by zhongyang219** [comment]
[“选项”-“常规设置”-“选择监控的CPU温度”](https://github.com/zhongyang219/TrafficMonitor/wiki/%E9%80%89%E9%A1%B9%E8%AE%BE%E7%BD%AE#%E7%A1%AC%E4%BB%B6%E7%9B%91%E6%8E%A7)

**Comment by sakumakenshin** [comment]
懂了。多谢
