### ISSUE TITLE
开机启动问题

### ISSUE THREAD

**Issue by eliscott** [zhongyang219/TrafficMonitor#71]
设置为管理员运行模式之后无法开机启动，但是不设置管理员运行的话，会一直弹出无法写入配置文件的窗口，这个该怎么解决呢

**Comment by zhongyang219** [comment]
请问你目前用的是哪个版本？1.73版本应该不会出现无法写入配置文件的问题了。

**Comment by eliscott** [comment]
用的是1.73版本

**Comment by zhongyang219** [comment]
能否把截图发上来看看？

**Comment by eliscott** [comment]
现在pc没网……我来描述一下吧
如果没有以管理员模式运行，会出现
警告：无法保存设置，无法向文件c:\user\...\appdata\roaming\trafficmonitor\config.ini写入数据，以管理员身份运行程序可能会解决问题。
如果以管理员身份运行，则开机不启动，任务管理器开机启动项里有trafficmonitor，进程里没有，双击打开之后能够正常运行。

**Comment by zhongyang219** [comment]
我暂时也不清楚为什么c:\user...\appdata\roaming\trafficmonitor\config.ini会无法写入，尝试一下把这个文件删除让它重新生成看看。

**Comment by zhongyang219** [comment]
之前配置文件是放在程序所在目录下的，现在之所以移动到C:\Users\用户名\AppData\Roaming\TrafficMonitor下面就是想解决有时程序所在目录无法写入数据的问题，按理说C:\Users\用户名\AppData\Roaming\TrafficMonitor这个目录是绝对不会出现无法写入的问题才对。关于你出现的问题，我暂时也没什么头绪。

**Comment by eliscott** [comment]
之前更改了这个文件的权限，还是没能解决，但是删除之后重新生成解决了！谢谢开发者～
