### ISSUE TITLE
主板温度显示异常

### ISSUE THREAD

**Issue by Whereu** [zhongyang219/TrafficMonitor#714]
主板温度显示异常！80度了。。。。。。

**Comment by CurtisWong458** [comment]
你还可以显示，我这边直接无法显示呢

**Comment by zb737472783** [comment]
HDD 主板 都无法显示  MSI笔记本

**Comment by zhongyang219** [comment]
抱歉，这个问题我解决不了，你可以向LibreHardwareMonitor的作者反馈。

**Comment by zhongyang219** [comment]
[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
[wiki-选项设置-常规设置-硬件监控](https://github.com/zhongyang219/TrafficMonitor/wiki/%E9%80%89%E9%A1%B9%E8%AE%BE%E7%BD%AE#%E7%A1%AC%E4%BB%B6%E7%9B%91%E6%8E%A7)
