### ISSUE TITLE
安装软件报错

### ISSUE THREAD

**Issue by ZDY321** [zhongyang219/TrafficMonitor#717]
下载最新的安装包，关闭杀毒软件之后安装时会出现：
由于找不到VCRUNTIME140.dll，无法继续执行代码。重新安装程序可能会解决此问题。
由于找不到MSVCP140.dll，无法继续执行代码。重新安装程序可能会解决此问题。

**Comment by zhongyang219** [comment]
安装[Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145)可以解决这个问题
