### ISSUE TITLE
1.80.3 缺少 MSVCP140.dll

### ISSUE THREAD

**Issue by Showfom** [zhongyang219/TrafficMonitor#719]
运行后提示缺少 MSVCP140.dll

解决方法，安装 Visual C++ Redistributable for Visual Studio 2015 

https://www.microsoft.com/en-hk/download/details.aspx?id=48145

但是我是用在服务器上的，以前老的版本都没问题，不是很想在服务器上装 Visual C++ 请问下个版本是否可以解决这个问题？

**Comment by zhongyang219** [comment]
请安装Visual C++ Redistributable for Visual Studio 2015来解决这个问题

**Comment by Showfom** [comment]
我不是已经说了解决方法么，问题是服务器上不是很适合装这个软件嘛

**Comment by zhongyang219** [comment]
抱歉，除了安装Visual C++ Redistributable for Visual Studio 2015，我也没有其他更好的解决方法。

**Comment by zhongyang219** [comment]
我知道问题出在哪了，应该是timyxl2.dll依赖了Visual C++ Redistributable for Visual Studio 2015。我一直奇怪，主程序使用已经将MFC的库作为静态库编译到exe里了，为什么还会提示缺少dll，而且我明明是用VS2019编译的。tinyxml2.dll是很久以前编译的，可能是用VS2915编的。

**Comment by LiteCoder** [comment]
下载MSVCP140.dll文件放在程序根目录应该也是可以的

**Comment by lfm09** [comment]
我也碰到这个问题，在同样没有安装VCR2015的情况下，Win7下没问题，Win10下则提示缺少msvcp140.dll以及vcrutime140.dll，1.7.8版没有此问题。

**Comment by lfm09** [comment]
我也碰到这个问题，先后提示缺少msvcp140.dll以及vcruntime140.dll，1.7.8版是正常的。

**Comment by lfm09** [comment]
> 
> 
> 我知道问题出在哪了，应该是timyxl2.dll依赖了Visual C++ Redistributable for Visual Studio 2015。我一直奇怪，主程序使用已经将MFC的库作为静态库编译到exe里了，为什么还会提示缺少dll，而且我明明是用VS2019编译的。tinyxml2.dll是很久以前编译的，可能是用VS2915编的。

老大，昨天的最新版本(7fd2b65)，问题依旧

**Comment by zhongyang219** [comment]
> 老大，昨天的最新版本(7fd2b65)，问题依旧

还是提示缺少MSVCP140吗？

**Comment by lfm09** [comment]
> > 老大，昨天的最新版本([7fd2b65](https://github.com/zhongyang219/TrafficMonitor/commit/7fd2b65da4c5733cfdb2424f958df0f830a44a58))，问题依旧
> 
> @lfm09 还是提示缺少MSVCP140吗？

是的，需要拷贝那几个运行库文件到程序目录下，才能运行。

另外顺带反映一个问题：当浏览器打开多个页面cpu占用率接近100%时，1.80.3信息显示更新不及时（即使关了显卡、主板、硬盘等模块），延迟非常大。测试1.79.1是正常的。

**Comment by lfm09** [comment]
> 
> 
> > 老大，昨天的最新版本([7fd2b65](https://github.com/zhongyang219/TrafficMonitor/commit/7fd2b65da4c5733cfdb2424f958df0f830a44a58))，问题依旧
> 
> @lfm09 还是提示缺少MSVCP140吗？

是的。

再反映一个问题：Firefox浏览器（版本78.12.0esr）打开多个页面时，最新的1.80.3会出现卡顿、信息显示延迟的问题。测试1.79.1是正常的。

**Comment by lfm09** [comment]
> 
> 
> > > 老大，昨天的最新版本([7fd2b65](https://github.com/zhongyang219/TrafficMonitor/commit/7fd2b65da4c5733cfdb2424f958df0f830a44a58))，问题依旧
> > 
> > 
> > @lfm09 还是提示缺少MSVCP140吗？
> 
> @zhongyang219 是的。
> 
> 再反映一个问题：Firefox浏览器（版本78.12.0esr）打开多个页面时，最新的1.80.3会出现卡顿、信息显示延迟的问题，即使关闭主板、显卡、硬盘等模块也一样，不过有时候又是正常的，无语了。测试1.79.1是一直正常的。

@zhongyang219  又测试了一下，卡顿、延迟的问题终于找出点规律了：设置"开机自动运行"的情况下，重启电脑后，计划任务里“TrafficMonitor”的状态是“正在运行”，此时运行Firefox同时打开多个页面，问题即可复现。

**Comment by Showfom** [comment]
1.81 版本还是一样提示，已滚回 1.79.1

**Comment by Germxu** [comment]
同, 希望修复
