### ISSUE TITLE
集成显卡和主板的温度不能显示？

### ISSUE THREAD

**Issue by neatgz** [zhongyang219/TrafficMonitor#720]
Macbook pro 15寸，CPU是 i7-4770hq，没有独立显卡，带有核显。
其他软件 如 AIDA64 等，可以显示 集显 也就是 **G**PU 的温度。
TrafficMonitor 无法识别和显示集显的温度，使用率。
![image](https://user-images.githubusercontent.com/22790906/120729520-f1fdf380-c511-11eb-99c2-713d9fe2611c.png)

**Comment by zhongyang219** [comment]
请参照[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by soloopooo** [comment]
@neatgz 确认问题解决后，请关闭此issue，以保持issue的整洁与时效性。
