### ISSUE TITLE
1.80.3无法显示详细信息

### ISSUE THREAD

**Issue by shyshy-a** [zhongyang219/TrafficMonitor#721]
![image](https://user-images.githubusercontent.com/58125698/120756921-76686a80-c542-11eb-850e-5a3b287cd824.png)
cpu：amd3800x
显卡：GT630
硬盘：西数南盘
主板：华硕450

**Comment by zhongyang219** [comment]
请参照[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
