### ISSUE TITLE
1.80.3 会引出 UAC

### ISSUE THREAD

**Issue by iieeann** [zhongyang219/TrafficMonitor#722]
今天从 1.79 升级去 1.80.3，结果引发 UAC, 由于不是 Admin 结果不能用，只能跑回旧的版本。

**Comment by zhongyang219** [comment]
https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.80.3/TrafficMonitor_V1.80.3_x64_without_temperature.zip
