### ISSUE TITLE
1.80.3，所有温度都是灰色的，无法开启

### ISSUE THREAD

**Issue by lainbo** [zhongyang219/TrafficMonitor#725]
i7-9700k，微星z390 edge，aida64可以正常显示
![image](https://user-images.githubusercontent.com/46062895/120811633-c402c880-c57e-11eb-81a3-ba9334fe01d8.png)

**Comment by zhongyang219** [comment]
请参见[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by lainbo** [comment]
原因是我重新安装后没有在设置中开启温度监控
