### ISSUE TITLE
[1.80.3] Cannot display CPU&GPU's temperature properly.

### ISSUE THREAD

**Issue by charlottelatest** [zhongyang219/TrafficMonitor#729]
**My issue:**
![2021-06-09_11-01-23](https://user-images.githubusercontent.com/34669056/121287019-9e830100-c895-11eb-8dbc-b2579ce83bdc.png)

**Here are my `LibreHardwareMonitor` details:**
CPU temperature:
![2021-06-09_11-06-05](https://user-images.githubusercontent.com/34669056/121287052-b5c1ee80-c895-11eb-9bae-b521b512963e.png)

GPU temperature:
![2021-06-09_11-06-34](https://user-images.githubusercontent.com/34669056/121287080-c5d9ce00-c895-11eb-992f-4d0657682c41.png)

**Comment by zhongyang219** [comment]
The hardware monitor function is turned off by default, if you want to display temperature, you need to turn it on in ["Option Settings"-"General Settings"-"Hardware Monitoring"](https://github.com/zhongyang219/TrafficMonitor/wiki/%E9%80%89%E9%A1%B9%E8%AE%BE%E7%BD%AE#%E7%A1%AC%E4%BB%B6%E7%9B%91%E6%8E%A7)
