### ISSUE TITLE
[1.80.3]任务栏窗口显示错位。

### ISSUE THREAD

**Issue by AdoShan** [zhongyang219/TrafficMonitor#730]
靠右显示会错位。靠左显示不会。已经尝试过重启系统以及软件。都无效，就是更新这个版本之后出现的。前一个版本不会。
![image](https://user-images.githubusercontent.com/44154107/121343188-fd5b7f80-c954-11eb-9956-ee83e781583d.png)
![image](https://user-images.githubusercontent.com/44154107/121343240-0d735f00-c955-11eb-9e19-fc3345769fda.png)
![image](https://user-images.githubusercontent.com/44154107/121343308-1d8b3e80-c955-11eb-914f-1a0f881656ab.png)

**Comment by zyLiu6707** [comment]
Same here. My Windows just updated [(update pack info)](https://support.microsoft.com/zh-cn/topic/2021-%E5%B9%B4-6-%E6%9C%88-8-%E6%97%A5-kb5003637-os-%E5%86%85%E9%83%A8%E7%89%88%E6%9C%AC-19041-1052-19042-1052-%E5%92%8C-19043-1052-fd782405-7736-478e-b8d0-b08f735f7e54) and every time after booting, the icons in the system tray overlap on each other.

My current OS is Windows 10 Pro 20H2.

**Comment by TeFo-Leo** [comment]
同样的问题

**Comment by Im-fengyin** [comment]
老哥可以参考https://github.com/zhongyang219/TrafficMonitor/issues/702 看一下

**Comment by AdoShan** [comment]
> 老哥可以参考#702 看一下

解决了。感谢
