### ISSUE TITLE
任务栏显示bug

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [zhongyang219/TrafficMonitor#732]
当监控信息全部都打开时，任务栏窗口最后面部分的温度信息会显示不完全，如下图：
![image](https://user-images.githubusercontent.com/51226051/121616777-246d9a80-ca96-11eb-88a1-b04e30e6a17f.png)

**Comment by CurtisWong458** [comment]
哈哈你知足吧，我这边主板温度都不显示的

**Comment by JoyfulAndSpeedyMan** [comment]
> 哈哈你知足吧，我这边主板温度都不显示的

我就是反馈一下bug，哈哈。我这也不显示主板温度

**Comment by primaryonetwo** [comment]
补充一个，任务栏隔了一段空处，强迫症很难受[https://i.loli.net/2021/06/12/iQohDE5wmfg1jRs.png](url)

**Comment by zhongyang219** [comment]
这个应该算是老问题了，这个问题偶尔会出现，你只要把任务栏右侧通知区的任意一个图标向上拖动将其隐藏，再拖下来，也就是触发任务栏最小化区域宽度变化，就能恢复正常了，可以参考常见问题的第10条：[任务栏窗口有时会显示不全，比如单位被覆盖了](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#10-%E4%BB%BB%E5%8A%A1%E6%A0%8F%E7%AA%97%E5%8F%A3%E6%9C%89%E6%97%B6%E4%BC%9A%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%85%A8%E6%AF%94%E5%A6%82%E5%8D%95%E4%BD%8D%E8%A2%AB%E8%A6%86%E7%9B%96%E4%BA%86)

**Comment by LTHPKBTE** [comment]
> 补充一个，任务栏隔了一段空处，强迫症很难受[https://i.loli.net/2021/06/12/iQohDE5wmfg1jRs.png](url)
见#702。
