### ISSUE TITLE
显卡使用率 不准确

### ISSUE THREAD

**Issue by lloyd18** [zhongyang219/TrafficMonitor#733]
用格式工厂剪一个视频，显卡占用基本100%了，任务栏依然不到 20%

电脑是R9000P，它有个独显直连模式，是开了的，不知道和这个有没有关系。

![Snipaste_2021-06-13_01-32-53](https://user-images.githubusercontent.com/10294460/121784600-5d695480-cbe7-11eb-8f0b-5114b64dcaba.jpg)

**Comment by zhongyang219** [comment]
请参见[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
