### ISSUE TITLE
 *Windows 11 Optimization* ASAP

### ISSUE THREAD

**Issue by anirudh-pixel** [zhongyang219/TrafficMonitor#739]
Optimise for win11 asap. i just installed win11 the leaked version iso of win11 and this program isnt at all working. it is displaying over other app icons, moving left to right and what not.( due to a massive change of win11 taskbar ).

**Comment by zhongyang219** [comment]
Before the official version of windows 11 is released, the adaptation of Windows 11 will not be considered.
