### ISSUE TITLE
希望在任务栏网速的数字和单位之间增加空白

### ISSUE THREAD

**Issue by kailiu42** [zhongyang219/TrafficMonitor#74]
现在没有任何空白，网速的数字和单位直接挤在一起不是很美观，也不利于快速辨识数字。

下图是Traffic Monitor（无空）和NetSpeedMonitor（有空）的效果的对比。

![截图](https://user-images.githubusercontent.com/358679/40587007-43cba710-61fc-11e8-8d58-a24728c7d8ea.png)

**Comment by zhongyang219** [comment]
谢谢你的反馈，这个问题会在下个版本中解决。

**Comment by aplk1002** [comment]
请作成选项
我不喜欢空白
另外1.74版比1.72版
任务栏下面留空更多了
能否改成居中

**Comment by zhongyang219** [comment]
@aplk1002 关于任务栏下面留空多了的问题，是我不小心将任务栏窗口的高度调小了一个像素，下次更新会改成和1.73版本一样。

**Comment by aplk1002** [comment]
@zhongyang219 
配置文件若能在
软件根目录写入的话
是否可不在C盘生成
感觉写入不能的
应该都是WIN10的权限问题吧

**Comment by kraml** [comment]
@Dealtz 字体是Google的Roboto，渲染是用的MacType。另外屏幕是15.6寸4K的，所以渲染还不错。
