### ISSUE TITLE
建议增加Windows11任务栏窗口支持

### ISSUE THREAD

**Issue by Helloworlllld** [zhongyang219/TrafficMonitor#742]
Windows11上的任务栏布局集中中间（可能是布局的逻辑变了）
导致任务栏窗口叠在图标下（所有显示图标的右侧），不论任务栏靠左还是居中都是如此
不知道11正式版如何
Edition	Windows 11 Pro
Version	Dev
Installed on	‎2021/‎6/‎18
OS build	21996.1
Experience	Windows Feature Experience Pack 321.14700.0.3
![image](https://user-images.githubusercontent.com/62730995/122641805-0fe66d80-d13a-11eb-9965-54331710226b.png)
![image](https://user-images.githubusercontent.com/62730995/122641809-1b399900-d13a-11eb-8539-5d7f4965bebd.png)

**Comment by CurtisWong458** [comment]
https://github.com/zhongyang219/TrafficMonitor/issues/738
