### ISSUE TITLE
最新win11测试版，任务栏显示不正确

### ISSUE THREAD

**Issue by AlphaD999** [zhongyang219/TrafficMonitor#743]
开启任务栏显示之后和任务栏图标重叠
![image](https://user-images.githubusercontent.com/26535266/122666394-7e313b80-d1df-11eb-98e2-35d066228fc5.png)

**Comment by YG201506** [comment]
哭了啊

**Comment by SekiBetu** [comment]
+1

**Comment by hfc1994** [comment]
测试版Windows的问题就不要提了吧。。。谁知道正式版会不会再改点什么呢
