### ISSUE TITLE
温度一栏希望能对齐

### ISSUE THREAD

**Issue by conghuahuadan** [zhongyang219/TrafficMonitor#745]
如图
![image](https://user-images.githubusercontent.com/20864280/122680481-f6b8ec00-d221-11eb-8dba-ac286f08ac38.png)

**Comment by lloyd18** [comment]
这6个字母都可以改的啊

**Comment by zhongyang219** [comment]
在选项设置-任务栏窗口设置中使用数值右对齐即可

**Comment by lfm09** [comment]
> 
> 
> 在选项设置-任务栏窗口设置中使用数值右对齐即可

数值右对齐会导致上传下载符号和网速数值之间离的太远，一大片的空白，逼死强迫症
