### ISSUE TITLE
windows11 任务栏：应用不再能够自定义任务栏区域

### ISSUE THREAD

**Issue by Yueasdy** [zhongyang219/TrafficMonitor#749]

**Comment by AlphaD999** [comment]
![image](https://user-images.githubusercontent.com/26535266/123372491-37b05800-d5b6-11eb-9f0a-60760ed145b1.png)
看来可能win11任务栏区域不能显示了

**Comment by AlphaD999** [comment]
可以学习一下msi afterburner将温度等监测信息显示在系统托盘

**Comment by zhongyang219** [comment]
win11的这个变化对TrafficMonitor的任务显示没有影响，微软说的任务栏将不再支持自定义内容是针对使用微软提供的任务栏接口的，而我根本没有使用微软提供的任务栏接口，而是直接将窗口嵌入到任务栏的。目前只是显示的位置不正确，但是很容易解决。
