### ISSUE TITLE
最新版本cpu温度检测好像不太准，玩游戏的时候也一直显示五十多度。 本人windows10，

### ISSUE THREAD

**Issue by ourunfeng** [zhongyang219/TrafficMonitor#750]
最新版本cpu温度检测好像不太准，玩游戏的时候也一直显示五十多度。 本人windows10，

**Comment by soloopooo** [comment]
![image](https://user-images.githubusercontent.com/36123081/123761931-ddd0ca80-d8f4-11eb-9d63-bc784eac3161.png)
将平均温度改为Core Avg.
平均温度会将To TJMax的温度算上平均而导致不准确。

**Comment by ourunfeng** [comment]
感谢！已解决

**Comment by soloopooo** [comment]
@ourunfeng 确认问题解决后，请关闭此issue，以保持issue的时效性。
