### ISSUE TITLE
Win11系统下状态栏显示异常

### ISSUE THREAD

**Issue by airsimonhan** [zhongyang219/TrafficMonitor#751]
![bug](https://user-images.githubusercontent.com/15105562/123392493-b06fde00-d5cf-11eb-9b00-c32a3b84dae9.png)

win11系统下状态栏显示异常，设置为左侧后依然不对

**Comment by CurtisWong458** [comment]
作者说过在Windows 11正式发布之前暂时不考虑对Windows 11非正式版的适配

**Comment by 44886** [comment]
对，我也发现了，暂时只能用浮窗了
