### ISSUE TITLE
任务栏无法靠边

### ISSUE THREAD

**Issue by Lost-f** [zhongyang219/TrafficMonitor#752]
没有自定义位置选项，调不了位置，中间留了好大的空。
![屏幕截图 2021-06-27 133553](https://user-images.githubusercontent.com/26590981/123534044-9508ee00-d709-11eb-98ce-9f2c8b17d438.png)

**Comment by thhyaa** [comment]
+1，希望作者大大可以修复

**Comment by LTHPKBTE** [comment]
。。。尝试关闭windows的“资讯和兴趣”功能试试。
右键任务栏-资讯和兴趣-关闭
