### ISSUE TITLE
windows11 显示异常

### ISSUE THREAD

**Issue by 8680** [zhongyang219/TrafficMonitor#755]
![image](https://user-images.githubusercontent.com/85273405/123689210-8d6e5400-d885-11eb-9008-44fc60def5cc.png)

**Comment by Yueasdy** [comment]
![image](https://user-images.githubusercontent.com/22210602/123707319-18f2df80-d89c-11eb-9ddf-eec325700594.png)
和应用图标在一起，跟着引用图标居中或者靠左。

**Comment by MusherM** [comment]
same question

**Comment by duduzz2017** [comment]
同样的问题

**Comment by MusherM** [comment]
盲猜win11是把任务栏的图标区域把一整条改成了只有固定图标的动态区域，原来的窗口逻辑是在这个区域右对齐贴边，现在就变成了这样，开发者可能需要查查现在有没有替代方案了

**Comment by Beisaac** [comment]
是的，同样碰到了此问题。

**Comment by baizhougod** [comment]
同样的问题

**Comment by senobor** [comment]
希望能尽快弄好吧
我还是很喜欢这个软件的😁

**Comment by euukey** [comment]
同款问题
