### ISSUE TITLE
在Dev渠道正式更新Windows 11之后，TrafficMonitor被重叠了。  无论是居左或居中，都一样会被重叠。

### ISSUE THREAD

**Issue by NianBroken** [zhongyang219/TrafficMonitor#757]
在Dev渠道正式更新Windows 11之后，TrafficMonitor被重叠了。  无论是居左或居中，都一样会被重叠。
![比特截图2021-06-29-12-50-33](https://user-images.githubusercontent.com/57057288/123740155-8cb3dd00-d8da-11eb-8924-329560abe575.png)
![比特截图2021-06-29-12-50-46](https://user-images.githubusercontent.com/57057288/123740164-91789100-d8da-11eb-9d5f-e99c34abd8fb.png)

**Comment by thhyaa** [comment]
我也是，而且在win10时也已经出现了类似的情况

**Comment by CurtisWong458** [comment]
急啥，都还没出正式版

**Comment by DEabcdp** [comment]
+1

**Comment by mr-lv0861** [comment]
我也是难受，

**Comment by senobor** [comment]
确实

**Comment by yixiang666888** [comment]
+1

**Comment by jumpywin** [comment]
+1

**Comment by Enderwaiter** [comment]
给作者发了邮件，希望可以尽快修复qwq

**Comment by Enderwaiter** [comment]
> 急啥，都还没出正式版

其实是Dev通道被推送了 不然也不会这么着急就用

**Comment by liulangdecuan** [comment]
我主窗口打不开了，这个软件的配置文件在哪里

**Comment by Enderwaiter** [comment]
> 我主窗口打不开了，这个软件的配置文件在哪里

安装目录（默认路径的话就是Appdata）

**Comment by CurtisWong458** [comment]
> > 急啥，都还没出正式版
> 
> 其实是Dev通道被推送了 不然也不会这么着急就用



> > 急啥，都还没出正式版
> 
> 其实是Dev通道被推送了 不然也不会这么着急就用

https://github.com/zhongyang219/TrafficMonitor/issues/738

**Comment by etoyz** [comment]
+1

**Comment by Faintsnow** [comment]
+1

**Comment by Coco-king** [comment]
俺也一样

**Comment by yankq79** [comment]
看到大家都一样，我就放心了。

**Comment by sscco55** [comment]
不急不急,小场面.
建议看能不能把任务栏窗口做到日期和显示桌面的中间

**Comment by iluwgl** [comment]
俺也一样

**Comment by pdone** [comment]
俺也一样  不过看情况  这个问题貌似不太容易解决  任务栏逻辑貌似变了

**Comment by immccn123** [comment]
俺也一样
![issue1](https://user-images.githubusercontent.com/41335471/124114661-68edc400-da9f-11eb-9948-666922ebec09.jpg)

**Comment by zhangDand** [comment]
俺也一样

**Comment by BigDream324** [comment]
俺也一样

**Comment by ZetaSp** [comment]
[ZetaSp/TrafficMonitor](https://github.com/ZetaSp/TrafficMonitor) 我修好了
![Snipaste_2021-07-10](https://user-images.githubusercontent.com/36418285/125168796-c2f63400-e1d9-11eb-8680-04e9fa457d6c.png)
如果需要能选中就把 **背景透明** 关掉

**Comment by BigDream324** [comment]
> [ZetaSp/TrafficMonitor](https://github.com/ZetaSp/TrafficMonitor) 我修好了
> ![Snipaste_2021-07-10](https://user-images.githubusercontent.com/36418285/125168796-c2f63400-e1d9-11eb-8680-04e9fa457d6c.png)
> 如果需要能选中就把 **背景透明** 关掉

感谢!!! 可以正常使用了!!!

**Comment by mr-lv0861** [comment]
> [ZetaSp/TrafficMonitor](https://github.com/ZetaSp/TrafficMonitor) 我修好了
> ![Snipaste_2021-07-10](https://user-images.githubusercontent.com/36418285/125168796-c2f63400-e1d9-11eb-8680-04e9fa457d6c.png)
> 如果需要能选中就把 **背景透明** 关掉

可以可以很好用
