### ISSUE TITLE
不能智能识别当前所用网卡

### ISSUE THREAD

**Issue by kettly1260** [zhongyang219/TrafficMonitor#76]
我有线和WiFi都有数据连接，但当通过WiFi访问互联网的时候网速依旧显示的是有线的连接速度（事实上此时有线为内网），只有禁用有线才会显示WLAN的速度。建议可以自动识别或者增加全部网卡网速数据

**Comment by kettly1260** [comment]
由于我只显示了任务栏的网速工具，在右键的时候并没有网络连接的选项。只有依稀记得刚刚安装的时候看到了有一个选择网卡的功能，之后却怎么找都找不到了。希望可以把这个功能集成在菜单里面。
现在安装win10的人很多，只在任务栏显示网速很符合win10的显示效果，我觉得一定还有很大一部分人和我一样找不到切换网卡的位置

**Comment by zhongyang219** [comment]
@kettly1260 谢谢你的建议，我会考虑在任务栏窗口的右键菜单中增加“选择网络连接”的菜单顶。

**Comment by zhongyang219** [comment]
@kettly1260 另外，我已经增加了监控所有网络连接的网速的功能，请更新到1.74版本。

**Comment by kettly1260** [comment]
@zhongyang219 已经使用最新版，挺方便的说。谢谢开发大大提醒
