### ISSUE TITLE
很好用，未来会增加磁盘读写的监控么？

### ISSUE THREAD

**Issue by thanatos369** [zhongyang219/TrafficMonitor#764]
感觉加上磁盘读写监控就完美了

**Comment by zhongyang219** [comment]
看了一下Liberalhardwaremonitor有这个监控项，要加上的话不是很难

**Comment by thanatos369** [comment]
[作者你好，我下了预编译版本，但是无法显示磁盘设备。
![1](https://user-images.githubusercontent.com/1468135/126732622-ef35b217-b69e-40ca-8070-e7b875a129f6.png)
![2](https://user-images.githubusercontent.com/1468135/126732626-717e50be-129c-48bd-977d-d5a063373925.jpg)
