### ISSUE TITLE
Windows10下 状态栏文字错位

### ISSUE THREAD

**Issue by Fitye** [zhongyang219/TrafficMonitor#767]
![image](https://user-images.githubusercontent.com/63393725/124229872-c6186280-dafd-11eb-886c-ad5d2f8e86c0.png)

**Comment by Mr-Second** [comment]
有个解决方案：
1. 解除任务栏锁定
![1](https://user-images.githubusercontent.com/38907693/124353841-86579500-dc3b-11eb-9d13-05cbe3676e17.png)
2. 把任务栏往上拉一拉
3. 把任务栏往下拉还原就
4. 这个过程后文字的位置会恢复

**Comment by Fitye** [comment]
好的 感谢
