### ISSUE TITLE
温度显示异常

### ISSUE THREAD

**Issue by S15932807676** [zhongyang219/TrafficMonitor#769]
在正常使用下，
娱乐大师显示为37度，TrafficMonitor显示为77度。
以及其他温度也普遍偏高

**Comment by zhongyang219** [comment]
温度的问题请先参考 [常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)
