### ISSUE TITLE
希望增加GPU使用率监控

### ISSUE THREAD

**Issue by jakara** [zhongyang219/TrafficMonitor#77]

**Comment by ky0ncheng** [comment]
https://www.windowscentral.com/how-track-gpu-performance-data-windows-10

微軟幫你做了

**Comment by ky0ncheng** [comment]
@jakara 你行你提交代碼，私有 API 怎麼調也幫忙問下 M$

**Comment by zhongyang219** [comment]
@jakara 任务管理器能获取到GPU利用率并不代表普通开发者就可以通过编程来实现。Windows并不是个开源系统，Windows自带的任务管理器也不是开源的软件，我们无法知道微软是通过什么方式来获取GPU利用率的。正是因为Windows并非开源，对于我们这些Windows的程序员来说，我们无法直接操作硬件，所有对硬件的操作都必须通过微软提供的Windows API来实现。当然有些软件比如鲁大师等已经实现了这个功能，开发这些软件的大神们通过某种方法获取到了GPU利用率等信息，但是他们的软件也并非开源。我并非大神，如果要在我的软件中显示GPU利用率，只能使用微软或第三方的库和API。

**Comment by zhangenming** [comment]
> 取到GPU利用率并不代表普通开发者就可以通过编程

后台实时监控任务栏显存并ocr  开玩笑的

**Comment by zhongyang219** [comment]
GPU使用率监控的功能会在下个版本中到来，你也可以下载预构建版本体验。
