### ISSUE TITLE
配置文件保存到程序所在目录功能失效，且配置文件异常

### ISSUE THREAD

**Issue by LTHPKBTE** [zhongyang219/TrafficMonitor#770]
如题，打开了开机时自动运行功能，然后重启之后发现软件恢复了默认设置。程序所在目录的config.ini发现如下状况:
![图片](https://user-images.githubusercontent.com/53574505/124272881-ebdf4f00-db71-11eb-8f53-bde97ab77dbf.png)
文件一共4,631字节，但都是这样的内容。另外从修改时间来看确实是关机前的配置文件。
貌似是更新了V1.80.3之后出现的。更新方式是直接解压覆盖旧版更新。根目录下文件如下：
![图片](https://user-images.githubusercontent.com/53574505/124273479-a3746100-db72-11eb-8cac-130afbb43802.png)
error.log的内容：
2021/07/01 22:47:51.886: 检测到历史流量数据丢失，当前记录个数：1，已从备份文件恢复182条记录。

**Comment by LTHPKBTE** [comment]
global_cfg.ini:
[config]
portable_mode = false

**Comment by zhongyang219** [comment]
你这问题从来没遇到过，暂时不清楚是什么原因造成的。1.80.3并没有更改关于配置文件的代码。

**Comment by zhongyang219** [comment]
请问一下这个问题发生的频率怎么样？

**Comment by LTHPKBTE** [comment]
> 请问一下这个问题发生的频率怎么样？
发生了之后每次都会这样

**Comment by zhongyang219** [comment]
> > 请问一下这个问题发生的频率怎么样？
> 
> 发生了之后每次都会这样，一重启就变成了配置文件在系统文件夹里

把损坏的配置文件删除能解决问题吗？

**Comment by LTHPKBTE** [comment]
> 把损坏的配置文件删除能解决问题吗？

不能。

**Comment by zhongyang219** [comment]
读写配置文件的代码应该不会有问题，或许是配置文件被其他软件损坏了，另外检查一下你的电脑有没有被感染计算机病毒。

**Comment by LTHPKBTE** [comment]
我现在测试不了....
![图片](https://user-images.githubusercontent.com/53574505/128204768-07207074-b34d-497b-b416-b8ffe45a71d4.png)
win11这里就离谱（我把主窗口和任务栏图标都关了

**Comment by LTHPKBTE** [comment]
![图片](https://user-images.githubusercontent.com/53574505/128207478-cc03129f-7e33-480e-9097-cf5b0612be53.png)
![图片](https://user-images.githubusercontent.com/53574505/128207528-12a692b0-8a35-4888-82aa-0a1fbb0b9fd5.png)
貌似正常了？我重启试试

**Comment by LTHPKBTE** [comment]
正常了，谢谢关注
