### ISSUE TITLE
适配windows 11 任务栏错位

### ISSUE THREAD

**Issue by JiaRZ** [zhongyang219/TrafficMonitor#771]

**Comment by gxmandppx** [comment]
附议

**Comment by CaptainNemo000** [comment]
同样问题

**Comment by aecra** [comment]
+1

**Comment by Just-Prog** [comment]
https://github.com/zhongyang219/TrafficMonitor/issues/751#issuecomment-868321283

**Comment by 1400033236** [comment]
[https://sm.ms/image/4WAy8nzuFBZbd6S](url)
在截至今日dev最新windows11预览版使用时，如图，任务栏窗口不会固定在两侧而是和居中的图标重叠。
[https://sm.ms/image/JeOPqLfFt4skpTM](url)
任务栏图标居左放置时，窗口也会随之跑到左边与它重叠。。
[https://i.loli.net/2021/07/04/9mV5yBurQo1WC3I.png](url)
当在任务栏设置中开关“pen menu”时，任务栏窗口会短暂回到正确位置，但关闭设置又会失效。

不知道是不是win11的bug0.0

**Comment by Huadao1108** [comment]
+1

**Comment by jimmyk1m** [comment]
+1

**Comment by giterfor126** [comment]
哈哈哈哈哈  +1

**Comment by unicorn1009** [comment]
+1

**Comment by HzAlen** [comment]
+1 辛苦大佬兼容一下

**Comment by skyltl** [comment]
+1

**Comment by LeedyJon** [comment]
+1

**Comment by huanimal92** [comment]
+1

**Comment by wonchong** [comment]
+10086

**Comment by ZhouYingde** [comment]
+1

**Comment by aiko79849642** [comment]
+1

**Comment by Nagihiko-szz** [comment]
同情下大大
