### ISSUE TITLE
1.80.3 无法检测温度

### ISSUE THREAD

**Issue by byyxx128** [zhongyang219/TrafficMonitor#778]
在我电脑上最后一个可用的版本是 1.80.1，可以正常显示 CPU、硬盘温度。GPU 和主板温度检测不到，不过也无所谓，反正是笔记本。

但是，1.80.2、1.80.3 这两个版本，我就不能显示任何硬件的温度了。经过大量排除，最终确认，就是从 1.80.2 之后就不能检测硬件温度了。

我翻了下更新日志，1.80.2 中有一条：“获取温度信息改用LibreHardwareMonitor”，目前猜测可能和这个有关。但是我不确认，是程序对 LibreHardwareMonitor 的调用有误，还是仅仅不识别我的电脑。如果是后者，可能还要去给 LibreHardwareMonitor 反馈，或者换个检测组件。

**Comment by byyxx128** [comment]
补一下，根据此 [**提示**](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13)，我进一步检测如下——
![image](https://user-images.githubusercontent.com/20079289/124844665-7f2be080-dfc7-11eb-92af-439989ac9631.png)
如上图所示，我的 CPU、GPU、SSD 的温度均可正常检测，可见应该是 TrafficMonitor 的调用出现了问题。

**Comment by zhongyang219** [comment]
温度监控功能默认是关闭的，请问你打开温度监控功能了吗？

**Comment by Lost-f** [comment]
> 补一下，根据此 [**提示**](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13)，我进一步检测如下——
> ![image](https://user-images.githubusercontent.com/20079289/124844665-7f2be080-dfc7-11eb-92af-439989ac9631.png)
> 如上图所示，我的 CPU、GPU、SSD 的温度均可正常检测，可见应该是 TrafficMonitor 的调用出现了问题。

这是什么监控软件?

**Comment by Lost-f** [comment]
> 温度监控功能默认是关闭的，请问你打开温度监控功能了吗？

我2个硬盘, 主硬盘NVME识别空白, 副的SATA就正常, 这是怎么回事?

**Comment by byyxx128** [comment]
> 温度监控功能默认是关闭的，请问你打开温度监控功能了吗？

那当然打开了啊……我又不是第一次用……而且我都清清楚楚说了，1.80.1 之前版本我是可以的，1.80.2、1.80.3 我就不可以了，温度显示为`--`。我唯一想到的可能是，换了温度检测组件，恰好，1.80.2 就是换组件了。但是，我直接用 LibreHardwareMonitor 又可以获取到我的硬件温度，那么就很可能在调用上出现了问题。

**Comment by byyxx128** [comment]
> 温度监控功能默认是关闭的，请问你打开温度监控功能了吗？

那当然打开了啊……我又不是第一次用……而且我都清清楚楚说了，1.80.1 之前版本我是可以的，1.80.2、1.80.3 我就不可以了，温度显示为`--`。我唯一想到的可能是，换了温度检测组件，恰好，1.80.2 就是换组件了。但是，我直接用 LibreHardwareMonitor 又可以获取到我的硬件温度，那么就很可能在调用上出现了问题。

![image](https://user-images.githubusercontent.com/20079289/126039587-64286a16-7e9c-465a-ba96-74a5f85147a9.png)
![image](https://user-images.githubusercontent.com/20079289/126039601-53bf3fa7-6e62-4145-bb94-b9a000868c3f.png)
**上：1.80.1 👆
下：1.80.3 👇**
![image](https://user-images.githubusercontent.com/20079289/126039529-9fd32be0-90ad-4ddd-95a7-394ce281c07e.png)
![image](https://user-images.githubusercontent.com/20079289/126039747-ce71e116-15b7-4412-93a4-ba4a76193d07.png)
![image](https://user-images.githubusercontent.com/20079289/126039845-ae56d40a-0184-4730-818c-9faae04fad96.png)

**Comment by byyxx128** [comment]
> 这是什么监控软件?

你没认真读我图片上面的第一句话……

**Comment by byyxx128** [comment]
> 这是什么监控软件?

你没认真读我图片上面的第一句话……
https://github.com/zhongyang219/TrafficMonitor/issues/778#issuecomment-876026677

**Comment by zhongyang219** [comment]
> > 温度监控功能默认是关闭的，请问你打开温度监控功能了吗？
> 
> 那当然打开了啊……我又不是第一次用……而且我都清清楚楚说了，1.80.1 之前版本我是可以的，1.80.2、1.80.3 我就不可以了，温度显示为`--`。我唯一想到的可能是，换了温度检测组件，恰好，1.80.2 就是换组件了。但是，我直接用 LibreHardwareMonitor 又可以获取到我的硬件温度，那么就很可能在调用上出现了问题。
> 
> ![image](https://user-images.githubusercontent.com/20079289/126039587-64286a16-7e9c-465a-ba96-74a5f85147a9.png)
> ![image](https://user-images.githubusercontent.com/20079289/126039601-53bf3fa7-6e62-4145-bb94-b9a000868c3f.png)
> **上：1.80.1 👆 下：1.80.3 👇**
> ![image](https://user-images.githubusercontent.com/20079289/126039529-9fd32be0-90ad-4ddd-95a7-394ce281c07e.png)
> ![image](https://user-images.githubusercontent.com/20079289/126039747-ce71e116-15b7-4412-93a4-ba4a76193d07.png)
> ![image](https://user-images.githubusercontent.com/20079289/126039845-ae56d40a-0184-4730-818c-9faae04fad96.png)

温度监控功能在某些电脑中存在问题，因此从1.80.3版本开始默认关闭了温度监控功能。如果你不是特别想看电脑的温度，建议不要使用温度监控功能。如果你想使用温度监控功能，请确认“选项”-“常规设置”-“硬件监控”中对应的复选框处于勾选状态：
![image](https://user-images.githubusercontent.com/30562462/126040057-abcfbab4-d301-4ce9-9b9c-6c11f2a3e52a.png)
如果这里没有勾选，则任务右键菜单中“显示设置”对应的项目是灰色不可用的。

**Comment by zhongyang219** [comment]
如果你你的问题仍然不能被解决，建议你下载并安装Visual Studio 2019，然后下载TrafficMonitor的源代码，用Visual Studio 2019打开解决方案，打开OpenHardwareMonitorImp.cpp文件，在COpenHardwareMonitor::GetHardwareInfo()函数里设置一个断点，按F5启动调试，当断点中断后，按F10单步调试，查看变量的值，以确定问题的原因。

**Comment by zhongyang219** [comment]
很多用户反馈温度监控的问题很多，比如内存占用异常，甚至导致蓝屏死机的，我正在考虑要不要在下个版本是砍掉这个功能

**Comment by byyxx128** [comment]
>请确认“选项”-“常规设置”-“硬件监控”中对应的复选框处于勾选状态

勾选后亲测可用，除了主板温度之外都可以正确识别了，比之前 1.80.1 果然更加强大。

>如果你不是特别想看电脑的温度，建议不要使用温度监控功能

我是属于非常想看温度的啊！我机子散热不好，盯着温度我好知道什么时候需要加强通风。打开温度监控功能之后，越来越喜欢这个版本了。
![image](https://user-images.githubusercontent.com/20079289/126041238-76022273-b80d-4202-aff9-e48a6dab1c62.png)

>我正在考虑要不要在下个版本是砍掉这个功能

不要啊！我真的好喜欢这个功能的……要知道，出现问题的毕竟还是少数用户。想当年，Win10这么多bugs，微软不也没砍了嘛……不过可以这样——
1. 在首次启动时，弹出对话框，提示用户需要手动开启温度监控才可使用相关功能，并警告可能风险。
2. 温度监控功能加个总开关，每次打开这个总开关的时候，均提示可能的风险。
3. 继续分别发行带和不带温度组件的两个版本，和现在一样。
4. 如果有人反馈这方面的 issues，还是能修就修呗，可以优先级根据情况再看，但这么好的功能可别砍啊！
5. 大佬怎么也还没睡……😂

**Comment by byyxx128** [comment]
>请确认“选项”-“常规设置”-“硬件监控”中对应的复选框处于勾选状态

勾选后亲测可用，除了主板温度之外都可以正确识别了，比之前 1.80.1 果然更加强大。

>如果你不是特别想看电脑的温度，建议不要使用温度监控功能

我是属于非常想看温度的啊！我机子散热不好，盯着温度我好知道什么时候需要加强通风。打开温度监控功能之后，越来越喜欢这个版本了。
![image](https://user-images.githubusercontent.com/20079289/126041238-76022273-b80d-4202-aff9-e48a6dab1c62.png)

>我正在考虑要不要在下个版本是砍掉这个功能

不要啊！我真的好喜欢这个功能的……要知道，出现问题的毕竟还是少数用户。想当年，Win10这么多bugs，微软不也没砍了嘛……不过可以这样——
1. 在首次启动时，弹出对话框，提示用户需要手动开启温度监控才可使用相关功能，并警告可能风险。
2. 温度监控功能加个总开关，每次打开这个总开关的时候，均提示可能的风险。
3. 继续分别发行带和不带温度组件的两个版本，和现在一样。
4. 如果有人反馈这方面的 issues，还是能修就修呗，可以优先级根据情况再看，但这么好的功能可别砍啊！
5. 大佬你这个软件现在已经风靡全网了，你要是真把功能给砍了，那就太令人失望了……这么多网友盯着呢。

话说大佬怎么也还没睡……😂
