### ISSUE TITLE
升级windows 11后，出现任务栏显示问题，现在退回win10，任务栏还是回复不了

### ISSUE THREAD

**Issue by JiaRZ** [zhongyang219/TrafficMonitor#781]
![image](https://user-images.githubusercontent.com/32418843/125184657-28860700-e252-11eb-9b9a-669943636696.png)
如上图所示，有一段空白，卸载软件都不行

**Comment by soloopooo** [comment]
请关闭任务栏的 资讯与兴趣。

**Comment by JiaRZ** [comment]
已解决

**Comment by soloopooo** [comment]
请关闭issue。
