### ISSUE TITLE
TrafficMonitor for windows11，已配置好，运行就行

### ISSUE THREAD

**Issue by mjyhj** [zhongyang219/TrafficMonitor#782]
https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1895145&highlight=TrafficMonitor

看到远景上有人编译改了一个 适配了WIN11的版本，大家可以先用这个。

**Comment by soloopooo** [comment]
https://github.com/zhongyang219/TrafficMonitor/issues/780#issuecomment-877656448

还请尽量不要使用未知源码的编译二进制文件。
