### ISSUE TITLE
能不能添加显示网口速率，100Mbps/1

### ISSUE THREAD

**Issue by zwj4031** [zhongyang219/TrafficMonitor#783]
能不能添加显示网口速率，100Mbps/1Gbps之类的，非常有用

**Comment by 44886** [comment]
这个需要实时看么？？？你网口不稳定的吗？

**Comment by zwj4031** [comment]
有些场景需要看这个，百兆的就拔掉网线，日常维护

**Comment by byyxx128** [comment]
嗯，这个有一定需求，比如有时候水晶头没插好，千兆就变百兆了……不过这个功能系统级来实现似乎更好。

**Comment by zhongyang219** [comment]
连接详情里不是有速度吗
![image](https://user-images.githubusercontent.com/30562462/126052835-09858072-e546-466d-95fa-24e555486dd7.png)

**Comment by zwj4031** [comment]
> 连接详情里不是有速度吗
> ![image](https://user-images.githubusercontent.com/30562462/126052835-09858072-e546-466d-95fa-24e555486dd7.png)

是有，但这个软件显示的东西哪个系统里没有的？关键是显示在桌面。

**Comment by byyxx128** [comment]
楼主正解，这个小工具的意义就在于一眼望去一目了然，就好比仪表盘一样，随时可以看，而不是要费尽点开才能看。

**Comment by johnchen99** [comment]
同意，希望也可以先是在实时速度的旁边
