### ISSUE TITLE
程序长期运行占用大量虚拟内存导致系统崩溃？

### ISSUE THREAD

**Issue by cxw620** [zhongyang219/TrafficMonitor#784]
多次系统崩溃
查看事件管理器发现如下错误：
【弹出应用程序: TrafficMonitor.exe - 系统错误: 无法创建新的堆栈防护页面。】【Windows 成功诊断出虚拟内存不足的情况。以下程序使用了大部分虚拟内存: TrafficMonitor.exe (11072) 使用了 38064463872 字节】
是否是bug？

**Comment by soloopooo** [comment]
是有内存泄漏的问题，这个问题是老问题了

**Comment by CordyHo** [comment]
> 是有内存泄漏的问题，这个问题是老问题了

能修得好吗

**Comment by zhongyang219** [comment]
请问你是否开启了温度监控的功能呢，有可能是温度监控的功能导致的，因为我想不到我的代码里有哪些可能导致内存泄漏的地方，之前也没收到过类似的反馈。

**Comment by MAX-XiaoKui** [comment]
我有一点卡顿的情况，有时候就会突然系统卡住然后十几分钟之后才能恢复正常，有时候TrafficMonitor就崩溃了，会在%LocalAppData%\CrashDumps生成一个dmp文件
我关闭TrafficMonitor的时候没有任何问题
[TrafficMonitor.exe.12248.dmp.zip](https://github.com/zhongyang219/TrafficMonitor/files/6834189/TrafficMonitor.exe.12248.dmp.zip)

**Comment by soloopooo** [comment]
> 请问你是否开启了温度监控的功能呢，有可能是温度监控的功能导致的，因为我想不到我的代码里有哪些可能导致内存泄漏的地方，之前也没收到过类似的反馈。

这种疑似内存泄漏反馈我记得在几个月前有过几次，看看之前的相关issue

**Comment by soloopooo** [comment]
> > 请问你是否开启了温度监控的功能呢，有可能是温度监控的功能导致的，因为我想不到我的代码里有哪些可能导致内存泄漏的地方，之前也没收到过类似的反馈。
> 
> 这种疑似内存泄漏反馈我记得在几个月前有过几次，看看之前的相关issue

找到了
#716

**Comment by cxw620** [comment]
是的，开启了温度监控。

**Comment by zhongyang219** [comment]
> 是的，开启了温度监控。

温度监控的功能确实在很多电脑中存在问题，建议把它关闭不要使用

**Comment by cxw620** [comment]
似乎关掉CPU的温度监控就没什么问题了，只开启GPU的，内存11MB

**Comment by Ndministrator** [comment]
是的,我也发现来了内存泄漏.但是之前用的一款叫做Radar(软媒魔方上摘出来的某个监控模块)的监控软件,也开启了温度监控,但是它家貌似就没有内存泄漏的问题,不知道人家怎么实现的. @zhongyang219
