### ISSUE TITLE
任务栏窗口错位

### ISSUE THREAD

**Issue by Carlos920** [zhongyang219/TrafficMonitor#786]
隐藏通知区域图标后，某些情况下会出现任务栏窗口错位
![Snipaste_2021-07-16_10-29-30](https://user-images.githubusercontent.com/32257015/125882587-7975d3a2-fce0-4bd2-a72d-6e9fa74becbb.png)
重新显示通知区域图标才会恢复正常（或者重开软件）

```
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎3/‎17
操作系统内部版本	19043.1083
体验	Windows Feature Experience Pack 120.2212.3530.0

```

**Comment by zhongyang219** [comment]
这个是老问题了，目前也一直找到一个好的解决办法，但是这并不是一个严重的问题，你只需要把通知区的任意一个图标向上拖动将其隐藏，再拖下来就好了。请参照 [常见问题-任务栏窗口有时会显示不全，比如单位被覆盖了](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#10-%E4%BB%BB%E5%8A%A1%E6%A0%8F%E7%AA%97%E5%8F%A3%E6%9C%89%E6%97%B6%E4%BC%9A%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%85%A8%E6%AF%94%E5%A6%82%E5%8D%95%E4%BD%8D%E8%A2%AB%E8%A6%86%E7%9B%96%E4%BA%86)
