### ISSUE TITLE
请问如何设置这个双列的排序？比如我想把上面一行全部都放使用率，下面一行全部放置温度

### ISSUE THREAD

**Issue by CrazyDoge666** [zhongyang219/TrafficMonitor#789]
![image](https://user-images.githubusercontent.com/36259181/126080113-9fca2b21-37c7-485a-a755-3c0df8a6f972.png)

**Comment by soloopooo** [comment]
https://github.com/zhongyang219/TrafficMonitor/actions/runs/1042134999

**Comment by CrazyDoge666** [comment]
> https://github.com/zhongyang219/TrafficMonitor/actions/runs/1042134999
x64_20210718_172615_TrafficMonitor
我试了这个没有发现有自定义排序选项。也尝试过按照不同顺序开启显示但是依然不会排序

**Comment by soloopooo** [comment]
粗略看了下代码，预购建版本目前只能通过修改ini配置文件自定义排序

**Comment by zhongyang219** [comment]
已经添加排序功能，请等待下个版本更新，或者下载预构建版本体验
