### ISSUE TITLE
win10   1803启动不了

### ISSUE THREAD

**Issue by cuiyubao** [zhongyang219/TrafficMonitor#79]
win10   1803启动不了，无论是管理运行还是其他，都不行

**Comment by zhongyang219** [comment]
什么叫启动不了，能详细描述一下吗？

**Comment by ktmsobs** [comment]
我也是1803的系统，能正常运行

**Comment by greyair** [comment]
1803可以正常运行

**Comment by song195617** [comment]
我的情况一样，开机自启不了，没有悬浮窗、没有任务栏图标、没有任务栏显示，手动启动（包括管理员模式启动）也不会开启软件，就跟没点过软件一样，最近几天才出的问题，但是我半个月前就更新1803了。

**Comment by cuiyubao** [comment]
我的最新的软件版本是不行的，就像上面说的“就像没有点一样”，不过换之前的上一个版本就可以了，不更新就可以使用

**Comment by cuiyubao** [comment]
的确是   把 C:\Users\jade\AppData\Roaming\TrafficMonitor目录下的文件清除就能启动了

**Comment by zhongyang219** [comment]
@song195617 @cuiyubao 这个问题我也很难解决，由于我无法在自己的电脑上重现你们的问题，我无法知道你们的电脑上到底发生了什么。之前版本配置文件是保存在程序所在目录下，由于有很多网友反馈出现无法保存设置的问题，所以这次就改到C:\Users\用户名\AppData\Roaming\下面，然后又出现了你们说的问题。

**Comment by zhongyang219** [comment]
@cuiyubao 如果你把C:\Users\用户名\AppData\Roaming\TrafficMonitor\config.ini删除就能正常启动了，说明通过调查config.ini文件也许就能找到问题所在，你能不能帮我测试一下，在程序无法正常启动时，把config.ini备份，再将其删除，此时再把备份的config.ini和新生成的config.ini对比一下。或者你把你程序不能启动时备份的config.ini发一份给我，看看我能不能重现你的问题。

**Comment by zhongyang219** [comment]
根据一个网友提供的配置文件，这个问题已经找到了，我也找到了重现步骤：勾选“显示任务栏窗口”，勾选“鼠标穿透”，在任务栏窗口右键菜单上去掉“显示通知区图标”，退出，再次启动程序就会挂。
暂时的解决方法是：将config.ini中show_notify_icon一项改成1，并且暂时不要在开启鼠标穿透的情况下隐藏通知区图标。这个问题已经解决，会在下次更新中修正，我很快就会更新，请耐心等待。
这其实是一个比较低级的错误，是我的疏忽造成的，有兴趣的可以[点击这里](https://github.com/zhongyang219/TrafficMonitor/commit/1eb70db4577bb6b0b7b529763e5b2e05a6f516c7)查看代码。
