### ISSUE TITLE
win10LTSC CPU显示为4倍实际占用

### ISSUE THREAD

**Issue by dragon0629** [zhongyang219/TrafficMonitor#790]

**Comment by dragon0629** [comment]
系统：WIN10 LTSC
CPU： I3 4130 双核四线程
版本：1.80.3
问题：观察资源监视器，悬浮框显示的CPU占用一直是实际的大约4倍
![image](https://user-images.githubusercontent.com/29683336/126105264-906cf165-cd88-4e54-a5cd-5c7f6e5f4789.png)
虽然截图是静止画面，但实际观察基本都是4倍样子

**Comment by soloopooo** [comment]
![image](https://user-images.githubusercontent.com/36123081/126105398-1f224475-4cff-4537-9772-8f18bbabde60.png)

**Comment by dragon0629** [comment]
谢谢，看了半天才发现这个，默认感觉还是直接基于性能好点
感恩！
