### ISSUE TITLE
CPU显示和任务管理器中的CPU占用率不一致

### ISSUE THREAD

**Issue by LuBarry** [zhongyang219/TrafficMonitor#792]

**Comment by zhongyang219** [comment]
请参照[常见问题-CPU利用率显示和任务管理器不一致](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#12-cpu%E5%88%A9%E7%94%A8%E7%8E%87%E6%98%BE%E7%A4%BA%E5%92%8C%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86%E5%99%A8%E4%B8%8D%E4%B8%80%E8%87%B4)
