### ISSUE TITLE
切换到一个新的未连接过的Wifi热点时,TrafficMonitor会报错

### ISSUE THREAD

**Issue by leewinq** [zhongyang219/TrafficMonitor#793]
操作步骤:
1、设置TrafficMonitor为开机启动；
2、开机启动后，无线网卡默认连接到一个常用wifi热点A（假定SSID名称为A）;
3、TrafficMonitor也正常启动了，并开始显示上行下行实时网速；
4、一段时间后，打开无线连接管理线，连接一个新的WiFi热点（以前从未连接过的），输入密码，连接；
5、此时，TrafficMonitor会弹出一个置顶窗体，报错！
由于报错时，未及时截图，当下，检索到的wifi热点均已连接过了，再次切换这种已连接过的wifi热点，似乎没有报错了。

**Comment by zhongyang219** [comment]
1.80开始的版本确实存在一些崩溃的问题，现在应该已经解决了，你可以到[Actions页面](https://github.com/zhongyang219/TrafficMonitor/actions)下载预构建的版本，看看问题是否解决。
