### ISSUE TITLE
硬件识别不了

### ISSUE THREAD

**Issue by yudi126** [zhongyang219/TrafficMonitor#796]
反馈：Intel(R) Iris(R) Xe Graphics 显卡，SAMSUNG MZVLB512HBJQ-000L2 SSD，识别不了

**Comment by zhongyang219** [comment]
请参照[常见问题-关于TrafficMonitor温度监控的问题](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by yudi126** [comment]
谢谢回复！
请问现在预览版不能下载了吗

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年7月25日 19:44
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [zhongyang219/TrafficMonitor] 硬件识别不了 (#796)


请参照常见问题-关于TrafficMonitor温度监控的问题<https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#13-%E5%85%B3%E4%BA%8Etrafficmonitor%E6%B8%A9%E5%BA%A6%E7%9B%91%E6%8E%A7%E7%9A%84%E9%97%AE%E9%A2%98>

―
