### ISSUE TITLE
状态栏模式下显示内容是置顶而不是居中

### ISSUE THREAD

**Issue by iceunlim** [zhongyang219/TrafficMonitor#8]
我使用的是单状态栏模式，环境是dpi125% win10。
内容是贴近状态上的上边界的，我希望能够改成上下居中，请问有什么方法可以实现吗？

**Comment by zhongyang219** [comment]
@iceunlim 你好，没太看懂你描述的问题，我把dpi调成125%之后似乎一切正常，你能否发个截图上来看看？

**Comment by iceunlim** [comment]
好尴尬，我任务栏是纯黑的，因此把显示屏的黑边也误以为是任务栏的一部分了23333@zhongyang219
