### ISSUE TITLE
能否增加带秒的时间显示

### ISSUE THREAD

**Issue by digiant** [zhongyang219/TrafficMonitor#801]
Win11任务栏时间没法显示秒，能否为软件增加此功能？

**Comment by soloopooo** [comment]
放哪？
不是人人都有超宽屏的

**Comment by digiant** [comment]
> 
> 
> 放哪？
> 不是人人都有超宽屏的

可以直接选择显示网速或者时间，最好带周几和农历

**Comment by byyxx128** [comment]
### 这个最好还是给 Windows 去反馈吧。第三方软件即使能做，意义也不大，而且也只能少数人用上，还可能有各种各样的问题。

### 请直接去反馈中心反馈。啊对了，你不要开新反馈，点赞就行了。

# [👉点这里👈](https://aka.ms/AAd8div)
![image](https://user-images.githubusercontent.com/20079289/127428865-41628779-9a50-487e-99f0-0f400cd74eee.png)

**Comment by zhongyang219** [comment]
我并不考虑在Trafficmonitor中添加这个功能
