### ISSUE TITLE
TrafficMonitor_V1.81_x64这个版本好像自启动失效了吗？

### ISSUE THREAD

**Issue by zhougjstudy** [zhongyang219/TrafficMonitor#802]
这个版本好像自启动失效了吗？我在选项中已经设置了开机启动了，但无效

**Comment by WSQAQ** [comment]
我也是 突然自启动失效

**Comment by microchitose** [comment]
确实无效了，你可以做个快捷方式放在C:\Users\用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup文件夹里

**Comment by lfm09** [comment]
我这测试自启动没失效啊，不过这个版本在CPU高占用时（比如火狐同时打开多个页面），网速信息更新不及时、反应卡顿，在旧电脑上比较明显。之前1.80.x，以计划任务启动的话也有这个问题，但手工运行的则正常。（系统Win10 x64）

被这个问题折腾烦了，只好暂时用回1.79.1。

**Comment by zhougjstudy** [comment]
> 确实无效了，你可以做个快捷方式放在C:\Users\用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup文件夹里

Start Menu在Windows目录下我没找到，不知道为什么。

**Comment by zhongyang219** [comment]
开机自启动的问题请先参照这里：[常见问题-设置了开机自动运行仍然无法开机自启](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#3-%E8%AE%BE%E7%BD%AE%E4%BA%86%E5%BC%80%E6%9C%BA%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C%E4%BB%8D%E7%84%B6%E6%97%A0%E6%B3%95%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
另外，开机无法自启动的一个常见原因是你可能移动了TrafficMonitor主程序的位置。如果你为TrafficMonitor设置好了开机自动运行，但是你将TrafficMonitor移动到了其他位置，那么开机自启动肯定就失效了。你需要打开TrafficMonitor的“选项设置”——“常规设置”，如果“开机时自动运行”处于勾选状态，先去掉勾选，然后再次打开“选项设置”——“常规设置”，重新勾选“开机时自动运行”即可。

**Comment by zhongyang219** [comment]
> 我这测试自启动没失效啊，不过这个版本在CPU高占用时（比如火狐同时打开多个页面），网速信息更新不及时、反应卡顿，在旧电脑上比较明显。之前1.80.x，以计划任务启动的话也有这个问题，但手工运行的则正常。（系统Win10 x64）
> 
> 被这个问题折腾烦了，只好暂时用回1.79.1。

@lfm09 你可以试试这个版本：https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.81/TrafficMonitor_V1.81_x64_without_temperature.zip

**Comment by zhougjstudy** [comment]
> 开机自启动的问题请先参照这里：[常见问题-设置了开机自动运行仍然无法开机自启](https://github.com/zhongyang219/TrafficMonitor/blob/master/Help.md#3-%E8%AE%BE%E7%BD%AE%E4%BA%86%E5%BC%80%E6%9C%BA%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C%E4%BB%8D%E7%84%B6%E6%97%A0%E6%B3%95%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
> 另外，开机无法自启动的一个常见原因是你可能移动了TrafficMonitor主程序的位置。如果你为TrafficMonitor设置好了开机自动运行，但是你将TrafficMonitor移动到了其他位置，那么开机自启动肯定就失效了。你需要打开TrafficMonitor的“选项设置”——“常规设置”，如果“开机时自动运行”处于勾选状态，先去掉勾选，然后再次打开“选项设置”——“常规设置”，重新勾选“开机时自动运行”即可。

成功了，谢谢啦

**Comment by lfm09** [comment]
> 
> 
> > 我这测试自启动没失效啊，不过这个版本在CPU高占用时（比如火狐同时打开多个页面），网速信息更新不及时、反应卡顿，在旧电脑上比较明显。之前1.80.x，以计划任务启动的话也有这个问题，但手工运行的则正常。（系统Win10 x64）
> > 被这个问题折腾烦了，只好暂时用回1.79.1。
> 
> @lfm09 你可以试试这个版本：https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.81/TrafficMonitor_V1.81_x64_without_temperature.zip

刚试过了，这个版本既不带硬件监控，默认也不是通过任务计划来自启动，没有问题。

而1.81带硬件监控（通过任务计划实现自启动）的版本测试情况如下：
1、硬件监控中勾选“硬盘”，不管是否自启动，都存在这个问题；
2、关闭硬件监控，关闭自启动，一切正常；
3、自启动打开（任务计划里显示状态为“正在运行”），不管是否启用硬件监控，都存在这个问题。

另外，用任务计划方式自启动1.79.1或1.81不带硬件监控的版本，发现也存在同样的问题。

**Comment by BluePointLilac** [comment]
我这边也有问题，有时能启动，有时不能启动。在非管理员非任务计划程序的旧版本里面是完全没这种问题的，程序位置一直不变的

**Comment by BluePointLilac** [comment]
我大概知道是什么Bug了，我现在经常性的不能启动，因为我只开启了任务栏窗口，我猜测是任务计划程序的优先级过高，在任务栏还没建立完成时，程序窗口找不到任务栏错误中止了。而当我现在开启了桌面窗口时，是没有遇到不能重启的情况，建议老哥代码改成延时启动试试。 @zhongyang219

**Comment by caliban511** [comment]
同样遇到类似问题，，，貌似也不是不启动，而是启动失败，，，有的时候在后台可以看到进程，但任务栏上没有显示；有时候连进程也看不到，完全启动失败，，，
