### ISSUE TITLE
历史流量数据统计数据丢失，且数据异常。

### ISSUE THREAD

**Issue by yafovo** [zhongyang219/TrafficMonitor#805]
版本1.81 x64  不含温度监控版本。
更新到新版本后，这电脑上历史流量数据丢失，数据异常。
发不了图片 我识别文字了 发出来
——————————————————————————
列表视图日历视图
统计方式: 日视图  图表显示比例:线性比例
日期 上传 下载
总流量|图表
2021/08/01 (日)
16 KB 6 KB 22 KB
2021/07/30 (五)
12.61 MB 168.84 MB 181.45 MB
2021/07/29 (四)
90.19 MB 565.10 MB 655.29 MB
2021/03/07 (日)
7 KB 20 KB 27 KB
2021/03/06 (六)
3.45 MB 118.99 MB 122.43 MB]
2021/03/05五)
67.38 MB 729.17 MB 796.55 MB
————————————————————————————
这电脑用了1年多的历史数据，只有这一点了，统计的也有异常，软件一直是开启自启的，以前都很正常。比如说昨天7月31号，流量统计正常运行，但是没有统计数据。
更新新版本后出现的，或者硬盘数据有损坏？ 其他人有这问题吗？

**Comment by yafovo** [comment]
原因已经找到，这不是BUG，是我电脑存在多个TrafficMonitor引起的，我以为这软件在D盘，实际自动自动启动的是E盘的TrafficMonitor，数据保存在程序所在目录。

**Comment by yafovo** [comment]
还是今天早上检查软件更新的时候发现有点不对，才发现的，抱歉了，麻烦删掉这个帖子吧

**Comment by zhongyang219** [comment]
你可以用记事本打开两个history_traffic.dat文件，把里面的内容合并在一起，软件启动读取这个文件时会自动合并相同日期的流量并自动排序。
