### ISSUE TITLE
任务栏空出了一大片

### ISSUE THREAD

**Issue by HumbleCoderX** [zhongyang219/TrafficMonitor#808]
Windows10
10.0.19043 21H1
V1.81

任务栏空出一大片，重启资源管理器无效，开机一出来就是空出这么多
![image](https://user-images.githubusercontent.com/44768142/128000369-4d6f05b2-49a1-4d40-bcd5-006096bbbd2f.png)
![image](https://user-images.githubusercontent.com/44768142/128000531-b189ceac-f545-4b6a-b6a7-5fa1a25b6705.png)

**Comment by soloopooo** [comment]
关闭资讯与兴趣。#734
