### ISSUE TITLE
任务栏网速显示调整

### ISSUE THREAD

**Issue by login404** [zhongyang219/TrafficMonitor#809]
网速在大于10KB/s时小数点后会精简为1位
当设置数据宽度为4 单位字节自动换算时
宽度仅会在1000-1023KB/s时才能填满
然而大多数时候网速都不会稳定在这23之间
有1字符的预留宽度长时间都是闲置的
无法有效利用 在右对齐时尤其明显
应修改为仅在网速大于1000KB/s
且单位未被换算时 才将小数点后精简为1位

**Comment by yafovo** [comment]
没看太懂，按你说的 假如网速在3位数的时候后 是不是该显示为366.6K/s

**Comment by yafovo** [comment]
没有这个必要 ，显的过于复杂了

**Comment by login404** [comment]
> 没看太懂，按你说的 假如网速在3位数的时候后 是不是该显示为366.6K/s

3位数时应该显示为366.60KB/s
现在是只有单位是KB的时候
小数位数才会被精简
也就是3位数显示366.6KB/s
如果单位不是KB就不会精简
例如MB会显示为366.60MB/s
只有KB这个单位行为不一致
