### ISSUE TITLE
建议加个【应用】按钮，点击后不会关闭选项框

### ISSUE THREAD

**Issue by lingyired** [zhongyang219/TrafficMonitor#814]
现在点击确定后选项框就消失了，而经常都是还有别的改动要改。

【应用】按钮的好处是，我修改了选项之后，点击应用可以直接看修改后的结果，如果不满意还可以再改。

现在每次点确定，都要重新去打开这个选项框

**Comment by zhongyang219** [comment]
已经添加，请更新到最新版本
