### ISSUE TITLE
任务栏透明背景下，文字边缘出现白点边缘

### ISSUE THREAD

**Issue by coderwaves** [zhongyang219/TrafficMonitor#837]
任务栏设置透明，文字出现类似抠图未扣干净情况
![Snipaste_2021-09-04_23-23-19](https://user-images.githubusercontent.com/36513983/132099665-ed4a38ba-3556-4bd2-8285-f06f69782b4c.png)

**Comment by CoderWaves** [comment]
跟换字体也是一样效果

**Comment by soloopooo** [comment]
现阶段trafficmonitor对任务栏透明后的透明显示效果特别差。看透明效果应该是将整体颜色做减淡，这样在这种背景下
![image](https://user-images.githubusercontent.com/36123081/132942008-c34da147-d911-4e7f-b04f-24c45a97a4ab.png)
显示就非常淡（背景原颜色为#000）。而单纯更改字体颜色又行不通，因为字体颜色也做了减淡处理，导致深色字体甚至显示效果不如浅色。
