### ISSUE TITLE
Dism++清理缩略图缓存重启explorer后任务栏刷新时间延长且窗口右移

### ISSUE THREAD

**Issue by 4dmini** [zhongyang219/TrafficMonitor#839]
![image](https://user-images.githubusercontent.com/61727188/132429588-23f8e617-c37f-4b57-bf98-5776d2d666f7.png)

**Comment by Twinkl4** [comment]
系统重启后才能恢复

**Comment by Twinkl4** [comment]
![image](https://user-images.githubusercontent.com/61727188/132430132-33c2b167-a7ce-47ab-b910-84e5f9ca4063.png)
关闭输入指示后恢复正常
