### ISSUE TITLE
Windows 10 1803 经常无故自动退出

### ISSUE THREAD

**Issue by Villivateur** [zhongyang219/TrafficMonitor#84]
没有任何征兆，也没有错误提示，程序就自动停止，再次打开一切正常

**Comment by zhongyang219** [comment]
很抱歉，这个问题已经解决，我很快就会更新，请耐心等待。这个问题是“连接详情”对话框引起的，在下一个版本更新之前，请暂时尽量避免打开“连接详情”对话框。

**Comment by Villivateur** [comment]
您好，我在安装完Windows 10 1803 最新的更新包（KB4284848）以后，无故自动停止的情况复现。仍然没有错误提示。

**Comment by zhongyang219** [comment]
请问你使用的是最新的1.74版本吗？

**Comment by zhongyang219** [comment]
请问你这个问题是偶尔出现还是每次出现？我也安装了KB4284848但是没有出现自动退出的问题。如果你出现了这个问题，可能程序还存在潜在的bug，但是跟之前版本中自动退出的问题无关，因为之前的问题已经被修正了。

**Comment by Villivateur** [comment]
使用的是最新版
详情请见
https://github.com/zhongyang219/TrafficMonitor/issues/97
