### ISSUE TITLE
Win7托盘显示问题

### ISSUE THREAD

**Issue by lambggy** [zhongyang219/TrafficMonitor#85]
Win7在任务栏显示托盘图表正常，如果隐藏在任务栏显示图标，则显示为空白。
![tim 20180617170749](https://user-images.githubusercontent.com/18274333/41506500-90415f4e-7251-11e8-897e-f4848cef7d1d.png)

**Comment by zhongyang219** [comment]
那个不是空白啊，因为图标是白色的。那个图标是可以更换的，在右键菜单中选择“更多功能”——“更换通知区图标”可以更换图标。

**Comment by zhongyang219** [comment]
@lambggy 不过我也在考虑将win7下的默认图标改成蓝色的图标。
