### ISSUE TITLE
使用1.7.4 遇见的现象

### ISSUE THREAD

**Issue by nonono33333** [zhongyang219/TrafficMonitor#86]
系统 win10 ltsb 2016 x64
         win7 x64

 win10使用时（vbox虚拟机） 设置的任务栏在桌面右侧  当任务栏更改到下面的时候  无法显示软件如图

 win7 挪动任务栏则可正常显示

设置任务栏字体大小问题：
以前1.7.3 可以在任务栏使用15大小的字体 且不粘连在一起
现在1.7.4 使用15大小字体时 粘连在一起（希望可以使用15大小字体时不粘连）  
![1 7 3 15](https://user-images.githubusercontent.com/18210895/41507054-bce1238a-725c-11e8-9c33-a5a8be60d7a3.png)
![1 74 15](https://user-images.githubusercontent.com/18210895/41507055-bd89b70c-725c-11e8-9535-240df4045ac9.png)
![win10 ltsb 2016](https://user-images.githubusercontent.com/18210895/41507056-be2c4d50-725c-11e8-85e7-b5a67179d856.gif)

**Comment by zhongyang219** [comment]
@nonono33333 抱歉，是我不小心把任务栏窗口高度调小了一个像素，导致这个问题，下次更新我会改回来。
