### ISSUE TITLE
win11，TrafficMonitor 任务栏窗口不支持右键菜单

### ISSUE THREAD

**Issue by sanmaodo** [zhongyang219/TrafficMonitor#860]
如题，在TrafficMonitor任务栏窗口上点击鼠标右键，不会弹出TrafficMonitor右键菜单，所以，必须要保持主托盘图标存在，否则无法操控。

**Comment by LightAPIs** [comment]
目前暂时可以关闭"背景透明"来解决。

**Comment by fjj739964256** [comment]
我汇总一下亲测可行的解决办法。操作步骤：
1、首先完全关闭TrafficMonitor应用程序（进入任务管理器，结束”流量监控器“任务）；
2、用文件编辑器（notepad或者记事本）打开软件目录（或者Appdata文件夹）的配置文件”config.ini“，搜索”show_notify_icon“，将”false“改成”true“，保存，关闭文件；
3、运行TrafficMonitor，就能看到任务栏的图标，右击图标，打开”选项“，选择”任务栏窗口设置“，将”背景透明“取消勾选。保存后，开始栏的网速显示位置就能右击出菜单了。
![Snipaste_2021-10-16_14-57-21](https://user-images.githubusercontent.com/33320479/137577274-5f6272d4-7c39-4bd6-ac8f-a49e4af8b8e5.jpg)

**Comment by sanmaodo** [comment]
期待！！！

**Comment by DavidChou92** [comment]
期待！！！

**Comment by DavidChou92** [comment]
稳定版22000.318已经解决这个问题了
