### ISSUE TITLE
与StartAllBack冲突求解决

### ISSUE THREAD

**Issue by yejinson** [zhongyang219/TrafficMonitor#863]
开启任务栏窗口内容显示不全，如果勾选显示在任务栏的左侧可以正常显示但显示在左端不好用，之前有网友反馈过同样的问题，求解决非常感谢。

**Comment by mjyhj** [comment]
![1](https://user-images.githubusercontent.com/22577418/136614979-7271996a-f3e6-4426-83fb-ba411185557d.png)
打开StartAllBack后，我的网速显示偏右了，右边一部分看不到

**Comment by suheandzl** [comment]
在我这里直接没法显示在任务栏了 如果可以的话希望作者大佬能看看解决一下 谢谢

**Comment by yejinson** [comment]
> ![1](https://user-images.githubusercontent.com/22577418/136614979-7271996a-f3e6-4426-83fb-ba411185557d.png) 打开StartAllBack后，我的网速显示偏右了，右边一部分看不到

我的只显示上下两个箭头其他啥都看不到
![Snipaste_2021-10-09_15-01-42](https://user-images.githubusercontent.com/73937339/136648066-d9e33841-7040-4e1b-8d27-0600a48cc575.png)

**Comment by microka** [comment]
因为这个问题，我暂时选择了“主窗口”，取消了“任务栏窗口”。

**Comment by Blueapple76** [comment]
使用V1.80.3版本正常，暂不要更新

**Comment by Blueapple76** [comment]
> 每天都来看一下，一周了都没新版本啊，求更新
使用V1.80.3版本正常，暂不要更新

**Comment by u2shana** [comment]
> > 每天都来看一下，一周了都没新版本啊，求更新
> > 使用V1.80.3版本正常，暂不要更新

还真的是,前一个版本显示正常,感谢告知

**Comment by Rimliya** [comment]
我也在等解决，总不能一直1.80.3

**Comment by Cyclonekid** [comment]
确实·    1.80.3在StartAllBack上显示正常，更新到后面，不管是发布版本  还是dev的构建版本·   都不正常后了·

**Comment by Cyclonekid** [comment]
经过摸索可以了，关闭StartAllBack的任务栏增强模式后，1.81及最新的构建版本都可以正常使用了·
![image](https://user-images.githubusercontent.com/17697818/143408458-4088b9e5-6e40-4f3f-b9e5-28b5f5a6bc0e.png)

**Comment by zhucaidan** [comment]
> 经过摸索可以了，关闭StartAllBack的任务栏增强模式后，1.81及最新的构建版本都可以正常使用了·
> 
> ![image](https://user-images.githubusercontent.com/17697818/143408458-4088b9e5-6e40-4f3f-b9e5-28b5f5a6bc0e.png)
> 
> ![image](https://user-images.githubusercontent.com/17697818/143408564-f215a527-3abd-4845-ab17-acf3cd42b807.png)
> 
> 

我这装startallback就是为了任务栏还原回win10一样啊😂

**Comment by Rimliya** [comment]
> 

你关掉这个，那startallback的存在意义就没了啊。。。

**Comment by Cyclonekid** [comment]
没有啊·   关闭这个只是关闭了任务栏右侧的图标的经典机制·  其他的都还正常·····
![image](https://user-images.githubusercontent.com/17697818/143409367-38d8440a-1492-4685-8879-1f3a8684ecfa.png)

**Comment by Rimliya** [comment]
> 没有啊· 关闭这个只是关闭了任务栏右侧的图标的经典机制· 其他的都还正常····· ![image](https://user-images.githubusercontent.com/17697818/143409367-38d8440a-1492-4685-8879-1f3a8684ecfa.png)

我能接受win11的新版开始，但是我需要任务栏靠右

**Comment by zhucaidan** [comment]
> 没有啊·   关闭这个只是关闭了任务栏右侧的图标的经典机制·  其他的都还正常·····
> 
> ![image](https://user-images.githubusercontent.com/17697818/143409367-38d8440a-1492-4685-8879-1f3a8684ecfa.png)
> 
> 
> 
> 
> 
> 

你关了能和win10一样满了再合并显示成图标？能拖动文档到任务栏打开的程序中载入文件？

**Comment by Cyclonekid** [comment]
好吧·  那是需求不一样·  我偏偏不喜欢任务栏满了合并图标，我喜欢直接显示图标········

**Comment by yejinson** [comment]
> 使用V1.80.3版本正常，暂不要更新
谢谢已使用旧版本

**Comment by zhongyang219** [comment]
这个问题已经解决，请更新到最新的1.82版本。

**Comment by yejinson** [comment]
> 这个问题已经解决，请更新到最新的1.82版本。

确实可以了，谢谢辛苦了。
