### ISSUE TITLE
可否参考火绒的网速监控？

### ISSUE THREAD

**Issue by AyunZ** [zhongyang219/TrafficMonitor#867]
可以看到每个程序的上传下载速度，可以看到每个程序的具体连接情况，可以对某个程序限速。

**Comment by byyxx128** [comment]
能做到但没必要，任务管理器就能干这个事了。

**Comment by taoletsgo** [comment]
那只能建议用火绒，不明白现在为什么还有限速需求，带宽100M都没的嘛；每个程序链接情况推荐你直接任务管理器，或者clash（能访问github的，不会不用这个吧，不会吧不会吧）

**Comment by xushet** [comment]
这没有这么大权限限制别的程序网速吧
