### ISSUE TITLE
任务栏的显示一闪一闪

### ISSUE THREAD

**Issue by ding-sir** [zhongyang219/TrafficMonitor#87]
我的是win10教育版1803，在微信有消息来的时候，微信显示在任务栏右侧没有隐藏的时候，微信一闪一闪，这个显示的也跟着一闪一闪的

**Comment by zhongyang219** [comment]
可是我并没有出现你描述的情况。

**Comment by zuilintan** [comment]
的确有闪动的问题,像资源管理器刷新一样
