### ISSUE TITLE
Show Mouse Tooltip in Taskbar window

### ISSUE THREAD

**Issue by z1nc0r3** [zhongyang219/TrafficMonitor#888]
In Taskbar Windows Settings, "mouse tooltip" is not working. Also "Double click action", "Resource usage graph" are not working. Can I see the daily or monthly data usage using mouse over tooltip?

**Comment by soloopooo** [comment]
you can trying disable the background transparent to solve this.

**Comment by z1nc0r3** [comment]
@soloopooo Thank you. Unticking "Background transparent" fixed the problem.

**Comment by soloopooo** [comment]
This bug was fixed in the code. You can consider closing the issue now.
Anyway, you can select another background color that is NOT BLACK( RGB (0,0,0) ) (like RGB (0,0,1) ) and the background transparent will work again.
