### ISSUE TITLE
希望加入后台清理

### ISSUE THREAD

**Issue by gaokangk** [zhongyang219/TrafficMonitor#89]
这样就可以完全抛弃各大安全软件了。

**Comment by zhongyang219** [comment]
@关于内存清理的功能，之前也有人提过，但是我并不打算做这个功能，因为我并不认为内存清理会使电脑运行更快。可以参考这个链接：https://www.zhihu.com/question/48612888

**Comment by gaokangk** [comment]
用火绒很久了。确实不需要清理后台。只不过我用习惯了

发送自 Windows 10 版邮件应用

发件人: zhongyang219
发送时间: 2018年6月18日 12:55
收件人: zhongyang219/TrafficMonitor
抄送: gaokangk; Author
主题: Re: [zhongyang219/TrafficMonitor] 希望加入后台清理 (#89)

@关于内存清理的功能，之前也有人提过，但是我并不打算做这个功能，因为我并不认为内存清理会使电脑运行更快。可以参考这个链接：https://www.zhihu.com/question/48612888
