### ISSUE TITLE
Please point and help me re-enable TrafficMonitor settings in tray on Windows boot not working on windows 11

### ISSUE THREAD

**Issue by philongphongvan** [zhongyang219/TrafficMonitor#896]
Yesterday I didn't know what clicking on the TrafficMonitor installer icon made it disappear from the window tray. 
![2021-11-08_085514](https://user-images.githubusercontent.com/70433050/140672686-825b0d66-eb44-4cff-b8a5-fec729335b39.jpg)

Now when I hover my mouse over the application icon screen I can't find the program's miniature settings icon anymore. I've tried turning it off, deleting and re-downloading then extracting and re-running so many times but it's still the same. Please show me how to re-enable the app settings icon to minimize on windows tray, thank you very much :(
![2021-11-08_084810](https://user-images.githubusercontent.com/70433050/140672351-0d03e607-532d-4f94-8be9-2fc137448fbc.jpg)
![2021-11-08_084827](https://user-images.githubusercontent.com/70433050/140672362-fe38d10d-53e5-490c-baae-42414de4e870.jpg)
![2021-11-08_084856](https://user-images.githubusercontent.com/70433050/140672373-992f04c6-38ae-4d78-991c-12cc69e54f96.jpg)
![2021-11-08_084931](https://user-images.githubusercontent.com/70433050/140672384-ba92d4d1-a5b5-4f1f-a0fe-f3eeeeae1e32.jpg)

**Comment by philongphongvan** [comment]
Can anyone help me to restore the app defaults like I said above, please :(

**Comment by zhongyang219** [comment]
* Select "Options" in the right-click menu, switch to the "General Settings" tab, click "Open configuration file directory".
* Exit TrafficMonitor.
* Open "config.ini" file, modify "show_notify_icon" as "true".
```ini
[config]
show_notify_icon= true
```

**Comment by philongphongvan** [comment]
> * Chọn "Tùy chọn" trong menu chuột phải, chuyển sang tab "Cài đặt chung", nhấp vào "Mở thư mục tệp cấu hình".
> * Thoát TrafficMonitor.
> * Mở tệp "config.ini", sửa đổi "show_notify_icon" thành "true".
> 
> ```ini
> [config] 
> show_notify_icon = true
> ```

I'm on windows 11, I can't find your instructions. Can you please attach a picture to guide me in detail? Thank you very much, please
![2021-11-13_140248](https://user-images.githubusercontent.com/70433050/141609548-32047e31-8ead-4e42-9c90-743b981973fa.jpg)
![2021-11-13_140305](https://user-images.githubusercontent.com/70433050/141609552-9a2386da-b62c-4cf3-aef1-6ff722fbb479.jpg)

**Comment by zhongyang219** [comment]
It seems that the location of "config.ini" is "`C:\Users\<username>\AppData\Roaming\TrafficMonitor`".
Exit TrafficMonitor and open "config.ini" file in the location above, modify "show_notify_icon" as "true".
```ini
[config]
show_notify_icon= true
```

**Comment by philongphongvan** [comment]
> Có vẻ như vị trí của "config.ini" là " `C:\Users\<username>\AppData\Roaming\TrafficMonitor`". Thoát khỏi TrafficMonitor và mở tệp "config.ini" ở vị trí trên, sửa đổi "show_notify_icon" thành "true".
> 
> ```ini
> [config] 
> show_notify_icon = true
> ```

I followed your instructions and restored the icon display. I would like to send you my most sincere thanks from the bottom of my heart to you. Wish you always a lot of health, peace, happiness and success in life 😍😍😍😘😘😘
![2021-11-13_185553](https://user-images.githubusercontent.com/70433050/141643049-618b3b80-1b86-4cd3-b814-f01ccd17152a.jpg)
![2021-11-13_185731](https://user-images.githubusercontent.com/70433050/141643054-cf2e32e7-8280-4192-89a0-62c957f64491.jpg)

**Comment by zhongyang219** [comment]
Please update to the latest version 1.82. This problem should not be appeared any more.

**Comment by philongphongvan** [comment]
I updated to the latest version this morning when I just turned on my computer.  The application is great, thank you very much, wish you all the best. 🤩😘
