### ISSUE TITLE
上传实时速度显示不准确

### ISSUE THREAD

**Issue by cnsimo** [zhongyang219/TrafficMonitor#90]
# 环境
- windows10 + 无线网卡
- 开启TrafficMonitor显示实时网速
- 使用[http://www.speedtest.cn/](http://www.speedtest.cn/)测速
# 问题
感觉上传显示得不是很准啊，下载速度显示还可以，上传速度显示的一直是0-10kb/s左右。测速的平均上传速度却远远高于这个值，那么实时网速都没这么高，平均值怎么可能这么高。试了好几次，应该是这个工具显示的实时上传速度不准确。希望改进！！

**Comment by zhongyang219** [comment]
我试了一下，没有出现你说的问题啊。
![988](https://user-images.githubusercontent.com/30562462/41849728-85f8f6fa-78b4-11e8-9901-7e42804ecfdb.png)

**Comment by xieerduos** [comment]
时进行多个任务上传的时候，上传速度并不准确，单个任务上传速度是对的

![image](https://github.com/user-attachments/assets/8d01eeb7-f822-4975-af98-7d40a4cb12bb)
