### ISSUE TITLE
win11与ExplorerPatcher软件冲突，开发者建议在任务栏上增加自动/手动重定位功能

### ISSUE THREAD

**Issue by zapplelove** [zhongyang219/TrafficMonitor#906]
具体问题和讨论请参照这个[issue](https://github.com/valinet/ExplorerPatcher/issues/461)

谢谢

**Comment by novaeye** [comment]
> 具体问题和讨论请参照这个[issue](https://github.com/valinet/ExplorerPatcher/issues/461)
> 
> 谢谢

配合 explorerpatcher 等工具修改出来的经典任务栏使用时,  可以试试用1.80.3版本,  这个版本在 WIN 11 + 经典任务栏上不会有错位的问题.

**Comment by zapplelove** [comment]
> > 具体问题和讨论请参照这个[issue](https://github.com/valinet/ExplorerPatcher/issues/461)
> > 谢谢
> 
> 配合 explorerpatcher 等工具修改出来的经典任务栏使用时, 可以试试用1.80.3版本, 这个版本在 WIN 11 + 经典任务栏上不会有错位的问题.

感谢，已经解决。
