### ISSUE TITLE
皮肤11流量数据显示不全的问题

### ISSUE THREAD

**Issue by frankruizhi** [zhongyang219/TrafficMonitor#91]
首先，感谢作者的热心开发。
版本为当前最新版v1.74，屏幕显示分辨率：2560*1440，皮肤的展示情况如下：

![image](https://user-images.githubusercontent.com/25580946/41818255-5ff509a8-77dd-11e8-9b17-ea0d80ce478c.png)

下载网速显示首位无法完整显示，如果是大于1000多数字也是一样的情况，首位数字无法完全显示，有时甚至会隐藏一大半，如下：

![image](https://user-images.githubusercontent.com/25580946/41818272-c08fd81a-77dd-11e8-924d-cef3ffabcc52.png)

**Comment by zhongyang219** [comment]
使用皮肤11时确实会有这样的问题，建议在选项设置——主窗口设置中勾选“网速显示简洁模式”。

**Comment by zhongyang219** [comment]
使用皮肤11时确实会有这样的问题，建议在选项设置——主窗口设置中勾选“网速显示简洁模式”。

**Comment by soap-man** [comment]
怎么喜欢用悬浮框，个人习惯显示在任务栏，可以设置显示的网速的位数
