### ISSUE TITLE
The taskbar window doesn't work with 'StartAllBack' taskbar feature enabled. 

### ISSUE THREAD

**Issue by Nura57** [zhongyang219/TrafficMonitor#911]
When I open startallback and use any of it's features the taskbar window keeps glitching and doesn't show up at all. The window is there mind you but it doesn't appear. I've tried with default and different settings but it still doesn't work. Please kindly look into this.

**Comment by Nura57** [comment]
[Here's a screen recording of the issue I'm talking about.](https://drive.google.com/file/d/1z0_v6rdsMNXdWXuZ4yqO1uV4XX1R1t1y/view?usp=sharing)

**Comment by AO2233** [comment]
same issues

**Comment by zhongyang219** [comment]
This probles has been fixed now:
https://github.com/zhongyang219/TrafficMonitor/actions/runs/1530435386
