### ISSUE TITLE
win11,无法点击主页面问题

### ISSUE THREAD

**Issue by yimouz** [zhongyang219/TrafficMonitor#912]
巧的是升级了win11，更巧的是隐藏了主页面，任务栏只显示了网路速率，但无法通过点击任务栏的图标进行操作了！！！

**Comment by oldsboy** [comment]
同,正想提这个issue,任务管理器关掉再开也会被记录到这个情况了,导致无法设置了,估计只能重新安装或者重新配置参数吧.
看了文档,应该是win11导致任务栏那里无法触发控件的右键导致的这种情况.
有解决方案麻烦拍下我,当然现在也能用就是了

**Comment by zhongyang219** [comment]
@yimouz  @oldsboy 此问题已经在最新版本（1.82）中解决。

**Comment by oldsboy** [comment]
牛逼嗷!
