### ISSUE TITLE
“背景透明”选项被自动重置

### ISSUE THREAD

**Issue by ZyyMaker** [zhongyang219/TrafficMonitor#917]
在系统设置中切换浅色/深色模式后，“背景透明”选项会被自动恢复到勾选状态。
未使用第三方任务栏美化工具。

系统版本：Windows 11 22000.348
软件版本：1.81 (x64)

**Comment by sceraser** [comment]
Windows 10也是这样的，而且10在深色模式下任务栏没有显示，怎么调整都没用

**Comment by zhongyang219** [comment]
根据你的问题描述，你应该是勾选了“自动适应Windows10深色/浅色主题”。在这种情况下，你应该把你当前设置保存到预设中。点击“预设方案”按钮，“选择修改预设方案”，选择一个预设，此时就会把当前颜色设置保存到选择的预设中。点击“自动适应设置”按钮，可以设置在深色和浅色模式下分别使用哪个预设的设置。
![image](https://user-images.githubusercontent.com/30562462/145710266-7cdd09d1-010b-4e06-8012-28ded5d33e18.png)
![image](https://user-images.githubusercontent.com/30562462/145710269-ffcf4abc-fb1b-4507-a1d5-5bd29d5e3dab.png)
你可以参照以下帮助文件：
[选项设置 · zhongyang219/TrafficMonitor Wiki (github.com)](https://github.com/zhongyang219/TrafficMonitor/wiki/选项设置#任务栏窗口设置)

**Comment by ZyyMaker** [comment]
感谢解答。

**Comment by ZyyMaker** [comment]
> 根据你的问题描述，你应该是勾选了“自动适应Windows10深色/浅色主题”。在这种情况下，你应该把你当前设置保存到预设中。点击“预设方案”按钮，“选择修改预设方案”，选择一个预设，此时就会把当前颜色设置保存到选择的预设中。点击“自动适应设置”按钮，可以设置在深色和浅色模式下分别使用哪个预设的设置。 ![image](https://user-images.githubusercontent.com/30562462/145710266-7cdd09d1-010b-4e06-8012-28ded5d33e18.png) ![image](https://user-images.githubusercontent.com/30562462/145710269-ffcf4abc-fb1b-4507-a1d5-5bd29d5e3dab.png) 你可以参照以下帮助文件： [选项设置 · zhongyang219/TrafficMonitor Wiki (github.com)](https://github.com/zhongyang219/TrafficMonitor/wiki/%E9%80%89%E9%A1%B9%E8%AE%BE%E7%BD%AE#%E4%BB%BB%E5%8A%A1%E6%A0%8F%E7%AA%97%E5%8F%A3%E8%AE%BE%E7%BD%AE)



> 根据你的问题描述，你应该是勾选了“自动适应Windows10深色/浅色主题”。在这种情况下，你应该把你当前设置保存到预设中。点击“预设方案”按钮，“选择修改预设方案”，选择一个预设，此时就会把当前颜色设置保存到选择的预设中。点击“自动适应设置”按钮，可以设置在深色和浅色模式下分别使用哪个预设的设置。 ![image](https://user-images.githubusercontent.com/30562462/145710266-7cdd09d1-010b-4e06-8012-28ded5d33e18.png) ![image](https://user-images.githubusercontent.com/30562462/145710269-ffcf4abc-fb1b-4507-a1d5-5bd29d5e3dab.png) 你可以参照以下帮助文件： [选项设置 · zhongyang219/TrafficMonitor Wiki (github.com)](https://github.com/zhongyang219/TrafficMonitor/wiki/%E9%80%89%E9%A1%B9%E8%AE%BE%E7%BD%AE#%E4%BB%BB%E5%8A%A1%E6%A0%8F%E7%AA%97%E5%8F%A3%E8%AE%BE%E7%BD%AE)

感谢解答。
