### ISSUE TITLE
速度显示问题

### ISSUE THREAD

**Issue by eliscott** [zhongyang219/TrafficMonitor#93]
![40](https://user-images.githubusercontent.com/39257369/42008404-ecc4413c-7ab7-11e8-9f1e-c375f0cc65aa.png)
TrafficMonitor显示的速度比实际速度大很多，这是为什么呢？

**Comment by zhongyang219** [comment]
TrafficMonitor监控的是网卡的流量，并非单个应用的网速，你这个情况应该是还有其他系统进程正在下载，可能是系统正在下载更新。

**Comment by eliscott** [comment]
![41](https://user-images.githubusercontent.com/39257369/42015610-a15e6c18-7ada-11e8-9381-5ccb8e7d72c0.png)
emmmm,我只连接了无线网，任务管理器中显示的网速也不高，而且当前只有utorrent占用网速。
感觉只有运行utorrent的时候会出现网速显示不正常的情况

**Comment by zhongyang219** [comment]
任务管理显示网速为46.9Mbps = 5.86MB/s，没问题啊。

**Comment by eliscott** [comment]
看到发送那一栏去了QAQ不好意思，谢谢开发者
