### ISSUE TITLE
右下角任务栏窗口，上传、下载的位置无法交换

### ISSUE THREAD

**Issue by jy3344511** [zhongyang219/TrafficMonitor#931]
1.82版，右下角任务栏窗口，上传、下载的位置无法交换，希望增加。

右下角通知栏的图标，无法隐藏，希望修改。

![无标题](https://user-images.githubusercontent.com/49992475/145709187-94ea36b9-070c-40bc-8050-19140c754828.png)

**Comment by zhongyang219** [comment]
请打开“设置”——“任务栏窗口设置”，点击“显示设置”按钮，选中“上传”，点击“下移”按钮，点击确定即可。
![image](https://user-images.githubusercontent.com/30562462/145710033-63f123db-d700-42b7-89aa-79054768671d.png)

**Comment by soloopooo** [comment]
> 1.82版，右下角任务栏窗口，上传、下载的位置无法交换，希望增加。
> 
> 右下角通知栏的图标，无法隐藏，希望修改。
> 
> ![无标题](https://user-images.githubusercontent.com/49992475/145709187-94ea36b9-070c-40bc-8050-19140c754828.png)

若想隐藏通知栏图标，请关闭桌面主窗口的鼠标穿透。更多请查看code更新记录。
