### ISSUE TITLE
这个监测软件是不是和翻墙软件有冲突

### ISSUE THREAD

**Issue by tiger0313** [zhongyang219/TrafficMonitor#94]
我只要使用这个来监测速度，翻墙软件用到几分钟后就没速度，然后导致翻墙软件不能用，很邪门。不使用这个来监测，翻墙软件就一直正常

**Comment by jamesyangget** [comment]
SSR可以正常使用啊🙄

**Comment by LisonFan** [comment]
我也碰到这个情况了，偶发性断网，刷新即可恢复
关了TrafficMonitor 就没有偶发性断网了

**Comment by LisonFan** [comment]
@zhongyang219

**Comment by LisonFan** [comment]
和 trafficmonitor 没关系
