### ISSUE TITLE
Unable to "auto-run when windows start" v1.82.

### ISSUE THREAD

**Issue by SandeeepKiran** [zhongyang219/TrafficMonitor#944]
Unable to "auto-run when windows start" v1.82.
was working on v1.81.

Since it was an update, I copy pasted the two config files to save my settings I used on v1.81 to v1.82.
I just deleted v1.81 folder and now using v1.82 exe file to launch the app.

I go to options > general settings > tick "auto-run when windows start" > Apply > ok.
This doesn't stay.
again I go to options > general settings > it is disabled.

How do I fix this?
![image](https://user-images.githubusercontent.com/36911157/145875243-21100777-ccba-49d6-ac01-061a815695c2.png)

**Comment by SandeeepKiran** [comment]
Made a duplicate of
#929 

Please do fix ASAP. Can't live without this app.

**Comment by isMehrdad** [comment]
same here
