### ISSUE TITLE
1.82设置任务栏窗口透明背景颜色时背景会影响文字

### ISSUE THREAD

**Issue by NianBroken** [zhongyang219/TrafficMonitor#955]
设置白色背景并且勾选透明背景时：
![image](https://user-images.githubusercontent.com/57057288/146173418-d241f735-ad1a-41d2-8f13-c0d555b9c2bf.png)
设置黑色背景时：
![image](https://user-images.githubusercontent.com/57057288/146173659-43d0e93e-8afb-4c93-959c-dcb332db8620.png)
红色时：
![image](https://user-images.githubusercontent.com/57057288/146173708-4c635504-d646-4b6a-9ad5-5b44b60a77b9.png)

1.81是没有这个问题的，升级1.82才有的这个问题
并且出现问题后我尝试退回1.81版本，但是问题依然存在......

系统版本截图：
![image](https://user-images.githubusercontent.com/57057288/146174408-9c65b14c-0076-4001-8225-993c03a13ec5.png)

**Comment by soloopooo** [comment]
这个问题在之前的预购建版本中即已存在。请参照https://github.com/zhongyang219/TrafficMonitor/issues/777#issuecomment-953882403

**Comment by NianBroken** [comment]
> 这个问题在之前的预购建版本中即已存在。请参照[#777 (comment)](https://github.com/zhongyang219/TrafficMonitor/issues/777#issuecomment-953882403)

那这个问题可以解决吗

**Comment by soloopooo** [comment]
除非将GDI重写为GDI+，否则解决的可能性不是很大。这个问题可能来源于GDI显示TrueType字体的时候自动的抗锯齿。

**Comment by soloopooo** [comment]
目前缓解这一情况的做法是使用 TranslucentTB 将任务栏透明，并勾选“根据任务栏颜色自动设置背景色”。

**Comment by NianBroken** [comment]
> 目前缓解这一情况的做法是使用 TranslucentTB 将任务栏透明，并勾选“根据任务栏颜色自动设置背景色”。

可是我的任务栏设置了模糊，使用"根据任务栏颜色自动设置背景色"起不到作用
![image](https://user-images.githubusercontent.com/57057288/146176819-75490494-5397-4d3e-9361-049d5dd9bf34.png)
我现在就想不明白为什么我使用1.81版本的时候没有出现这个问题
而且我现在回退1.81版本也无法解决这个问题....

这是我更新1.82版本之前截的图
![22 %8HH37_ISGGHL25LBNGT](https://user-images.githubusercontent.com/57057288/146177020-c3578ea0-ddf7-4560-9e9a-47cccfe40ebe.jpg)
![image](https://user-images.githubusercontent.com/57057288/146177113-d32e6f8b-b3af-4620-949f-f70856b6bac4.png)

**Comment by soloopooo** [comment]
1.81之前，使用TranslucentTB的时候，位于任务栏的窗口如果背景的颜色是浅色调的，那么颜色将无法被正常显示，会被白色所覆盖掉。
所以之前所使用的透明，应该是将所有的颜色减淡一个值。

**Comment by soloopooo** [comment]
实测使用深色背景+任务栏模糊，肉眼效果会好很多
![image](https://user-images.githubusercontent.com/36123081/146177975-b188620b-3e81-49c6-901c-d24fd3c65ba7.png)

**Comment by codehz** [comment]
* 使用一个非 TrueType 字体也会好（
* 比如 fixedsys

**Comment by soloopooo** [comment]
我之前试过非 TrueType 字体，确实会好。

但是好看的非 TrueType 字体太少了（

**Comment by rabbitFS** [comment]
软件版本：1.84.1
系统版本：WIN11专业版 22H2
问题：存在任务栏窗口与软件显示内容重叠的情况
希望作者能解决这个问题呀。
![微信图片_20240703181441](https://github.com/zhongyang219/TrafficMonitor/assets/60863490/8636f932-ae2f-4008-9740-c6c09b9f938f)

**Comment by rabbitFS** [comment]
> 软件版本：1.84.1 系统版本：WIN11专业版 22H2 问题：存在任务栏窗口与软件显示内容重叠的情况 希望作者能解决这个问题呀。 ![微信图片_20240703181441](https://private-user-images.githubusercontent.com/60863490/345380966-8636f932-ae2f-4008-9740-c6c09b9f938f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDIwMjMsIm5iZiI6MTcyMDAwMTcyMywicGF0aCI6Ii82MDg2MzQ5MC8zNDUzODA5NjYtODYzNmY5MzItYWUyZi00MDA4LTk3NDAtYzZjMDliOWY5MzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwMTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMjUzYzAxOTI2MTgyZDM0YTRmOGVhNjQ2ZmNiYmMzNzMzM2MxYTg4ZWY1OTkyMzEzNmVhNjFiYTJkNjI3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zJ5JNexIac-JzOYp-hVDpoUfB8pxy6DnLtaZb4dLwvw)

![181441](https://github.com/zhongyang219/TrafficMonitor/assets/60863490/3e1fc323-440a-474f-979a-c14abefba0d9)


且如果正好选中被遮盖部分的窗口这个字体毛边又出现了。
