### ISSUE TITLE
1.82_x64 版本在Windows 10 21H1 状态栏中显示方向不正确

### ISSUE THREAD

**Issue by 597585136** [zhongyang219/TrafficMonitor#964]
![image](https://user-images.githubusercontent.com/19337508/146482680-125985ef-8151-45e8-9140-83bd7d59bb29.png)

**Comment by 597585136** [comment]
设置成英文没这个问题

**Comment by codehz** [comment]
你是选成@开头的字体了吧

**Comment by 597585136** [comment]
自动回复：您好，您的邮件我已经收到！

**Comment by 597585136** [comment]
> 你是选成@开头的字体了吧

还真是，解决了，感谢
