### ISSUE TITLE
auto open in windows 11

### ISSUE THREAD

**Issue by TahirAhmad01** [zhongyang219/TrafficMonitor#967]
autorun when Windows start is not enabled in windows 11.  please fix it

**Comment by AniAve** [comment]
Same problem: option in app isn't working

**Comment by ASFLY61** [comment]
> autorun when Windows start is not enabled in windows 11. please fix it

Remove old cron on you pc

**Comment by AniAve** [comment]
> > autorun when Windows start is not enabled in windows 11. please fix it
> 
> Remove old cron on you pc

Cron?

**Comment by ASFLY61** [comment]
> > > autorun when Windows start is not enabled in windows 11. please fix it
> > 
> > 
> > Remove old cron on you pc
> 
> Cron?
Windows Scheduled Tasks

**Comment by TahirAhmad01** [comment]
Thanks! It worked.

**Comment by TahirAhmad01** [comment]
> > > > autorun when Windows start is not enabled in windows 11. please fix it
> > > 
> > > 
> > > Remove old cron on you pc
> > 
> > 
> > Cron?
> > Windows Scheduled Tasks

Thanks! It worked.
