### ISSUE TITLE
Change position

### ISSUE THREAD

**Issue by DanRotaru** [zhongyang219/TrafficMonitor#970]
Add possibility to change taskbar window indicator position (download and upload)
![image](https://user-images.githubusercontent.com/7759507/146788982-52dd5cb0-8849-42ec-80b3-ea19a6625efc.png)

**Comment by zhongyang219** [comment]
In the latest version, you can customize the order of all items in the taskbar, so the option "swap position of upload and download" is no longer needed.
Please open "Settings"-"Taskbar Window Settings", click the "Display Settings" button, select "Upload", click the "Move Down" button, and click OK.
![](https://user-images.githubusercontent.com/30562462/145710033-63f123db-d700-42b7-89aa-79054768671d.png)

**Comment by DanRotaru** [comment]
A, sorry, thank you

**Comment by Mahoneko13** [comment]
Great, that worked, thank you so much!
