### ISSUE TITLE
配置文件路径更改

### ISSUE THREAD

**Issue by sunnyday2006** [zhongyang219/TrafficMonitor#98]
你好，非常喜欢这款工具。感谢开发和分享。

目前配置文件夹里面包括了config、error和history_traffic。能够自定义配置文件路径吗？比如放在程序所在文件夹，而不是%appdata%路径？这样方便原设置移植到其他电脑上，同时也容易读取和上报错误日志。

还有一处，若选择了鼠标穿透，则“双击主窗口动作”就不能“打开连接详情”（默认）了。这时候能不能改成双击托盘图标，来打开连接详情？当然，这个未必合理，若增加了内存占用或是运行负担，则可以忽略这条。

**Comment by zhongyang219** [comment]
将配置文件放在appdata目录下也是大多数软件的做法，关于自定义配置文件的路径的功能我以前也想过，但是感觉做起来很麻烦而且意义不大。首先配置文件的路径肯定不能放在配置文件里，否则就会出现类似于“打开箱子的钥匙被锁在箱子里”的尴尬，那么配置文件的路径只能放在注册表里，要是这样的话，我既然写入了注册表，我为什么不干脆把所有设置全部写入注册表里？但是这样估计有人会反对，他们觉得一个绿色软件不应该把配置保存在注册表里。
关于双击通知区图标打开“连接详情”的功能，感觉这个并不是很合理，暂时不考虑吧。

**Comment by sunnyday2006** [comment]
所以，不写注册表的绿色软件实际上并不存在？类似于*.ini的配置文件，其实是在已经写入注册表的前提下产生的，对吗？

如果理解没有问题，能否提供卸载TrafficMonitor写入的注册表项？如果只是单纯删除软件目录，有可能会造成卸载的项目残留。当然，我还没有细看TrafficMonitor的程序，不知道是不是这么一回事？

**Comment by zhongyang219** [comment]
绿色软件也可以不写入注册表，比如Trafficmonitor就只有在实现开机自启动功能时写入了注册表，如果不做开机自启动功能的话就没有任何注册表操作了。关于你说想要一个卸载程序，这个我可以考虑做一个。

**Comment by sunnyday2006** [comment]
如此甚好。感谢。
