### ISSUE TITLE
v1.8.2无法关闭任务栏图标

### ISSUE THREAD

**Issue by yunyuyuan** [zhongyang219/TrafficMonitor#982]
我记得之前可以关闭的啊，为啥取消了呢

**Comment by Nolan-Wink** [comment]
+1

**Comment by y9858** [comment]
win10可以在设置-常规设置里关闭 win11这个选项是灰的
![QQ截图20211230115057](https://user-images.githubusercontent.com/53130835/147720310-eb159f82-5644-4bbd-9f9a-20578f376299.png)

**Comment by sanmaodo** [comment]
> win10可以在设置-常规设置里关闭 win11这个选项是灰的 ![QQ截图20211230115057](https://user-images.githubusercontent.com/53130835/147720310-eb159f82-5644-4bbd-9f9a-20578f376299.png)

https://github.com/zhongyang219/TrafficMonitor/issues/932
