### ISSUE TITLE
有准备弄mac版本吗

### ISSUE THREAD

**Issue by soap-man** [zhongyang219/TrafficMonitor#99]

**Comment by zhongyang219** [comment]
暂时没有这方面的计划，因为我没有mac笔记本或电脑，也几乎没用过mac系统，也不会开发mac软件。由于这个软件是完全开源的，这项工作也许可以交给其他懂mac软件开发的大神。

**Comment by comwrg** [comment]
macOS有现成的,  **iStat Menus**

**Comment by cxgreat2014** [comment]
mac上的iStat Menus和这个相比貌似还没有换肤功能。。还是这个漂亮一些
